api/bin/www, api/server.js
Je pense que la Func review ça va être compliqué... Pas grand risque à merger ça de toute façon.
Pour tester:
```bash
curl -X OPTIONS http://1216-fix-cors-headers.pix-dev.ovh/api/ -H 'Access-Control-Request-Method: GET' -H 'Origin: https://pix-api.scalingo.io' -v
```
Et vérifier que la ligne:
> < access-control-allow-headers: Accept,Authorization,Content-Type,If-None-Match,X-Requested-With 
est présente (surtout le X-Requested-With qui était le header manquant).
=> [#17] Corriger le problème de CORS (US-1216).

api/scripts/get-results-certifications.js, api/tests/unit/scripts/get-results-certifications_test.js
Pour cet US: 
- L'API renvoyait déjà toutes les informations
- Nous avons juste ajouté de nouvelles colonnes au CSV créé par le script
- Nous en avons profité pour créer un fichier csv comme fichier de sortie (avec la date comme nom)
- Le parseArgs et le slice(4) faisait la même chose, on l'a retiré
=> [#16] [FEATURE] Ajout de toutes les informations dans le CSV d'export (US-1181).

api/lib/infrastructure/plugins/metrics.js, api/tests/unit/infrastructure/plugins/metrics_test.js
A valider sur : http://1202-path-on-error-metrics.pix-app.ovh/metrics
=> [#22] Les métriques de /metrics exposent le path dans les compteurs api_request (US-1202)

api/lib/application/authentication/authentication-controller.js, api/lib/application/authentication/index.js, api/lib/application/usecases/checkUserCredentialsAndGenerateAccessToken.js, api/lib/domain/errors.js, api/package-lock.json, api/tests/integration/application/authentication/index_test.js, api/tests/unit/application/authentication/authentication-controller_test.js, api/tests/unit/application/usecases/checkUserCredentialsAndGenerateAccessToken_test.js
Ajout des endpoints `POST /api/token` et `POST /api/revoke` en suivant les spécifications OAuth 2 pour la stratégie [Password Credentials Grant](https://tools.ietf.org/html/rfc6749#section-4.3) (moins la partie rafraîchissement de l'access token, pas très utile dans la mesure où les access_token qu'on génère durent 7 jours [remarque : ce qui est trop d'après la-dite doc!]).
OAuth 2 déconseille cette stratégie sauf dans le cas où le client fait parfaitement confiance au back, ce qui est notre cas dans la mesure où nous avons la main sur l'un et l'autre.
Remarque ⚠️!  dans la mesure où les credentials sont passés en clair, **il est absolument nécessaire que la communication se fasse par HTTPS !**
-----------
[RFC 6749](https://tools.ietf.org/html/rfc6749)
Cet endpoint est utilisé pour …
=> [#14] [FEATURE] Ajout de nouveaux endpoints d'authentification OAuth 2 (US-1205)

live/app/templates/components/app-footer.hbs
Remplacer `contact@pix.beta.gouv.fr` dans le footer par `contact@pix.fr`
=> [#34] [BUGFIX] Corriger l'adresse de contact (US - 1220).

live/scripts/signal_deploy_to_pr.sh, scripts/trello/comment_with_review_app_url.sh
et utiliser le compte de service pour les notifications Github
J'ai changé le nom de la variable de token pour ne pas casser la build avant de merge. On supprimera la variable en trop quand cette PR sera sur dev.
=> [#46][BSR] Pointer l'url d'intégration vers integration.pix.fr

api/lib/domain/models/CompetenceMark.js, api/lib/domain/services/assessment-result-service.js, api/lib/domain/services/assessment-service.js, api/lib/domain/services/certification-service.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js, api/tests/acceptance/application/certification-controller_test.js, api/tests/acceptance/application/certification-course-controller_test.js, api/tests/factory/build-competence-mark.js, api/tests/factory/index.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/integration/infrastructure/repositories/certification-repository_test.js, api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js, api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js, api/tests/unit/application/assessments/assessment-controller-save_test.js, api/tests/unit/application/certificationCourses/certification-course-controller_test.js, api/tests/unit/application/certifications/certification-controller_test.js, api/tests/unit/domain/models/CompetenceMark_test.js, api/tests/unit/domain/services/assessment-result-service_test.js, api/tests/unit/domain/services/assessment-service_test.js, api/tests/unit/domain/services/certification-service_test.js, api/tests/unit/infrastructure/repositories/assessment-repository_test.js, api/tests/unit/infrastructure/repositories/certification-course-repository_test.js, live/app/components/competence-level-progress-bar.js, live/app/templates/components/competence-level-progress-bar.hbs, live/tests/unit/components/competence-level-progress-bar-test.js
Correction de bogues liés à la gestion du calcul des scores de fin d'assessment. 
1 - Affichage d'un niveau 6 sur la page profil d'un utilisateur pour un test de positionnement.
2 - Manque de la propriété "completedAt" sur l'objet certificationCourse d'une certification 
Les deux bogues ont été réglé dans l'idée de mettre la Rustine™ le plus "loin" possible pour "libérer" le code / l'algorithme des limites "artificielles" de niveaux.
=> [#76] [BUGFIX] Correction des bogues sur la gestion de la fin d'un test (PF-170)

api/lib/application/assessments/assessment-controller.js, api/lib/cat/assessment.js, api/lib/domain/services/assessment-service.js, api/lib/domain/usecases/get-next-challenge-for-certification.js, api/lib/domain/usecases/get-next-challenge-for-demo.js, api/lib/domain/usecases/get-next-challenge-for-placement.js, api/lib/infrastructure/adapters/assessment-adapter.js, api/lib/infrastructure/airtable.js, api/lib/infrastructure/logger.js, api/lib/infrastructure/repositories/certification-challenge-repository.js, api/lib/settings.js, api/tests/factory/build-cat-assessment.js, api/tests/unit/infrastructure/adapters/assessment-adapter_test.js
Fait:
- choix du niveau de logging par variable d'environnement (`LOG_LEVEL`) avec défaut à `info` (comme avant)
- toutes les traces sont écrite au niveau `logger.trace()`, [qui est inférieur à debug](https://github.com/trentm/node-bunyan#levels)
- Ajout de quelques traces vues avec Benoit pour aider au débugging
=> [#109] Ajout de traces de log dans la sélection du next challenge (PF-267).

api/db/knexfile.js
Le PG de l'application de staging n'autorise que 30 connexions simultanées or la configuration de `knex` autorisait un _pool_ de 100 connexions. On a eu une erreur 500 en staging avec dans le log l'erreur suivante : 
```
[web-1] error: remaining connection slots are reserved for non-replication superuser connections
[web-1] at Connection.parseE (/app/api/node_modules/pg/lib/connection.js:545:11)
[web-1] at Connection.parseMessage (/app/api/node_modules/pg/lib/connection.js:370:19)
[web-1] at TLSSocket.<anonymous> (/app/api/node_modules/pg/lib/connection.js:113:22)
[web-1] at emitOne (events.js:116:13)
[web-1] at TLSSocket.emit (events.js:211:7)
[web-1] at addChunk (_stream_readable.js:263:12)
[web-1] at readableAddChunk (_stream_readable.js:250:11)
[web-1] at TLSSocket.Readable.push …
```
=> [#121] [BUGFIX] Respecter la variable DATABASE_CONNECTION_POOL_MAX_SIZE pour le pool PG en staging (PF-284)

api/lib/domain/strategies/SmartRandom.js, api/tests/unit/domain/strategies/SmartRandom_test.js
**Correction** : 
- Lorsque l'on filtre les `Challenges` valides, on vérifie maintenant que le `Challenge` n'a pas été posé
**Explication du bug**(via un exemple) : 
- Le `targetProfil` contient les `skills` `@outilsTexte1` et `@outilsTexte2`
- La question qui valide `@outilsTexte2` est un QROCM-dep qui valide `@outilsTexte2` et `@outilsTexte4`
- Lorsque la question est loupé, on invalide les `skills` de niveaux supérieurs qui sont dans le `targetProfil`, donc seulement `@outilsTexte2`
- L'acquis `@outilsTexte4` reste non-visité pour l'algorithme
- La question (toujours présente dans la liste des challenges possibles) revient plus tard car `@outilsTexte4` est un skill qui peut apporter de l'information (car non visité).
**Discussions qu'il y eu sur ce bug** :
- Cette correction est très …
=> [#130] [BUGFIX] Correction du bug des questions en doubles dans le smart-random (PF-287)

live/app/routes/application.js, live/tests/unit/routes/application-test.js
Quand on avait une session expirée, le serveur renvoyait une erreur 401 à l'appel de `/users/me`. Cette erreur était traitée automatiquement par ember en redirigeant vers la page "Oups" (`error.hbs`) et il était impossible de se connecter.
Correction : 
- interception explicite de l'erreur 401 dans la route de base,
- invalidation de la session,
- redirection vers `/login`
=> [#136] [BUGFIX] Correction de la page "Oups" qui s'affiche en boucle à l'expiration de la session (PF-297).

api/lib/application/campaigns/campaign-controller.js, api/lib/application/organizations/organization-controller.js
Problème : 
- Le fichier CSV des profils partagées se téléchargeait mal sous Firefox. N'apparaissait que "Pix" sans extension de fichier
Cause : 
- Firefox ne supporte pas les espaces dans les noms de fichiers pour le téléchargement
Résolution : 
- Ajout de double quote autour du nom
- Même modification pour les fichiers csv des campagnes pour mettre le nom des campagnes
=> [#172] [BUGFIX] Problème de téléchargement du fichier csv des profils partagées sous Firefox (PF-285)

mon-pix/config/environment.js, scripts/jira/comment-with-review-app-url.js, scripts/signal_deploy_to_pr.sh
L'espace perso est maintenant accessible via app.pix.fr et www.app.pix.fr
Les RAs sont maintenant accessibles via app.integration.pix.fr
Ce commit met à jour l'environment.js qui spécifie l'API à utiliser en fonction de l'environnement, et 2 scripts afin qu'ils utilisent maintenant la nouvelle url en 'app'.
=> [#181] [FEATURE] Rendre accessible l'espace perso pix via l'url app.pix.fr (PF-345)

README.md, api/lib/domain/services/mail-service.js, api/lib/infrastructure/mailjet.js, api/lib/settings.js, api/scripts/recompute-assessment-results.js, api/tests/acceptance/application/course-controller_test.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/application/qmail/qmail-controller_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/services/qmail-validation-service_test.js, api/tests/unit/infrastructure/mailjet_test.js, api/tests/unit/scripts/recompute-assessment-results_test.js, mon-pix/tests/unit/services/mail-generator-test.js, orga/app/templates/components/login-form.hbs, orga/config/environment.js
NOTE : Il va falloir qu'on se prenne du temps pour réfléchir à notre gestion des urls, et plus particulièrement la manière dont on "référencie" l'url d'une app dans une autre (ex l'url de l'api dans mon orga).
A mettre dans la partie 'Environment' de scalingo ?!
=> [#186] Tous les liens vers l'espace perso utilisent app.pix.fr (PF-346)

scalingo.json
Without a specification in scalingo.json, Scalingo defaults to M-sized containers for review apps, which cost twice as much as the S-sized containers which are sufficient.
=> Set scalingo formation for review apps

mon-pix/config/environment.js, nginx.conf.erb, orga/config/environment.js
Avec cette PR, les applications front (https://app.pix.fr, https://orga.pix.fr) accèdent à l'API via https://app.pix.fr/api/ et https://orga.pix.fr/api/ ce qui évite au navigateur d'avoir à faire des requêtes `OPTIONS`.
=> [#210] [TECH] Publication de l'API sur les domaines front pour éviter les requêtes OPTIONS

api/lib/application/users/index.js, api/lib/application/users/user-controller.js, api/lib/domain/models/SearchResultList.js, api/lib/domain/usecases/find-users.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/bookshelf.js, api/lib/infrastructure/repositories/user-repository.js, api/lib/infrastructure/serializers/jsonapi/user-serializer.js, api/lib/infrastructure/utils/query-params-utils.js, api/package-lock.json, api/package.json, api/tests/acceptance/application/users/users-controller-find-users_test.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/tooling/database-builder/factory/build-pix-role.js, api/tests/tooling/database-builder/factory/build-user-pix-role.js, api/tests/tooling/database-builder/factory/build-user.js, api/tests/tooling/database-builder/factory/index.js, api/tests/unit/application/users/index_test.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/models/SearchResultList_test.js, api/tests/unit/domain/usecases/find-users_test.js, api/tests/unit/infrastructure/utils/query-params-utils_test.js
Pix Admin
L'objet de cette PR est de définir dans l'API la ressource `GET /api/users`, qui permet de : 
- lister des utilisateurs (id, firstName, lastName, email) ;
- filter des utilisateurs par prénom, nom et/ou email ;
- et de les retourner de façon paginée.
Cette ressource est réservée aux Pix Masters.
La route prend les paramètres (optionnels) suivants : 
| Param     | Type   | Usage      | Default value |
|-----------|--------|------------|---------------|
| firstName | string | search     | null          |
| lastName  | string | search     | null          |
| email     | string | search     | null          |
| page      | number | pagination | 1             |
| pageSize  | number | pagination | 10            |
- `GET /api/users`
- `GET …
=> [#208] [FEATURE] Ajout du endpoint d'administration "GET /api/users" permettant de lister, filtrer et paginer des utilisateurs (PA-46).

api/db/migrations/20181015115708_add_title_to_campaign.js, api/db/seeds/data/3rd-to-create/campaigns.js, api/lib/domain/models/Campaign.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/tooling/database-builder/factory/build-campaign.js, api/tests/tooling/factory/build-campaign.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, orga/app/models/campaign.js, orga/app/templates/components/campaign-creation-form.hbs, orga/tests/acceptance/campaign-creation-test.js, orga/tests/integration/components/campaign-creation-form-test.js
Besoin :
Un utilisateur de Pix Orga doit pouvoir ajouter un titre à sa campagne de manière facultative. Ce champ sera affiché ultérieurement dans le bandeau de reprise d'une campagne, ou dans l'en-tête lorsque l'on répond à une campagne (parcours).
Tech :
Ajout au formulaire d'un champ "titre du parcours" lors de la création d'une campagne.
Ajout en base d'un champ "title" dans campaign.
=> [#231] [FEATURE] Ajout d'un titre lors de la création d'une campagne (PO-73)

mon-pix/app/models/challenge.js
Besoin : En tant qu'utilisateur d'Internet Explorer, je dois pouvoir répondre à des questions avec des applications embarquées.
Technique : Remplacement du `startsWith` non supporté par IE par `indexOf === 0`
=> [#240] [BUGFIX] Les documents 'embed' fonctionnent maintenant sous Internet Explorer (PF-432)

api/tests/unit/scripts/delete-user_test.js, api/tests/unit/scripts/recompute-assessment-results_test.js
Il y a deux tests sur des scripts qui utilisent directement
console.log(). Ces appels généraient du bruit inutiles sur la sortie
console des tests.
J'ai stubé ces appels pour les tests, ce qui ne génère plus de bruit.
Pour aller plus loin, on pourrait éviter d'appeler console.log() et
utiliser une lib de log (je crois qu'on a bunyan par exemple), qui
devrait se comporter correctement par défaut pendant les tests.
=> [BSR] Supprime les messages de log dans la sortie console des tests

mon-pix/app/components/results-warning.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_results-warning.scss, mon-pix/app/templates/components/results-warning.hbs, mon-pix/app/templates/compte.hbs, mon-pix/public/images/icons/icon-warning.svg, mon-pix/tests/integration/components/results-warning-test.js
Besoin : L'utilisateur doit pouvoir être averti que les résultats de ses campagnes ne sont pas inclus dans son profil, si il a commencé et/ou terminé et/ou partagé au moins une campagne.
Tech : Ajout d'un composant basé sur si oui ou non on a une campaignParticipation.
=> [#244] [FEATURE] Ajout d'un message pour prévenir l'utilisateur que le résultats de ses campagnes ne sont pas inclus dans son profil (PF-400)

mon-pix/ember-cli-build.js
Il y a un actuellement un bug sous IE11 qui empêche, une fois sur l'écran de résultat après un positionnement, de voir les réponses individuellement.
Après différentes recherches, le fait d'ajouter un polyfill à ember-cli-babel permet d'avoir un full support des transformations, et fait fonctionner le schmilblick => https://github.com/babel/ember-cli-babel#Polyfill
=> [#247] Ajout de polyfill à ember-cli-babel pour un meilleur support ES6 (PF-433)

mon-pix/app/styles/components/_signup-form.scss
Besoin : Un utilisateur d'Internet Explorer doit pouvoir s'inscrire à Pix en voyant s'afficher correctement la phrase légale en bas de page.
Technique : Ajout de propriétés CSS permettant un affichage correct sous IE.
=> [#256] [BUGFIX] Affichage correct sous IE de la phrase légale lors de la création de compte (PF-441).

api/db/seeds/data/organization-with-related/dragon-and-co-builder.js
Certains codes d'organisation dans les données de _seed_ étaient trop longs pour le champ `organization.code`. On ne s'en est pas rendu compte plus tôt à cause de SQLite qui ne contrôle pas les longueurs de champs.
=> [TECH] Correction des seeds pour PG (codes orga trop longs)

api/lib/infrastructure/datasources/airtable/skill-datasource.js, api/tests/tooling/fixtures/infrastructure/skillRawAirTableFixture.js, api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
*Besoin* : 
- Il y a des acquis non utilisé dans Airtable (acquis en cours de développement, sans question etc...) qui étaient remontés dans la liste des acquis. Ces acquis sans question posaient problème notamment lors du calcul du nombre de Pix gagné, qui dépend des acquis présents.
*Tech* : 
- Une colonne "Status" a été ajouté dans AirTable pour préciser le status de l'acquis. Suite à une discussion avec Benoit, c'est via ce status que nous souhaiterions filtrer les acquis, dans tous les cas  : "’à partir du moment où un acquis est marqué comme non valide, il ne devrait pas exister pour l’appli".
- Ajout d'un filtre sur le status dans le _doQuery par lequel passe list(), findBy*()
=> [#259] [BUGFIX] Filtrer les acquis par status (PF-147).

api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js, api/tests/acceptance/application/assessments/assessment-controller-get_test.js, api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js, mon-pix/app/components/resume-campaign-banner.js, mon-pix/app/models/assessment.js, mon-pix/app/templates/components/resume-campaign-banner.hbs, mon-pix/tests/integration/components/resume-campaign-banner-test.js, mon-pix/tests/unit/components/resume-campaign-banner-test.js
Un utilisateur de Pix doit pouvoir voir une bannière en haut de son profil lorsqu'il n'a pas encore partagé ses résultats mais qu'il a terminé son parcours. Cette bannière doit lui proposer de partager des résultats sur le parcours en question (avec le titre, si celui-ci a été spécifié lors de la création de la campagne).
Technique : Remontée côté front du 'state' ('started' ou 'completed') d'un 'assessment'. Affichage conditionnel du message.
=> [#264] [FEATURE] Mise-à-jour de la bannière de reprise pour le cas où l'utilisateur n'a pas partagé ses résultats (PF-405).

mon-pix/app/routes/assessments/checkpoint.js, mon-pix/app/templates/assessments/checkpoint.hbs, mon-pix/tests/unit/routes/assessments/checkpoint-test.js
Un utilisateur de Pix doit pouvoir passer une campagne en ayant une certaine en-tête, puis arriver sur une page de résultats intermédiaires, avec la même en-tête.
Remplacement de la course-banner par la campaign-banner et récupération de la campaign pour avoir son titre dans le checkpoint et le donner à la campaign-banner.
=> [#266] [BUGFIX] Affichage de l'en-tête avec le titre (s'il existe) sur les pages de résultats intermédiaires (PF-445).

api/scripts/get-changelog.js, api/tests/unit/scripts/get-changelog_test.js
*Besoin:*
Simplifier la mise en prod
*Changement sur le script:*
-Le Script prend en compte des Merge au format "[FEATURE] Nom de la Pr (PF-Num).", sans numéro de la PR au début > **Suppression du numéro de PR dans le nom de la PR**
-Le numéro de PR est toujours présent dans le Changelog (car récupéré de la PR et non du titre).
-Tri automatiquement les PR par type.
-Remise en place du "v" de "version" dans le numéro de version.
=> [TECH] Amélioration du script récupérant le ChangeLog

api/lib/plugins.js
Pour mieux comprendre ce qui nous arrive en production, une idée est de générer des logs à un format plus facile à exploiter et analyser.
Actuellement les logs que nous générons explicitement dans le code sont au format JSON avec `bunyan`. Mais les logs générés par requête par Hapi sont au format texte.
Cette PR passe les logs Hapi au format JSON quand `NODE_ENV` contient `production` ou `staging`.
=> [TECH] Génération de logs au format JSON

api/lib/infrastructure/airtable.js, api/lib/infrastructure/caches/cache.js, api/lib/infrastructure/caches/in-memory-cache.js, api/lib/infrastructure/caches/preloader.js, api/lib/infrastructure/caches/redis-cache.js, api/lib/infrastructure/caches/redis-client.js, api/lib/settings.js, api/package-lock.json, api/package.json, api/tests/integration/infrastructure/airtable_test.js, api/tests/unit/infrastructure/caches/cache_test.js, api/tests/unit/infrastructure/caches/in-memory-cache_test.js, api/tests/unit/infrastructure/caches/redis-cache_test.js
Aujourd'hui, quand plusieurs requêtes utilisateur ont besoin de la même ressource Airtable, et que celle-ci n'est pas en cache, alors chaque requête va tenter de récupérer la valeur dans Airtable, ce qui provoque une surcharge du service et de grosse lenteurs (voir de l'indisponibilité) de Pix.
Solution: gérer les demandes de resources Airtable similaires via un système de lock.
Quand plusieurs requêtes ont beosin de la même resources Airtable "en même temps" et que celle-ci n'est pas en cache, la première requête va récupérer un lock dans Redis (clé de type "locks:**) avant de faire la requête Airtable. Les requêtes suivantes vont elles aussi essayé de prendre le même lock, mais celui-ci étant déjà pris, vont se faire jeter. Elles vont alors attendre quelques secondes, puis réessayer, …
=> [TECH] Ajout d'un système de lock afin de limiter les requêtes à Airtable (PF-416).

mon-pix/app/routes/login.js, mon-pix/tests/unit/routes/login-test.js
Dans a02f04ef nous avons introduit cette régression en travaillant sur le login SAML.
Il manquait un appel à `super(...)` dans la surcharge d'un `beforeModel`.
On en profite pour ajouter un test qui vérifie le fonctionnement de cette redirection.
=> [BUGFIX] Rétablir la redirection de /connexion vers /compte pour les utilisateurs déjà authentifiés (PF-456)

api/lib/cat/assessment.js, api/lib/domain/strategies/SmartRandom.js, api/tests/unit/domain/strategies/SmartRandom_test.js
En tant qu'utilisateur, je dois pouvoir répondre à une première question, peu importe le niveau des acquis.
Avant : La première question est obligatoirement une question non timée de niveau 2. Si je n'ai pas de niveau 2 non timé, je n'ai pas de question.
Maintenant : La première question est non timée et de niveau 2. Si je n'ai de de question niveau 2 non timé, la première question est non timée et de niveau 1. Si je n'ai de de question niveau 1 non timé, la première question est non timée et de niveau 3. Etc avec les niveaux supérieurs.
=> [FEATURE] Mise à jour de la gestion de la première question posée à l'utilisateur (PF-436).

mon-pix/config/environment.js, orga/config/environment.js
pix.matomo.cloud →stats.pix.fr
Comme la vie est bien faite, les IDs ne changent pas 😄
=> [TECH] Mise à jour des URL pour Matomo (Piwik).

api/db/seeds/data/3rd-to-create/assessment-results.js, api/lib/domain/models/Profile.js, api/tests/unit/domain/models/profile_test.js, api/tests/unit/infrastructure/serializers/jsonapi/profile-serializer_test.js, mon-pix/app/components/competence-level-progress-bar.js, mon-pix/app/templates/components/competence-level-progress-bar.hbs, mon-pix/tests/unit/components/competence-level-progress-bar-test.js
En tant qu'utilisateur de Pix Board, je dois pouvoir voir les mêmes valeurs de niveau dans le CSV des snapshots que dans chaque profil utilisateur.
La plateforme peut poser des questions de niveaux supérieurs si un utilisateur est suffisamment doué. Le "vrai" niveau est stocké en base, mais le niveau "obtenu" et donc affiché à l'utilisateur, sera le niveau maximum (actuellement 5).
Le niveau dans l'affichage du profil utilisateur est plafonné, ce n'était pas le cas lors de la sauvegarde du profil dans la table snapshots. Solution :
- Le profil envoyé au front ou sauvegardé côté snapshots est le même, à savoir le plafonné.
- Le front ne gère plus le plafonnage
Dans un ticket tech ultérieur, on voulait supprimer la classe Score, et couper les liens à cat dans assessmentService. Les 2 …
=> Le CSV des snapshots doit refléter les profils utilisateurs (PF-358).

api/lib/infrastructure/caches/redis-client.js
Notre hébergeur semble de temps en temps déconnecter ou redémarrer le serveur Redis. 
Actuellement cela occasionne un crash de l'application car l'événement `error` remonté par le client Redis n'est pas intercepté, et tout événement `error` émis sans abonné provoque la fin du processus Node.js par défaut (https://nodejs.org/api/events.html#events_error_events).
C'est dommage car le client Redis que nous utilisons (https://www.npmjs.com/package/redis) possède une logique de reconnexion automatique (avec délai exponentiel). Il suffit donc de s'abonner à cet événement `error` pour donner une chance à cette reconnexion d'avoir lieu.
De plus, on active l'option `retry_unfulfilled_commands` qui autorise le client Redis à réessayer les commandes éventuellement impactées par une déconnexion. Ceci …
=> [TECH] Ne pas planter l'application quand Redis est temporairement déconnecté

api/lib/application/organizations/index.js, api/lib/application/organizations/organization-controller.js, api/lib/domain/usecases/find-organizations.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/lib/interfaces/controllers/security-controller.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/application/organizations/index_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/unit/application/organizations/index_test.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/domain/usecases/find-organizations_test.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js
Lien vers le ticket jira : https://1024pix.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=PIX&modal=detail&selectedIssue=PA-60
🤷‍♀️ 🤷‍♂️ Besoin :
Pouvoir effectuer une recherche dans des inputs en laissant le serveur totalement responsable de gérer la pagination ainsi que le filtrage des résultats
👩‍💻👨‍💻Technique :
On réutilise et s'inspire beaucoup de ce qui a été fait pour les users. L'ancienne recherche basée sur la notion de service et appelée `search` a été renommée en `find` pour homogénéité avec les users, et a été transposé d'un `service` à un `usecases`
**Attention limitation importante :** la librairie [qu'on utilise](http://onechiporenko.github.io/ember-models-table/v.2/docs/classes/Components.ModelsTableServerPaginated.html) pour gérer les tables dans Ember est …
=> [FEATURE] Ajouter de la recherche filtrée et paginée des organisations (PA-60)

api/lib/domain/models/Profile.js, api/lib/domain/usecases/get-assessment.js, api/tests/acceptance/application/assessments/assessment-controller-get_test.js, api/tests/unit/domain/usecases/get-assessment_test.js
En tant qu'utilisateur de Pix, lorsque je me positionne sur une compétence et que je la réussi parfaitement, je devrait voir mon niveau plafonné lors de l'affichage de mes résultats (page de fin de positionnement).
Côté back, on ajoutait déjà des propriétés à `assessment` pour pouvoir afficher cette page de résultats. La valeur de `estimatedLevel` n'était pas plafonnée. Pour résoudre ce bug, il a fallu plafonner le niveau envoyé au front pour affichage.
Ce plafonnage est fait côté back puisque le plafonnage du profil est également fait côté back (affichage du profil et partage du profil).
=> [BUGFIX] Le niveau affiché à la fin d'un parcours par compétence devrait être plafonné (PF-492).

api/scripts/delete-assessment.js, api/scripts/delete-user.js, api/scripts/export-organisation-snapshot.js, api/scripts/fill-score-level.js, api/scripts/get-changelog.js, api/scripts/get-results-certifications-old.js, api/scripts/get-results-certifications.js, api/scripts/import-certifications-from-csv.js, api/scripts/recompute-all-score.js, api/scripts/recompute-assessment-results.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js
Many scripts in `/api/scripts` are required by tests (because they are tested), and had side effects if `NODE_ENV` was != `'test'`. This was a problem to run tests on a real Postgres database, which requires `NODE_ENV` to be `production`.
There exists in Node.js a better protection mecanism to avoid side effects when standalone scripts are required instead of run.
So in `/api/scripts`, I changed all instances of:
```
if (process.env.NODE_ENV !== 'test') {
main();
}
```
to:
```
if (require.main === module) {
main();
}
```
=> [BUGFIX] Change /api/scripts to avoid side effects in tests

api/tests/unit/cat/assessment_test.js
🌍 Context
-----------
The test `Unit | Model | Assessment #assessedSkills should return the union of failed and validated skills` was failing randomly.
Cause: it was randomly building two different tubes with identical level 2 skills, which is never supposed to happen.
🗜️Fix
------
This fix gives a fixed name to the two tubes, so the level 2 skills are always different.
=> [BSR] Fix a randomly failing test

api/db/seeds/data/assessments.js, api/db/seeds/data/certification-courses.js, api/lib/domain/usecases/find-certification-assessments.js, api/lib/domain/usecases/find-placement-assessments.js, api/lib/domain/usecases/start-campaign-participation.js, api/lib/domain/usecases/start-placement-assessment.js, api/lib/infrastructure/repositories/assessment-repository.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/unit/domain/usecases/find-certification-assessments_test.js, api/tests/unit/domain/usecases/find-placement-assessments_test.js, api/tests/unit/domain/usecases/start-placement-assessment_test.js, mon-pix/app/routes/courses/create-assessment.js, mon-pix/mirage/routes/find-assessments.js, mon-pix/tests/unit/routes/courses/create-assessment-test.js
En tant qu'utilisateur de Pix, lorsque je retente un compétence, je veux créer une nouvelle évaluation, et non en reprendre une ancienne non terminée.
Lorsqu'on cherche les assessments resumable :
1) chercher les assessments pour le user et le course donnés
2) les trier par date de création
3) prendre le plus récent
4) regarder si le plus récent est commencé ou terminé
Si commencé : c'est une reprise ; si terminé : on crée une nouvelle évaluation.
=> [BUGFIX] Retenter une compétence doit créer une nouvelle évaluation sur la compétence (et non en reprendre une ancienne) (PF-484).

api/scripts/get-pull-requests-to-release-in-prod.js, api/tests/unit/scripts/get-pull-requests-to-release-in-prod_test.js, scripts/release/prepare.sh
Ne plus se baser sur les milestones dans GitHub pour savoir quels PR à livrer en production.
Ne plus faire la manipulation dans GitHub pour ajouter les PR à une milestone.
Utiliser les dates données par l'API de GitHub pour sélectionner les PR à mettre en production.
- Appeler l'API GitHub pour connaitre la date de la dernière MEP.
- Appeler l'API GitHub pour récupérer les PR `closed`
- Filtrer les PR qui sont `merge` dans dev depuis la dernière MEP
- Afficher les PR dans la console pour pouvoir les ajouter au `CHANGELOG.md`
Il n'est plus nécessaire d'appeler le script 
`> node api/scripts/get-changelog.js <numéro de la milestone dans l'url github>`
L'affichage des PR à ajouter dans le `CHANGELOG.md` se fait directement après le script 
`> npm run release:prepare <type de version>`
Pour …
=> [TECH] Simplifier le process de MEP en utilisant l'api GitHub

api/tests/unit/application/assessments/assessment-controller-save_test.js
🌍 Context
-----------
Running the API tests sometimes display a stack trace showing a `UnhandledPromiseRejectionWarning` error, without failing the tests:
```
(node:33509) UnhandledPromiseRejectionWarning: CustomError: No Rows Updated
at Child.<anonymous> (/Users/sebastien.roccaserra/Developer/Pix/pix/api/node_modules/bookshelf/lib/model.js:1128:19)
at Child.tryCatcher (/Users/sebastien.roccaserra/Developer/Pix/pix/api/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/Users/sebastien.roccaserra/Developer/Pix/pix/api/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/Users/sebastien.roccaserra/Developer/Pix/pix/api/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromise0 …
```
=> [TECH] Fix random stack trace message in API tests

api/lib/infrastructure/mail-check.js, api/lib/infrastructure/mailjet.js, api/tests/unit/infrastructure/mailjet_test.js
Notre fournisseur d'envoi d'email, Mailjet, exige que notre taux d'erreur d'envoi reste en-dessous de 8%. Il nous incombe donc de faire le maximum pour éviter de soumettre des adresses erronées à l'envoi.
On utilise la fonction [dns.resolveMx](https://nodejs.org/api/dns.html#dns_dns_resolvemx_hostname_callback) pour vérifier que le domaine de l'adresse possède bien un enregistrement MX. Ceci devrait permettre d'intercepter une bonne partie des adresses en erreur.
Réaliser une inscription avec une adresse dont le domaine n'existe pas.
Constater dans les logs de l'application qu'un message `Could not send email to '…'` a été généré.
On peut aussi vérifier que Mailjet n'a pas été contacté, par exemple en configurant une clé d'API invalide.
=> [BUGFIX] Vérifier le domaine d'une adresse avant de la soumettre à Mailjet (PF-509)

api/lib/application/campaigns/campaign-controller.js, api/lib/application/campaigns/index.js, api/lib/application/organizations/organization-controller.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/unit/application/campaign/campaign-controller_test.js, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
En tant qu'utilisateur de Pix Orga, je veux pouvoir télécharger les résultats du CSV juste après avoir créé une nouvelle campagne.
- Déplacement de la logique de génération du token lors du GET campaigns/:id et non plus lors du GET organizations/:id/campaigns
- Le `campaign#getById` est maintenant accessible uniquement authentifié (nécessaire pour avoir les credentials). Le `campaign#getByCode` est, lui, toujours accessible sans authentification.
=> [BUGFIX] Génération du token des résultats CSV sur la page de détails (PO-187).

docs/CONTRIBUTING.md, docs/PULL_REQUEST_TEMPLATE/pull_request_template.md
Proposition d'intégrer nos standards et guidelines dans le répo, pour la retrouver facilement, la partager au monde, et pouvoir avoir des discussions autour de sa mise à jour (par exemple en utilisant les mêmes process de relecture que ceux qu'on utilise déjà pour le code).
Infos sur les guidelines selon Github :
- https://help.github.com/articles/setting-guidelines-for-repository-contributors/
=> [TECH] Ajoute une première version de nos standards de code

.buildpacks, .slugignore, certif/nginx.conf.erb, mon-pix/nginx.conf.erb, nginx.conf.erb, orga/nginx.conf.erb, package.json, scripts/jira/comment-with-review-app-url.js, scripts/signal_deploy_to_pr.sh
Ne pas faire tourner 4, (5 avec Pix Admin) _review apps_ à chaque PR.
On crée une seule _review app_ pour toutes les applis _front_, qui ne servent que des fichiers statiques. Ça nous laissera donc 2 applications pour chaque PR : une pour l'API, qui ne change pas, et une pour toutes les applications _front_. Dans cette application Scalingo nommée `pix-front-integration-prXXX`, les fichiers de `mon-pix` (_alias_ `app`), `orga` et `certif` sont construits et servis dans des sous-répertoires nommés comme l'application en question, ex. https://pix-front-integration-pr370.scalingo.io/orga/index.html .
Bien entendu, nos applications _front_ ne sont pas préparées à exister dans un sous-répertoire et ne fonctionnent donc pas directement ainsi. C'est pourquoi on a introduit par ailleurs …
=> [TECH] Déployer une seule application "front" pour les "review apps"

mon-pix/app/models/assessment.js, mon-pix/app/routes/assessments/resume.js, mon-pix/tests/acceptance/resume-campaigns-test.js, mon-pix/tests/unit/models/assessment-test.js, mon-pix/tests/unit/routes/assessments/resume-test.js
Dans cette PR, je me suis attaqué à deux problèmes, sur un fichier centrale de l'application front, celui qui gère la reprise d'assessment :
- Permettre à 5 développeurs de travailler en parallèle sur les 5 types d'assessment
- Réduire le coût d'entrée du code avec des techniques simples 
Ce fichier me semblait idéal pour ça parce qu'il mélange beaucoup de choses: on a plein de transitions possibles, certaines que pour certains types d'assessments. 
**Concrètement**, si Benoit débarque et demande, _Au fait, il se passe quoi dans le cas des positionnements si l'utilisateur éteint le navigateur par erreur après avoir envoyé la dernière question, et qu'il reprend la certification ?_  Si vous n'avez pas touché aux assessments depuis un moment, vous ouvrez `resume.js` et vous tombez sur ça …
=> [TECH] Refacto des transition de reprise des assessments 

admin/package-lock.json, admin/package.json, api/package.json, certif/package.json, mon-pix/package.json, orga/package.json, package.json, scripts/release/prepare.sh
Suite à l'ajout de Pix Admin dans le mono repo, nous avons oublier de modifier le script de préparation de la release afin qu'il monte aussi la version de Pix Admin dans son package.json
=> [TECH] Mise à jour du script de préparation de release pour monter aussi la version de PixAdmin.

api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Permettre à un Pix Master de créer une session sans indiquer de `certificationCenterId`.
Bon à savoir : 
- `parseInt(undefined)` → NaN.
- JS considère que NaN === false
- Bookshelf ne peut pas enregister NaN pour un champ de type `Number`
=> [BUGFIX] Créer une session sans ID de centre de certification depuis Pix Admin.

orga/app/styles/pages/authenticated/campaigns/details.scss, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs
- Faire que le message d'erreur lorsque la personne ne rentre pas de libellé soit le même que les autres erreurs
- Dans les détails d'une campagne, renommé "Identifiant" en "Libellé de l'identifiant" et ne pas afficher du tout la zone quand il n'y a pas d'identifiant
- Utiliser la même class `error-message` pour l'erreur
- Mettre la `div` du libellé dans un `if`, et changer le CSS pour que la largeur de la colonne pour l'URL soit toujours la même (40%), et ne devienne pas le 2eme enfant (et se retrouver avec 15%)
:smirk_cat:
=> [FEATURE] Modifier un message d'erreur et l'affichage d'un libellé dans pix Orga (PO-191).

api/lib/application/campaignReports/campaign-report-controller.js, api/lib/application/campaignReports/index.js, api/lib/domain/models/Campaign.js, api/lib/domain/models/CampaignReport.js, api/lib/domain/usecases/get-campaign-report.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/campaign-participation-repository.js, api/lib/infrastructure/repositories/campaign-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-report-serializer.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/lib/routes.js, api/tests/acceptance/application/campaign-report_test.js, api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js, api/tests/unit/application/campaignReports/campaign-report-controller_test.js, api/tests/unit/domain/usecases/get-campaign-report_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, orga/app/components/routes/authenticated/campaigns/details-item.js, orga/app/models/campaign-report.js, orga/app/models/campaign.js, orga/app/routes/authenticated/campaigns/details.js, orga/app/styles/globals/texts.scss, orga/app/styles/pages/authenticated/campaigns/details.scss, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
ETQ Orga Member, JV voir le nb de participants et le nb de profils reçus sur la page de DETAIL d'une campagne.
Création d'un objet campaignReport lié à une campagne, il est récupéré par le front via un 'link' dans le jsonapi de la campagne.
=> [FEATURE] Affiche le nombre de participants et les profils reçus sur la page de détails d'une campagne. (PO-183)

mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_password-reset-demand-form.scss, mon-pix/app/styles/components/_signin-form.scss, mon-pix/app/styles/pages/_sign-form.scss, mon-pix/app/templates/components/password-reset-demand-form.hbs, mon-pix/app/templates/components/reset-password-form.hbs, mon-pix/app/templates/components/signin-form.hbs, mon-pix/app/templates/components/signup-form.hbs, mon-pix/mirage/config.js, mon-pix/mirage/scenarios/default.js, mon-pix/tests/acceptance/password-reset-test.js, mon-pix/tests/integration/components/password-reset-demand-form-test.js, mon-pix/tests/integration/components/reset-password-form-test.js, mon-pix/tests/integration/components/signin-form-test.js, mon-pix/tests/integration/components/signup-form-test.js
Changer du wording sur les pages de reset de mot de passe + email (sur MailJet).
Pour plus de détails : https://1024pix.atlassian.net/browse/PF-497
Du refacto a été fait dans le html/css des pages de login et reset de mot de passe.
La logique suivie est la même que pour Pix Orga : on fait du BEM-like et on sépare le style du positionnement.
On y gagne : réutilisation des éléments de style, pour plus de cohérence dans le design et dans le code. Positionnement spécifique en fonction des pages, avec des possibilité de réutilisation de positionnement si on retrouve les mêmes structures (d'où un fichier sign-form.scss commun au login et aux différentes étapes du workflow de reset de mot de passe).
> sign-form-header__instruction pour le positionnement (.Block__Element)
> sign-form-title2 pour …
=> [FEATURE] Changement de wording sur les pages et email du changement de mot de passe (PF-497)

mon-pix/app/components/progress-bar.js, mon-pix/app/models/answer.js, mon-pix/app/models/assessment.js, mon-pix/app/routes/assessments/resume.js, mon-pix/tests/unit/components/progress-bar-test.js
Les positionnements concernant les campagnes, ainsi que les démo et les preview affichent une barre de progression indiquant le nombre de questions restantes avant le prochain _checkpoint_. Le problème étant que dès que l'utilisateur donne sa réponse, la barre se met à jour instantanément. 
La manifestation la plus laide de problème étant lors de la validation d'une question juste avant le checkpoint, où la barre pleine revient subitement à 1/5, avant que la vue ne soit complètement remplacé par le checkpoint. 
En image ça donne ça : https://1024pix.atlassian.net/secure/RapidBoard.jspa?rapidView=33&projectKey=PIX&modal=detail&selectedIssue=PF-508
Le problème vient d'une des principales forces d'Ember, les `computed properties`. Ces dernières permettent d'être observées et donc de garantir …
=> [BUGFIX] Mise à jour de la barre de progression au bon moment (PF-508).

certif/app/components/routes/authenticated/sessions/list-items.js, certif/app/styles/globals/tables.scss, certif/app/styles/globals/texts.scss, certif/app/templates/components/routes/authenticated/sessions/list-items.hbs, certif/package-lock.json, certif/package.json, certif/tests/acceptance/session-list-test.js, certif/tests/integration/components/routes/authenticated/sessions/list-items-test.js
On souhaite afficher le tableau des sessions de certification en n'utilisant plus ember-table (qu'on a été obligés de forker).
- Suppression de ember-table du package.json
- Fixer la version de Lodash, qui était en 'latest'.
rien en particulier
=> [TECH] Supprimer ember-table de Pix Certif (PF-534).

.circleci/config.yml
Faire de nouveau fonctionner les tests _front_ sur CircleCI, qui ne démarrent plus depuis que l'image `circleci/node:10.15-browsers` a été mise à jour (il y a 3 jours) pour inclure Chrome 73. Le problème a été rencontré par d'autres : https://github.com/GoogleChrome/puppeteer/issues/3774 mais la solution n'est pas encore claire.
En attendant, on force CircleCI à utiliser une version plus ancienne de l'image (`10.15.1-browsers` alors que la dernière est `10.15.3-browsers`) qui fournit Chrome 72 avec lequel les tests fonctionnent bien.
C'est un peu dommage d'avoir à changer la version de Node pour changer la version de Chrome, et on pourrait contourner ça en construisant notre propre image, mais ça ne vaut pas vraiment le coup ici. De plus, en production on utilise actuellement Node 10.15.1 …
=> [TECH] Correction du build CircleCI en forçant Chrome 72

api/lib/domain/usecases/get-assessment.js, api/tests/acceptance/application/assessments/assessment-controller-get_test.js, api/tests/unit/domain/usecases/get-assessment_test.js
A chaque appel à /api/assessments/{id}, on recalculer le résultat de l'assessment, pour pouvoir l'afficher à la fin des résultats de positionnement.
C'est un calcul complexe et inutile, surtout que cette route est appelé à chaque question.
Récupérer les résultats directement de l'assessmentResult s'il existe
Votre pouce a la même longueur que votre nez.
=> [TECH] Ne plus recalculer le résultat de l'assessment à chaque appel (PF-549).

api/package.json, api/tests/tooling/database-builder/database-builder.js
The tables where deleted in the order of insertion, generating foreign key constraint errors in PG.
This commit reverses the order for the deletion, fixing 18 tests for PG.
Les girafes ont la langue bleue.
=> [TECH] DatabaseBuilder: reverse the deletion order

mon-pix/app/components/circle-chart.js, mon-pix/app/styles/components/_circle-chart.scss, mon-pix/app/styles/pages/_skill-review.scss, mon-pix/app/templates/campaigns/skill-review.hbs
En tant qu'utilisateur de mon-pix sous Internet Explorer, je veux pouvoir visualiser correctement ma page de détails de résultats d'un parcours.
=> [BUGFIX] Correction de l'affichage du pourcentage dans le cercle de progression sous IE (PF-552).

api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js, api/tests/acceptance/application/campaign-participation-controller_test.js, api/tests/acceptance/application/users/users-get-campaign-participations_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js, mon-pix/app/routes/compte.js
Une régression était apparu coté front : lorsqu'un utilisateur avait fini sa campagne mais ne l'avait pas partager à son organisation, le bandeau de reprise affichait le message "Vous n'avez pas terminé", plutôt que le message "Vous avez terminé ! Partagez vos résultats".
Savoir si une `campaign-participation` est terminé revient à voir si l'`assessment` lié a un status `completed`. Il faut donc que l'objet `campaign-participation` ait un lien vers son assessment.
Durant nos récents développement, on avait retiré coté API un lien vers l'assessment sur la route `/api/users/{id}/campaign-participations`.
J'ai ajouté un links dans le serializer et Ember fait le reste.
=> [BUGFIX] Afficher le bon message coté front quand l'utilisateur n'a pas partagé sa campagne (PF-541).

admin/app/adapters/application.js, admin/app/adapters/certification-details.js, admin/app/adapters/certification.js, admin/config/environment.js, admin/mirage/config.js, admin/mirage/serializers/organization.js
En tant qu'utilisateur de Pix Admin, je veux pouvoir y accéder et que cela fonctionne :)
Suppression du namespace `/api` dans Pix Admin, de la même manière que les autres appli.
Ce sera mis dans l'api dans PF-551.
=> [BUGFIX] Suppression du namespace `/api` dans Pix Admin.

mon-pix/app/routes/assessments/challenge.js, mon-pix/tests/unit/routes/assessments/challenge-test.js
Quand l'enregistrement d'une réponse échoue, la réponse reste dans le _store_ Ember Data, et dans la collection des réponses de l'_assessment_ en cours, mais sans `id` puisque l'enregistrement n'a pas eu lieu.
Si on continue ensuite (sans recharger la page) l'évaluation jusqu'à la page de résultats, alors celle-ci présente des réponses malformées. Et quand on demande le détail d'une de ces réponses la requête envoyée au serveur est invalide (`answerId` vide).
On s'assure d'oublier la réponse créée en mémoire (ou d'annuler les modifications s'il s'agissait d'une modification de réponse) avec un `rollbackAttributes` bien senti.
Le test colle très exactement à l'implémentation 😿, j'aimerais bien savoir faire autrement.
⌚️ Jusqu'à l'occupation allemande, la France utilisait le même fuseau …
=> [BUGFIX] Ne pas garder en mémoire les réponses dont l'enregistrement a échoué (PF-555)

mon-pix/app/controllers/assessments/checkpoint.js, mon-pix/app/templates/assessments/checkpoint.hbs, mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
Le completionPercentage de smartPlacementProgression est censé être complet quand l'assessment est 'completed' mais l'action de mettre l'assessment à completed se fait après le final checkpoint.
=> [BUGFIX] Affiche 100% d'avancement quoiqu'il arrive sur le dernier checkpoint. (PF-542)

admin/nginx.conf.erb, certif/nginx.conf.erb, mon-pix/nginx.conf.erb, nginx.conf.erb, orga/nginx.conf.erb
On a constaté qu'un nombre non négligeables de navigateurs mettaient en cache le contenu du fichier `index.html` qui sert à démarrer les applications Ember de Pix. En conséquence, ils mettent plus longtemps à se mettre à jour lorsqu'une nouvelle version est déployée, avec le risque d'avoir une application _front_ désynchronisée avec l'API. Pire, on a vu des navigateurs utiliser un ancien `index.html` pour ensuite demander des ressources statiques (ex. `/assets/mon-pix-f54959fb48bfffe11ec408af4553fa60.js`) qui n'existent plus sur le serveur : le résultat étant une erreur ou une page blanche affichée à l'utilisateur.
On utilise les directives Nginx appropriées (`expire`) pour générer les _headers_ de contrôle de cache qui indiquent aux navigateurs quelles ressources peuvent être mises en …
=> [TECH] Spécification de la politique de cache des ressources statiques

mon-pix/app/components/challenge-actions.js, mon-pix/app/components/challenge-item-generic.js, mon-pix/app/templates/components/challenge-actions.hbs, mon-pix/app/templates/components/challenge-item-qcm.hbs, mon-pix/app/templates/components/challenge-item-qcu.hbs, mon-pix/app/templates/components/challenge-item-qroc.hbs, mon-pix/app/templates/components/challenge-item-qrocm.hbs, mon-pix/tests/integration/components/challenge-actions-test.js
En tant que user, je veux pouvois appuyer sur "Entrée" pour valider une réponse d'un parcours.
Désormais, les status des boutons "skip" (je passe) et "validate" (je valide) sont passés depuis `challenge-item-generic` jusqu'à `challenge-actions` pour pouvoir gérer l'état de la `<form />` nouvellement insérée dans le dom.
Les embeds (applications customs) écoutent le keypress Enter et volent la faculté de submit la form en appuyant sur Enter.
=> [BUGFIX] En tant que user, je veux pouvoir appuyer sur "Entrée" pour valider une réponse d'un parcours (PF-566)

mon-pix/app/components/challenge-embed-simulator.js
Jérémy Jade voulais un moyen de savoir quand un embed était lancé pour exécuter une action au démarrage de l'expérience. ✌
Un CustomEvent (https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent).
=> [TECH] Dispatch d'un CustomEvent au lancement d'un Embed (PF-567)

api/tests/docs/jsonapi-serializer.test.js
Il arrive parfois qu'on utilise une librairie dont la documentation laisse quelque peu à désirer, parce qu'elle est inexistante ou parce qu'elle est gigantesque. On se retrouve souvent à devoir : 
- Faire des tests nous même à la main dans un REPL. Inconvénient: il faut s'en rappeler 
- Chercher dans toute la doc. Inconvénient: ça prend beaucoup de temps
- Chercher sur Google et tomber sur un lien Stackoverflow. Inconvénient: risque de réponse osbolète
- Lire le code source. Inconvénient: difficile
Une solution possible est d'exécuter la librairie directement en enregistrant le résultat sous forme de tests unitaires, ce qui a pour effet également de les documents et de faciliter les montées de versions lorsqu'elles contiennent des breaking change.
Ce fichier se veut vivant. Si on cherche …
=> [TECH] Ajout d'un fichier de documentation d'une lib sous forme de tests unitaires

api/tests/integration/infrastructure/repositories/answer-repository_test.js, api/tests/integration/infrastructure/utils/query-builder_test.js
Environ 150 tests d'intégration et d'acceptance échouent sur PG.
Corrige une dizaine de tests d'intégration sur PG, en ajoutant les valeurs nécessaires aux foreign keys dans le setup de la base, ou en ajoutant des critères de tri pour garantir l'ordre de recherche dans PG.
=> Fix a few integration tests on PG

api/lib/infrastructure/repositories/campaign-participation-repository.js, api/tests/acceptance/application/campaign-participations-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js
Les `knowledge-elements` que remontent le repository doivent être unique par `skillId` et triés par date de création.
Rajouter un filtrage applicatif comme c'est le cas dans le `knowledge-elements-repository`.
=> [BUGFIX] Ajout d'un filtre sur l'accès aux knowledge-elements

.circleci/config.yml, README.md, admin/package.json, api/package.json, certif/package.json, mon-pix/package.json, orga/package.json, package.json
- Change all package.json
- Change the Readme.md to be consistant
Fuite mémoire en production
La mise à jour de Node v10.15.1 vers v10.15.3 ne coûte pas chère et peux avec un peu de chance 🍀 résoudre la fuite.
Mise en production rapide plzzz
=> [TECH] Montée de version de Node 10.15.1 à 10.15.3 (pour correction de la fuite mémoire).

api/lib/domain/models/Answer.js, api/lib/domain/models/AnswerStatus.js, api/lib/domain/models/Examiner.js, api/lib/domain/services/solution-service.js, api/tests/unit/domain/services/certification-service_test.js, api/tests/unit/infrastructure/adapters/assessment-adapter_test.js, mon-pix/mirage/fixtures/answers.js
En tant qu'utilisateur de Pix Admin, je voyais une réponse affichée comme "OK" alors que le futur certifié a passé la question.
Correction côté api, parce que cette dernière confondait les status et les values.
Si un utilisateur rentre `#ABAND#` dans sa réponse et valide, la question est enregistrée comme "passée"
=> [BUGFIX] Correction de l'affichage des détails d'une certification pour une réponse "Abandon" (PA-82).

api/scripts/extract-answers.sh
Lorsqu'on a besoin de faire des statistiques sur les réponses, on a besoin de sorties les answers anonymisées avec plusieurs informations liés, et sans avoir de doublons.
Le logiciel utilisé prend des fichiers .csv, avec le header, et maximum de 250 Mo.
Ajout d'un script qui permet, en indiquant la date à partir de laquelle on souhaite les résultats, et la base de données, sort plusieurs fichiers CSV.
Requête très lourde que l'on pourrait peut être optimisée.
Si le "digest" ne se fait pas, lancer au préalable sur la base de données : `CREATE EXTENSION pgcrypto;`
=> [TECH] Ajout d'un script pour récupérer les answers pour les statistiques.

docs/CONTRIBUTING.md
> Dans le code il y a régulièrement plusieurs façons de faire.
> Afin de pouvoir marquer et retrouver des blocs de code exemplaire, à l'état de l'art du jour, cette PR propose d'ajouter le marqueur `// @exemplary` pour identifier ces parties du code.
=> [TECH] Add state of the art markers in the code

mon-pix/app/routes/profilv2.js, mon-pix/app/styles/components/_results-warning.scss, mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/templates/components/results-warning.hbs, mon-pix/app/templates/profilv2.hbs, mon-pix/tests/acceptance/home-page-test.js, mon-pix/tests/acceptance/profilv2-test.js
En tant qu'utilisateur de Pix, je voudrais pouvoir accéder au profil v2 lorsque je suis sur mon profil v1. Inversement, lorsque je suis sur mon profil v2, je veux pouvoir revenir sur mon profil v1.
- Ajout d'un lien en bas de page du profil v1 vers le profil v2.
- Ajout d'un lien en haut de page du profil v2 vers le profil v1.
Complétion des routes mirage afin de tester en acceptance la redirection.
=> [FEATURE] Lier le profil v1 et le profil v2 grâce à un lien cliquable (PF-558).

.adr-dir, docs/adr/0001-enregistrer-les-decisions-concernant-l-architecture.md
Architecture Decision Records = enregistrements de décisions d'architecture.
Le besoin est de pouvoir :
- prendre des décisions concernant l'architecture facilement
- prendre des décisions qui modifient des décisions précédentes facilement
- savoir qu'une décision donnée a été modifiée ou remplacé par une décision ultérieure
- pouvoir comprendre pourquoi une décision a été prise dans le passé.
Pour ça, une pratique qui fonctionne bien est de matérialiser lesdites décisions par des fichiers texte au format Markdown, versionnés avec le code.
Chaque décision suit un formalisme simple et court, avec des images si nécessaire.
- Titre
- Contexte
- Décision
- Status (pas forcément utile, le mécanisme PR peut remplacer ce paragraphe)
- Conséquences
Voir aussi :
- …
=> [TECH] Ajoute le premier enregistrement d'architecture (ADR)

mon-pix/app/routes/competence-details.js, mon-pix/app/styles/components/_circle-chart.scss, mon-pix/app/styles/components/_competence-card.scss, mon-pix/app/styles/globals/_buttons.scss, mon-pix/app/styles/pages/_competence-details.scss, mon-pix/app/templates/competence-details.hbs, mon-pix/app/templates/components/circle-chart.hbs, mon-pix/app/templates/components/competence-card.hbs, mon-pix/mirage/routes/get-scorecards.js, mon-pix/tests/acceptance/competence-details-test.js, mon-pix/tests/acceptance/profilv2-test.js
En tant qu'utilisateur de Pix, lorsque je vois mon profil V2, je veux pouvoir cliquer sur la carte d'une compétence (le cercle) et être redirigé vers la page de détails d'une compétence.
- Ajout d'un lien sur le cercle
- Modification du svg pour que le bord du rond colle au bord du svg afin qu'on aie un joli rond gris au hover
- Ajout du bouton de retour sur la route competence-details
Le cercle autour est à garder pour la vraie implémentation du hover de la carte entière.
=> [FEATURE] Lier la carte de la compétence à la page de détails de cette compétence (PF-554).

mon-pix/app/styles/components/_challenge-response.scss, mon-pix/app/styles/globals/_redesign-inputs.scss
Avant on avait ça:
Maintenant c'est aligné:
=> [BUGFIX] Corriger l'alignement des listes à puces pour les phrases trop longues (PF-141)

api/db/migrations/20190503173617_add_courseId_index_to_assessments_table.js
De nombreuses requêtes du types : `select assessments.* from assessments where assessments."courseId" in ('1234');`
Prennent du temps à s'exécuter sur notre environnement de production.
Ajout d'un indexe sur la colonne `courseId`.
Une page du Pix wiki documente le sujet -> [page du Wiki](https://1024pix.atlassian.net/wiki/spaces/DEV/pages/883851310/2019-05-03+Blocages+de+la+prod+pb+de+CPU+Postgres)
=> Ajoute un indexe sur la colonne courseId de la table assessments

mon-pix/app/styles/components/_circle-chart.scss
Avant les niveau d'une compétence s'affichaient mal sous IE:
Contraindre `left` à `0` sur le text des cercles de progression pour rétablir un affichage correct.
=> [BUGFIX] Corriger le problème d'affichage des niveaux sous IE. (PF-595)

mon-pix/app/components/qrocm-ind-solution-panel.js, mon-pix/app/styles/components/_qrocm-solution-panel.scss, mon-pix/app/templates/components/qrocm-ind-solution-panel.hbs, mon-pix/tests/integration/components/qrocm-ind-solution-panel-test.js, mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
Le texte des réponses à un QCROQM-ind s'affiche mal, il était optimisé pour les QCROQM-ind sous forme le liste:
Corriger la disposition des réponses, remplacer les listes (div) par des blocks de texte inline:
Un compromis a été fait sur la margin entre deux labels
=> [BUGFIX] Corriger la disposition des réponses d'un QCROQM-ind (PF-570).

mon-pix/app/templates/components/warning-page.hbs
Le wording de la page d'avertissement du chronomètre laissait sous-entendre que toute la suite du parcours serait chronométré. 
Modifier le wording pour préciser qu'uniquement la question suivante sera chronométrée.
=> [FEATURE] Modifier le wording de la page d'avertissement du chronomètre. (PF-115)

mon-pix/app/controllers/assessments/checkpoint.js
La barre de progression est cassée:
```
Uncaught Error: Assertion Failed: You attempted to access the `completionPercentage` property (of <(unknown):ember640>).
Since Ember 3.1, this is usually fine as you no longer need to use `.get()`
to access computed properties. However, in this case, the object in question
is a special kind of Ember object (a proxy). Therefore, it is still necessary
to use `.get('completionPercentage')` in this case.
```
Réutiliser `this.get`.
=> [BUGFIX] Rétablir l'affichage de la barre de progression d'un checkpoint. (PF-597)

mon-pix/app/routes/competence-details.js
Le circle chart d'une compétence n'était pas MAJ lors d'un changement de la propriété `pixScoreAheadOfNextLevel` (lors d'une update de `scorecard`).
Reloader la `scorecard` sur la page de `compétence-details`
=> [BUGFIX] Unifier l'affichage du cercle de progression d'une compétence (pf-599)

mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/styles/pages/_profilv2.scss, mon-pix/app/templates/profilv2.hbs, mon-pix/tests/acceptance/profilv2-test.js
Les utilisateurs vont progressivement découvrir un tout nouvel affichage de leur profil. Il est essentiel de leur expliquer son fonctionnement.
Nous affichons un lien vers https://pix.fr/actualites/votre-profil-evolue en mode target pour renseigner l'utilisateur.
Le clic sur le lien ouvre automatiquement un nouvel onglet.
=> [FEATURE] Afficher un lien temporaire d'explications pour Profil v2(PF-589).

mon-pix/app/templates/components/warning-page.hbs
suite à la démo, y'a eu un petit feedback sur le ticket PF-115. Tu peux remplacer le mot 'épreuve' par 'question' dans la phrase suivante please: 'Vous pourrez continuer à répondre ensuite, mais l’épreuve ne sera pas considérée comme réussie.' C'est pour la V2.41.0, pour rester cohérent. Thanks!
=> [BUGFIX] Correction d'une typo dans la modale de prévention sur support mobile.

mon-pix/app/components/scorecard-details.js, mon-pix/app/helpers/replace-zero-by-dash.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_competence-card.scss, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/styles/globals/_text.scss, mon-pix/app/templates/components/competence-card.hbs, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/package-lock.json, mon-pix/tests/acceptance/competence-details-test.js, mon-pix/tests/acceptance/profilv2-test.js, mon-pix/tests/integration/components/competence-card-test.js, mon-pix/tests/integration/components/scorecard-details-test.js, mon-pix/tests/unit/components/scorecard-details.js, mon-pix/tests/unit/helpers/replace-zero-by-dash-test.js
Le design de scorecard-details n'était pas à jour. En plus il était offensant pour les utilisateurs car il affichait des zéros partout, ce qui peut faire très mal d'après les experts en psychologix.
Remplacer ces vilains zéros par des tirets PC, ajouter un bouton "Commencer/Reprendre".
=> [FEATURE] Modification du design de scorecard-details (PF-594)

.gitignore, api/scripts/extract-answers-reference-list, api/scripts/extract-answers.sh
Lors d'une extraction d'answers, nous avons remarqué que le script 
* ne s'exécutait pas sur `MacOS` ;
* qu'il pouvait être compliqué à utiliser;
* qu'il était trop lent de façon générale.
Désormais, le script :
* est auto-suffisant (pas d'autres lignes de commande à utiliser en amont);
* créé le container Docker avec `docker-compose`;
* utilise des options de lignes de commande compatibles sur `MacOS` et `Linux`;
* utilise 2 core de CPU pour aller plus vite;
* utilise une liste de référence pour éviter la génération de tables et de `foreign keys` superflues, qui prenaient un temps considérable ;
* prend en argument `$1` le fichier `PostgreSQL` ;
* prend en argument `$2`la date et l'heure souhaitées ;
* nettoie le container Docker et le volume associé.
Pour rendre les commandes `Linux` …
=> [TECH] Améliorer le script d'extraction d'answers.

api/package.json
Depuis l'intégration de `node-heapdump` dans #478, le script `npm run start:watch` de l'API ne fonctionne plus : l'application ne redémarre plus quand un fichier est modifié, et au lieu de ça un fichier `heapdump-….heapsnapshot` est créé dans le répertoire `api`.
Il s'avère que `node-heapdump` installe un gestionnaire du signal `SIGUSR2` pour pouvoir déclencher des _dumps_. Mais `nodemon` utilise par défaut le signal `SIGUSR2` pour arrêter le processus de l'application en cas de changement.
On ajoute donc une option à la ligne de commande de `nodemon` pour éviter le conflit en utilisant `SIGTERM` à la place.
Pour en savoir plus : https://jvns.ca/blog/2016/06/13/should-you-be-scared-of-signals/
=> Réparer le script `npm run start:watch` de l'API

api/db/seeds/seed.js
Les seeds ne remplissaient plus la table Answers
Remise en place de l'appel à `answersBuilder`
Ce changement permet de re-tester les certifications avec UserPix1
=> [TECH] Remise en place des Answers dans les seeds.

high-level-tests/e2e/cypress/integration/profilv2.feature, high-level-tests/e2e/cypress/support/step_definitions/profilv2.js
On manque de scénarios Cypress.
Ajout d'un scénario d'accès à la page de détails d'une compétence via le profilv2
=> [TECH] Ajout de scénarios Cypress.

api/db/migrations/20190520161908_add_status_to_competence_evaluations.js, api/lib/domain/constants.js, api/lib/domain/models/CompetenceEvaluation.js, api/lib/domain/models/Scorecard.js, api/lib/domain/usecases/get-scorecard.js, api/lib/domain/usecases/get-user-scorecards.js, api/lib/domain/usecases/start-or-resume-competence-evaluation.js, api/lib/infrastructure/repositories/assessment-repository.js, api/lib/infrastructure/repositories/competence-evaluation-repository.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/lib/infrastructure/serializers/jsonapi/competence-evaluation-serializer.js, api/tests/acceptance/application/competence-evaluation-controller_test.js, api/tests/acceptance/application/scorecard-controller_test.js, api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js, api/tests/integration/infrastructure/repositories/competence-evaluation-repository_test.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/tooling/database-builder/factory/build-competence-evaluation.js, api/tests/tooling/domain-builder/factory/build-competence-evaluation.js, api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js, api/tests/unit/domain/models/Scorecard_test.js, api/tests/unit/domain/usecases/get-scorecard_test.js, api/tests/unit/domain/usecases/get-user-scorecards_test.js, api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js, api/tests/unit/infrastructure/serializers/jsonapi/competence-evaluation-serializer_test.js, mon-pix/app/components/competence-card.js, mon-pix/app/models/competence-evaluation.js, mon-pix/tests/unit/components/competence-card-test.js
A l'heure actuelle, l'objet `competenceEvaluation` ne possède pas de champs explicite permettant de connaître son état. Ce dernier est reconstitué dynamiquement à travers notamment l'objet du domaine `Scorecard` de sorte que : 
- Si au moins un `knowledgeElement` pour la compétence existe, alors il est en `not_started`
- Si l'`assessment` existe et est `completed` alors il sera en `completed` 
- Autrement il sera en `started`
Cette PR embarque une migration de schéma ajoutant un champs `status` aux compétences évaluations et gère les 3 états de façon explicite et au plus proche des cas d'utilisations qui déclenchent les transitions, plutôt qu'en les reconstituant de façon ad-hoc à postériori.
Les nouveaux états sont 
- `started` lorsqu'une compétence évaluation est créée pour la première …
=> [FEATURE] Ajout d'un champs status aux compétences évaluations (PF-579-3).

api/lib/domain/services/user-service.js
Pour pouvoir certifier un profil v2, on doit désormais créer un `course` en fonction des `knowledge elements` et non plus à partir du dernier positionnement (v1) par compétence.
Or, cet `assessment` est utilisé à plusieurs endroits dans la fonction qui sélectionne les questions à poser pour créer le `course` de certification.
De plus, ladite fonction utilise des promesses qui font parfois passe-plat, ce qui rend la compréhension du code difficile.
Cette PR est un remaniement qui permet de s'appuyer le moins possible sur les positionnements.
Comme tout bon remaniement, cette PR ne modifie pas le comportement. Jonathan a généré et comparé les courses des 500 dernières personnes à avoir été certifiées avant et après le remaniement, il n'y a pas de régression.
La deuxième édition du livre …
=> [TECH] Remaniement de la génération du profil de certification v1

mon-pix/app/index.html, mon-pix/app/templates/components/learning-more-panel.hbs, mon-pix/app/templates/components/modal-mobile.hbs, mon-pix/app/templates/components/password-reset-demand-form.hbs, mon-pix/app/templates/components/pix-logo.hbs, mon-pix/app/templates/components/reset-password-form.hbs, mon-pix/app/templates/components/signin-form.hbs, mon-pix/app/templates/components/signup-form.hbs, mon-pix/app/templates/components/tutorial-panel.hbs, mon-pix/tests/integration/components/modal-mobile-test.js, mon-pix/tests/integration/components/pix-logo-test.js
Le mot "PIX" c'est un peu lourd, on a préféré "Pix".
Remplacer "PIX" par "Pix".
J'ai modifié les Terms of Services de Orga et Certif car ils utilisaient Pix et PIX pour désigner Pix sous toutes ses formes. J'ai donc voulu unifier mais si pour des raisons légales il n'est pas permis de changer ces documents j'enlève les commits en question.
=> [FEATURE] Renommer PIX en Pix (PF-609)

api/lib/application/users/index.js, api/lib/application/users/user-controller.js, api/lib/domain/usecases/index.js, api/lib/domain/usecases/reset-competence-evaluation.js, api/lib/infrastructure/repositories/competence-evaluation-repository.js, api/tests/acceptance/application/users/users-controller-reset-competence-evaluation_test.js, api/tests/unit/domain/usecases/reset-competence-evaluation_test.js
Pour l'instant, il n'existe aucune manière de réinitialiser une compétence dans le cadre du profil v2.
Créer une route `/api/users/:id/competences/:id/reset`, son controller, et un usecase `resetCompetenceEvaluation` afin de permettre à l'utilisateur de réinitialiser une compétence.
=> [FEATURE] Création d'une route pour reset une CompetenceEvaluation (PF-579-4).

mon-pix/app/components/scorecard-details.js, mon-pix/tests/integration/components/scorecard-details-test.js, mon-pix/tests/unit/components/scorecard-details-test.js, mon-pix/tests/unit/components/scorecard-details.js
La mention "n Pix avant le niveau x" était visible lorsque le parcours était terminé et que l'utilisateur ne disposait pas de moyen de progresser ce qui pouvait être frustrant.
La cacher si scorecard.isFinished
Elle réapparaîtra au bout de 7 jours dans les PRs suivantes lorsque l'utilisateur pourra reset sa competenceEvaluation.
=> [FEATURE] Cacher "n Pix avant le niveau x" si le parcours est terminé (PF-610)

api/lib/domain/constants.js, api/lib/domain/errors.js, api/lib/domain/models/KnowledgeElement.js, api/lib/domain/models/Scorecard.js, api/lib/domain/usecases/get-scorecard.js, api/lib/domain/usecases/reset-competence-evaluation.js, api/lib/domain/usecases/start-or-resume-competence-evaluation.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js, api/lib/infrastructure/utils/error-manager.js, api/tests/acceptance/application/scorecard-controller_test.js, api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js, api/tests/acceptance/application/users/users-controller-reset-competence-evaluation_test.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/unit/domain/models/KnowledgeElement_test.js, api/tests/unit/domain/models/Scorecard_test.js, api/tests/unit/domain/usecases/get-scorecard_test.js, api/tests/unit/domain/usecases/reset-competence-evaluation_test.js
Je veux pouvoir réinitialiser une compétence, seulement après un délai de 7 jours durant lequel je n'ai répondu à aucune question portant sur cette même compétence.
- Calcul de ce délai et ajout de celui-ci au sein de la Scorecard pour qu'il soit affiché côté front (dans une PR ultérieure)
- Vérification lors du reset que ce délai est respecté
=> [FEATURE] Ajout du délai de 7 jours pour réinitialiser une évaluation de compétence (PF-579-6).

api/lib/domain/models/Scorecard.js, api/tests/unit/domain/models/Scorecard_test.js
Une fois une campagne terminée, certaines compétences possédaient des Pix avec une scorecard NOT_STARTED. Le bouton était alors à l'état "Commencer" au lieu de "Reprendre"
Faire une vérification de l'existence de knowledgeElements pour determiner le status d'une scorecard.
=> [BUGFIX] Afficher "Reprendre" si la scorecard possède des knowledgeElements (PF-618)

.circleci/config.yml
Les tests end to end échouent régulièrement au démarrage, avec l'erreur :
> Build Error (broccoli-persistent-filter:Babel > [Babel: ember-lodash]) in lodash/snakeCase.js
C'est dû au fait qu'Ember utilise le nombre de CPUs de la CI, qui est très grand, pour spawner des process de build npm. Or sur la CI, s'il y a beaucoup de CPUs, très peu nous sont réellement assignés.
En suivant cette recommandation, on limite explicitement le nb de jobs créés par Ember pour les fronts :
- https://github.com/ember-cli/ember-cli/blob/master/docs/build-concurrency.md
=> [TECH] Améliore la probabilité de succès des tests end to end

admin/app/models/certification.js, admin/app/templates/authenticated/certifications/single/info.hbs, api/db/migrations/20190606125500_add_is-v2-certification_column_in_certification-course.js, api/db/seeds/data/certification-courses-builder.js, api/lib/domain/models/CertificationCourse.js, api/lib/domain/services/certification-service.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/tooling/database-builder/factory/build-certification-course.js, api/tests/tooling/domain-builder/factory/build-certification-course.js, api/tests/unit/domain/services/certification-service_test.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js
Avant de lancer les certifications du profil v2, il est important de pouvoir se souvenir du type de certification passé par l'utilisateur. Ensuite le scoring de la certification pourra se baser sur cette donnée.
Ajout d'une colonne `isV2Certification` dans la table `certificationCourse`.
Pour pouvoir valider ça, nous avons ajouté l'affichage du type de la certification dans Pix Admin.
Il faudra se souvenir de ré-initialiser les `assessment-results` des certifications V2 dès que le scoring V2 sera prêt.
=> [FEATURE] Afficher la version de la certification dans Pix Admin (PF-577).

mon-pix/app/templates/components/qroc-proposal.hbs, mon-pix/app/templates/components/qrocm-proposal.hbs, mon-pix/tests/integration/components/qroc-proposal-test.js, mon-pix/tests/integration/components/qrocm-proposal-test.js
L'autocomplétion des QROC et QROCM n'est pas désactivé.
Rajouter `autocomplete="off"` sur les inputs des QROC et QROCM.
J'ai rajouté un élément d'accessibilité manquant sur QROCM.
=> [FEATURE] Désactiver l'autocomplétion des QROC et QROCM (PF-627)

mon-pix/app/routes/challenge-preview.js
Les previews ne s'affichaient plus
Les previews envoyaient encore les objets plutot que les id quand on transitait vers la route assessments.challenge, ce qui posait problème.
La transition a donc été réécrite
=> [BUGFIX] Remise en place des previews.

mon-pix/app/styles/globals/_palette.scss, mon-pix/app/styles/pages/_skill-review.scss
La page de résultats d'une campagne ne s'imprime pas correctement.
Ajout d'une media query `print` pour afficher correctement le contenu lors d'une impression.
Le `background-color` ne s'imprime pas par défaut, il a été remplacé par des `border-color`.
La media query a été rajoutée à la fin du fichier CSS correspondant. Si d'autres pages doivent être modifiées, envisager la création d'un fichier `print.scss` spécifique ?
=> [BUGFIX] Ajustements sur le CSS pour imprimer la page de résultats d'une campagne (PF-583).

api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/assessment-result-repository_test.js
> Les tests d'intégration d'assessment-repository et d'assessment-result-repository utilisent knex.
> Utiliser si possible le helper DatabaseBuilder
=> [TECH] Remaniement des tests d'intégration d'assessment-repository

mon-pix/config/environment.js
L'API du plugin pix-auto-answer démarre en local sur le port 3000. Quand on veut l'utiliser sur Pix en local, on doit donc démarrer l'API Pix sur un autre port.
Pb : on ne peut pas configurer l'API_HOST de mon-pix en environnement `development`.
Permettre de configurer l'API_HOST de mon-pix en environnement `development`.
=> [TECH] Permettre de configurer API_HOST sur mon-pix en dev

mon-pix/app/components/feedback-panel.js, mon-pix/app/styles/components/_feedback-panel.scss, mon-pix/app/templates/components/comparison-window.hbs, mon-pix/app/templates/components/feedback-panel.hbs, mon-pix/tests/acceptance/challenge-feedback-test.js, mon-pix/tests/integration/components/comparison-window-test.js, mon-pix/tests/integration/components/feedback-panel-test.js, mon-pix/tests/unit/components/feedback-panel-test.js
L'UX de la fenêtre pour signaler un problème n'est pas très clair :
- infos rgpd mises trop en avant
- bouton annuler non-intuitif
- déplacement du texte rgpd après la textarea
- suppression du bouton annuler
- lien d'ouverture maintenant un toggle
=> [FEATURE] Retouche de la fenêtre pour signaler un problème. (PF-612)

orga/app/components/routes/authenticated/campaigns/details/collective-results-tab.js, orga/app/models/campaign-collective-result.js, orga/app/routes/authenticated/campaigns/details/collective-results.js, orga/app/styles/pages/authenticated/campaigns/details/participants/participant-results.scss, orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs, orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs, orga/tests/integration/components/routes/authenticated/campaigns/details/participants/results-item-test.js, orga/tests/unit/models/campaign-collective-results-test.js
Pour le Sup et Sco, on souhaite améliorer l'affichage des infos de résultat d'une campagne.
- Supprimer Compétences testées
Déplacement des éléments suivants:
- Acquis validés
- Acquis évalués
- Résultats partagés
- Résultat (en %)
Le visuel cible est encore en cours de réflexion.
- https://projects.invisionapp.com/share/GWP9OGTXFPK/#/screens/333006833
=> [FEATURE] Affichage de la moyenne des résultats d'une campagne. (PO-197)

api/db/migrations/20190621155332_create_member_organization_role.js
Les prescripteurs ne pouvaient être que des administrateurs.
Maintenant ils peuvent être de simples membres sans droits d'administration. Via une migration.
Le nommage MEMBER/Membre peut être discuté.
=> [TECH] Ajout du role MEMBER dans Pix Admin/Orga (PA-95)

orga/app/routes/authenticated/campaigns/details/collective-results.js
> Sous IE, l'onglet des résultats collectifs ne s'affiche plus
> Lors de la récupération du model, supprimer les async/await
=> [BUGFIX] Affichage des résultats collectifs sous IE (PO-212)

api/lib/domain/services/scorecard-service.js, api/lib/infrastructure/repositories/assessment-repository.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/unit/domain/services/scorecard-service_test.js
Lorsqu'on faisait une Remise à Zéro plusieurs fois sur la même compétence, et affectant la même campagne, on avait une erreur 500, suite à un `Cannot read property 'campaign' of null`
Ce bug était lié au fait qu'on retentait de reset un assessment de campagne qui avait déjà été reset.
On ne récupère pas les assessments  `aborted`
Ajout de l'utilisation de _.get() pour récupérer les informations sur la campagne, pour éviter une erreur de type `Cannot read property 'campaign' of null`
=> [BUGFIX] Erreur lors de la Remise à Zéro impactant plusieurs fois la même campagne (PF-717).

mon-pix/app/components/progress-bar.js, mon-pix/app/models/assessment-progression.js, mon-pix/app/routes/assessments/challenge.js, mon-pix/tests/unit/components/progress-bar-test.js, mon-pix/tests/unit/models/assessment-progress-test.js
Lors des DEMO et des CERTIFICATIONS, la barre de progression disparaissait lorsqu'on effectuait un refresh. 
Il convient de s'assurer que le model reload bien les relationships avant de rendre la vue, quelque soit le point d'entrée.
J'ai essayé de mettre des test cypress mais il faut fixturer un profil certifiable ce que je ne parvenais pas à faire de la bonne façon et rapidement. Je laisse ça pour un autre ticket, où l'on écrira une batterie de test cypress.
=> [BUGFIX] Fix de la disparition de la barre de progression en démo et en certification

mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/tests/acceptance/competence-details-test.js
Pour la mise en prod : retirer le bouton remise à zéro.
A remettre après la mise à jour.
=> [TECH] Retirer le bouton pour la remise à zéro.

api/db/migrations/20190626111900_add_campaign_participation_unique_constraint_on_user_and_campaign.js
Actuellement dans notre DB il est possible d'avoir plusieurs Campaign-Participation pour un même User. 
Nous avons donc plusieurs lignes dans la DB qui posent des soucis à l'affichage, au résultat calculé ...
Nous avons pris le parti de mettre une contrainte dans notre table "Campaign-participation"
- Utilisation d'une Unique sur les colonnes "UserId" et "campaignId".
- Utilisation du Delete sur les doublons déjà présents en base.
=> [BUGFIX] Nettoyage des données dans la DB. Puis plus de doublon dans Campaign-participation. (PF-702)

mon-pix/app/components/feedback-panel.js, mon-pix/app/templates/components/challenge-item-qcm.hbs, mon-pix/app/templates/components/challenge-item-qcu.hbs, mon-pix/app/templates/components/challenge-item-qroc.hbs, mon-pix/app/templates/components/challenge-item-qrocm.hbs, mon-pix/app/templates/components/feedback-panel.hbs, mon-pix/tests/integration/components/feedback-panel-test.js, mon-pix/tests/unit/components/feedback-panel-test.js
Le formulaire de feedback restait déroulé après avoir submit ou changé de question.
Utiliser le hook `didUpdateAttrs` pour re-render correctement le composant.
=> [BUGFIX] Vider et replier le feedback_panel après avoir envoyé le commentaire. (PF-708)

api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/tooling/database-builder/factory/build-user.js
> Dans l'objectif de faire passer tous les tests sous PostgreSQL, des modifications doivent être faites dans les tests d'intégration de user-repository.
> Utilisation du helper Database-factory-builUser
=> [TECH] Remaniement des tests d'intégration de user-repository

api/lib/application/competence-evaluations/competence-evaluation-controller.js, api/lib/application/competence-evaluations/index.js, api/lib/application/users/index.js, api/lib/domain/usecases/start-or-resume-competence-evaluation.js, api/tests/acceptance/application/competence-evaluation-controller_test.js, api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js, api/tests/unit/application/competence-evaluations/competence-evaluation-controller_test.js, api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js, mon-pix/app/adapters/competence-evaluation.js, mon-pix/app/adapters/scorecard.js, mon-pix/app/routes/competences/resume.js, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/mirage/config.js, mon-pix/mirage/routes/post-competence-evaluation.js, mon-pix/tests/acceptance/competence-details-test.js, mon-pix/tests/unit/adapters/competence-evaluation-test.js, mon-pix/tests/unit/adapters/user-test.js, mon-pix/tests/unit/routes/competences/resume-test.js
Quand on commence un parcours par competence, qu'on le reset et qu'on recommence, le parcours reprend là où il en était au lieu de repartir à zéro.
Le problème vient de l'enchaînement du `peekAll` suivi d'un `createRecord` qui ne gère pas le cas où la competenceEvaluation est `reset`, il a été donc été décidé de :
- Remplacer cette logique par un `queryRecord` spécifique pour appeler le endpoint dédié. 
- Remplacer le POST /competence-evaluations en POST /competence-evaluations/start-or-resume.
=> [BUGFIX] La remise à zéro plante lors de la 2e raz (PF-740).

api/lib/infrastructure/repositories/campaign-collective-result-repository.js, api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
1 - Un utilisateur a remis à zéro une compétence
2 - Un utilisateur est le seul à passer une campagne portant sur cette compétence
3 - il la termine et envoie ses résultats
Observé : Dans Pix Orga, les résultats individuels ne sont pas les même que les résultats individuels alors qu'il n'y a qu'une seule personne.
Attendu : Dans Pix Orga les résultats collectifs doivent être les même que les résultats individuels.
Lors de la récupération des résultats collectifs, l'enchaînement des actions de filtres et tris ne se faisait pas dans le bon ordre.
Pour les knowledge elements validés, on doit : 
1 - trier par date
2 - faire un unique par skillId pour avoir le dernier
3 - trier par knowledge elements validés
Avant : 
1 - trier par knowledge elements validés
2 - trier par date
3 - faire un …
=> [BUGFIX] Sortir les résultats collectifs avec les bonnes statistiques (PO-214).

api/db/migrations/20190701102247_remove_organizationRoleId_column.js
Une typo, nous empêche de jouer une migration et de déployer sur l'environnement d'intégration.
Fix de la typo.
Ré-écrtiure, du `down` pour qui soit correct.
=> [BUGFIX] Correction de la faute de frappe du nom de la colonne.

api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/settings.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Les certifications v2 sont en production depuis le 7 juin, on n'a plus besoin de pouvoir revenir sur un fonctionnement "certifs v1 uniquement".
De plus, conserver des bascules trop longtemps revient à du code mort et conduit à une combinatoire complexe.
Supprimer la bascule FT_USE_ONLY_V1_CERTIFICATION.
Plus d'infos sur la gestion des bascules en #543.
=> [TECH] Supprime la bascule FT_USE_ONLY_V1_CERTIFICATION

admin/app/services/session-info-service.js, admin/tests/unit/services/session-info-service-test.js
Pour une session de certification dans Pix Admin, lors d'un export de résultats après jury, le fichier .ods généré ne met pas à jour le contenu de la colonne "Identifiant Externe"
Le problème venait du fait que notre parser ne traduisait pas toutes les valeurs des cellules en string. Si la cellule parsée ne contient qu'un nombre, par exemple 42, on obtenait `42` et non `'42'`. Notre condition de mise-à-jour de fonctionnait alors pas comme attendu.
On a rajouté une conversion en String en amont, et modifié la condition de non-mise à jour d'un champ.
Info : `_.isEmpty(42)` renverra true.
En appliquant un `_.trim` sur chaque valeur parsée, on effectue en même temps une conversion en string. `_.isEmpty('42')` renverra false
On en a profité pour refacto une suite d'appels à …
=> [BUGFIX] parsing des externalId dans l'export des résultats d'une certif (PA-97).

api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
On a détecté en intégration que suite à #563 on n'arrive plus à démarrer une certification sur `dev`.
Corriger le code défaillant, et ajouter des contraintes dans les tests unitaires qui reproduisent ce bug.
Pour l'histoire, lors d'un merge on est passé de
```
userService.getProfileToCertifyV1(userId, now), 
```
à 
```
userService.getProfileToCertifyV1({ userId, now }), 
```
alors que l'interface de la fonction est passé de 
```
getProfileToCertifyV1(userId, limitDate) {
```
à
```
getProfileToCertifyV1({ userId, limitDate }) { 
```
Il se trouve que ce code n'est pas testé (pas de test d'acceptance) :(
=> [BUGFIX] Corrige le démarrage des certifications

api/lib/domain/services/mail-service.js, api/tests/unit/domain/services/mail-service_test.js
En regardant quels sont nos usages de MailJet d'un point de vue applicatif (i.e. hors Discourse & cie.), je me suis rendu compte qu'on a une méthode morte. #RGPD
L'objet de cette PR consiste à supprimer ce code mort.
> **Remarque** : le template - dont l'ID est `129291` - a été supprimé de MailJet.
=> [TECH] Supprime la méthtode inutile mail-service#sendWelcomeEmail

orga/app/styles/pages/authenticated/team/list.scss, orga/ember-cli-build.js
Le site ne fonctionne plus sous IE11
Le message d'erreur est "Promise is undefined"
Enlever *async/await* du service **current-user**.
=> [BUGFIX] PixOrga ne fonctionne plus sous IE11 (PO-221).

api/lib/application/users/user-controller.js, api/tests/unit/application/users/user-controller_test.js
La fonction `userController.getAuthenticatedUserProfile()`, qui répond au  `GET /api/users/me/profile` :
- n'était pas testée ;
- était décorée d'un beau `// FIXME: pas de tests ?!` ;
- utilisait deux `.then()`, la version `await` serait plus lisible.
- ajouter un test ;
- une fois le test ajouté, convertir les `.then()` en `await`.
J'avais envie de m'entrainer sur un refactoring, sur "Use Mocks for Commands; Stubs for Queries" et d'avoir des retours.
Refs :
- https://blog.ploeh.dk/2013/10/23/mocks-for-commands-stubs-for-queries/
- http://geepawhill.org/always-small-always-better-always-wrong/
=> [TECH] Refactoring du contrôleur de `GET /api/users/me/profile`

api/lib/application/answers/answer-controller.js, api/lib/domain/errors.js, api/lib/domain/models/User.js, api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/domain/usecases/get-current-user.js, api/lib/infrastructure/data/user.js, api/lib/infrastructure/repositories/user-repository.js, api/lib/infrastructure/serializers/jsonapi/user-serializer.js, api/lib/infrastructure/utils/error-manager.js, api/tests/acceptance/application/users/users-controller-get-current-user_test.js, api/tests/acceptance/application/users/users-controller-get-user_test.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js, api/tests/unit/domain/usecases/get-current-user_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js, mon-pix/app/models/user.js, mon-pix/app/routes/compte.js, mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/templates/profilv2.hbs, mon-pix/mirage/routes/post-authentications.js, mon-pix/mirage/scenarios/default.js, mon-pix/tests/acceptance/compte-authentication-and-profile-test.js, mon-pix/tests/acceptance/profilv2-test.js, mon-pix/tests/helpers/testing.js
On veut créer les nouveaux users directement en profil v2.
Utiliser la colonne isProfileV2 le temps de la migration pour afficher le profil v2 aux nouveaux utilisateurs.
On a par ailleurs bloqué l'accès à profil v1 pour ces utilisateurs.
=> [FEATURE] Création des nouveaux comptes en profil v2 (PF-741).

mon-pix/app/controllers/campaigns/fill-in-campaign-code.js, mon-pix/app/router.js, mon-pix/app/routes/campaigns/fill-in-campaign-code.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/globals/_fonts.scss, mon-pix/app/styles/pages/_fill-in-campaign-code.scss, mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs, mon-pix/config/environment.js, mon-pix/tests/acceptance/start-campaigns-test.js, mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
Actuellement les utilisateurs de Pix doivent copier-coller l'url d'une campagne pour y accéder. Avec la nouvelle page `/campagnes` ils pourront rentrer le code Campagne et commencer leur parcours.
- Création de la page `/campagnes` ;
- Gestion des erreurs (code vide, code erroné).
On souhaiterait rajouter un bouton annuler, mais les faire naviguer vers où ? Puisqu'il viennent de différents endroits, et qu'ils sont connectés ou non.
=> [FEATURE] Création de la page /campagnes permettant de rentrer un code Campagne (PF-639).

admin/app/components/organization-members-section.js, admin/app/models/organization.js, admin/app/styles/authenticated/organizations/get.scss, admin/app/templates/components/organization-information-section.hbs, admin/tests/acceptance/organization-memberships-management-test.js, api/db/migrations/20190719152419_add_column_externalId_to_organizations.js, api/lib/domain/models/Organization.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/tooling/database-builder/factory/build-organization.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
On veut pouvoir préciser un identifiant externe à une *Organisation*.
(paramètre optionnel d'une orga)
Ce champs sera renseigné lors de l'import open-data des établissements. 
Ajout d'une colonne `externalId` dans la table `organizations`.
Ajout de l'affichage de ce paramètre sur la page de détail d'un organisation dans Pix admin.
=> [FEATURE] Ajouter des identifiants externes aux Organisations. (PA-83)

api/lib/domain/services/mail-service.js, api/lib/settings.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/domain/services/mail-service_test.js
Actuellement les identifiants de templates Mailjet utilisés pour l'envoi des emails de création de compte et de réinitialisation de mot de passe sont codés en dur, ce qui rend impossible d'utiliser un compte Mailjet différent pour les applications de test et d'intégration.
On introduit deux nouvelles variables d'environnement, `MAILJET_ACCOUNT_CREATION_TEMPLATE_ID` et `MAILJET_PASSWORD_RESET_TEMPLATE_ID` pour paramétrer ces identifiants de templates.
En production, il faudra bien ajouter ces variables avec les valeurs actuelles :
```
scalingo -a pix-api-production env-set MAILJET_ACCOUNT_CREATION_TEMPLATE_ID=143620
scalingo -a pix-api-production env-set MAILJET_PASSWORD_RESET_TEMPLATE_ID=232827
```
On peut tout à fait ajouter ces variables bien avant le déploiement de cette PR.
Penser à …
=> [TECH] Rendre les identifiants de templates Mailjet configurables

api/scripts/extract-challenge-with-skills.js, api/scripts/migrate-v1-to-v2.js
- Les utilisateurs qui ont déjà répondus à des questions en V1 doivent pouvoir avoir des pix en V2, liés aux acquis qu'ils ont validés
- On veut prendre en considération les réponses données lors du dernier `assessment` de chaque compétence (on ignore les `answers` des compétences que l'on a retenté).
- On veut éviter une trop grosse coupure de la plateforme : pour cela, se préparer et lancer possiblement le script en juillet (moins d'utilisateurs)
- `extract-challenge-with-skills.js` : permet de récupérer un tableau avec, pour un challenge et la résultat de l'utilisateur, toutes les informations dont on a besoin sur les skills pour les knowledge-elements
- ` migration-v1-v2.js` : Un cron qui actuellement, prend MAX_USERS_MIGRATE utilisateurs, récupère leurs assessments et les answers …
=> [TECH] Migration des données de V1 vers V2.

api/lib/domain/constants.js, api/lib/domain/models/Scorecard.js, api/lib/domain/services/scorecard-service.js, api/lib/domain/usecases/get-scorecard.js, api/lib/domain/usecases/get-user-scorecards.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/unit/domain/models/Scorecard_test.js, api/tests/unit/domain/services/scorecard-service_test.js, api/tests/unit/domain/usecases/get-user-scorecards_test.js
- Actuellement sur Pix, les utilisateurs ne doivent pouvoir gagner que 40 pix par compétence, donc le niveau 5, et aussi 640 pix en tout.
- Suite à des dépassements possibles dans certains cas, nous souhaitons garder le nombre de pix gagnés en base, mais n'afficher que le nombre de pix pris en compte (voir les limitations ci-dessusà
- Bloquer le nombre de pix renvoyé, notamment pour le nombre de total de Pix, qui doit être cohérent avec le nombre de pix par compétence.
=> [FEATURE] Limiter visuellement le nombre de Pix maximum pouvant être gagnés actuellement (PF-767).

api/lib/domain/services/certification-result-service.js, api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js, api/scripts/compute-missing-certifv2-scores/bin.js, api/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores.js, api/tests/unit/domain/services/certification/certification-result-service_test.js, api/tests/unit/scripts/compute-missing-certifv2-scores/compute-missing-certifv2-scores_test.js
La certification Pix regroupe un ensemble de briques fonctionnelles dont le bon fonctionnement repose sur deux hypothèses quand aux données utilisées, qui donne lieu à deux algorithmes différents : c'est ce que l'on nomme souvent V1 (basé sur les `answers`) et V2 (basé sur les `knowledgeElements`). Pour permettre au plus tôt de se certifier en V2, il a été décidé déployer une partie de la certification V2, sans que le scoring V2 soit déployé, ce qui a engendré des scoring incohérents en base de donnée, bloquant ainsi l'annonce des résultats. Cette PR propose un script permettant de rattraper ainsi le scoring afin de remettre les données dans un bon état.
Le script (`api/scripts/compute-missing-v2-certification-score/bin.js`) énumère les certifications V2 terminées et ré-exécute le …
=> [FEATURE] Recalculer le score des certifications V2 dans un état inconsistent (PF-646).

admin/testem.js, certif/testem.js, mon-pix/testem.js, orga/testem.js
Depuis Chrome 76, il est impossible de lancer `npm test` sur mac.
En s'appuyant sur : https://github.com/ember-cli/ember-cli/pull/8774, on enlève `--disable-gpu` dans les différents `testem`.
=> [TECH] Correction du crash de Chrome 76 sur Mac pendant les tests front.

mon-pix/app/styles/globals/_buttons.scss, mon-pix/app/styles/pages/_profile.scss
Le hover du bouton fermeture du bandeau d'information nouveau profil ne correspond pas aux attentes de Manu car il n'est pas en accord avec ceux de Pix-site. 
Faire correspondre le hover à ceux de Pix-site.
https://app-pr641.review.pix.fr/profil
=> [FEATURE] Changement du hover du bouton pour fermer la bandeau d'information nouveau profil (PF-785).

api/lib/application/saml/saml-controller.js, api/tests/acceptance/application/saml-controller_test.js, api/tests/unit/application/saml/saml-controller_test.js, high-level-tests/e2e/cypress/fixtures/users.json, high-level-tests/e2e/cypress/integration/campaign.feature, high-level-tests/e2e/cypress/integration/login.feature, high-level-tests/e2e/cypress/integration/profile.feature, high-level-tests/e2e/cypress/support/commands.js, high-level-tests/e2e/cypress/support/step_definitions/index.js, high-level-tests/e2e/cypress/support/step_definitions/login.js, high-level-tests/e2e/package.json, mon-pix/app/routes/application.js, mon-pix/app/routes/login.js, mon-pix/tests/helpers/testing.js, mon-pix/tests/unit/routes/application-test.js, mon-pix/tests/unit/routes/login-test.js
Les utilisateurs provenant du GAR sont bloqués sur la page de login lorsqu'un autre utilisateur (ou le même) est déjà loggué. Ils veulent pouvoir accéder à leur profil Pix sans être bloqué.
De plus, lorsqu'il s'agit d'un utilisateur différent de celui déjà connecté, Pix devrait authentifier celui qui cherche à accéder à sa page profil, et non accéder au profil de l'ancien utilisateur.
Problèmes techniques 🤖 : 
Un `transitionTo('/compte')` après `session.authenticate` a été supprimé dans un refacto précédent, ayant pour conséquence que l'utilisateur n'était pas redirigé.
De plus, on a rencontré un autre problème, qui est que l'implémentation ci-dessous ne fonctionnait pas, puisque le `this._super` n'a plus la même référence (idem en asynchrone) : 
```
return …
```
=> [BUGFIX] Un utilisateur doit pouvoir accéder à son profil Pix via le GAR et ne pas être bloqué (PF-774).

api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js, api/lib/domain/usecases/get-answer.js, api/lib/domain/usecases/get-correction-for-answer.js
Les routes de réponses ne marchent pas en stagging.
PG et Sqlite ne renvoient pas la même chose pour les `bigint`. Changement des `!==` récemment ajoutés en `!=`
Cette solution est un patch pour débloquer l'environnement de stagging. 2 actions devront être mises en place pour éviter ce type de compromis :
- passer à PG partout
- uniformiser les id qui sont des fois en `integer` et des fois en `bigint`
=> [BUGFIX] Répare les routes de réponses.

api/lib/domain/services/user-service.js, api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js
Pendant une certification V2, le candidat pouvait être interrogé sur des questions relatives à des compétences d'un niveau inférieur à 1, à partir du moment où il avait au moins une bonne réponse en positionnement sur celles-ci.
Lorsqu'on récupère le profil du candidat (les fonctions getProfileToCertifyVX), et plus précisément au moment de sélectionner les questions à poser pour la certification (_pickChallengesForUserCompetences), on applique un filtre pour s'assurer que chaque compétence à certifier a bien un niveau supérieur ou égal à 1.
On notera que le développement de cette PR a commencé avant la migration V1 -> V2. Des tests V1 on été rajoutés/réécrits pour mieux comprendre les intentions.
=> [BUGFIX] Empêcher de poser des questions en trop en certification (PF-781)

orga/app/styles/pages/authenticated/campaigns/details.scss
Sur Pix Orga, lorsque le nom de la campagne est long, le code campagne s'affiche sur plusieurs lignes. 
Ajouter un `min-width` pour laisser l'affichage du code campagne sur une seule ligne.
=> [FEATURE] Obliger le code campagne à s'afficher sur une seule ligne (PO-222).

mon-pix/app/routes/competences/results.js
Dans certains cas la page de résultats d'un parcours par compétence affiche "commencer" au lieu du nombre de Pix sur la compétence.
Le score est calculé depuis l'objet `scorecard` qui peut être déjà présent dans le store et n'est donc pas à jour, on force son reload avant d'afficher les résultats.
=> [BUGFIX] La page de résultats d'un parcours par compétence n'affiche pas le nombre de Pix.

api/db/seeds/data/certification-candidates-builder.js
Afin d'alimenter la base de données, dans les environnements dév/RA, on utilise des seeds. Récemment a été introduit le concept de candidat de certification. Logiquement, quelques candidats de certification ont été créés via les seeds afin de pouvoir travailler. Pourtant, à l'usage, il est possible d'avoir des sessions de certification pour lesquelles sont inscrits plus d'une centaine de candidats.
On souhaite pouvoir approcher davantage l'environnement de production et les environnements dév/RA en ajoutant une large quantité de seeds candidats.
- Génération de candidats à l'aide de faker
- Quantité : 300 pour la session d'id 4
- La locale de faker a été temporairement fixée à "fr" pour avoir un jeu de données francisé.
Chaque génération des seeds produira un jeu de données candidats …
=> [TECH] Génération d'une importante quantité de candidats de certification dans les seeds

certif/app/components/login-form.js, certif/app/styles/components/login-form.scss, certif/app/templates/components/login-form.hbs, certif/tests/integration/components/login-form-test.js, mon-pix/app/components/form-textfield.js, mon-pix/app/styles/components/_form-textfield.scss, mon-pix/app/templates/components/form-textfield.hbs, mon-pix/tests/integration/components/form-textfield-test.js, orga/app/components/login-form.js, orga/app/styles/components/login-form.scss, orga/app/templates/components/login-form.hbs, orga/tests/integration/components/login-form-test.js
Lorsque l'utilisateur veut se créer un compte ou se connecter, celui-ci ne peut pas voir le mot de passe qu'il a tapé.
Ajout d'une icône oeil sur les champs mot de passe, permettant d'afficher ou non le mot de passe.
Un problème existe lorsque l'on souhaite se créer un compte, une fois le mot de passe entré (focus dans le input) et que l'on souhaite afficher son mot de passe en cliquant sur l'oeil, on perd l'action du clique à cause de la vérification du champs.
=> [FEATURE] Possibilité d'afficher le mot de passe dans les formulaires (PF-116).

api/lib/domain/validators/user-validator.js, api/lib/settings.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/domain/validations/user-validator_test.js, api/tests/unit/infrastructure/validators/password-validator_test.js, mon-pix/app/components/reset-password-form.js, mon-pix/app/components/signup-form.js, mon-pix/app/utils/password-validator.js, mon-pix/tests/integration/components/signup-form-test.js, mon-pix/tests/unit/components/form-textfield-test.js, mon-pix/tests/unit/components/reset-password-form-test.js, mon-pix/tests/unit/utils/password-validator-test.js
Afin de suivre les recommandations de la CNIL, le format des mots de passe doit être modifié.
Les nouvelles règles sont : 
- 8 caractères minimum, avec au moins un chiffre, une minuscule et une majuscule. 
- Mise à jour du pattern regex
- Mise à jour les messages d’erreur de format de mot de passe
- Mise à jour l’email de reset password (template MAILJET en prod)
=> [FEATURE] Modifier le format des mots de passe (PF-748).

orga/app/styles/app.scss, orga/app/styles/pages/authenticated/campaigns/new-item.scss, orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs, orga/tests/acceptance/campaign-creation-test.js
Rappel RGPD pour la création d'une campagne, si un identifiant externe sera demandé.
Ajouter en bas de page le texte suivant : 
* En vertu de la loi Informatique et libertés, et en tant que responsable de traitement, soyez attentifs à ne pas demander de donnée particulièrement identifiante ou signifiante si ce n’est pas absolument indispensable. Le numéro de sécurité sociale (NIR) est à proscrire ainsi que toute donnée sensible.
=> [FEATURE] Afficher une information RGPD lors de la création d'une Campagne avec Identifiant externe (PO-223).

certif/tests/integration/components/login-form-test.js, mon-pix/app/components/form-textfield.js, mon-pix/app/styles/components/_form-textfield.scss, mon-pix/app/templates/components/signin-form.hbs, mon-pix/app/templates/components/signup-form.hbs, mon-pix/tests/integration/components/form-textfield-test.js, orga/tests/integration/components/login-form-test.js
Lorsque l'utilisateur tape son mot de passe, appuie sur l'oeil puis continue de taper, l'icône de l'oeil n'était pas le bon.
Résoudre le problème de surcharge de la computed de `textfieldType`.
=> [BUGFIX] Problème d'affichage de l'oeil lorsque l'utilisateur souhaite continuer d'écrire (PF-807).

certif/app/styles/components/login-form.scss, certif/app/templates/components/login-form.hbs, mon-pix/app/styles/components/_form-textfield.scss, mon-pix/app/templates/components/form-textfield.hbs, mon-pix/tests/integration/components/form-textfield-test.js, orga/app/styles/components/login-form.scss, orga/app/templates/components/login-form.hbs
Depuis l'ajout de l'oeil pour afficher le mot de passe ou non, lorsque l'utilisateur souhaite envoyer le formulaire après avoir saisi son mot de passe en appuyant sur la touche "entrer". Celui-ci se retrouve à afficher ou non son mot de passe, mais pas à envoyer le formulaire comme attendu. 
Ajouter un attribut `type="button"` au bouton contenant l'oeil, permettant de dire qu'il ne s'agît pas du bouton `type="submit"`.
=> [BUGFIX] Problème quand l'utilisateur appuie sur la touche entrer après avoir rempli un formulaire d'authentification (PF-808).

api/lib/domain/models/UserCompetence.js, api/lib/domain/services/certification-result-service.js, api/lib/domain/services/scoring/scoring-certification.js, api/lib/domain/services/scoring/scoring-service.js, api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js, api/lib/infrastructure/repositories/assessment-repository.js, api/tests/integration/domain/services/scoring/scoring-certification_test.js, api/tests/integration/domain/services/user-service_get-profile-to-certify_test.js, api/tests/unit/domain/services/certification/certification-result-service_test.js, api/tests/unit/domain/services/scoring-service_test.js, api/tests/unit/domain/usecases/create-assessment-result-for-completed-assessment_test.js
Le score et le niveau par compétence a récemment été plafonné, côté parcours d'évaluation. On souhaiterait avoir le même plafonnement pour les certifications futures, sans impacter les certifications existantes.
À l'heure actuelle, le résultat d'une certification est enregistré dans la table `competence-marks`, ainsi que `assessment-result`, en mode "append-only". On décide ainsi de stocker le score plafonné afin d'avoir un vrai _snapshot_ intemporel comme requis par le métier.
Cela signifie que pour l'instant, **on ne peut pas** obtenir l'information du scoring plafonné et non-plafonné. Si le besoin s'en fait sentir, cela pourra faire l'objet d'une autre PR.
Tous les premiers `commit` sont des `commits` de bsr. Les deux seuls `commits` fonctionnels sont : 
- …
=> [FEATURE] Plafonner le score et le niveau lors d'une certification (PF-773).

docs/API.md
🗺️ Contexte
=========
On aimerait mettre en prod ne fonctionnalité (exemple "Certification v2"), tout en ayant la capacité de la désactiver sans générer une nouvelle version de l'application pendant les premières semaines.
Sur des fonctionnalités longues à développer, on a aussi parfois le besoin de livrer une partie du code en production sans que la fonctionnalité associée soit visible par l'utilisateur.
🥚 Proposition
==========
Discuté dans l'issue  #543, introduire  la notion de _feature toggle_, ou _feature flipping_. Voir toute la proposition dans le diff ci-dessous.
=> [DOC] Ajouter la notion de feature toggle dans la doc de l'API

api/db/seeds/data/pix-aile-profile-builder.js
Depuis le commit cbfec9a2e, quand on reprenait la compétence 1.1 de Pix Aile, on se retrouvait sur une page checkpoint avec 5 answers, dont deux sans texte.
Lors de la création des seeds, on crée une answer par knowledge element. Or sur ce profile il y a deux challenges qui valident deux compétences. Donc deux knowledge elements sur le même challenge. Donc deux answers sur le même challenge 🤒
Créer une answer par challenge, et un knowledge element par skill.
=> [BUGFIX] Corrige les seeds du profile de Pix Aile

docs/CONTRIBUTING.md
En avril 2019, nous avions décidé de marquer des lignes de code exemplaires par le tag `@exemplary`.
Ce tag n'a pas été utilisé à ce jour.
Je propose de le supprimer de la doc.
C'est peut-être le mot "exemplary" qui est intimidant, est-ce qu'un autre mot pourrait marcher, comme "inspirant" par exemple ?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/1024pix/pix/683)
=> [DOC] Supprimer la convention @exemplary

api/db/migrations/20170306151003_update_answers.js
Un fichier de migration concernant la table `answers` contenait des opérations qui ne retournaient pas de promesses.
Retourner des promesses aux endroits nécessaires.
- Cela peut ou pas résoudre un problème ponctuel lors de lancement de la commande npm t (drop -> create -> migrate -> test). En effet, à de rares occasions, beaucoup de tests liés aux answers plantaient. Peut-être était-ce dû à la correction de la présente PR, ou pas !!
- Aucun impact sur intégration ou la prod, ou même sur les PR courantes
=> [BUGFIX] Une migration de mise à jour de la table answers n'était pas bloquante

api/tests/acceptance/application/answers/answer-controller-save_test.js
De façon aléatoire, une ribambelle de tests (liés à la table answers) échouaient.
Après investigation, il se trouve qu'un test d'acceptance sur le controller d'`answer` présentait une conception douteuse. En effet, un des tests imbriqué contenait un crochet `beforeEach` lequel déclenchait une requête POST vers le serveur. Seulement, il existait déjà un crochet `beforeEach` qui effectuait cette même opération. Par conséquent, une des requêtes n'étaient plus attendue par mécanisme de promesse, et générait une création non-souhaitée d'un enregistrement `answer` dans la table.
Réorganisation cohérente du fichier de test afin de prévenir les multiples requêtes.
=> [BUGFIX] Empêche plusieurs tests API liés à answers d'échouer

certif/app/styles/components/login-form.scss, certif/app/templates/components/login-form.hbs, mon-pix/app/styles/components/_form-textfield.scss, mon-pix/app/templates/components/form-textfield.hbs, mon-pix/tests/integration/components/form-textfield-test.js, mon-pix/tests/integration/components/signup-form-test.js, orga/app/styles/components/login-form.scss, orga/app/templates/components/login-form.hbs
Les deux icônes d'œil n'ont pas exactement la même taille et cela créé un décalage des icônes lors de l'appuie.
Fixer la taille du `button` contenant les icônes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/1024pix/pix/679)
=> [BUGFIX] Problème de taille des icônes d'œil pour les champs mot de passe.

api/lib/domain/services/session-service.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/unit/domain/services/session-service_test.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Dans des cas dont la liste précise est difficile à évaluer (ouverture de deux navigateurs et lancement de session de certification presque en simultané + léger lag côté API), on peut se retrouver avec deux certification-courses créés pour un même utilisateur sur une session donnée.
Il existait pourtant une vérification côté API pour s'assurer de ne pas créer deux fois le certification-course. Mais la création du certification-course ne suit pas directement la vérification : avant, le profil de l'utilisateur est compute de sorte à générer la liste des challenges pour la certification. Cette opération peut parfois prendre un peu de temps, et donc la vérification peut être obsolète entre temps.
Ajout d'une deuxième vérification après le computing des challenges
Je suis ouverte à toutes les …
=> [BUGFIX] Empêcher la création de plus d'un certification-course pour un même utilisateur dans une session (PF-814)

api/lib/domain/services/scorecard-service.js, api/tests/tooling/domain-builder/factory/build-assessment.js, api/tests/unit/domain/services/scorecard-service_test.js
Lorsque l'utilisateur remet à zéro une compétence alors qu'il passe une campagne, on recrée un assessment et l'ancien devient `aborted` pour la campagne. Suite à l'ajout de la colonne "campaignParticipationId", celle-ci était vide dans ce cas là.
Lorsqu'on crée le nouvel Assessment, on met bien le campaignParticipationId
=> [BUGFIX] Ajout d'une campaignParticipationId dans le cas d'une remise à zéro durant une campagne

admin/app/controllers/authenticated/certifications/single/details.js, admin/app/controllers/authenticated/certifications/single/info.js, admin/app/styles/app.scss, admin/app/styles/components/confirm-popup.scss, admin/app/templates/authenticated/certifications/single/info.hbs, admin/app/templates/components/confirm-popup.hbs, api/lib/domain/services/certification-service.js
Le plafonnement d'une certification (https://github.com/1024pix/pix/pull/663) s'opère actuellement à un certain niveau, en sortie de calcul et juste avant d'enregistrer une liste de `CompetenceMarks` en base. Lors d'un jury, une nouvelle liste vient écraser la première. Or cette liste n'est pas plafonnée comme elle le devrait.
Les opérateurs de pix admin ont la main sur tout. Ils peuvent modifier une certification sans restrictions. Néanmoins pour les assister dans leurs modifications, on décide d'ajouter un message d'avertissement lorsque leur modifications sont contraires aux règles de la certification.
Aucune remarque particulière.
Saviez vous que le code de l'émoji 😔est _pensive_. 
Vous trouvez que ça a l'air de quelqu'un qui pense vous ? 🤔
---
This change is [<img …
=> [FEATURE] Afficher un warning lorsqu'une modification jury est illégale (PF-811).

admin/app/templates/components/organization-members-section.hbs
Beaucoup de membres ajoutés dans les différentes Orga. Pour vérifier que les membres ont bien été ajoutés, on veut pouvoir afficher 50 membres dans la liste.
Set a `pageSize=50` in `templates/components/organization-members-section.hbs`
Pour moi, en faisant ça on va pas dans le sens du produit (qui serait d'ajouter la pagination). Mais on apporte de l'autonomie au métier.
=> [FEATURE] Augmenter la liste de membre d'une organisation (PA-108).

mon-pix/app/routes/campaigns/fill-in-id-pix.js
On pouvait être bloqué lors de la saisie du `participantExternalId` si on avait déjà saisi un  `participantExternalId` lors d'une précédente campagne au cours d'une même session continue et sans rechargement.
On reset les variables utilisées sur la page à la sortie complète de la route afin de se prémunir de toute sauvegarde de données de la part d'Ember.js
=> [BUGFIX] Lancer consécutivement deux campagnes avec demande ID (PF-825).

api/lib/plugins.js, docs/Glossaire-Variables-Env.md, scalingo.json, scripts/jira/comment-with-review-app-url.js, scripts/signal_deploy_to_pr.sh
Actuellement les _review apps_ sont créées sur la base des applications Scalingo :
* `pix-api-integration`
* `pix-front-integration`
`pix-front-integration` est dédiée à ces créations de _review app_ mais `pix-api-integration` est également utilisée pour tester `dev`. Ceci présente plusieurs inconvénients :
* tout paramétrage (variables d'environnement) fait sur `pix-api-integration` est hérité par les _review apps_ ;
* à cause d'un bug Scalingo (qu'on vient de leur remonter), une _review app_ peut démarrer avant que son instance de PostgreSQL soit allouée, ce qui fait qu'elle se connecte à la base de `pix-api-integration`, avec des effets désastreux si la PR contient une migration.
On va créer deux applications vouées à ne servir que de _template_ pour les _review apps_ :
* …
=> [TECH] Découpler les review apps de l'application d'integration

high-level-tests/e2e/cypress/fixtures/campaigns.json, high-level-tests/e2e/cypress/integration/campaign.feature, high-level-tests/e2e/cypress/support/step_definitions/campaign.js, high-level-tests/e2e/cypress/support/step_definitions/index.js, high-level-tests/e2e/package-lock.json, high-level-tests/e2e/package.json, mon-pix/app/controllers/campaigns/campaign-landing-page.js, mon-pix/app/routes/campaigns/fill-in-id-pix.js, mon-pix/app/routes/campaigns/start-or-resume.js, mon-pix/tests/acceptance/resume-campaigns-test.js, mon-pix/tests/acceptance/start-campaigns-test.js, mon-pix/tests/helpers/testing.js, mon-pix/tests/unit/controllers/campaigns/campaign-landing-page-test.js, mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Les prescripteurs voudraient pouvoir sortir des statistiques sur leurs prescrits et leurs informations personnelles (âge, ancienneté, secteur...).
1 - Les prescrits remplissent un questionnaire en ligne (en-dehors de app.pix.fr) ;
2 - Cela leur donne un "identifiant" ;
3 - Ils commencent leur parcours prescrit avec cet identifiant comme `identifiant externe` ;
4 - Ils partagent leurs résultats ;
5 - Les prescripteurs récupèrent tous les résultats (et donc les identifiants), et croisent les données avec les résultats du questionnaire pour avoir leurs données ;
6 - Ils font de beaux graphiques statistiques 😃.
Ce qui nous manque juste, c'est la partie 3. Cette PR ajoute cette partie 3.
- Upgrade de `cypress-cucumber-preprocessor`.
- Ajout de tests end to end.
=> [FEATURE] Accéder à un parcours prescrit avec l'identifiant externe dans l'URL (PF-824).

api/db/seeds/data/certification-courses-builder.js, api/lib/domain/services/certification-service.js, api/tests/acceptance/application/certification-course-controller_test.js
Dans Pix Admin, la page qui liste les certifications d'une session était cassée.
C'est une régression suite à la PF-811.
Il y a 415 CertificationCourse sans Assessment. Quand on essaie d'afficher la liste des certifications d'une session qui contient l'un de ces CertificationCourse, l'API  essayait d'accéder à assessment.id d'un assessment undefined => erreur 500.
Voir [PA-109](https://1024pix.atlassian.net/browse/PA-109).
1. Rétablir la vérification que l'assessment existe avant d'accéder à son id
2. Ajouter une seed qui permet de valider la correction en RA
Cadeau, voici un nombre au hasard : 440906
=> [BUGFIX]  Corrige l'affichage des certifications d'une session (PA-109)

api/lib/infrastructure/caches/redis-client.js
Parfois, le serveur Redis en production se met à redémarrer en boucle, jusqu'à ce qu'on redémarre les conteneurs de l'API.
Après analyse il s'avère que le serveur Redis consomme toute la mémoire qui lui est allouée pour préparer les réponses aux questions qui lui sont soumises.
Or, le client Redis pour Node accumule par défaut les requêtes Redis soumises quand le serveur Redis n'est pas disponible, pour les poser dès que le serveur redevient disponible (l'hypothèse étant que l'indisponibilité du serveur est transitoire, et qu'il vaut mieux faire patienter le client quelques secondes de plus, plutôt que de lui renvoyer une erreur). De plus, en 25802cf5cbb393e9e09db2e679933189e21724b9 nous avons activé une option supplémentaire qui conserve et retente les requêtes dont on attendait la …
=> [TECH] Éviter les plantages de Redis causés par une accumulation de requêtes

certif/app/templates/components/login-form.hbs, orga/app/templates/components/login-form.hbs, orga/app/templates/components/routes/authenticated/team/new-item.hbs
Lors des montées de version des dépendances, une correction a été apportée dans les templates `.hbs`, lors du passage de la déclaration de champs input du style Mustache à AngleBracket, au niveau de l'attribut `required`. Il s'avère que par le passé, ce champs n'était pas correctement déclaré `{{input required}}` plutôt que `{{input required=true}}`. Par conséquence, Firefox n'appliquait pas son comportement par défaut consistant à mettre des bordures rouge sur les "champs requis". 
La solution retenue pour fixer le problème est de se dire qu'on va être iso-prod et donc de supprimer (peut-être temporairement) l'attribut `required`.
=> [BUGFIX] Correction de l'apparition de bordures rouges pour les champs de saisie du formulaire de connexion pour Pix Orga et Pix Certif.

certif/app/styles/components/login-form.scss, orga/app/styles/components/login-form.scss
Suite à la montée de version et à la conversion `{{input}}` vers `<Input />`, il y a un souci de rendu au survol du champ "mot de passe" pour le formulaire de login de Pix Orga et Pix Certif.
**Avant**
**Après**
=> [BUGFIX] Correction du champ de saisie du mot de passe à la connexion pour Pix Orga et Pix Certif.

admin/app/models/organization.js, admin/app/templates/components/organization-information-section.hbs, api/db/migrations/20190918105231_add_column_provinceCode_to_organizations.js, api/lib/domain/models/Organization.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/tooling/database-builder/factory/build-organization.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
L'information du département (code) des Organisations n'est actuellement pas stockée. On souhaite pouvoir la stocker dans le cadre de l'import en masse des Organisations.
Ajout d'une colonne `provinceCode` dans la table `Organization` et affichage de ce champ dans Pix Admin.
=> [FEATURE] Ajout du département (code) aux Organisations et affichage dans Pix Admin (PA-105).

admin/app/controllers/authenticated/certifications/sessions/info/list.js, admin/app/templates/authenticated/certifications/sessions/info/list.hbs, admin/package-lock.json, admin/package.json
Deux méthodes d'import de PV de session coexistent dans PixAdmin :
- l'import du PV de session en format ODS
- l'import d'un csv issu d'un calcul réalisé par une macro sur un document custom qui rassemble plusieurs PVs de session.
Cette dernière méthode n'est désormais plus du tout utilisée.
Retirer le bouton et l'ensemble du code liés à cette méthode d'import.
=> [TECH] Retrait de la fonctionnalité plus utilisée d'import CSV dans PixAdmin (PA-111)

api/scripts/reload-cache-everyday.js
La tâche CRON permettant le nettoyage des caches ne fonctionne plus.
La route d'authentification utilisée n'existe plus.
Utilisation du POST /api/token
TODO: Ecrite des tests unitaires pour effectuer les vérifications formelles des URLs utilisées par le script.
=> [BUGFIX] Dysfonctionnement du nettoyage journalier des caches (PF-836)

api/lib/application/organizations/organization-controller.js, api/lib/domain/usecases/update-organization-information.js, api/lib/infrastructure/repositories/organization-repository.js, api/scripts/update-sco-organizations-with-province-code-and-external-id.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/scripts/update-sco-organizations-with-province-code-and-external-id_test.js, api/tests/acceptance/scripts/valid-organizations-test-file.csv, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/domain/usecases/update-organization-information_test.js
Actuellement aucune mise à jour de masse des organisations n'est possible. On veut pouvoir mettre à jour toutes les organisations déjà existantes en ajoutant un identifiant externe ainsi que le département.
Ajout d'un script permettant cette action.
Le script fait appel à la route `PATCH /organizations/id`, il a donc été nécéssaire d'ajuster ce cas d'utilisation.
=> [FEATURE] Mise à jour des organisations en ajoutant un identifiant externe et le département à l'aide d'un script (PF-778).

certif/app/routes/authenticated/index.js, certif/tests/unit/routes/authenticated-test.js
La route front `/` faisait une vérification sur `currentUser.pixOrgaTermsOfServiceAccepted` (au lieu de `pixCertifTermsOfServiceAccepted`) pour savoir si elle devait rediriger vers `/cgu` ou vers `sessions/list`.
Les tests passaient , et ça marchait quand même grâce à la redirection d’après : `/` -> `/cgu` -> `sessions/list` au lieu de `/` -> `sessions/list`.
Ajouter un test qui échoue, et corriger la typo.
Il y a deux commit, un qui change la structure, puis un qui change le comportement.
J'ai suivi les idées de cette page de la doc Ember :
- https://guides.emberjs.com/v3.12.0/testing/testing-routes/
=> [BUGFIX] Corrige une typo dans la vérification cgu de Pix Certif (PC-75)

api/lib/domain/models/Scorecard.js, api/tests/unit/domain/models/Scorecard_test.js
La constatation suivante a été faite : 
> Parcours autonomie sur 1.1 => répondre tout faux
> Remettre à zéro sa comp 1.1
> Lancer la campagne de test KKPUTW913 sur la 1.1 et la 2.3
> Répondre tout faux et terminer la campagne
> Envoyer ses résult et revenir à son profil
> La compétence 1.1 est toujours au statut "commencer" et la 2.3 et "reprendre
> — la 1.1 devrait aussi être en "reprendre"
Les `knowledge-elements` acquis en campagne sont bien associés à la compétence remise à zéro.  
Pour établir le statut d'une `Scorecard`, on utilise maintenant les `knowledge-elements` 
- soit en l'absence de `competenceEvaluation` 
- soit quand le statut de la `competenceEvaluation` est à l'état de `CompetenceEvaluation.statuses.RESET`.
=> [BUGFIX] Mise à jour via campagnes des scorecards remises à zéro (PF-841).

api/lib/application/courses/course-controller.js, api/lib/application/courses/index.js, api/lib/domain/services/course-service.js, api/tests/unit/application/courses/course-controller_test.js, api/tests/unit/domain/services/course-service_test.js
Lors d'un PR précédente, un control a été rajouté utilisant `auth: true` dans la configuration d'hapi, qui utilise un handler fait par nos sois dont l'implémentation ne permettait pas d'exécuter le code du controller si jamais le décodage du token n'était pas successful.
La solution consiste à utiliser, comme c'est fait à d'autres endroit, le parsing directement à la main au niveau du controller grace au `tokenService`.
=> [BUGFIX] Pouvoir passer une démo à nouveau

mon-pix/app/components/resume-campaign-banner.js, mon-pix/tests/acceptance/profile-test.js, mon-pix/tests/integration/components/resume-campaign-banner-test.js, mon-pix/tests/unit/components/resume-campaign-banner-test.js
On a vu que 
* Se rendre sur un profil n'ayant pas de campagne en cours
* Lancer une campagne
* La quitter au bout de la 1ere question
* Le bandeau jaune "reprendre" n'apparaît pas
* Il faut reload sa page pour  voir le bandeau apparaître
On refactorise le composant pour se servir des propriétés d'observation des attributs offerts par Ember. 
Dans `/routes/profile.js`, on aurait pu faire :
```js
await user.hasMany('campaignParticipations').reload();
```
Toutefois, le problème sous-jacent n'aurait pas été résolu et aurait ralenti la page de chargement du profil
=> [BUGFIX] Optimise le chargement de la bannière de reprise de campagne (PF-840).

mon-pix/app/components/routes/board-page.js, mon-pix/tests/acceptance/board-organization-test.js, mon-pix/tests/integration/components/routes/board-page-test.js
En changeant la méthode d'authentification de mon-pix, l'export des snapshots a été oublié, il utilisait toujours l'ancienne manière qui n'existait plus. En conséquence, les utilisateurs de Pix Board ne pouvaient plus exporter les anciens snapshots issus des profils v1 de leurs élèves.
Corriger la méthode de récupération du token d'authentification.
Rajout d'un test d'acceptance pour vérifier le bon fonctionnement global.
=> [BUGFIX] Permettre de nouveau l'export des snapshots - profil v1 (PF-844).

mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/templates/assessments/checkpoint.hbs
Actuellement, on voit ça 
On s'attend à voir ça 
On ajoute un modifier css pour conserver le visuel des autres `rounded-panel-title`
Idéalement, il faudrait s'aligner complètement au InVision et faire une classe css `rounded-panel-headtitle` pour les checkpoints. Dans l'attente, on part sur la philosophie YAGNI.
[Pour en savoir plus sur `font-variant-caps`](https://developer.mozilla.org/fr/docs/Web/CSS/font-variant-caps)
=> [BUGFIX] Polir le titre des checkpoints (PF-823).

api/lib/application/answers/answer-controller.js, api/lib/application/assessments/assessment-controller.js, api/lib/application/campaignParticipations/campaign-participation-controller.js, api/lib/application/campaigns/campaign-controller.js, api/lib/application/certification-centers/certification-center-controller.js, api/lib/application/certifications/certification-controller.js, api/lib/application/organizations/organization-controller.js, api/lib/application/preHandlers/assessment-authorization.js, api/lib/application/preHandlers/snapshot-authorization.js, api/lib/application/preHandlers/user-existence-verification.js, api/lib/application/scorecards/scorecard-controller.js, api/lib/application/sessions/session-controller.js, api/lib/domain/usecases/complete-assessment.js, api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js, api/lib/domain/usecases/get-answer.js, api/lib/domain/usecases/get-correction-for-answer.js, api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js, api/lib/domain/usecases/get-scorecard.js, api/lib/domain/usecases/get-user-certification-with-result-tree.js, api/lib/interfaces/controllers/security-controller.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/usecases/get-user-certification-with-result-tree_test.js
Il existe des ids traités parfois en entier, d'autres fois en chaîne, et comparés de manière non stricte `==` `!=` au lieu de `===` `!==`
Depuis le changement de type des colonnes en base de données de BIGINT vers INTEGER, ce traitement en tant que chaîne n'est plus nécessaire. Tous les casts et les comparaisons en tant que chaîne ont été remplacés par des comparaisons entre entiers (comme il se doit d'ailleurs lorsqu'on traite avec des ids entiers).
=> [TECH] S'assurer que les ids sont toujours traités en tant qu'entier

docs/API.md, docs/Ember.md, docs/Tests.md
- Le fichier Test.md ne contenait qu'une seule information qui concerne l'API
- Dans API.md, il y avait une section sur transitionTo qui concerne Ember
- Supprimer Test.md et déplacer l'info dans API.md
- Créer Ember.md et y déplacer l'info sur `transitionTo
=> [DOC] Supprime Test.md et déplace `transitionTo` dans Ember.md

api/db/migrations/20191008142311_alter_feedback_answer_column_to_text.js
Dans les signalements actuelles (table `feedbacks`), on remonte la réponse de l'utilisateur. Cette réponse est enregistrée dans la table `answers` via un champ `text`, mais via un champ `varchar(255)` dans la table `feedbacks`.
Si un utilisateur enregistrait une réponse trop longue et faisait un signalement, alors le signalement plantait car la taille de la réponse dépassait 255.
Changer le type de la colonne `answer` de `feedbacks` pour la passer en `text`, comme dans la table `answers`
-
=> [BUGFIX] Des réponses trop longues envoyées dans les signalements (PF-865).

mon-pix/app/styles/components/_feedback-panel.scss, mon-pix/app/templates/components/feedback-panel.hbs
Certains utilisateurs utilisent le text-area des signalements pour mettre des messages trop longs.
Limiter la taille du message à 10000 caractères.
Le ticket de base PF-855 correspondait à cette demande, mais remontait en faite un bug réglé par la pr #752
=> [FEATURE] Limiter la taille des messages de feedbacks (PF-864).

api/lib/domain/models/UserCompetence.js, api/tests/unit/domain/models/UserCompetence_test.js
Lors d'un refactoring sur une PR précédente, un commit (https://github.com/1024pix/pix/pull/750/commits/9d69948a54321611bcc4aa9ffbb9cf8953fe53eb) a modifié l'initialisation des `UserCompetence` en replaçant `this.skills = []` par `this.skills = skills` étant donné que les skills étaient passés en paramètre en tant que propriété de l'objet `competence`. 
L'initialisation avec des array vide était néanmoins intentionnelle.
Réinitialiser les `UserCompetence` sans y mettre tout le référentiel pix.
=> [BUGFIX] Initialiser les UserCompetences sans skills ni challenges 

admin/nginx.conf.erb, certif/nginx.conf.erb, docs/Glossaire-Variables-Env.md, mon-pix/nginx.conf.erb, orga/nginx.conf.erb
Aujourd'hui dans notre routage des applications front vers leur api, on ne peut pas spécifier de région particulière pour Scalingo. Ces applications front ne peuvent référencer que des APIs référencées par la région agora, vouée à disparaitre.
On ajoute une nouvelle variable d'environnement pour adapter le suffixe du host API en fonction de nos besoins.
On prévoit le cas par défaut ``scalingo.io`` qui fait référence à agora, et qui correspond à notre cas d'usage jusque ici.
=> [TECH] Variabiliser le routage des apps front pour le changement de région Scalingo

api/lib/application/authentication/authentication-controller.js, api/tests/acceptance/application/authentication-controller_test.js, api/tests/unit/application/authentication/authentication-controller_test.js
Les utilisateurs se retrouvent déconnectés toutes les heures et tombent sur une page "Oups!".
Supprimer l'attribut `expire_in` lors de la création de l'`access-token`.
Si l'attribut `expire_in` est présent le front (concrètement, `ember-simpl-auth`) tente de refresh le token, ce qui n'est pas encore implémenté dans l'API.
=> [BUGFIX] Les utilisateurs étaient déconnectés intempestivement (PF-870).

README.md
Problème de validité de lien relevé par un visiteur dans l'issue https://github.com/1024pix/pix/issues/743
Le lien .../teams/pix n'existe pas (404)
Remplacer par le lien .../teams/everyone
Ne connaissant pas les droits pour les "visiteurs", si quelqu'un pouvait prendre le temps de lui répondre concernant les accès. Car je ne sais pas si il a accès au nouveau lien tout de même !
=> [DOC] Lien vers les teams Pix cassé dans le README du repo Pix.

mon-pix/app/routes/error.js, mon-pix/app/styles/pages/_error.scss, mon-pix/app/templates/error.hbs
On ne sait pour quelles erreurs l'utilisateur tombe sur la page "Oups".
On affiche le message et le détail de l'erreur directement sur la page "Oups"
Les erreurs front n'ont pas de détail.
Il faudra peut-être améliorer le style (voir Quentin).
=> [FEATURE] Ajouter le details des erreurs sur la page "Oups" (PF-882).

api/lib/domain/usecases/get-results-campaign-in-csv-format.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/acceptance/application/organization-controller_test.js
Il n'est pas possible de télécharger les résultats CSV des campagnes qui ont 3000 participations.
C'est dû :
- à une multiplication de promesses qui se lancent en même temps
- à un temps de traitement supérieur à 30 secondes (donc timeout de Scalingo même si la requête réussit)
Ce n'est pas une solution dans le sens où elle ne permet pas de télécharger les résultats, mais au moins :
- les promesses sont maintenant séquentielles
- au bout de 30 secondes, le traitement qui génère le CSV est annulé, ce qui libère l'instance API utilisée
Il faut faire mieux, par exemple en utilisant les streams comme pour les snapshots (voir 9fab661cf8cc532468fc5594fb5f97b0b9022a2b)
=> [FEATURE] Annule le téléch. des résultats longs d'une campagne (PO-255)

mon-pix/app/styles/components/_certification-not-certifiable.scss, mon-pix/app/styles/components/_scorecard-details.scss
Sous IE, la page compétence n'est pas lisible
Pour IE, il y a besoin de préciser le max-width correctement, sinon le texte dépasse du bloc.
=> [BUGFIX] Correction du style pour la page compétence sous IE (PF-860).

api/db/migrations/20191017151624_add_columns_outdated_to_target_profiles_table.js, api/lib/application/organizations/organization-controller.js, api/lib/domain/models/TargetProfile.js, api/lib/domain/services/organization-service.js, api/lib/infrastructure/adapters/target-profile-adapter.js, api/lib/infrastructure/repositories/target-profile-repository.js, api/tests/integration/infrastructure/repositories/target-profile-repository_test.js, api/tests/tooling/database-builder/factory/build-target-profile.js, api/tests/tooling/domain-builder/factory/build-target-profile.js, api/tests/unit/domain/services/organization-service_test.js
Aujourd'hui les profils cibles (ceux qui portent sur les compétences de Pix) qui ne sont plus à jour, sont proposé lors de la selection du profil-cible à la création d'une campagne.
Ajouter un attribut `outdated` sur les profils-cibles, pour préciser si il sont archivé/périmé/plus à jour.
C'est un premier pas pour gérer l'obsolescence des profils-cibles.
=> [FEATURE] Ne pas afficher les profils cibles archivés (PO-254).

orga/app/styles/globals/fonts.scss
Sur certains écrans, certains libellés  et boutons s'affichent dans une mauvaise police (Times-New Roman plutôt que Roboto). 
Rajouter des polices par défaut.
=> [BUGFIX] Ajout d'une police par défault pour les fonts Roboto et Open-Sans sur Pix Orga (PO-258).

admin/app/styles/app.scss, certif/app/styles/app.scss, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_form-textfield.scss, orga/app/styles/app.scss
On gère déjà les erreurs dans les formulaires, et le comportement par défaut des navigateurs faisait doublons. 
Désactiver le style par défaut des navigateurs.
=> [BUGFIX] Supprime le style par défaut sur les invalid input (PF-812).

mon-pix/app/components/warning-banner.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_warning-banner.scss, mon-pix/app/templates/application.hbs, mon-pix/app/templates/components/warning-banner.hbs, mon-pix/config/environment.js, mon-pix/tests/integration/components/warning-banner-test.js
Il arrive que certains utilisateurs utilisent l'intégration sans même le savoir. 
Une partie de la solution est l'ajout d'une bannière. Celle-ci s'affiche en fonction d'une nouvelle variable d'environnement `IS_WARNING_BANNER_ENABLED`. Elle permet à l'utilisateur de mieux se rendre compte d'où il se trouve. 
La variable est donc ajouté dans mon-pix.
=> [FEATURE] Ajout d'une bannière pour staging 

api/lib/application/campaigns/campaign-controller.js, api/lib/domain/usecases/index.js, api/lib/domain/usecases/start-writing-campaign-results-to-stream.js, api/tests/unit/application/campaign/campaign-controller_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
Il n'est pas possible de télécharger les résultats CSV des campagnes qui ont 3000 participations.
C'est dû :
- à un temps de traitement supérieur à 30 secondes (donc timeout de Scalingo même si la requête réussit)
Utiliser un stream comme pour les snapshots (voir 9fab661cf8cc532468fc5594fb5f97b0b9022a2b)
Il faut faire mieux, permettre de résister à une combinatoire de 6000 participations x 700 acquis (profil cible).
Aussi, on a mesuré l'occupation mémoire, dans nos mesures elle était du même ordre de grandeur (environ 200 Mo max) pour un export csv seul que pour deux exports en même temps.
Un seul export :
Deux exports (les 0 sont des faux, ce sont des marqueurs de démarrage et de fin) :
=> [BUGFIX] Télécharger les résultats CSV de grosses campagne (PO-257).

orga/app/routes/login.js, orga/tests/acceptance/authentication-test.js
- se connecter à PixOrga et voir la liste des campagnes
- taper l'URL : `/connexion`
- se retrouver nez à nez avec une page blanche
Pix Orga est tout perdu car il essaie de rediriger vers `/index`, page n'existant pas. Il faut spécifier à la route `login` que `routeIfAlreadyAuthenticated` est à `authenticated` (par défaut `index`), et ainsi être redirigé vers la page par défaut, qui se trouve être la page `/campagnes`.
=> [BUGFIX] User connecté /index redirigé vers /campagnes (PO-264).

orga/app/components/sidebar-menu.js, orga/app/styles/components/sidebar-menu.scss, orga/app/styles/globals/colors.scss, orga/app/templates/authenticated.hbs, orga/app/templates/components/sidebar-menu.hbs, orga/tests/acceptance/authentication-test.js
Lorsqu'un utilisateur SCO de Pix Orga se pose une question, il ne sait pas quoi faire.
Ajouter un bouton en bas du menu, afin de rediriger les SCO sur le guide d'utilisation de Pix.
=> [FEATURE] Ajout d'un bouton de navigation sur Pix Orga (PO-252).

api/tests/unit/application/organizations/index_test.js
Le test unitaire de GET /api/organizations/{id}/invitations échouait quand on lançait les tests unitaires sans base de donnée car son usecase n'était pas bouchonné.
Bouchonner le usecase.
Pour lancer les tests unitaires sans base de données :
$ TEST_DATABASE_URL=trololo npm run test:api:unit
=> [TECH] Corrige le TU de GET /api/organizations/{id}/invitations

api/lib/application/organizations/index.js, api/scripts/organizeOrganizationsByExternalId.js, api/scripts/send-invitations-to-sco-organizations.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/application/organizations/index_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/test-helper.js, api/tests/unit/application/organizations/index_test.js, api/tests/unit/domain/usecases/update-organization-information_test.js, api/tests/unit/scripts/helpers/csvHelpers_test.js, api/tests/unit/scripts/helpers/valid-organizations-test-file.csv, api/tests/unit/scripts/organizeOrganizationsByExternalId.js
Pour le 5 novembre, il faut pouvoir envoyer des emails en masse aux différents chefs d'établissements scolaires concernés.
Les organisations en questions seront créées par le script d'import d'organisations. Elles sont alors créées avec `isManagingStudents=false`.
Envoyer des emails en masse avec un script parsant de la donnée format CSV. Le script modifiera aussi le champ `isManagingStudents` en le settant à `true`.
=> [FEATURE] Script d'envoie des invitations SCO (PF-862)

api/lib/application/organizations/organization-controller.js, api/lib/domain/usecases/update-organization-information.js, api/lib/infrastructure/repositories/organization-repository.js, api/scripts/update-sco-organizations-with-is-managing-students-to-true.js, api/tests/acceptance/scripts/update-sco-organizations-with-is-managing-students-to-true_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/unit/domain/usecases/update-organization-information_test.js
Le déploiement SCO se fait par le biais de l'attribut `isManagingStudents`. Il nous faut un script permettant de mettre à jour ce booléen pour les organisations que l'on souhaite au fur et à mesure du déploiement SCO.
Ajout d'un script prenant en entrée un fichier csv avec juste les UAI des établissements scolaires concernés.
```
035tructruc
044bidule
```
=> [FEATURE] Ajout d'un script déclenchant le déploiement SCO.

api/tests/acceptance/application/answers/answer-controller-save_test.js
- Le test passait en affichant une erreur dans la console. Il devait échouer.
- Ajout d'un `return` manquant
- Modification de la réponse de l'utilisateur pour être correct par rapport à celle crée via le buildChallenge
=> [TECH] Corriger le test d'acceptance de POST /answers

mon-pix/app/components/signup-form.js, mon-pix/app/templates/application.hbs, mon-pix/app/templates/campaigns/fill-in-id-pix.hbs, mon-pix/app/templates/campaigns/skill-review.hbs, mon-pix/app/templates/components/certification-starter.hbs, mon-pix/app/templates/components/signup-form.hbs, mon-pix/tests/integration/components/signup-form-test.js
Il arrive que des utilisateurs double-clic sur le bouton de soumission du formulaire de création de compte sur la page `/inscription`. Ce comportement génère des erreurs mal gérées côté API, en particulier des erreurs de base de données liées à la contrainte d'unicité de l'e-mail. 
Cette PR propose une petite correction rapide et efficace pour empêcher le double-clic, tout en donnant un feedback de traitement (le loader) à l'utilisateur.
L'erreur visée est celle-ci ~ https://sentry.io/organizations/pix/issues/1226792847/?project=1398749&query=is%3Aunresolved
=> [BUGFIX] Ajout d'un état "loading" quand on clique sur le bouton de création de son compte (PF-904)

admin/app/transforms/date-only.js, api/db/seeds/data/certification-courses-builder.js, certif/app/transforms/date-only.js, mon-pix/app/transforms/date-only.js, orga/app/transforms/date-only.js
Lorsqu'un utilisateur avait des certifications en attente ou publiées et que celles-ci contenaient une date de naissance vide, une page oups! était rendue suite au clic de 'Mes certifications'
Bugfix apparu suite au merge de la PR https://github.com/1024pix/pix/pull/747. Une regex est opérée dans le cadre des transfomations ajoutées dans les fronts `date-only`, même pour les valeurs 'falsy' ce qui générait un plantage côté front.
Ligne en cause :
`// date-only.js`
`    if (date.search(dateRegex) === 0) {`
Solution : 
`// date-only.js`
`    if (date && date.search(dateRegex) === 0) {`
Application de la solution dans tous les fronts + ajout de seeds permettant d'illustrer les cas possibles
=> [BUGFIX] Une page oups! s'affichait lorsque l'utilisateur souhaitait voir ses certifications

api/lib/domain/services/smart-random/smart-random.js
Quand on choisit un challenge, on fait choisit de manière aléatoire parmi toutes les questions possibles.
Si à la fin de l'algorithme, il y avait 2 acquis possibles, avec 10 questions, on prenait aléatoirement dans les 10 questions.
Cas problématique : Si un des acquis a 9 réplications et l'autre un seul, l'aléatoire donne 90% de chance de choisir le premier acquis, ce qui fait peu de différence d'un utilisateur à l'autre, et donne une impression de passer toujours par le même chemin.
- Lors du choix aléatoire de l'épreuve, les grouper par acquis, choisir aléatoirement un acquis, puis aléatoirement une épreuve de cet acquis.
Test effectué pour vérifier l'apport du ticket !
Sur la compétence 2.3, Collaborer, il n'y a que 2 acquis de niveau 2 (pour la première épreuve), @skill1 qui possède …
=> [FEATURE] Choisir une épreuve aléatoirement par acquis puis par challenge (PF-900).

mon-pix/app/controllers/campaigns/fill-in-campaign-code.js, mon-pix/app/controllers/campaigns/join-restricted-campaign.js, mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js, mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Lorsqu'un élève essaye de rejoindre une campagne et que la réconciliation ne peut être effectuée, un message d'erreur est affiché l'invitant à contacter l'organisateur de sa campagne. Le terme "campagne" n'est pas le bon et doit être remplacé par "parcours". 
Remplacer "campagne" par "parcours".
=> [FEATURE] Remplacement du mot campagne par parcours dans un message d'erreur (PF-914).

orga/app/styles/app.scss, orga/app/styles/globals/loading.scss, orga/app/templates/authenticated/campaigns/details/collective-results-loading.hbs
Dans Pix Orga, si les données concernant une campagne sont très importantes, l'ouverture de l'onglet **Résultats collectifs** peut durer plusieurs secondes.
Durant ce temps, aucune information est présente pour prévenir l'utilisateur.
Inclure un loader accompagné d'un texte pour prévenir l'utilisateur.
=> [FEATURE] Ajouter un loader pendant le calcul des résultats collectifs (PO-275).

api/Procfile, api/bin/www, api/db/knex-database-connection.js, api/package.json
On a des messages d'avertissement dans les logs du serveur PostgreSQL chez Scalingo du type :
```
2019-10-29 15:42:34.049640680 +0100 CET [postgresql-1] 2019-10-29 14:42:34 UTC LOG:  could not receive data from client: Connection reset by peer
```
Après investigation, il s'avère que ce message est écrit par le serveur quand un client ferme sa connexion sans l'avoir fait proprement.
On constate effectivement qu'une série de messages de ce type est écrit à chaque arrêt d'un conteneur de l'application.
On intercepte le signal envoyé par Scalingo demandant l'arrêt du conteneur et on utilise la fonction `destroy` de `knex` pour fermer proprement les connexions ouvertes.
Noter qu'il faut se débarrasser du processus `npm` pendant l'exécution afin que le signal `SIGTERM` soit correctement reçu …
=> [TECH] Fermer proprement les connexions à PostgreSQL lors de l'arrêt (PF-923)

api/lib/application/users/user-controller.js, api/lib/domain/usecases/find-users.js, api/lib/infrastructure/repositories/user-repository.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/usecases/find-users_test.js
Lors de la recherche des utilisateurs dans Pix Admin, la recherche est longue.
2 appels identiques étaient réalisés pour récupérer les utilisateurs : 
- un premier pour les récupérer véritablement en fonction de filtres et d'une pagination ;
- un second qui effectuait exactement la même requête mais faisait un `.count()` derrière.
Or en faisant un `.fetchPage()` on peut récupérer de base le nombre total d'utilisateurs correspondant aux filtres.
Il est possible que cela ne change pas grand chose, mais c'est déjà ça :)
=> [TECH] Supprimer un appel superflu sur la récupérations des utilisateurs dans Pix Admin (PA-115).

api/db/seeds/seed.js
Ponctuellement, lors du déploiement des _seeds_ dans la base, il arrive que cette opération soit en échec à cause d'une violation de la contrainte d'unicité dans la colonne `email` de la table `users`.
Récemment, une colonne (fk) `userId` a été ajoutée à la table `certification-candidates`. Elle représente le lien qui peut exister entre un utilisateur et son inscription à une session de certification. De fait, selon la règle des _builders_ (notamment _databaseBuilder_), si l'on passe la valeur `userId = undefined` dans le _builder_ de _certificationCandidate_, alors un lien est automatiquement crée (aka, un appel à _buildUser_ est effectué).
Dans les seeds sont crées environ 300 certification candidates. Et pour l'ensemble de ces candidats, un user est généré. Pour ces utilisateurs, on …
=> [BUGFIX] Il arrive que le seeding soit en échec à cause d'une violation de contrainte d'unicité sur les emails de la table users

scripts/release/publish.sh
Lors d'une mise en production, la release sentry ne fonctionne pas.
- Ajout de l'organisation dans les commandes `sentry-cli`. 
- Mettre dans l'ordre les options pour associer les commits à la release
=> [BUGFIX] Patch sentry-cli releases dans le script de release publish.

api/lib/plugins.js
Sentry écrit les versions sans le 'v'.
Rajout du 'v' en préfix du numéro de version.
=> [BUGFIX] Problème du nom de version de sentry.

scripts/release/publish.sh
Sentry ajoutait tous les commits faits depuis la dernière version même ceux hors master. 
Ne pas utiliser le mode commit auto de Sentry mais saisir le SHA du commit de la branche que l'on souhaite.
=> [BUGFIX] Problème d'ajout des commits dans les versions de Sentry.

api/lib/domain/services/students-xml-service.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/domain/services/students-xml-service_test.js
Il existe plusieurs règles de gestion pour savoir si un élève doit ou non être importé dans Pix Orga à partir du fichier SIECLE. Cette gestion est totalement différente selon les établissements scolaires. Il se trouve ici qu'il y a une règle de gestion que nous n'avions pas identifiée jusqu'alors : ne pas importer les élèves ayant une date de sortie renseignée dans le fichier SIECLE.
Ajouter cette règle de gestion.
Cette règle ne prévaut pas sur les autres règles déjà identifiées, elles ne se recoupent pas.
=> [FEATURE] Ne pas importer les élèves ayant une date de sortie dans le fichier SIECLE (PO-278).

api/db/migrations/20191118173128_copy-external-id-from-candidate-to-course.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/tests/acceptance/application/certification-course-controller_test.js, api/tests/tooling/airtable-builder/airtable-builder.js, api/tests/tooling/airtable-builder/factory/build-certification-prerequisites.js, api/tests/tooling/airtable-builder/factory/index.js
L'identifiant local du candidat, pourtant indiqué lors de l'inscription de celui-ci, n'est pas reporté
dans le certification-course lors de sa création, comme il devrait l'être à l'image des autres infos perso (nom, prénom, ddn et lieu de naissance)
Recopier cette information depuis le certification-candidate vers le certification-course lors de la création de ce dernier
- Cette PR inclut enfin des tests d'acceptance sur la route POST /api/certification-courses.
- Un script est prévu dans les semaines à venir pour recopier les identifiants externes qui ont manqué de l'être dans les sessions avant MEP.
=> [BUGFIX] L'identifiant externe n'était pas recopié depuis les données candidat vers le certification course à la création de celui ci (PA-120)

orga/app/styles/pages/authenticated.scss
Sous Windows uniquement, deux barres de scroll verticales s'affichent sur la liste des campagnes, et une barre horizontale (alors que désactivée).
Remplacer `overflow: scroll` par `overflow: auto`.
Il faudra sans doute faire de même sur Pix Certif (il y a le même code).
=> [BUGFIX] Supprimer les barres de scroll affichées en trop sur Pix Orga (PO-271).

api/lib/infrastructure/repositories/membership-repository.js, api/tests/integration/infrastructure/repositories/membership-repository_test.js, orga/app/models/membership.js, orga/app/templates/components/routes/authenticated/team/list-items.hbs, orga/tests/acceptance/team-list-test.js, orga/tests/integration/components/routes/authenticated/team/list-items-test.js
La liste des membre n'affichait que le nom et le prénom.
Afficher le rôle dans la liste des membres.
Trier les membres non pas par date d'ajout (tri de la bdd) mais par rôle d'abord et lastName ensuite.
=> [FEATURE] Afficher le rôle des membres dans Pix Orga (PO-210)

mon-pix/app/components/levelup-notif.js
À la fermeture d'une notification de succès entre deux checkpoints, les notifications suivantes ne s'affichaient plus. On pouvait par exemple voir un niveau 2 puis un niveau 4 après checkpoint sans voir le niveau 3.
Le problème avait lieu plus précisément lorsque on obtenait le niveau 2 à la question N puis le niveau 3 à la question N+1. À ce moment là, le composant n'est pas détruit mais réutilisé lors de l'acquisition d'un nouveau niveau. 
Il faut donc utiliser la méthode `didUpdateAttrs` pour réinitialiser la condition d'affichage au moment du recyclage du composant.
Si on avait détruit le composant, on aurait utilisé le double de ressources. ♻️
=> [BUGFIX] Afficher les prochaines notifications de succès après une fermeture (PF-913).

mon-pix/app/templates/components/certification-starter.hbs
Modification des textes suivants : 
"Vous souhaitez participer au test de certification" par "Vous allez commencer votre test de certification"
"Lancer mon test" par "Commencer mon test"
=> [FEATURE] Modification de certains textes dans la page de lancement de test de certification (PF-928)

api/server.js
On a parfois des erreurs qui n'apparaissent pas dans les logs API, comme les erreurs SQL.
À la sortie des contrôleurs, les requêtes sont traitées par un handler de `'onPreResponse'`. Ce handler ne passe que les erreurs dérivant de `DomainError` ou de `InfrastructureError` à l'`errorManager`.
Dans le `'onPreResponse'`, passer toutes les erreurs à l'`errorManager`. Il se comporte déjà correctement pour les traiter et il est déjà testé pour ce cas.
Note : les logs passent par Bunyan, donc on a des stack traces en JSON, c'est un brin moins lisible pour l'usage au quotidien.
=> [TECH] Loguer toutes les erreurs sortant des contrôleurs API

admin/app/controllers/authenticated/certifications/sessions/info/index.js, admin/app/controllers/authenticated/certifications/sessions/info/list.js, admin/app/routes/authenticated/certifications/sessions/info.js, admin/app/routes/authenticated/certifications/sessions/info/list.js, admin/app/styles/authenticated/certifications/sessions.scss, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/mirage/config.js, admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js, admin/tests/unit/controllers/authenticated/certifications/sessions/info/index-test.js
Dans le cadre de l'EPIX sur la finalisation de session, des données vont être ajoutées à PixAdmin, ainsi que des déplacements/duplications de fonctionnalités vers la page d'info de session.
Pour rester agiles, nous procédons petits pas par petits pas, en commencant par dupliquer le bouton d'export des résultats pour les prescripteurs vers la page d'info de session.
Duplication du bouton
Ajout de tests
=> [FEATURE] Dupliquer le bouton d'export des résultats pour les prescripteurs sur la page d'info de session dans Pix Admin (PA-118)

admin/app/models/session.js, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js, api/db/seeds/data/sessions-builder.js, api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/models/Session.js, api/lib/domain/usecases/finalize-session.js, api/lib/domain/usecases/get-session.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/acceptance/application/session/session-controller-put-finalization_test.js, api/tests/tooling/database-builder/factory/build-session.js, api/tests/tooling/domain-builder/factory/build-session.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/usecases/finalize-session_test.js, api/tests/unit/domain/usecases/get-session_test.js
Avec l'introduction de la notion de statut sur une session, on souhaite disposer de cette information sur PixAdmin.
Ajout d'une entrée **"Statut:   nom_du_statut"** dans la page d'info de la session sur PixAdmin
Au passage, sécurisation de la route `GET /sessions/:id`   (à voir si c'est OK, si il n'y a pas de transmission de lien en démo ou autres)
=> [FEATURE] Affichage du statut de la session dans PixAdmin (PA-119)

api/lib/application/sessions/session-controller.js, api/lib/domain/errors.js, api/lib/domain/usecases/link-user-to-session-certification-candidate.js, api/lib/infrastructure/serializers/jsonapi/certification-candidate-serializer.js, api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
La validation peut encore être améliorée lors de l'étape de réconciliation d'un candidat à une session de certification. Particulièrement, la date de naissance reçue depuis le front n'était pas checkée, ce qui pouvait, au moment du SELECT dans la base de données, déclencher une exception non gérée et donc une erreur 500.
Données désérialisées via le désérialiseur de certification-candidate, et donc on profite de check de validation de la date de naissance.
=> [BUGFIX] Eviter les erreurs 500 lors du check de date de naissance quand un candidat essaie de rejoindre une session de certification (PF-941)

mon-pix/app/styles/components/_challenge-statement.scss, mon-pix/app/styles/components/_qroc-solution-panel.scss
Lorsque l'écran est trop petit, la question dépasse de l'écran visible.
Exemple sur https://app-pr860.review.pix.fr/challenges/reco62b0R3iX3tQk6/preview
Ajout d'un `word-break` sur les champs concernés.
=> [BUGFIX] Ajouter des line-break dans la consigne des challenges (PF-939).

mon-pix/app/styles/components/_challenge-statement.scss, mon-pix/app/styles/components/_qroc-solution-panel.scss
L'initiative lancée par la PR https://github.com/1024pix/pix/pull/860 cause le problème suivant :
On utilise `overflow-wrap: break-word` au lieu de `word-break: break-all`
> Note : À la différence de word-break, overflow-wrap créera uniquement un saut de ligne si un mot entier ne peut pas être placé sur sa propre ligne sans dépasser.
https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
=> [BUGFIX] Utiliser overflow-wrap au lieu de word-break.

api/lib/application/certification-courses/certification-course-controller.js, api/lib/application/sessions/session-controller.js, api/lib/domain/errors.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/infrastructure/repositories/certification-candidate-repository.js, api/tests/acceptance/application/certification-course-controller_test.js, api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js, api/tests/unit/application/certification-courses/certification-course-controller_test.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js, mon-pix/app/components/certification-joiner.js, mon-pix/app/components/certification-starter.js, mon-pix/app/components/stepper.js, mon-pix/app/controllers/certifications/start.js, mon-pix/app/models/certification-course.js, mon-pix/app/templates/certifications/start.hbs, mon-pix/app/templates/components/certification-starter.hbs, mon-pix/app/templates/components/stepper.hbs, mon-pix/config/environment.js, mon-pix/tests/acceptance/certification-course-test.js, mon-pix/tests/unit/components/certification-starter-test.js
Dans le démarrage d'une certification, l'utilisateur pouvait entrer un id de session suivi d'un code d'accès qui ne correspondait pas à ladite session.
Vérifier que le code d'accès correspond bien à la session.
Nous avons supprimé le feature toggle `FT_IS_NEW_CERTIFICATION_START_ACTIVE` qui n'est plus nécessaire.
=> [BUGFIX] Vérifier que le code d'accès correspond à la session de certif (PF 931)

high-level-tests/e2e/cypress.json
- Durant les tests E2E, on attendait des réponses de stats.pix.fr, qui ne répondais pas ou lentement, et qui faisait planter les tests
Blacklister stats.pix.fr
=> [TECH] Ne pas faire les appels vers matomo dans les tests E2E.

mon-pix/app/components/challenge-statement.js
Lorsqu'on clique sur l'instruction des challenges, on observe le comportement suivant sur Chrome (sur Firefox, la ligne est en pointillés).
Cette manifestation visuelle est induite par l'utilisation de `tabindex="-1"`.
Initialement, on s'en servait pour faire un autofocus sur l'instruction du challenge en cours. 
Aujourd'hui, il semblerait que cet autofocus ne soit plus nécessaire et aucune référence à un id suivant le schéma `#challenge_statement_<id>` n'a été trouvé sur la page. 
On enlève donc les déclarations liées à `tabindex="-1"`.
> A negative value (usually tabindex="-1") means that the element is not reachable via sequential keyboard navigation, but could be focused with Javascript or visually. It's mostly useful to create accessible widgets with JavaScript. You can observe the …
=> [BUGFIX] Rendre l'instruction des challenges non cliquable (PF-956).

api/lib/infrastructure/repositories/certification-repository.js
Le test du diff échouait environ une fois sur 130.
Rendre `certificationRepository.findByUserId()` déterministe.
J'ai choisi `orderBy('id', 'desc')`, qui était l'ordre remonté le plus souvent par le test. Est-ce bien le bon ordre ?
Pour faire mes stats, j'ai utilisé une boucle while qui écrivait un `.` en cas de succès, et un `E` en cas d'erreur (c'est du fish shell, il faut que je pense à repasser à bash).
```
while true ; env NODE_ENV=test npx mocha --exit api/tests/integration/infrastructure/repositories/certification-repository_test.js | awk '/7 passing/ {printf "."} ; /AssertionError/ {print "E"}' | tee out.log ; end
```
=> [TECH] Corrige un test qui échoue au hasard

admin/app/models/session.js, admin/app/styles/app.scss, admin/app/styles/authenticated/certifications/sessions.scss, admin/app/styles/authenticated/certifications/sessions/info/index.scss, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js
On souhaite enrichir les informations fournies par l'application aux utilisateurs. Dans notre cas,
on veut afficher, dans la page de détails d'une session, le nombre de certifications non terminées.
Il s'agit, plus techniquement, des certifications qui ne sont pas validées, c a d : pas terminées, pas validées, assessment manquant, etc...
Ajout d'une ligne sur la page de détails de session. Nous disposions déjà des infos nécessaires pour produire cette information, pas de sollicitation supplémentaire sur l'API.
Ajout d'un `computed` dans le modèle de session côté front pour compter le nombre de certifications pas validées.
=> [FEATURE] Affichage du nombre de certifications non validées sur la page de détails d'une session PixAdmin (PA-126)

mon-pix/app/routes/assessments/challenge.js, mon-pix/tests/unit/routes/assessments/challenge-test.js
Sur les épreuves de copier/coller, quand on utiliser le text-area, des personnes peuvent ajouter sans faire exprès (via un glissement, en appuyant sur entrée, etc..) des retours à la ligne et des espaces sur la fin de la solution.
- Trim la réponse avant de l'envoyer au back.
- A faire peut être dans le deserializer coté back, ou dans le Examiner qui corrige les answers, vous en pensez quoi ?
=> [BUGFIX] Ne pas prendre en compte les espaces et retour à la ligne inutile (PF-953).

api/db/migrations/20191202152127_add_column_externalId_to_certification_centers.js, api/db/migrations/20191202152240_add_column_type_to_certification_centers.js
Les centres de certification ne sont pas typés et ne possèdent pas d'identifiants externe.
Créer des scripts de migration afin d'ajouter les colonnes 'externalId' et 'type' dans la table 'certification-centers'.
Afin de limiter les impacts pour les centres de certifications existants déjà en production, la colonne 'type' n'est pas obligatoire pour le moment. Elle sera rendue obligatoire dans le futur.
=> [FEATURE] Ajout des colonnes 'externalId' et 'type' dans la table 'certification-centers'. (PF-944)

api/db/migrations/20191129100835_add_column_comment_to_session.js, api/lib/application/sessions/session-controller.js, api/lib/domain/models/Session.js, api/lib/domain/usecases/finalize-session.js, api/lib/infrastructure/repositories/session-repository.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/acceptance/application/session/session-controller-put-finalization_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/tooling/database-builder/factory/build-session.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/models/Session_test.js, api/tests/unit/domain/usecases/finalize-session_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js, certif/app/adapters/session.js, certif/app/components/session-finalization-examiner-comment-step.js, certif/app/controllers/authenticated/sessions/finalize.js, certif/app/models/session.js, certif/app/styles/app.scss, certif/app/styles/components/session-finalization-examiner-comment-step.scss, certif/app/styles/components/session-finalization-formbuilder-link-step.scss, certif/app/styles/components/session-finalization-step-container.scss, certif/app/styles/pages/authenticated.scss, certif/app/templates/authenticated/sessions/finalize.hbs, certif/app/templates/components/routes/authenticated/sessions/session-finalizer.hbs, certif/app/templates/components/session-finalization-examiner-comment-step.hbs, certif/tests/acceptance/session-finalization-test.js, certif/tests/integration/components/session-finalization-examiner-comment-step-test.js
Suite de l'EPIX Commentaires/fin de test (pix admin app), on ajoute la deuxième étape, à savoir le commentaire global de la session. Nous nommerons ce commentaire, ajouté par le surveillant après la fin de la session, "examiner-comment". 
Ajout d'une nouvelle étape dans la page de finalisation de session.
AVANT
APRES  ⬇️ 
Global comment = examiner comment
TODO :
=> [FEATURE] Ajouter une étape d'ajout de commentaire global lors de la finalisation de la session (PC-86) 

admin/app/models/certification.js, admin/tests/unit/services/session-info-service-test.js, api/lib/domain/services/certification-service.js, api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js, api/tests/unit/domain/services/certification/certification-service_test.js
Quand on charge une certification depuis PixAdmin et qu'on regarde le détail du payload, l'id du JsonApi object contenu dans celui-ci pouvait être erroné. C'est supposé être l'id du `certification-course` correspondant, mais parfois c'était celui de son `assessment-result`.
Corriger la manière dont est créé le certification-result dans le service correspondant +
retrait de la propriété `certificationId` qui apporte de la confusion et qui est redondant avec la propriété `id`
=> [BUGFIX] Le payload contenant les certifications pour PixAdmin pouvait avoir comme id celui de son assessment-result (PA-129)

api/lib/domain/services/user-service.js
Lors de la génération d'un test de certification, l'algorithme récupère un ensemble de challenges et sélectionne en priorité des challenges qui n'ont pas encore été posés au candidat pendant ses positionnements/campagnes. Par contre, c'est toujours la première question non posée qui est choisie. Et comme l'ensemble des challenges est récupéré toujours selon le même ordre, c'est souvent les mêmes questions qui sont posées (certaines questions n'ont même jamais été présentées en test de certification !)
Remplacer `_.first()` par `_.sample()` pour sélectionner aléatoirement une question.
Vu avec le métier, vu qu'on choisit parmi les variantes d'un même challenge, c'est ok.
=> [TECH] Mise en place de choix aléatoire des questions à poser lors d'un test de certification

api/lib/infrastructure/repositories/campaign-collective-result-repository.js, api/tests/integration/infrastructure/repositories/campaign-collective-result-repository-test.js
La récupération de résultats collectifs d'une campagne sature la mémoire et crash le container.
Refonte du code avec la méthodologie de Refactoring de *Martin Fowler*, au lieu de faire plusieurs requêtes qui nous remontent beaucoup d'informations que nous trions après dans le code.
Nous avons pris le partie de faire des requêtes qui vont directement chercher les bonnes informations déjà triées.
=> [FEATURE] Amélioration des performances de la récupération des résultats collectifs (PO-298).

mon-pix/app/styles/components/_challenge-response.scss
Les labels des champs de réponses des questions apparaissent en gras.
On met les labels en poids normal pour les champs de réponses.
=> [FEATURE] Retirer le bold des labels des encadrés réponses (PF-963).

admin/app/components/certification-session-report.js, admin/app/controllers/authenticated/certifications/sessions/info/list.js, admin/app/models/certification.js, admin/app/services/session-info-service.js, admin/app/templates/authenticated/certifications/sessions/info/list.hbs, admin/app/templates/components/certification-session-report.hbs, admin/tests/acceptance/certifications-parsing-uploaded-attendance-sheet-test.js, admin/tests/integration/components/certification-session-report-test.js, admin/tests/unit/components/certification-session-report-test.js, admin/tests/unit/services/session-info-service-test.js, api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/models/Session.js, api/lib/domain/usecases/get-session-certifications.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/data/session.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/lib/infrastructure/repositories/session-repository.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-get-certifications_test.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/unit/application/session/index_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/models/Session_test.js, api/tests/unit/domain/usecases/get-session-certifications_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Avec les _**EPIX**_ de _Début Certification_ et _Commentaires/fin de test_, des bouleversements, et donc des adaptations, sont à prévoir côté **PixAdmin**.
En l'occurrence, avec l'arrivée de ces **EPIX**, l'équipe du pôle certif sait qu'elle n'a plus à analyser le PV de session et à enregistrer les données afin d'avoir des certifications à peu près complètes. Cependant, et particulièrement parce que **_l'EPIX_** _Commentaires/fin de test_ n'est pas encore finie, l'équipe du pôle certif se trouve dans un état un peu de transition où les fonctionnalités ne se suffisent pas à elles-mêmes.
Pour le cas de ce ticket, il se trouve que les certifications dont le statut d'`assessment-result` est différent de `validated` n'étaient pas incluses dans le fichier exporté pour le jury.
On en profite …
=> [BUGFIX] Les certifications non 'validated' ne remontaient plus dans le fichier pour le jury (PA-125)

mon-pix/app/styles/globals/_loading.scss, mon-pix/app/templates/certifications/start-loading.hbs
En cas de coupure réseau, l'onglet certifications affichait le message "Votre profil n'est pas encore certifiable" même pour les utilisateurs dont le profil est certifiable.
Supprimer la page d'erreur de la route `certifications.start`.
Ça a pour effet d'afficher la page d'erreur par défaut (page Oups) en cas d'erreur réseau.
Et d'afficher une page de chargement en cas de lenteurs :
=> [BUGFIX] Corrige le message de profil non certifiable en cas de coupure réseau (PF-962)

admin/app/models/certification-details.js, admin/app/models/certification.js, admin/app/models/membership.js, admin/app/models/organization.js, admin/app/models/session.js, admin/app/models/user.js, admin/app/styles/authenticated/certifications/sessions/info/index.scss, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js, api/db/seeds/data/sessions-builder.js
Dans le cadre de l'EPIX de Commentaire/Fin de test, les utilisateurs appartenant à un centre de certification peuvent finaliser une session et laisser un commentaire global pour signaler un problème ou un quelconque souci rencontré durant le déroulé de celle-ci. Ce commentaire n'est pas encore visible par les utilisateurs de PixAdmin.
Affichage du commentaire global dans la page de détails de session dans PixAdmin.
=> [FEATURE] Affichage du commentaire global de la session dans la page de détails de session dans PixAdmin (PA-121)

api/lib/domain/errors.js, api/lib/domain/usecases/start-campaign-participation.js, api/lib/infrastructure/repositories/campaign-participation-repository.js, api/lib/infrastructure/utils/error-manager.js, api/tests/acceptance/application/campaign-participation-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js, api/tests/unit/domain/usecases/start-campaign-participation_test.js, mon-pix/app/controllers/campaigns/campaign-landing-page.js, mon-pix/app/controllers/campaigns/fill-in-id-pix.js, mon-pix/app/routes/campaigns/campaign-landing-page.js, mon-pix/app/routes/campaigns/fill-in-id-pix.js, mon-pix/app/styles/pages/_fill-in-id-pix.scss, mon-pix/app/templates/campaigns/campaign-landing-page.hbs, mon-pix/app/templates/campaigns/fill-in-id-pix.hbs, mon-pix/tests/acceptance/resume-campaigns-test.js
Sentry nous remonte ce type d'erreur : 
```
error
insert into "campaign-participations" ("campaignId", "createdAt", "participantExternalId", "userId") values ($1, $2, $3, $4) returning "id" - duplicate key value violates unique constraint "campaign_participations_campaignid_userid_unique"
environment
production
```
Après investigation, nous supposons avec @octo-thlo qu'il s'agit de double-click, venant de plusieurs page différentes.
- Empêcher la demander de sauvegarde d'aller jusqu'en base où l'erreur d'unicité est levée (et cause une erreur HTTP 500), mais la thrower bien avant pour la renvoyer au format HTTP Precondition Failed.
- Essayer d'endiguer le double-click sur les pages de présentation de campagne (landing page) et d'identifiant externe (fill-in-id-pix page).
Toutes les …
=> [BUGFIX] Empêcher l'erreur d'unicité des CampaignParticipation d'arriver jusqu'en base de données (PO-299). 

admin/app/services/session-info-service.js
Le nom du fichier csv téléchargé lorsqu'on télécharge les résultats de la session dans PixAdmin contient la date à laquelle le fichier a été crée, ce qui n'est plus très utile.
Le nom du fichier a maintenant la forme suivante: 
`<annee><mois><jour>_<heure><minute>_resultats_session_<id de la session>.csv`
Exemple pour une session d'id 5 du 4 janvier 1990 à 9h00 :
19900104_0900_resultats_session_5.csv
@Krysthalia merci, voici des recommandations suivies par cette PR concernant le nommage de fichier : https://doranum.fr/stockage-archivage/comment-nommer-fichiers/
=> [FEATURE] Modification du nom de fichier de résultats de la session dans PixAdmin (PA-130)

mon-pix/app/styles/components/_competence-card-desktop.scss, mon-pix/app/templates/components/profile-content.hbs, mon-pix/tests/acceptance/competence-profile-test.js, mon-pix/tests/integration/components/profile-content-test.js
L'affichage sur tablettes est cassé entre 768px et 890px, parce que le `media.isDesktop` renvoie le layout en mode mobile jusqu'à 980px alors que le css `is-device('tablet')` applique le CSS pour tablettes dès 768px.
Aligner le mode tablette sur le mode desktop et ne plus avoir de différence tablette/desktop (jusqu'à ce qu'on ait un design spécifique tablettes).
=> [BUGFIX] Aligner les règles css sur tablettes avec celles sur desktop (PF-978).

high-level-tests/e2e/cypress/fixtures/campaigns.json, high-level-tests/e2e/cypress/fixtures/memberships.json, high-level-tests/e2e/cypress/fixtures/organizations.json, high-level-tests/e2e/cypress/fixtures/students.json, high-level-tests/e2e/cypress/integration/campaign.feature, high-level-tests/e2e/cypress/plugins/index.js, high-level-tests/e2e/cypress/support/commands.js, high-level-tests/e2e/cypress/support/step_definitions/campaign.js, high-level-tests/e2e/cypress/support/step_definitions/index.js, high-level-tests/e2e/cypress/support/step_definitions/login.js, high-level-tests/e2e/package-lock.json, high-level-tests/e2e/package.json, mon-pix/app/controllers/campaigns/join-restricted-campaign.js, mon-pix/app/routes/campaigns/join-restricted-campaign.js, mon-pix/app/templates/campaigns/join-restricted-campaign.hbs, mon-pix/tests/acceptance/start-campaigns-test.js, mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Les utilisateurs hors GAR peuvent d'ors et déjà se réconcilier, mais ne peuvent pas changer leur nom et prénom, puisque ceux-ci sont grisés pour les utilisateurs venant du GAR.
Checker si l'utilisateur authentifié vient du GAR ou non, et lui permettre de saisir son nom et prénom ou non.
=> [FEATURE] Permettre aux utilisateurs non connectés via le GAR de saisir leur nom et prénom lors de la réconciliation (PF-886).

api/lib/application/preHandlers/session-authorization.js, api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/services/session-authorization-service.js, api/lib/domain/usecases/finalize-session.js, api/lib/domain/usecases/get-attendance-sheet.js, api/lib/domain/usecases/get-session-certification-candidates.js, api/lib/domain/usecases/get-session.js, api/lib/domain/usecases/import-certification-candidates-from-attendance-sheet.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/session-repository.js, api/tests/acceptance/application/session/session-controller-get-attendance-sheet_test.js, api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/unit/application/preHandlers/assessment-authorization_test.js, api/tests/unit/application/preHandlers/session-authorization_test.js, api/tests/unit/application/session/index_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/services/session-authorization-service_test.js, api/tests/unit/domain/usecases/finalize-session_test.js, api/tests/unit/domain/usecases/get-attendance-sheet_test.js, api/tests/unit/domain/usecases/get-session-certification-candidates_test.js, api/tests/unit/domain/usecases/get-session_test.js, api/tests/unit/domain/usecases/import-certification-candidates-from-attendance-sheet_test.js
L'accès à des sessions peut se faire via des routes communes utilisées par PixAdmin et PixCertif.
A ce titre, on peut être amené à vérifier si l'utilisateur a bien accès à la session en vérifiant dans le usecase :
- Si l'utilisateur a le rôle PixMaster
- Ou bien si l'utilisateur fait bien partie du centre de certification à l'origine de la création de la session
On factorise ce besoin dans un pre-handler.
- Application de ce prehandler sur toutes les routes dont le usecase dépendant utilisait ensureUserHasAccessToSession()
- Tests de validation : 
- non reg sur Pix certif
- consultation d'une session sur Pix admin
=> [TECH] Ajout d'un prehandler de vérification d'accès à une session (PC-92)

certif/app/adapters/session.js, certif/app/components/session-finalization-examiner-comment-step.js, certif/app/controllers/authenticated/sessions/finalize.js, certif/app/models/session.js, certif/app/templates/authenticated/sessions/finalize.hbs, certif/app/templates/components/routes/authenticated/sessions/session-finalizer.hbs, certif/app/templates/components/session-finalization-examiner-comment-step.hbs, certif/tests/acceptance/session-finalization-test.js, certif/tests/integration/components/session-finalization-examiner-comment-step-test.js
Les commentaires globaux de fin de session pouvaient réapparaître d'une page de session finalisation à une autre.
- Utiliser `session.examinerComment` comme vecteur de ce commentaire.
- Supprimer l'ancien `examinerComment` global.
=> [BUGFIX] Ne plus afficher d'ancients examinerComment dans le champs de text prévu à cet effet. (PC-93)

api/lib/application/assessments/index.js
La route /assessments/:id/next n'a plus besoin du `challengeId`. Cet usage a été supprimé avec #327 . Pour ne pas provoquer d'erreurs pour l'utilisateur si son front est dans une version inférieure, il a été choisi de rendre optionnel et déprécié l'utilisation de `challengeId`.
Maintenant que cela fait suffisamment longtemps que #327 a été mergée, nous pouvons supprimer cet usage déprécié.
Ceci est un BSR - Boy Scout Rule
_Leave your code better than you found it._
=> [TECH] BSR - Suppression de l'usage déprécié du ChallengeId lors de l'appel à la route /assessments/:id/next.

mon-pix/app/styles/components/_rounded-panel.scss
Des retours à la lignes sont faits après certains champs `input` dans la zone de réponse.
Par exemple sur le challenge [recAQDoflZcaBLqq3](https://app-pr919.review.pix.fr/assessments/10000004/challenges/recAQDoflZcaBLqq3)
Le label en `inline-block` par défaut a été overridé par `inline`.
=> [BUGFIX] Enlever le retour à la ligne après les inputs dans la zone de réponse

api/lib/infrastructure/airtable.js, api/lib/infrastructure/caches/preloader.js, api/lib/infrastructure/datasources/airtable/area-datasource.js, api/lib/infrastructure/datasources/airtable/challenge-datasource.js, api/lib/infrastructure/datasources/airtable/competence-datasource.js, api/lib/infrastructure/datasources/airtable/course-datasource.js, api/lib/infrastructure/datasources/airtable/datasource.js, api/lib/infrastructure/datasources/airtable/skill-datasource.js, api/lib/infrastructure/datasources/airtable/tube-datasource.js, api/lib/infrastructure/datasources/airtable/tutorial-datasource.js, api/lib/infrastructure/repositories/challenge-repository.js, api/lib/infrastructure/repositories/course-repository.js, api/tests/integration/infrastructure/airtable_test.js, api/tests/tooling/fixtures/infrastructure/skillAirtableDataObjectFixture.js, api/tests/unit/infrastructure/caches/preloader_test.js, api/tests/unit/infrastructure/datasources/airtable/area-datasource_test.js, api/tests/unit/infrastructure/datasources/airtable/course-datasource_test.js, api/tests/unit/infrastructure/datasources/airtable/datasource_test.js, api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js, api/tests/unit/infrastructure/datasources/airtable/tutorial-datasource_test.js, api/tests/unit/infrastructure/repositories/challenge-repository_test.js, api/tests/unit/infrastructure/repositories/course-repository_test.js, api/tests/unit/infrastructure/repositories/skill-repository_test.js
On exécute beaucoup trop de traitements de conversions à chaque requête client. Ce phénomène consomme trop de RAM + CPU + entrées I/O + temps. Ce qui dégrade ou limite les perfs du système et sa capacité à encaisser de la charge.
L'objet de cette PR est de préparer la mise en oeuvre d'un nouveau cache applicatif, toujours basé sur Redis (donc avec des valeurs stockées sous forme de String), mais au niveau des Datasources plutôt que de Airtable, dont l'objectif sera de réduire la quantité de ressources nécessaires pour l'éxécution des requêtes client.
Changements contenus dans cette PR:
- Mutualiser la logique d'appel (pour des besoins de type `get(id)` ou `list`) au module `infrastructure/airtable.js` pour toutes les Datasources dans un module de type pseudo-classe-mère (l'équivalent …
=> [TECH] Préparation à l'ajout d'un cache de second niveau pour les objets Airtable Datasources.

api/lib/application/student-user-associations/index.js, api/tests/acceptance/application/student-user-association-controller_test.js, api/tests/integration/application/student-user-associations/index_test.js, mon-pix/app/controllers/campaigns/join-restricted-campaign.js, mon-pix/app/utils/standardize-number.js, mon-pix/tests/unit/utils/standardize-number-test.js
Lors de la réconciliation entre un élève et un compte Pix, l'utilisateur (identifié avec son compte Pix) doit saisir sa date de naissance. S'il saisis un caractère en trop comme un espace ou bien un zéro supplémentaire, on se retrouve avec une date de naissance "valide" dans le formulaire, qui transite jusqu'au back, et finalement la base de données nous fait savoir que ce n'est pas une date valide.
Exemple : "2012- 12-12" ou "2012-009-12"
- Ajouter des checks côté front
- Ajouter des checks côtés back avec les validateurs Joi
Il y a 2 types de validateurs : 
- ceux du domaine, associé à un modèle du domaine, et définis dans un fichier à part ;
- ceux plus "application", associé à un payload, et implémentés directement dans la définition de la route dans `index.js`.
Dans notre cas cela ne …
=> [FEATURE] Ne pas prendre en compte les caractères en trop lors de la réconciliation (PF-935).

api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/infrastructure/repositories/answer-repository.js, api/lib/infrastructure/repositories/certification-challenge-repository.js, api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js, api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
En cas de lenteur API, plusieurs réponses à la même question pouvaient être enregistrés.
Ceci a des conséquences, nous pensons particulièrement à la certification : en effet, l'algo compte 2 réponses apportés à une compétence, alors qu'en fait il ne s'agit que d'une seule réponse en double (et donc on oublie de lui poser certaines questions, etc...)
Eviter en toute circonstance ce problème est compliqué étant donné l'existant de la base de données.
En effet, une solution radicale aurait pu être d'ajouter une contrainte d'unicité sur le couple challengeId/assessmentId dans la table `answers`, mais cela implique de nettoyer dans un premier temps les doublons déjà présents dans la table.
Il existe une solution qui peut se traduire par une requête SQL du style : (pseudo SQL) :
```
INSERT INTO …
```
=> [BUGFIX] Limiter le bug de multiples réponses à un même couple challengeId/assessmentId (PF-964)

api/lib/domain/usecases/start-writing-campaign-results-to-stream.js, api/lib/infrastructure/repositories/campaign-participation-repository.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
L'export du CSV est un besoin fonctionnel des organisations. Ces dernières cherchent à obtenir sous forme de CSV les résultats de chaque participant. Ces lignes servent par exemple, à donner une note à des étudiants, dans le cas des université. Certaines université ont donc parfois besoin d'avoir des CSV avec 3000 étudiants. Si la campagne en question concerne l'ensemble des 16 compétences, cela peut représenter plusieurs millions de cellules `csv`. 
Dans un premier temps, toutes les données étaient remontées en mémoire avant de faire des calculs. Avec certaines campagnes, cela ne tenait pas en mémoire, faisant crasher les conteneurs à chaque demande d'export. Une première solution a donc été mise en place, consistant à utiliser un `stream` afin d'alléger la pression sur la mémoire, et de …
=> [FEATURE] Améliorer les performances de l'export CSV (PO-296).

api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/errors.js, api/lib/domain/models/CertificationCandidate.js, api/lib/domain/usecases/link-user-to-session-certification-candidate.js, api/lib/infrastructure/utils/error-manager.js, api/package-lock.json, api/package.json, api/tests/integration/infrastructure/utils/error-manager_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/errors_test.js, api/tests/unit/domain/models/CertificationCandidate_test.js, api/tests/unit/domain/usecases/link-user-to-session-certification-candidate_test.js
Une erreur 500 était captée sur Sentry lorsque, lors de la réconciliation avec un utilisateur inscrit à une session, une date de naissance hors limite était indiquée (par exemple : 0000-01-01)
On utilise Joi pour valider l'ensemble de la donnée entrante. Depuis la nouvelle version de Joi, on peut faire une validation propre sur les dates avec format ISO.
Pour tester fonctionnellement, aller sur la page de réconciliation, afficher les requêtes réseaux sur la console du navigateur et entrer 01 01 0000 en date de naissance. Constater une erreur 400 et pas 500.
=> [BUGFIX] Correction de l'erreur 500 quand la date de naissance est hors limite lors de la réconciliation en certification (PF-984)

api/lib/application/preHandlers/session-authorization.js, api/lib/application/sessions/index.js, api/lib/domain/usecases/update-session.js, api/lib/infrastructure/repositories/session-repository.js, api/tests/acceptance/application/session/session-controller-get-certification-candidates_test.js, api/tests/acceptance/application/session/session-controller-patch_test.js, api/tests/acceptance/application/session/session-controller-put-finalization_test.js, api/tests/unit/application/preHandlers/session-authorization_test.js, api/tests/unit/application/session/index_test.js, api/tests/unit/domain/usecases/update-session_test.js
Récemment, un pré handler qui vérifie l'autorisation d'accès à une session a été crée. Appliquons-le là où il faut !
Dans la route PATCH /sessions/:id, on vérifiait l'autorisation pour la mise à jour via la récupération d'un user complet avec ses memberships etc, donc plusieurs requêtes SQL dans le usecase. Puisqu'on dispose de l'ID de la session, alors on peut se servir du pré handler ici.
Simplement tester la mise à jour d'une session via PixCertif pour le fonc.
=> [TECH] Utiliser le pré handler d'autorisation de session pour la route PATCH sessions/:id

orga/app/templates/components/routes/register-form.hbs
Sur la page d'inscription de l'application Pix, l'utilisateur est invité à renseigné son "Prénom" avant son "Nom" alors que c'est l'inverse sur la page permettant de rejoindre une organisation à travers une invitation dans Pix Orga.
Dans un soucis d'uniformisation, il a été décidé d'inverser l'ordre des champs "Nom" et "Prénom" dans la page permettant de rejoindre une organisation afin que le "Prénom" soit situé avant le "Nom" dans le formulaire.
=> [FEATURE] Inversion des champs "Nom" et "Prénom" dans page permettant de rejoindre une Orga via invitation (PO-295)

certif/tests/acceptance/session-new-test.js
Le test d'acceptance de création de session simulait la création d'une session planifiée pour la date du 25 décembre 2019. Or, il est impossible de choisir une date de session qui précède la date d'aujourd'hui. Et devinez quel jour on est aujourd'hui ?....
Faire galérer dans 10 ans le prochain dév sur le bug ;)
=> [BUGFIX] Date dépassée dans le test d'acceptance de la création de session

api/lib/infrastructure/utils/pre-response-utils.js, api/server.js, api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js, api/tests/integration/infrastructure/utils/pre-response-utils_test.js, api/tests/test-helper.js, api/tests/tooling/server/http-test-server.js, api/tests/unit/infrastructure/utils/pre-response-utils_test.js, api/tests/unit/tooling/http-test-server_test.js
Dans l'API, lors des tests d'intégration la prise en compte des preResponse n'existe pas dans le helper HttpTestServer.
cf. Issue #767
Inclure la fonction preResponse dans le helper.
=> [TECH] Ajouter la preResponse dans HttpTestServer

certif/app/models/certification-candidate.js, certif/app/models/session.js, certif/app/templates/components/routes/authenticated/sessions/details/certification-candidates-tab.hbs, certif/app/templates/components/routes/authenticated/sessions/details/parameters-tab.hbs, certif/app/templates/components/routes/authenticated/sessions/list-items.hbs, certif/mirage/config.js, certif/mirage/factories/certification-candidate.js, certif/mirage/factories/certification-center-membership.js, certif/mirage/factories/certification-center.js, certif/mirage/factories/session.js, certif/mirage/factories/user.js, certif/mirage/scenarios/default.js, certif/mirage/serializers/certification-center-membership.js, certif/mirage/serializers/certification-center.js, certif/mirage/serializers/session.js, certif/mirage/serializers/user.js, certif/package-lock.json, certif/package.json, certif/tests/acceptance/session-candidates-test.js, certif/tests/acceptance/session-details-test.js, certif/tests/acceptance/session-finalization-test.js, certif/tests/acceptance/session-list-test.js, certif/tests/acceptance/session-new-test.js, certif/tests/acceptance/session-update-test.js, certif/tests/acceptance/terms-of-service-test.js, certif/tests/helpers/test-init.js, certif/tests/integration/components/routes/authenticated/sessions/details/certification-candidates-tab-test.js
Le bouton de finalisation de session est accessible même lorsqu'il n'a pas lieu d'être, c'est-à-dire même lorsqu'aucun candidat n'est finalisable (n'as pas encore passé sa certif)
Tant qu'aucun candidat n'a été lié à un user, on cache le bouton
Cette PR améliore (un peu) le setup Mirage sur PixCertif
=> [FEATURE] Cacher le bouton de finalisation de session tant qu'il n'existe pas au moins un candidat lié (PC-97)

mon-pix/app/styles/components/_certification-starter.scss
Le ticket lié à cette PR évoque en fait 2 problèmes :
1) Sous Firefox, le champ de code d'accès à la session est encadré en rouge
2) On veut forcer la majuscule dans le champ de code d'accès
1) Pas réussi à reproduire
2) Forçage de la majuscule réalisé
REVUE FONC : Tester la non-régression du champ sous tous les navigateurs.
=> [FEATURE] Forcer la mise en majuscule du code d'accès à la session (PF-885)

certif/app/controllers/authenticated/sessions/list.js, certif/app/models/session.js, certif/app/templates/authenticated/sessions/list.hbs, certif/app/templates/components/routes/authenticated/sessions/list-items.hbs, certif/tests/acceptance/session-list-test.js, certif/tests/unit/models/session-test.js
La liste des sessions de status n'affichait pas le statut des sessions.
Ajouter cette colonne :
=> [FEATURE] Ajouter la colonne "Statut" à la liste des sessions de Certif (PC-96).

mon-pix/app/components/challenge-embed-simulator.js, mon-pix/app/components/challenge-statement.js, mon-pix/app/styles/components/_challenge-embed-simulator.scss, mon-pix/app/templates/components/challenge-embed-simulator.hbs, mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Cette PR corrige deux bugs identifiés sur la page des challenges:
- un téléchargement de fichier est lancé sur le premier challenge, passer le challenge, lancer un téléchargement au challenge suivant sans cliquer sur les radio boutons pour spécifier le format du fichier 
--> **BUG**: le deuxième fichier téléchargé est celui du challenge précédent
--> épreuve contenant des téléchargements: [http://app.pix.fr/courses/recZpODEGETeIjT6b](http://app.pix.fr/courses/recZpODEGETeIjT6b)
- lorsque le réseau est lent et que deux challenges avec des embed se suivent
--> **BUG**: le premier embed d'affiche le temps que le deuxième se charge
--> épreuve avec des embed: [http://app.pix.fr/courses/reciMJOtivLZgO9gO](http://app.pix.fr/courses/reciMJOtivLZgO9gO)
- Lorsque deux même types de challenge se …
=> [BUGFIX] Gestion de deux mêmes types de challenge à la suite (PF-828)

api/lib/application/organizations/index.js, api/tests/integration/application/organizations/index_test.js, api/tests/unit/application/organizations/index_test.js, orga/app/templates/components/routes/authenticated/team/new-item.hbs, orga/tests/integration/components/routes/authenticated/team/new-item-test.js
Dans Pix Orga, lors d'une invitation, il est possible d'utiliser une adresse e-mail vide !
1. Rendre ce champ obligatoirement rempli, avant d'envoyer l'invitation. 
2. Ajouter une pré-validation côté API.
=> [BUGFIX] Rendre le champ e-mail obligatoire lors d'une invitation (PO-319).

mon-pix/app/templates/components/reset-password-form.hbs
Suite au changement de la font-size de la classe "button--uppercase", le texte du bouton "Connectez-vous" de la page https://app.pix.fr/changer-mot-de-passe/{key} se retrouve sur deux lignes. 
Modifier le design afin que le texte du bouton ne s'affiche que sur une seule ligne.
=> [BUGFIX] Modifier l'affichage du bouton "Connectez-vous" afin qu'il n'apparaisse pas sur deux lignes (PF-1006)

api/db/knex-database-connection.js, api/tests/acceptance/application/certification-course-controller_test.js, api/tests/acceptance/application/security-controller_test.js, api/tests/acceptance/application/session/session-controller-import-certification-candidates-from-attendance-sheet_test.js, api/tests/integration/infrastructure/repositories/certification-candidate-repository_test.js, api/tests/tooling/database-builder/database-buffer.js, api/tests/tooling/database-builder/database-builder.js
Comparatif de durée de tests API entre le commit (4 septembre 2019) https://github.com/1024pix/pix/commit/ba4b06a887597d1287bfe32b0491f98b66cff2cb et (aujourd'hui) https://github.com/1024pix/pix/commit/a2e45ffca9acce2964649fddc875a242c5ca61b8 :
https://github.com/1024pix/pix/commit/ba4b06a887597d1287bfe32b0491f98b66cff2cb
| Catégorie | Nombre de tests | Durée (secondes) |
| --- | --- | --- |
| Unitaire | 2192 | 3.354 |
| Intégration | 415 | 10.148 |
| Acceptance | 251 | 14.889 |
| `npm t` | 2878 | 26.971 |
https://github.com/1024pix/pix/commit/a2e45ffca9acce2964649fddc875a242c5ca61b8
| Catégorie | Nombre de tests | Durée (secondes) |
| --- | --- | --- |
| Unitaire | 2200 | 4.123 |
| Intégration | 526 | 10.623 |
| Acceptance | 354 | 23.521 |
| `npm t` | 3100 | 38.041 |
On remarque de gros …
=> [TECH] Tentative d'amélioration du temps pris par les tests auto API

api/lib/domain/usecases/get-or-create-saml-user.js, api/tests/unit/domain/usecases/get-or-create-saml-user_test.js
Lorsque un étudiant se connecte à Pix via le GAR, un utilisateur est crée en base avec le champ "cgu" à true. Or, cet étudiant n'a jamais réellement accepté les CGU.  
Lors de la création de l'utilisateur pour un étudiant accédant à Pix depuis le GAR, les CGU ne doivent pas être validées par défaut.
=> [FEATURE] Non validation des CGU lors de la création d'un utilisateur provenant du GAR (PF-820)

api/db/migrations/20200106155510_update_cgu_for_gar_users.js
Suite à la PF-820, les utilisateurs (étudiants) se connectant à Pix depuis le GAR ne valident plus les CGU par défaut. Néanmoins, les utilisateurs créés avant ce changement ont toujours les CGU validées en base de donnée.
Créer un script de migration afin d'invalider les CGU pour tous les utilisateurs provenant du GAR (samlId non null).
=> [FEATURE] Script de migration permettant d'invalider les CGU pour les utilisateurs provenant du GAR (PF-821)

api/lib/domain/models/Campaign.js, api/lib/domain/usecases/retrieve-campaign-information.js, api/lib/infrastructure/repositories/campaign-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/unit/domain/usecases/retrieve-campaign-information_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, mon-pix/app/models/campaign.js, mon-pix/app/routes/login-or-register-to-access-restricted-campaign.js, mon-pix/app/styles/components/_login-or-register.scss, mon-pix/app/templates/components/routes/login-or-register.hbs, mon-pix/app/templates/login-or-register-to-access-restricted-campaign.hbs, mon-pix/mirage/scenarios/default.js, mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign-test.js, mon-pix/tests/unit/components/routes/login-or-register-test.js, mon-pix/tests/unit/routes/login-or-register-to-access-restricted-campaign-test.js
Pour les élèves qui vont accéder à un parcours prescrit (SCO), s’ils ne sont pas connectés au préalable, leur donner plus de contexte.
Ajoutez la phrase : [Nom de l'Organisation] vous invite à rejoindre Pix
=> [FEATURE] Afficher une phrase de contexte (SCO) en haut de la double mire de connexion (PF-992 ).

api/lib/domain/models/UserCompetence.js, api/lib/domain/services/user-service.js
Le choix des épreuves à la création d'un test de certification.
La méthode `UserCompetence.hasEnoughChallenges()` a un comportement inverse à son nom : elle renvoie vrai si on n'a pas assez de challenges 😬
Faire que cette méthode se comporte comme son non l'indique, et inverser la condition de sa seule utilisation.
FONC REVUE : @asrodride Tester comportement normal lors de la génération d'un test de certification
=> [TECH] Corriger `UserCompetence.hasEnoughChallenges()` (PF-1026)

mon-pix/app/templates/application.hbs, mon-pix/app/templates/campaigns/campaign-landing-page.hbs, mon-pix/app/templates/campaigns/start-or-resume-error.hbs, mon-pix/app/templates/components/navbar-desktop-header.hbs, mon-pix/app/templates/components/navbar-mobile-header.hbs, mon-pix/app/templates/components/tutorial-item-on-scorecard.hbs
Pour les malvoyants, ajouter un texte alternatif aux images.
Cette PR ajoute un attribut ALT aux images qui n'ont pas encore de textes alternatifs.
=> [A11Y] Ajouter des attributs ALT aux images (PF-669).

api/db/knex-database-connection.js
La configuration (sujet très bas niveau) de la BDD PostgreSQL entre notre instance locale Docker et l'addon fourni par Scalingo semble être légèrement différente. En tout cas, suffisamment différente pour faire échouer une raw query déclenchée lors de l'initialisation du _databaseBuilder_ qui permet de récupérer la liste des tables ordonnées selon leurs inter-dépendances de clés étrangères.
Cette requête est utilisée depuis peu pour l'optimisation du temps des tests API
UPDATE : Il semblerait que ce soit aussi lié à la version de PG. Sur Scalingo on est en PG12, docker en PG10. La requête marche sur 10, pas 12 :/
https://www.postgresql.org/message-id/28491.1560519572%40sss.pgh.pa.us
J'ai vérifié, les seeds ont bien été déployées ce coup-ci
=> [BUGFIX] Echec du déploiement des seeds en RA (PF-1028)

api/lib/domain/usecases/create-session.js, api/tests/acceptance/application/session/session-controller-post_test.js, api/tests/unit/domain/usecases/create-session_test.js
Portion de code plus utilisée permettant de créer une session en tant que PixMaster. Historiquement, ça permettait aux PixMasters, en utilisant l'outil POSTMAN, de créer une session directement via la route appropriée.
On retire le code et on ré-ajuste les tests.
FONC REVUE : tester la non-régression de création de session via pix certif
=> [TECH] Retrait du code lié à la création de session via POSTMAN (PF-1025)

mon-pix/app/components/certification-starter.js, mon-pix/app/templates/components/certification-starter.hbs
Récemment, on avait forcé la majuscule dans le champ code d'accès à la session, et on a oublié d'aussi forcer la majuscule lors de l'envoi du formulaire.
Mise en majuscule pour de bon
=> [BUGFIX] Le code d'accès à la session était forcé en majuscules seulement à l'affichage, mais pas lors de l'envoi du formulaire (PF-1032)

.circleci/config.yml, README.md, admin/package-lock.json, admin/package.json, api/lib/domain/models/Certification.js, api/lib/domain/models/Correction.js, api/package.json, certif/package-lock.json, certif/package.json, high-level-tests/e2e/cypress.json, high-level-tests/e2e/package-lock.json, high-level-tests/e2e/package.json, high-level-tests/load-testing/package.json, mon-pix/package-lock.json, mon-pix/package.json, orga/package-lock.json, orga/package.json, package.json
Les versions que l'on a actuellement sont bientôt obsolètes et portent éventuellement des problèmes.
On met à jour Node et NPM vers les versions LTS.
Reprise (avec un nom de branche correct) de https://github.com/1024pix/pix/pull/868
https://nodejs.org/api/deprecations.html#deprecations_dep0066_outgoingmessage_prototype_headers_outgoingmessage_prototype_headernames 
-> Sera traité dans une autre PR
On réactualise proprement https://github.com/1024pix/pix/pull/941 à la version LTS la plus récente
Les Dockerfiles de Cypress sont désormais buildés avec `npm@latest`. https://github.com/cypress-io/cypress-docker-images/blob/master/base/12.14.0/Dockerfile#L29
Il faudra donc soit se mettre à jour régulièrement soit faire évoluer notre `npm run preinstall` pour tolérer les versions patchées
=> [TECH] Mettre à jour node en v12.14.1 et npm en v6.13.4 (LTS) (PF-1009).

mon-pix/app/controllers/assessments/results.js, mon-pix/app/styles/pages/_assessment-results.scss, mon-pix/app/templates/assessments/results.hbs, mon-pix/tests/acceptance/course-ending-screen-test.js
Sans avoir créer de compte au préalable, il est possible de participer à une démo d'évaluation. Une fois cette évaluation terminée, sur la page de résultat, un bouton "Retour à l'accueil" est présent et renvoie vers la racine du site.
Il a été décidé de renommer ce bouton en "Poursuivre son expérience sur Pix" et de rediriger l'utilisateur sur la page d'inscription lorsqu'il cliquera sur ce dernier.
=> [FEATURE] Modification du lien de la page de résultat d'une démo d'évaluation (PF-1031)

api/lib/infrastructure/serializers/jsonapi/user-serializer.js, api/tests/acceptance/application/users/users-controller-get-current-user_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js, mon-pix/app/components/user-logged-menu.js, mon-pix/app/models/user.js, mon-pix/app/styles/components/_user-logged-menu.scss, mon-pix/app/templates/components/user-logged-menu.hbs, mon-pix/tests/integration/components/user-logged-menu-test.js, mon-pix/tests/unit/components/user-logged-menu-test.js
Suite à la possibilité pour un utilisateur de s'inscrire/se connecter via un identifiant et non plus une adresse email, il a été décidé d'afficher cet identifiant en lieu et place de l'adresse email dans le menu utilisateur.
On affichera toujours l'adresse email si celle-ci est renseignée, le nom d'utilisateur sinon.
=> [FEATURE] Afficher le nom d'utilisateur dans le menu utilisateur (PF-1022) 

certif/app/styles/globals/tables.scss, certif/app/styles/pages/authenticated/sessions.scss, certif/app/styles/pages/authenticated/sessions/details/certification-candidates-tab.scss, certif/app/templates/authenticated/sessions.hbs
(Pix certif > http://localhost:4203/sessions/3/finalisation)
Sous notre très cher ami IE, le design de la page de finalization de session était tout cassé.
AVANT
En fait, une div parent ("session-layout") était en flex, ce qui sous IE ne fonctionne pas vraiment comme prévu ... Etant donné que cette propriété de sert plus, il suffit de la retirer pour corriger le soucis. 
En regardant un peu sur internet les soucis de flex avec IE, il y a souvent des problèmes avec l'overflow et les `display: flex` nested... 
⬇️ APRES ⬇️ 
Une autre solution aurait été de mettre `max-width: 100%` ou `flex-basis: 100%;` ou encore `flex: 1;` (à ne pas confondre avec flex-grow) à l'élément enfant de "session-layout".
=> [BUGFIX] Design page finalisation session KO (pc-105)

.circleci/config.yml, scripts/release/publish.sh
Il y a deux branches qui ne sont plus utilisées aujourd'hui et qui sont inclues dans le process de mise en prod.
- La branche `maths` était utilisée au moment de [cette PR][pr] en janvier 2018. Mais aujourd'hui elle n'est plus utilisée, et le domaine `pix-dev.ovh` ne répond plus.
- La branche `preview` était utilisée pour prévisualiser les épreuves, mais ce n'est plus le cas aujourd'hui.
[pr]: https://github.com/betagouv/pix/pull/650
Supprimer les références à ces deux branches dans le script de mise en prod et dans CircleCI.
Se posera ensuite la question de la suppression de ces branches.
=> [TECH] Supprime les mises à jour des branches preview et maths

api/lib/config.js, high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json, high-level-tests/e2e/cypress/integration/demo.feature, high-level-tests/e2e/cypress/integration/page-title.feature, high-level-tests/e2e/cypress/integration/preview.feature, high-level-tests/e2e/cypress/integration/profile.feature, high-level-tests/e2e/cypress/support/step_definitions/assessment.js
Actuellement nous ne pouvons pas répondre à des questions parce que Airtable met trop de temps à répondre. 
Donc nous Cypress tombe en time Out 😭.
Faire un référentiel Airtable minimal et le lier à CircleCi.
Cette base pourra être partager en Read-Only avec des invités qui souhaitent jouer avec la base de données.
(Début de création de communauté sur Github 😎 ?!)
=> [TECH] utiliser un Airtable minimal pour nos tests e2e (Cypress)

mon-pix/app/components/certification-joiner.js, mon-pix/app/templates/components/certification-joiner.hbs
Lors du démarrage d'une session de certification, remplir la date de naissance du candidat ne change pas le focus vers l'input du mois de naissance puis vers celle de l'année de naissance.
Changer le focus au fur et a mesure que l'utilisateur tape.
=> [FEATURE] Placer le focus sur l'input suivante sur la page de démarrage d'une session de certification.

mon-pix/app/styles/components/_certification-result.scss
Un bouton s'affiche mal sous Safari en fin de certification.
Modifier son padding.
=> [BUGFIX] Corriger l'affichage d'un bouton de mon-pix sous Safari. (PF-1042)

mon-pix/app/components/levelup-notif.js, mon-pix/app/styles/components/_levelup-notif.scss, mon-pix/app/templates/components/levelup-notif.hbs
Actuellement, pour fermer la notification d'un succès, il faut cliquer sur la croix. Cette action n'est pas pratique à faire sur mobile.
- Bien séparer la croix du texte de la notification.
- Agrandir la zone d'action du bouton contenant la croix, pour la rendre plus facilement cliquable sur mobile
=>  [FEATURE] Homogénéiser le comportement de cloture des notifications de succès mobile et desktop (PF-899).

mon-pix/app/components/challenge-embed-simulator.js, mon-pix/app/styles/components/_challenge-embed-simulator.scss, mon-pix/app/templates/components/challenge-embed-simulator.hbs, mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Le design des embed n'est plus totalement cohérent avec le design global.
https://app-pr974.review.pix.fr/courses/reciMJOtivLZgO9gO
=> [FEATURE] Actualiser le design des embed (1/2) (PF-563).

api/lib/infrastructure/utils/error-manager.js, api/lib/interfaces/controllers/security-controller.js, api/tests/integration/infrastructure/utils/error-manager_test.js
Environ 60 % des lignes de logs de datadogs remontés par le filtre `Error` ne sont pas intéressantes et ne correspondent pas à des erreurs.
Elles apparaissent ici suite à un `logger.error()` qui soit n'est pas justifié, soit au mieux fait doublon avec les access logs.
Supprimer les `logger.error()` inutiles.
- InfrastructureErrors are already in access logs
- Domain errors are part of normal workflow
=> [TECH] Supprimer les logs non utiles

mon-pix/app/templates/campaigns/join-restricted-campaign.hbs, mon-pix/app/templates/components/routes/login-form.hbs, mon-pix/app/templates/components/routes/register-form.hbs
Actuellement sur plusieurs formulaires, il est possible de déclencher une requête lorsque l'on clicke plusieurs fois d'affilée (même avec l'affichage du loader) :
- pré-réconciliation (/identification) ;
- création d'utilisateur associé (/identification) ;
- connexion (/identification) ;
- réconciliation simple (/rejoindre).
- spécifier le type = `"button"` pour le bouton loader ;
- ajouter l'attribut `disabled`.
=> [BUGFIX] Ne pas permettre le click multiple sur les boutons de soumission de formulaire (PF-1043).

orga/app/controllers/login.js, orga/app/routes/join.js, orga/app/styles/components/login-form.scss, orga/app/styles/globals/colors.scss, orga/app/templates/components/routes/login-form.hbs, orga/app/templates/login.hbs, orga/mirage/config.js, orga/tests/acceptance/join-test.js
Lorsqu'un utilisateur clique sur un lien d'invitation à rejoindre Pix Orga et que cette invitation a déjà été acceptée, il est redirigé sur la page de connexion sans aucune information. 
Ajouter un message d'information sur la page de connexion dans le cas où l'invitation a déjà été acceptée afin de l'informer de la situation.
=> [FEATURE] Afficher un message d'information dans Pix Orga lorsqu'un utilisateur clique sur une invitation déjà acceptée (PO-276)

api/db/knex-database-connection.js, api/lib/infrastructure/bookshelf.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/application/saml-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, orga/app/models/campaign-report.js
Il y a longtemps, nous avons développé un petit patch custom qui caste le résultat de la méthode `Bookshelf.Model.count()` de `String` à `Number`. Par défaut, la méthode `#count()` renvoie une `String` plutôt qu'un entier. Cela est lié au fait que PostgreSQL peut renvoyer un BIG_INTEGER plutôt qu'un INTEGER.
Par ailleurs, nous espérions à l'époque que le correctif serait intégré dans les versions futures de Bookshelf. Ce qui n'a pas été le cas. 
Quoiqu'il en soit, nous avions à l'époque mis un test avec un message de warning, portant sur la version de Bookshelf utilisée. Finalement, au cours de ces dernières semaines, nous avons monté la version de Bookshelf en faisant fi de ce warning. Tout semble se passer correctement. Nous n'avons plus besoin de ce test.
1. Appliquer un meilleur patch …
=> [TECH] Amélioration de la gestion des types BIG_INTEGER dans PostgreSQL.

api/lib/domain/models/Competence.js, api/lib/domain/services/user-service.js, api/lib/domain/usecases/get-user-scorecards.js, api/lib/infrastructure/datasources/airtable/competence-datasource.js, api/lib/infrastructure/repositories/competence-repository.js, api/tests/integration/domain/services/user-service_test.js, api/tests/tooling/airtable-builder/factory/build-competence.js, api/tests/tooling/domain-builder/factory/build-competence-airtable-data-object.js, api/tests/tooling/domain-builder/factory/build-competence.js, api/tests/tooling/fixtures/infrastructure/competenceRawAirTableFixture.js, api/tests/unit/domain/usecases/get-user-scorecards_test.js, api/tests/unit/infrastructure/repositories/competence-repository_test.js, docs/Calcul-Airtable.md, docs/adr/0006-ajout-du-support-de-sendinblue-pour-le-mailing.md, docs/adr/0006-calcul-des-pix.md, docs/adr/0007-calcul-des-pix.md
Avec Pix+, Pix sera utilisé pour évaluer des acquis/compétences hors numérique.
Ces compétences ne doivent pas influencer le nombre de pix des utilisateurs.
Ces compétences ne doivent pas apparaître comme des cartes de score sur l'accueil de mon-pix.
Ces compétences ne sont pas certifiables.
Un attribut `Origin` est ajouté sur chaque compétence.
Cet attribut vaut `Pix` pour les compétences numériques.
Le champ `Pix Value` de chaque `Acquis` dans le référentiel est modifié pour valoir `0` si l'acquis n'est pas liée à une compétence numérique (identifiée par l'attribut `origine = "Pix"`)
Avec la modification du calcul de la colonne de `Pix Value` dans Airtable, cette PR ajoute une page de documentation sur les différents calculs actuels.
=> [FEATURE] Pix+ - Ajout et prise en compte de l'origine (Pix ou hors Pix) des compétences (PF-1047)

mon-pix/tests/test-helper.js
Les tests de monPix sur CircleCI se déclenchent 3 fois en parallèle, ce qui prend en moyenne 4 min 30 !!
C'est une régression, car avant, il y avait en effet 3 containers qui passaient les tests, mais ils se divisaient le travail !
Régression introduite par une mise à jour de ember-exam, avec un breaking change pas pris en compte lors de la montée de version (my bad :japanese_ogre: )
https://github.com/ember-cli/ember-exam/blob/master/CHANGELOG.md#v300--2019-04-08
=> [TECH] Les tests de MonPix sur CircleCI se déclenchaient 3 fois complètement en parallèle

mon-pix/app/components/challenge-item-qrocm.js
Sous IE 11, les utilisateurs ne pouvaient pas valider les épreuves QROCM.
Lors de la validation, un `document.querySelectorAll` récupérait la liste des input, et nous bouclions directement dessus avec un `forEach`.
Sous IE, il n'était pas possible de boucler directement sur le résultats du `querySelectorAll`
Passer par une boucle for.
En lien avec la PR du commit 1f3692d qui supprimait jQuery.
Sous IE, on ne peut pas faire de `forEach` sur le retour de `document.querySelectorAll`, ce n'est pas supporté : https://developer.mozilla.org/fr/docs/Web/API/NodeList
=> [BUGFIX] Probleme de validation des QROCM sous IE (PF-1055).

api/lib/infrastructure/caches/RedisClient.js
Cette PR est un fix de l'[erreur Sentry](https://sentry.io/organizations/pix/issues/1469577524/?project=1398749&query=is%3Aunresolved&statsPeriod=7d).
Nous suspectons un problème de "connexion non encore établie" au démarrage d'un conteneur d'API qui reçoit des reuqêtes dès qu'il se met à écouter.
Par le passé, nous avons désactivé l'option / feature "Offline Queue" de Redis qui générait beaucoup trop d'erreurs, du fait des trop nombreuses sollicitations de Redis (cf. PR #707). Depuis la PR #922 et l'amélioration de notre utilisation du cache et du fort diminution d'appels Redis, nous pouvons à nouveau activer ce mécanisme.
=> [BUGFIX] Correction d'une erreur Redis au démarrage de l'API. 

mon-pix/app/components/hexagon-score.js, mon-pix/app/styles/components/_hexagon-score.scss, mon-pix/app/templates/components/hexagon-score.hbs
- Nous indiquons que le nombre de Pix maximum est de 1024, alors qu'actuellement les utilisateurs peuvent en avoir 640 maximum
- Afficher une info bulle lorsque l'utilisateur passe sur l'hexagone contenant le score total.
- Ajout d'une div avec les informations
- Une croix seulement sur mobile pour fermer la bulle d'information
- Utilisation du `::before` pour l'effet de décoché
- Utilisation de deux classe `show` et `hide` modifié via `onmouseover` ou par clique sur la croix.
=> [FEATURE] Afficher une bulle d'information sur les Pix (PF-803).

mon-pix/app/components/qroc-proposal.js
Le champ de réponse d'une question est pré-rempli avec la réponse entrée à la question précédente.
Ce comportement intervient uniquement lorsque deux QROCs consécutives ont exactement les mêmes `proposals`.
Ceci est entrainé par le fait que l'attribut `proposals` étant le même, Ember ne re-compute pas la variable `blocks` dont on se sert pour configurer l'input.
Forcer un re-compute de la variable `blocks` à chaque affichage du composant.
Pour tester, utiliser le test statique : `/courses/recvHSPnmfGsmmfsg`.
=> [BUGFIX] Deux QROCs qui se suivent avec un même input conservent la réponse précédente

api/lib/domain/models/Scorecard.js, api/lib/domain/usecases/start-or-resume-competence-evaluation.js, api/lib/infrastructure/repositories/competence-repository.js, api/tests/acceptance/application/competence-evaluation-controller_test.js, api/tests/unit/domain/models/Scorecard_test.js, api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js, api/tests/unit/infrastructure/repositories/competence-repository_test.js
Cette PR fixe [l'erreur Sentry suivante](https://sentry.io/organizations/pix/issues/1459640624).
Certaines anciennes versions de Pix App requêtaient mal le service pour récupérer le détail du résultat d'une compétence : `/api/scorecards/:user_competence_id`. 
Ainsi, l'API subit des appels tels que : `/api/scorecards/1234_1234_recAbcd`, qui lèvent des erreurs 500.
Il nous paraît plus judicieux de renvoyer une 404.
Afin de pallier au problème, nous traitons l'erreur `NotFoundError` non plus au niveau de l'exploitant (ici, le service) mais plus bas / directement au niveau du repository, qui porte alors la responsabilité de convertir une erreur technique `infrastructure.datasources.airtable.AirtableResourceNotFound` en erreur du domaine `domain.NotFoundError`.
Au passage, cette PR remplace …
=> [BUGFIX] Requêter le détail d'une compétence avec un mauvais identifiant provoque désormais une erreur 404 plutôt que 500.

api/lib/domain/usecases/create-session.js, api/tests/unit/domain/usecases/create-session_test.js
La colonne status de la table Sessions a pour default value le status STARTED.
Malheureusement, bookshelfJS ne tient pas compte de ce paramétrage :( Du coup les sessions créées étaient initialisées au statut NULL.
Fixer le statut à la création.
=> [BUGFIX] L'initialisation du statut de la session à leur création ne fonctionnait pas (PC-112)

mon-pix/app/templates/components/hexagon-score.hbs
Le texte pour l'info bulle a été modifié
Le modifier
Quand on parle du nombre de pix, il faut mettre un p minuscule.
=> [BUGFIX] Changement de texte pour l'info-bulle des 1024 pix.

certif/app/templates/authenticated/sessions/finalize.hbs
Un texte de test a remplacé un sous-titre sur la page de finalisation de session :
Remettre le texte d'origine 😬
C'est très embarrassant 🤭
=> [BUGFIX] Corrige le sous-titre de la page de finalization (PC-113)

admin/app/adapters/learning-content-cache.js, admin/app/controllers/authenticated/certifications/sessions/info/list.js, admin/app/controllers/authenticated/tools.js, admin/app/router.js, admin/app/routes/authenticated/certifications/single/info.js, admin/app/routes/authenticated/tools.js, admin/app/styles/app.scss, admin/app/styles/authenticated.scss, admin/app/styles/authenticated/tools.scss, admin/app/styles/misc/button.scss, admin/app/styles/misc/callout.scss, admin/app/styles/misc/palette.scss, admin/app/templates/authenticated/organizations/list.hbs, admin/app/templates/authenticated/tools.hbs, admin/app/templates/components/menu-bar.hbs, admin/public/images/loader-white.svg, admin/tests/acceptance/tools-page-test.js, admin/tests/integration/components/menu-bar-test.js, admin/tests/unit/adapters/learning-content-cache-test.js, admin/tests/unit/controllers/authenticated/tools-test.js, admin/tests/unit/routes/authenticated/tools-test.js
Le (cache du) référentiel de données pédagogique est mis à jour automatiquement quotidiennement (vers 6h00).
Parfois, il peut être utile ou nécessaire de forcer une mise à jour.
La procédure actuelle est trop manuelle, donc trop compliquée, trop longue, trop pas MD10.
L'objet de cette PR est d'ajouter, dans Pix Admin, un **bouton de rafraîchissement du cache**, dans une page dédiée à l'outillage _back-office_.
Le endpoint de rechargement du cache est de type _mutation_ (c'est une action avec effets de bord sur le système et non pas une ressource) et n'est pas très Ember Data / JSONAPI _friendly_.
J'ai tenté dans un premier temps de passer sans Amber Data, juste avec Ember Fetch, mais je me suis pris : 
- 1 erreur CORS pour le verbe `PATCH`
- de devoir gérer les headers de requêtes …
=> [FEATURE] Ajout d'un bouton pour rafraîchir le cache de données pédagogiques dans Pix Admin (PA-139).

mon-pix/app/templates/components/challenge-embed-simulator.hbs
Il était possible de mettre le bouton de Réinitialisation en surbrillance en pointant la ligne.
Mettre le bouton de Réinitialisation en surbrillance en pointant le texte.
=> [BSR] Ajuster le style du bouton réinitialiser des embed (PF-1061).

api/lib/domain/usecases/create-and-associate-user-to-student.js, api/lib/domain/usecases/create-campaign.js, api/lib/domain/usecases/create-organization.js, api/lib/domain/usecases/create-user.js, api/lib/domain/validators/campaign-validator.js, api/lib/domain/validators/organization-creation-validator.js, api/lib/domain/validators/session-validator.js, api/lib/domain/validators/user-validator.js, api/tests/unit/domain/usecases/create-and-associate-user-to-student_test.js, api/tests/unit/domain/usecases/create-campaign_test.js, api/tests/unit/domain/usecases/create-organization_test.js, api/tests/unit/domain/usecases/create-user_test.js, api/tests/unit/domain/validations/campaign-validator_test.js, api/tests/unit/domain/validations/organization-creation-validator_test.js, api/tests/unit/domain/validations/session-validator_test.js, api/tests/unit/domain/validations/user-validator_test.js
Les validateurs ont des comportements hétérogènes + asynchrones dans certains cas (cas succès ou cas erreur, c'est pas constant). Du coup, une erreur qui devrait normalement être traitée et convertie correctement se retrouve perdue et convertie en erreur 500.
Exemple d'erreur occasionné :
https://sentry.io/organizations/pix/issues/1383959051/?project=1398749&query=is%3Aunresolved&statsPeriod=7d
On remet ça à plat, maintenant les validateurs sont synchrones.
Revoir fonctionnellement : Création d'orga, création de session, création d'utilisateur système mail + username. Il faut tester la valid', donc malmener les champs, les inputs, les données
=> Rendre les validateurs synchrones et s'assurer qu'ils jettent correctement leurs erreurs converties 4xx (PC-110)

scripts/release/publish.sh
Le script de MEP échoue sur la commande de création de release sentry car des organisations ont été supprimées sur sentry. Ça ne bloque pas la MEP, voici l'erreur affichée :
```
error: API request failed
caused by: sentry reported an error: request failure (http status: 400)
Object({"projects": Array([String("Invalid project slugs")])})
```
Ne pas les inclure dans la création de la release.
=> [BUGFIX] Mise à jour de la commande de création de release sentry-cli.

mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_certification-joiner.scss, mon-pix/app/styles/components/_form-textfield.scss, mon-pix/app/styles/components/_navbar-burger-menu.scss, mon-pix/app/styles/components/_navbar-desktop-header.scss, mon-pix/app/styles/components/_panel.scss, mon-pix/app/styles/components/_user-logged-menu.scss, mon-pix/app/styles/globals/_colors.scss
Sur Pix APP, la double mire de connexion apparaît comme suit : 
Ajouter la classe `panels` qui manquait à Pix APP pour retrouver le design suivant attendu : 
L'absence de la classe panels dans Pix APP a probablement créé une dépendance à Bootstrap qui vient d'être supprimé de l'application, d'où la régression.
Quel test pourrait-on ajouter pour couvrir ce cas d'erreur ? 
Un test de classe ne nous aurait pas averti du problème et un test sur la couleur aurait créé une dépendance au css. 
Les tests automatisés de non-régression visuelle (dans une approche différente de Cypress ou avec Cypress) sont peut-être intéressant.
Il faut être déconnecté puis saisir l'URL suivante :
https://app-pr1027.review.pix.fr/campagnes/AZERTY456/identification
=> [BUGFIX] Corriger le design de la double mire de connexion (PF-1069).

package-lock.json, package.json
Il n'est plus possible d'exécuter `npm ci` à la racine.
Suppression de la dépendance `sib-api-v3-sdk` qui n'a pas lieu d'être présente dans le package.json de la racine.
=> [TECH] Suppression de la dépendance sib-api-v3-sdk de la racine.

mon-pix/app/adapters/application.js, mon-pix/app/routes/application.js, mon-pix/app/routes/error.js, mon-pix/app/routes/login.js, mon-pix/package-lock.json, mon-pix/package.json, mon-pix/tests/unit/adapters/application-test.js
Pas à jour
À jour grâce aux recommandations `ember-simple-auth` suivantes : 
- https://github.com/simplabs/ember-simple-auth#1994
- https://github.com/simplabs/ember-simple-auth/blob/master/guides/managing-current-user.md#loading-the-current-user
```bash
200) [Chrome 79.0] Acceptance | Error page should redirect to route /connexion when the api returned a 401 error
expected '/mes-certifications' to equal '/connexion'
AssertionError: expected '/mes-certifications' to equal '/connexion'
at Context._callee$ (http://localhost:7357/assets/tests.js:3697:68)
at tryCatch (http://localhost:7357/assets/vendor.js:11551:40)
at Generator.invoke [as _invoke] (http://localhost:7357/assets/vendor.js:11777:22)
at Generator.prototype.<computed> [as next] (http://localhost:7357/assets/vendor.js:11603:21)
at …
```
=> [TECH] Mise à jour de PixApp en Ember 3.13 (PF-1053).

mon-pix/app/models/competence-evaluation.js, mon-pix/tests/acceptance/competences-details-test.js
Lorsqu'on arrivait sur la page de résultats d'une compétence, et qu'on pouvait remettre à zéro, le bouton remise à zéro ne fonctionnait pas.
- Ajout de `{ async : false }` dans le `BelongsTo` de la `competenceEvaluation` vers sa `scorecard`.
- Dans ce bug, le `scorecard.save()` ne fonctionnait pas, car le scorecard était un proxy et ne pouvait pas appeler sa méthode save.
- Pour éviter cela, l'ajout du async à false
Doc : `async: A boolean value used to explicitly declare this to be an async relationship. The default is true.`
=> [BUGFIX] Pouvoir remettre à zéro une compétence après l'avoir terminé (PF-872).

mon-pix/app/controllers/campaigns/join-restricted-campaign.js, mon-pix/app/styles/pages/_join-restricted-campaign.scss, mon-pix/app/templates/campaigns/join-restricted-campaign.hbs, mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Le message à la fin du formulaire n'est plus approprié car tout le monde ne se connecte pas via un ENT.
Le message d'erreur en cas d'informations de reconciliation est trop générique.
Suppression du message à la fin du formulaire.
Ajout d'un message d'erreur spécifique en cas d'informations déjà utilisées pour la réconciliation.
=> [FEATURE] Remplace le message d'erreur pour les comptes déjà créer (PF-989).

mon-pix/app/components/qrocm-proposal.js, mon-pix/app/templates/components/qrocm-proposal.hbs, mon-pix/app/utils/proposals-as-blocks.js, mon-pix/tests/integration/components/qrocm-proposal-test.js, mon-pix/tests/unit/utils/proposals-as-blocks-test.js
Les champs des QROCm ne sont pas accessibles et par conséquent, ne peuvent pas être lus par des screen-readers utilisés par les aveugles ou mal-voyants.
Attribuer aux inputs/textarea des QROCm un `label` ou `aria-label`.
Il existe plusieurs formats de QROCm (je ne pense pas avoir tout listé, donc il y a des potentiels bugs d'affichage pour les autres types):
- des textes à trous (challengeId: [recDdegyiMfqln0dr](https://app-pr1001.review.pix.fr/assessments/102067/challenges/recDdegyiMfqln0dr))
- des listes d'inputs (challengeId: [rec5uBBZC9FyAfIs7](https://app-pr1001.review.pix.fr/assessments/102067/challenges/rec5uBBZC9FyAfIs7))
- des listes de texte + input (challengeId: [recj0g7zZF5LTxij5](https://app-pr1001.review.pix.fr/assessments/102067/challenges/recj0g7zZF5LTxij5))
- des listes …
=> [A11Y] Ajouter des labels aux QROCm (PF-957)

mon-pix/app/styles/components/_challenge-statement.scss, mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/templates/components/challenge-statement.hbs
Sur les épreuves qui proposent de télécharger un fichier : 
- Les radio button et l'icone info était décalé
- Le tooltip de l'info n'était pas visible (passait sous la barre de progression) si le texte était court
- Supprimer le overflow:hidden
- Recaler le radio button et l'icone
Pour tester, trouver une épreuve avec un téléchargement et supprimer dans le DOM le texte de l'épreuve.
=> [BUGFIX] Correction de style sur les épreuves avec téléchargement (PF-1048).

admin/app/components/organization-information-section.js, admin/app/models/organization.js, admin/app/templates/components/organization-information-section.hbs, admin/tests/integration/components/organization-information-section-test.js
Bien qu'il soit possible de gérer les organisations SCO depuis Pix Admin, il n'existe pas de moyen de savoir si une organisation SCO gère ou non des élèves.  
Ajout de l'information de la gestion d'élèves pour les organisations SCO dans la page de détail d'une organisation.
=> [FEATURE] Afficher si l'organisation SCO gère des élèves (PA-140)

api/lib/infrastructure/repositories/organization-invitation-repository.js, api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js
Lors de la création d'une invitation à rejoindre une organisation, une vérification est effectuée au préalable afin de vérifier qu'il n'existe pas déjà une demande existante pour l'adresse email que l'on souhaite inviter. Cette vérification de l'adresse email est sensible à la casse et il arrive parfois que les utilisateurs créent des demandes d'invitations avec des emails contenant des majuscules pour des emails déjà invités.  
Rendre cette vérification de l'email insensible à la casse.
=> [BUGFIX] La vérification de l'existence d'une invitation n'est plus sensible à la casse pour l'email (PO-329)

api/db/migrations/20200129155649_add_column_finalizedAt_to_sessions.js, api/db/seeds/data/sessions-builder.js, api/lib/domain/usecases/finalize-session.js, api/lib/infrastructure/repositories/session-repository.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/tooling/database-builder/factory/build-session.js, api/tests/tooling/domain-builder/factory/build-session.js, api/tests/unit/domain/usecases/create-session_test.js, api/tests/unit/domain/usecases/finalize-session_test.js
Le pôle Certif, afin de traiter les sessions dans un ordre juste, souhaite pouvoir obtenir un ordre de finalisation de session, par le biais dans un premier temps de metabase.
Ajouter une date de finalisation de session à la table session lors de la finalisation de celle-ci dans PixCertif.
=> [FEATURE] Ajouter une date de finalisation lorsqu'un utilisateur PixCertif finalise une session (PC-111)

api/db/knex-database-connection.js, api/tests/tooling/database-builder/database-builder.js
Il arrive de plus en plus fréquemment que le job CircleCI `api_build_and_test` échoue de manière aléatoire.
La difficulté de l'analyse est que ce n'est pas toujours le même test qui échoue, qu'il n'échoue pas systématiquement, et qu'il n'est jamais reproduit en local.
Par chance, j'ai rencontré le problème en local, un jour où mon ordinateur était en fonctionnement dégradé (car batterie faible).
J'ai donc supposé que l'erreur est bien due à un test qui prend trop de temps et dépasse le timeout par défaut de `mocha`, qui est de 2 secondes.
Fort de cette supposition, je me suis lancé dans une investigation plus poussée en commençant par chercher à reproduire le test en échec de manière systématique.
Pour cela, j'ai lancé les tests en spécifiant un timeout de plus en plus petit jusqu'à faire …
=> [TECH] Résolution du test "flaky" (qui échoue aléatoirement) sur la CI - api

api/lib/infrastructure/repositories/user-repository.js, api/tests/integration/infrastructure/repositories/user-repository_test.js
1 - sur la double mire, faire la pré-réconciliation (First Last 10/10/2010)
2 - Choisir une inscription par email
3 - Remplir l'email avec un email déjà en base mais en majuscule (Userpix1@example.net)
2 - Remplir le champ mot de passe avec un mot de passe valide
3 - Valider
Constater qu'il y a une erreur 500. Côté utilisateur il ne se passe rien, donc l'utilisateur réessaie, donc on a des 500 en pagaille.
Checker l'email non sensible à la casse.
=> [BUGFIX] Lors de l'inscription, vérification de la non présence de l'email en base avec insensibilité à la casse (PF-1077).

certif/app/components/session-finalization-formbuilder-link-step.hbs, certif/app/components/session-finalization-reports-informations-step.hbs, certif/app/controllers/authenticated/sessions/finalize.js, certif/app/styles/components/finalize.scss, certif/app/styles/components/session-finalization-examiner-global-comment-step.scss, certif/app/templates/authenticated/sessions/finalize.hbs, certif/tests/acceptance/session-finalization-test.js, certif/tests/integration/components/session-finalization-formbuilder-link-step-test.js, certif/tests/unit/controllers/authenticated/sessions/finalize-test.js
Sur la page de finalisation de session, des labels ne sont pas à jour.
Le label _commentaire_ passe à la ligne différemment selon le nombre de caractère en commentaire.
Mettre à jour les labels.
Ne pas aligner le label _commentaire_ avec le champs du nombre de caractère insérés.
On a 2 px de décalage au niveaux des commentaires 😱
=> [FEATURE] Mettre à jour les labels pour la finalisation de session (PC-114)

api/db/seeds/seed.js, api/lib/domain/models/CertificationCenter.js, api/lib/infrastructure/repositories/certification-center-repository.js, api/scripts/create-certification-center-memberships-from-organization-admins.js, api/tests/integration/infrastructure/repositories/certification-center-repository_test.js, api/tests/integration/scripts/create-certification-center-memberships-from-organization-admins_test.js, api/tests/tooling/database-builder/factory/build-certification-center.js, api/tests/unit/scripts/create-certification-center-memberships-from-organization-admins_test.js
Via un script, à partir d'un fichier csv contenant une liste d'ExternalIds, rattacher les administrateurs des organisations aux centres de certifications correspondants.
1. Identifier les memberships des organisations (identifié avec leur externalId) qui sont administrateurs.
2. Identifier les centres de certifications (identifiés par leur externalId).
3. Effectuer les correspondances et créer les certificationCenterMemberships en base de données.
=> [FEATURE] Script pour rattacher les administrateurs des organisations aux centres de certification correspondants (PF-952).

mon-pix/mirage/routes/get-campaign-participation.js, mon-pix/mirage/serializers/campaign-participation-result.js, mon-pix/mirage/serializers/campaign-participation.js, mon-pix/mirage/serializers/certification-course.js, mon-pix/mirage/serializers/competence-evaluation.js, mon-pix/mirage/serializers/competence.js, mon-pix/mirage/serializers/scorecard.js, mon-pix/mirage/serializers/user.js
Sur Pix App, il y a plusieurs façons de charger nos données mirage: en amont via des fixtures ou pendant les tests avec des factories. Ces données sont ensuite serialisés pour les convertir en JSON API.
Parfois même, on n'utilise ni fixture no factory: l'objet JSON API attendu est directement construit à la main.
Cela rend nos tests compliqués à modifier et debugger.
Modifier notre manière d'utiliser mirage, pour coller davantage à la documentation ember-cli-mirage et uniformiser par rapport aux autres applis Pix.
Cette PR concerne le **refacto des serializers existants**.
D'autres PR suivront... ;)
=> [TECH] Refacto serializers mirage sur mon-pix (PF-1038).

certif/app/controllers/authenticated/sessions/finalize.js, certif/app/templates/authenticated/sessions/finalize.hbs, certif/tests/acceptance/session-finalization-test.js, certif/tests/unit/controllers/authenticated/sessions/finalize-test.js
Le message contextuel de la popin *finalize* affiche `true` au lieu de `1` lorsque la liste ne contient qu'un seul élément
Il faut forcer le cast du boolean en number `Number(true)`
mettre le “s” du mot “candidats” entre () => candidat(s)
ne PAS afficher la phrase qui indique le nombre de FDT non cochées si ce nombre est = 0
=> [BUGFIX] Fix sumBy when list contain 1 value (pc-117)

api/package-lock.json, api/package.json
`@hapi/hapi` (`18.4.0`) n'est pas à jour
Passer le package `@hapi/hapi` en `18.4.1`
=> [TECH] Mise à jour de hapi. 

admin/app/models/session.js, admin/tests/unit/models/session-test.js
Sur Pix Admin, dans la page de détail d'une session pour la ligne "Nombre d'écrans de fin de test non renseigné", lorsqu'on a qu'une seule certification il est affiché "true" ou "false" (au lieu de 0 ou 1).
En fait le sumBy de lodash ne cast pas lorsqu'il n'y a qu'un élément dans la collection. 
On cast donc nous même le booleen en nombre. 
=> [EXPEDIT] Bug d'affichage du "Nombre d'écran de FDT non renseignés" quand une seule certif pour une session

api/lib/domain/models/Campaign.js, api/lib/infrastructure/data/campaign.js, api/lib/infrastructure/repositories/campaign-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/tooling/domain-builder/factory/build-campaign.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, high-level-tests/e2e/cypress/support/step_definitions/campaign.js, orga/app/models/campaign.js, orga/app/models/user.js, orga/app/styles/globals/tables.scss, orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs, orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
Les utilisateurs de PIX Orga ont besoin de savoir qui est le créateur d'une campagne.
Nous avons ajouté une colonne "Créé par" dans la liste des campagnes.
On est pas satisfait du beforeEach de la suite de "save" qui utilise la fonction `buildCampaign` du domain pour créer les données à insérer en base.
Nous sommes preneur de vos suggestions.
=> [FEATURE] Ajoute la colonne "Créé par" dans la liste des campagnes (PO-308).

admin/app/models/session.js, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/tests/integration/components/routes/authenticated/certifications/sessions/certifications-session-info-test.js, api/lib/domain/models/Session.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/unit/domain/models/Session_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Le pôle certif* s'occupent de "traiter" les sessions lorsque celles-ci sont finalisées. C'est à dire:
- que les sessions se sont déroulées (passées dans le temps),
- et que le CDC ont noté les signalements et ont validé avoir vu, ou non, les fin de tests sur les écrans des candidats (l'action "finaliser la session" est faite sur l'appli certif). 
*pôle certif = Anne-C, Pablo, Josselin de chez Pix
*CDC = centre de certification
Pour savoir quelles sont les sessions dont le pôle certif doit s'occuper, ils aimeraient avoir accès à plusieurs informations, dont la date de finalisation de la session.
Afficher la date de finalisation de la session dans Pix admin sur la page de détail de la session choisie.
La date de finalisation ne s'affiche que pour les sessions au status "finalisé".
=> [FEATURE] Ajout date finalisation sur la page de détail d'une session (PA-145)

api/lib/infrastructure/airtable.js, api/tests/tooling/airtable-builder/airtable-mock-route.js
Depuis pix editor, lors de la MAJ du cache d'un challenge donnée, l'API Airtable prend une erreur 422.
Après investigation, la requête est mal formatée : la valeur de l'id doit être mis entre quotes (") sinon Airtable le considère comme un nom de champ.
Mettre la valeur de l'id entre quotes lors de l'appel.
A passer rapidement, car les preview de challenges de pix editor ne fonctionne pas.
=> BUGFIX: Réparation de la mise à jour du cache Airtable d'un élément unique

api/lib/infrastructure/repositories/area-repository.js, api/lib/infrastructure/repositories/competence-tree-repository.js, api/tests/acceptance/application/certifications/certification-controller_test.js, api/tests/unit/infrastructure/repositories/area-repository_test.js, api/tests/unit/infrastructure/repositories/competence-tree-repository_test.js
Quand des compétences / domaines non-Pix (Pix+) existent dans le référentiel, elles ne sont pas certifiables.
Actuellement, le problème est que ces compétences sont affichées dans les résultats de certification.
Filtrer les compétences / domaines affichées dans les résultats de certification qui ne sont pas Pix.
En faisant la modification, les tests de `certification-controller` échouaient.
En essayant de comprendre pourquoi, j'ai constaté que les tests n'utilisaient pas les `builders` rendant la lecture et la compréhension des tests.
J'ai donc commencé par un refacto de `certification-controller_test`.
=> [BUGFIX] Les résultat Pix+ ne doivent pas apparaître dans les résultats de certification (PF-1098)

orga/package-lock.json
Pix Orga dépend indirectement de `fsevents` mais son `package-lock.json` verrouille une version qui ne supporte pas Node 12. La conséquence est un message d'erreur à chaque `npm install` ou `npm ci` (sur Mac), qui n'empêche pas le fonctionnement parce que cette dépendance est optionnelle, mais c'est quand même contrariant.
On met à jour la version de `fsevents` référencée par `package-lock.json` afin d'utiliser une version compatible Node 12.
Comme `fsevents` n'est pas une dépendance directe de `orga`, on ne peut pas se contenter d'un simple `npm update`. Nous avons plutôt été supprimer le bloc correspondant à `fsevents` dans `package-lock.json` puis relancé `npm install` qui l'a réintroduit mais avec une version à jour.
=> [TECH] Pix Orga: Mise à jour de `fsevents` pour supporter Node 12

high-level-tests/e2e/README.md, high-level-tests/e2e/cypress/integration/campaign-management.feature, high-level-tests/e2e/cypress/integration/campaign.feature, high-level-tests/e2e/cypress/integration/demo.feature, high-level-tests/e2e/cypress/integration/login-logout.feature, high-level-tests/e2e/cypress/integration/page-title.feature, high-level-tests/e2e/cypress/integration/preview.feature, high-level-tests/e2e/cypress/integration/profile.feature, high-level-tests/e2e/cypress/integration/signup.feature
Les tests Cypress sont écrits en français mais les mots-clés anglais (`Given`, `When`, `Then`…) sont utilisés ce qui est désagréable à la lecture.
On utilise la possibilité offerte par [cypress-cucumber-preprocessor](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor) d'utiliser des mots-clés dans une autre langue que l'anglais.
Cette PR ajoute aussi dans le `README.md` la commande à lancer pour connaître les mots-clés disponibles.
Cette commande a été utilisée pour automatiser le processus :
```
gsed -i -e $'s/Feature:/#language: fr\\\nFonctionnalité:/' \
-e 's/Background:/Contexte:/' \
-e 's/Scenario:/Scénario:/' \
-e 's/Given /Étant donné que /' \
-e 's/And /Et /' \
-e 's/When /Lorsque /' \
-e 's/Then /Alors /' \$
./cypress/integration/*.feature
```
Noter que le style …
=> [TECH] Utilisation de mots-clés français dans les tests Cypress

api/lib/application/cache/index.js, api/tests/acceptance/application/cache-controller_test.js, api/tests/unit/application/cache/index_test.js
Comme vu par @jonathanperret dans la PR #1074, l'API ne fait pas de contrôle sur le format des clés de cache et utilise le paramètre d'entrée directement dans l'appel de l'API Airtable.
Il existe donc une faille potentielle par laquelle une personne pourrait injecter une formule Airtable comme identifiant, entraînant un comportement non maitrisé.
C'est le même type qu'une attaque par injection SQL mais avec une formule Airtable. (https://fr.wikipedia.org/wiki/Injection_SQL)
Valider le format de la clé du cache en entrée de l'API.
Pas de validation fonctionnelle sur la review app.
Il faudra s'assurer en intégration que Pix editor arrive toujours à mettre à jour le cache pour une épreuve donnée.
=> [Tech] Se prémunir d'une attaque de type "Airtable formula injection"

api/lib/application/campaigns/campaign-controller.js, api/lib/domain/usecases/get-campaign.js, api/tests/integration/application/campaigns/index_test.js, api/tests/unit/domain/usecases/get-campaign_test.js, orga/app/routes/authenticated/campaigns/details.js, orga/tests/unit/routes/authenticated/campaigns/details-test.js
On a des erreurs 500 qui sont générées parce que les utilisateurs demandent côté front la page `/campagnes/liste`. Cette page n'existe plus, mais il se trouve que ça match le template `/campagnes/id`, et donc le front va chercher la campagne d'id `liste`. En arrivant côté back, on fait un `parseInt(id)`, on se retrouve donc avec un `NaN`. Ce qui échoue en base en jetant une 500.
- Côté back, empêcher d'aller plus loin avec un check côté domain sur le type de l'ID. Le `GET /campaign/liste` ressort donc avec une 404 Not Found.
- Côté front, catcher l'erreur après le findRecord, et rediriger vers la page `Not Found`.
Il se trouve qu'actuellement la page `Not Found` redirige vers la page par défaut. Niveau UX, ce n'est pas forcément le meilleur comportement. Néanmoins, ce n'est pas à cette PR …
=> [BUGFIX] Ne pas générer d'erreurs 500 lorsque la route /campaign/id est appelée avec un id non valide (PO-251).

mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_certification-not-certifiable.scss, mon-pix/app/styles/components/_rounded-panel.scss, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/styles/globals/_titles.scss, mon-pix/app/styles/pages/_fill-in-campaign-code.scss, mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs, mon-pix/app/templates/components/certification-not-certifiable.hbs, mon-pix/app/templates/components/profile-content.hbs, mon-pix/app/templates/components/scorecard-details.hbs
Les titres sur les pages /profil, /campagnes et /certification ont des titres de style différent.
edit: le titre de la page `competences.details` est aussi concerné
Cette PR uniformise les styles de ces titres.
Vu avec @QuentinChapelain-ui : les titres sont en `<h3>` car ce ne sont pas les gros titres / textes que l'on s'attendrait à voir en `<h1>`
=> [STYLE] Align pages title styles (PF-1020)

.circleci/config.yml, docker-compose.yml
L'image docker a été mise à jour rendant les scripts de migrations inopérant: 
https://github.com/docker-library/postgres/issues/681
Il faut rajouter une variable dans le docker-compose.yml
=> [TECH] Ajout de la variable d'environnement POSTGRES_HOST_AUTH_METHOD au docker-compose.yml pour réparer postgres (PF-1107).

mon-pix/app/styles/pages/_skill-review.scss, mon-pix/app/templates/campaigns/skill-review.hbs
Suite à la PR #1082, les titres de certaines pages ont été alignés sur leur style.
Il manque la prise en compte de la page de résultats d'une campagne.
Aligner le titre des résultats d'une campagne.
=> [BUGFIX] Fix style du titre de la page résultats d'une campagne

mon-pix/app/components/certification-joiner.js, mon-pix/app/modifiers/autofocus.js, mon-pix/app/styles/components/_certification-starter.scss, mon-pix/app/templates/components/certification-joiner.hbs, mon-pix/app/templates/components/certification-starter.hbs, mon-pix/package-lock.json, mon-pix/package.json, mon-pix/tests/acceptance/certification-course-test.js
Le premier écran du tunnel de certification dans MonPix possède un autofocus sur le premier champ du formulaire. En revanche, le deuxième écran (celui du code d'accès), n'en a pas, et c'est bien dommage !
Le truc c'est que la propriété autofocus des input n'est prise en compte que lors du premier rendu de toute la fenêtre (à un refresh par exemple). Dans le cadre du tunnel de certification ( - et plus généralement dans toutes nos applis, puisque SPA), on rend l'ensemble qu'une seule fois, puis on rend individuellement les components en fonction du besoin. Donc, en cas de remplacement d'un component par un autre par exemple, la propriété n'est pas prise en compte.
En suivant les conseils de la doc ember, on ajoute donc un _modifier_ pour pouvoir facilement définir l'autofocus sur l'élément …
=> [FEATURE] Autofocus les premiers champs de formulaire des deux écrans du tunnel de certification dans MonPix (PF-1117)

mon-pix/app/styles/components/_competence-card-desktop.scss, mon-pix/app/templates/components/competence-card-desktop.hbs
Pour accéder aux détails d'une compétence, il fallait cliquer exactement sur le cercle de la carte compétence: ce qui n'est pas intuitif car toute la carte réagit dès que on la survole.
Agrandir la zone de click pour pouvoir cliquer sur toute la zone avant le bouton "commencer" ou "reprendre".
=> [FEATURE] Agrandir la zone de click de la carte compétence (PF-1011)

admin/app/models/certification.js
Un petit cafouillage lors du merge de la https://github.com/1024pix/pix/pull/1057. 
Les écrans de fin de test n'étaient plus pris en compte lors de l'analyse du PV de session dans PixAdmin
On en tient compte !
=> [EXPEDITE][BUGFIX] Les écrans de fin de test issus de l'analyse du PV de session dans PixAdmin ne sont pas pris en compte (PA-158)

admin/app/services/session-info-service.js, admin/tests/unit/services/session-info-service-test.js
Des plaintes ont été remontées depuis les prescripteurs vers le pôle certif.
Comme on le sait, à l'issue d'un arbitrage d'une session de certification, le pôle certif génère, via PixAdmin, un fichier csv à destination du ou des prescripteurs de la session de certification qui contient les résultats.
Les résultats sont présentés comme suit : dans le fichier, nous avons une ligne par certification passée. Au sein d'une ligne, des colonnes contenant diverses informations sur la certif (identité du candidat par ex, etc), mais aussi le détail du niveau certifié par compétence du candidat.
En l'état, que la compétence soit échouée ou carrément pas du tout évaluée, elle est marquée avec un tiret : -
Or, les prescripteurs souhaiteraient avoir la distinction entre une compétence non-évaluée et une …
=> [FEATURE] Distinguer les compétences non évaluées de celles échouées dans le fichier de résultats pour prescripteur (PA-160)

api/lib/domain/models/CertificationReport.js, api/lib/infrastructure/repositories/certification-report-repository.js, api/lib/infrastructure/serializers/jsonapi/certification-report-serializer.js, api/tests/acceptance/application/session/session-controller-get-certification-reports_test.js, api/tests/integration/infrastructure/repositories/certification-report-repository_test.js, api/tests/tooling/database-builder/factory/build-certification-report.js, api/tests/tooling/domain-builder/factory/build-certification-report.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-report-serializer_test.js, certif/app/adapters/session.js, certif/app/components/session-finalization-examiner-global-comment-step.hbs, certif/app/controllers/authenticated/sessions/finalize.js, certif/app/models/session.js, certif/tests/acceptance/session-finalization-test.js, certif/tests/unit/adapters/session-test.js, certif/tests/unit/controllers/authenticated/sessions/details-test.js, certif/tests/unit/controllers/authenticated/sessions/finalize-test.js, certif/tests/unit/controllers/authenticated/sessions/list-test.js, certif/tests/unit/controllers/authenticated/sessions/new-test.js
Comment reproduire le bug :
- Accéder à la page de finalisation de session avec au moins une certification
- Cliquer dans le champ signalement d'une certification (sans rien écrire dedans)
- Finaliser la session -> échec
Dans le cas reproduit au dessus, le payload envoyé à l'API contient, pour l'attribut `examinerComment` de la certification pour laquelle on a cliqué dans le champ, la valeur '' (chaîne vide). Or, la validation JOI des données de la certification côté API interdit une chaîne vide pour cet attribut (mais tolère `null` et `undefined`)
- Front et Back, convertir les chaînes vides en `null` (à l'envoi et à la désérialization)
Cette PR contient également :
- Une réécriture de l'action de finalisation côté front qui soit plus _Ember-like_
- Ajout de tests unitaires de …
=> [EXPEDITE][BUGFIX] Finalisation de session en échec dans un cas particulier (PC-129)

api/lib/infrastructure/utils/query-params-utils.js, api/tests/unit/infrastructure/utils/query-params-utils_test.js
Quand l'utilisateur saisie la page 0 il y a une erreur 500 et l'utilisateur a une page blanche
Parser en INT les paramètres de la page
Il y a une méthode ensureIntWithDefault qui applique la pagination par défaut quand la pagination n'est pas valide.  Elle se base sur un !number et en lui passant "0" il ne détecte pas que c'est une mauvaise pagination
https://github.com/bookshelf/bookshelf/blob/e7d81f5401ca2ec0695d5817cdf9f3d709f6b353/lib/helpers.js#L10
=> [BUGFIX] Appliquer la pagination par défaut lorsque la page 0 est demandée (PO-342).

api/lib/domain/models/Assessment.js, api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/infrastructure/repositories/answer-repository.js, api/tests/acceptance/application/answers/answer-controller-save_test.js, api/tests/integration/infrastructure/repositories/answer-repository_test.js, api/tests/test-helper.js, api/tests/unit/domain/models/Assessment_test.js, api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Quand la base de données a des difficultés, on se retrouvait dans le problème suivant : 
- Un utilisateur répond à une question
- Une entrée est enregistré dans la table Answers, mais les KnowledgeElements ne sont pas enregistrés
- Quand on cherche la prochaine question, l'algo ne considère donc pas les acquis précédemment vue, et repose le même acquis, et le même challenge
- L'utilisateur revoit la même épreuve marqué "déjà répondu" et donc on ne réenregistre rien
- Ça boucle : donc l'utilisateur est bloqué sur une épreuve déjà répondu
Pour cela, on utilise les transactions de Bookshelf. Pour faciliter cela, il y a eu plusieurs refacto du usecase pour sauvegarder l'Answer et les KnowledgeElements au même endroit.
Une méthode a été ajouté pour sauvegarder les deux dans le repository de …
=> [BUGFIX] Eviter de sauvegarder les réponses sans leurs KE (PF-1116).

admin/app/adapters/session.js, admin/app/controllers/authenticated/certifications/sessions/info/index.js, admin/app/models/session.js, admin/app/styles/authenticated/certifications/sessions/info/index.scss, admin/app/templates/authenticated/certifications/sessions/info/index.hbs, admin/mirage/config.js, admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js, admin/tests/unit/adapters/session-test.js, api/db/migrations/20200218114201_add_sendToPrescriber_column_in_session_table.js, api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/models/Session.js, api/lib/domain/usecases/flag-session-results-as-sent-to-prescriber.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/session-repository.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/tooling/database-builder/factory/build-session.js, api/tests/tooling/domain-builder/factory/build-session.js, api/tests/unit/application/session/index_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/models/Session_test.js, api/tests/unit/domain/usecases/flag-session-results-as-sent-to-prescriber_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Le pôle certif* s'occupent de "traiter" les sessions* lorsque celles-ci sont "finalisées" (passées dans le temps). 
Traiter une session consiste à : 
- envoyer au prescripteur* les résultats de la session,
- diffuser / publier les résultats auprès des candidats (ils pourront les voir sur l'application pix en se connectant avec le compte avec lequel ils ont passé leur certification). 
Aujourd'hui ce traitement des sessions se faire sur un google sheet par le pôle certif.
*pôle certif = Anne-C, Pablo, Josselin de chez Pix
*session = un jour donné, examen encadré par un surveillant, de quelques minutes sur l'application pix (contenu des questions adapté à chaque candidat)
*prescripteur = organisation qui a demandé que son public passe une session de certification
Plus le pôle certif a de …
=> [FEATURE] Tagger les résultats d'une session comme "envoyés au prescripteur" (PA-134)

api/lib/domain/models/CertificationReport.js, api/lib/domain/models/Session.js, api/lib/infrastructure/repositories/certification-report-repository.js, api/lib/infrastructure/serializers/jsonapi/certification-course-serializer.js, api/lib/infrastructure/serializers/jsonapi/certification-report-serializer.js, api/lib/infrastructure/serializers/jsonapi/certification-serializer.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-get-certification-reports_test.js, api/tests/integration/infrastructure/repositories/certification-report-repository_test.js, api/tests/test-helper.js, api/tests/tooling/database-builder/factory/build-certification-report.js, api/tests/tooling/domain-builder/factory/build-certification-report.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-candidate-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-report-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js, certif/app/controllers/authenticated/sessions/finalize.js
Suite au bug PC-129, on a détecté que permettre d'envoyer une chaîne vide dans le commentaire examinateur d'une certification causait une erreur de validation, et à cette occasion on s'est dit que traiter différemment une chaîne vide ou blanche (que des espaces) d'un `null` semble inutile et trompeur. On a donc implémenté un traitement commun de tout ces cas pour le commentaire examinateur des certification sur la page de finalisation de session.
Or il y a d'autres commentaires examinateurs. Il serait étrange qu'ils se comportent différemment.
Par conséquent : ce ticket homogénéise les traitements de commentaires nuls, vides et blancs.
=> [TECH] Gestion des commentaires examinateurs et globaux vides et blancs (PC-130)

api/lib/domain/services/csv-service.js, api/lib/domain/usecases/start-writing-campaign-results-to-stream.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/unit/domain/services/csv-service_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
Lors de l'export csv des résultats d'une campagne, si le nom des acquis commence par un '@' il sera mal retranscrit dans un tableur.
Echapper les chaines de caractères commençant par les symboles =, -, +, ou @
avec le caractère " **'** "
=> [FEATURE] Gestion des caractères à risque lors des exports CSV dans Pix Orga - nom des acquis (PO-332).

mon-pix/app/components/routes/register-form.js, mon-pix/app/templates/components/routes/register-form.hbs, mon-pix/tests/acceptance/start-campaigns-test.js, mon-pix/tests/helpers/mirage.js
_Scénario pour reproduire :
1 - Sur la double mire, faire la pré-réconciliation (First Last 10/10/2010)
2 - Choisir e-mail sur le toggle
3 - Remplir avec un email déjà existant (userpix1@example.net) et un mot de passe valide
4 - Valider (un message d'erreur s'affiche, logique)
5 - Cliquer sur identifiant sur le toggle
6 - Constater le problème que l'identifiant "first.last1010" a disparu_
_ Remplacer le binding de l'input username par la propriété username qui ne réinitialise pas . 
Contrairement à celle du modele student user association qui subi un reset lors du changement de mode de connexion._
=> [BUGFIX] L'identifiant ne doit pas se vider après avoir tenté de s'inscrire avec adresse email existante (PF-1074).

api/lib/domain/services/csv-service.js, api/lib/domain/usecases/start-writing-campaign-results-to-stream.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/unit/domain/services/csv-service_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js
Lors de l'export csv des résultats d'une campagne, si les nom, prénom et identifiant externe
commencent par un '@' : 
- ils seront mal retranscrits dans un tableur.
- ils peuvent permettre l'exécution de code malicieux
Echapper les chaines de caractères commençant par les symboles =, -, +, ou @
avec le caractère " ' "
=> [FEATURE] Gestion des caractères à risque dans l'export des résultats de campagne (PO-351).

admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js
Un "only" était resté par mégarde dans la PR : https://github.com/1024pix/pix/pull/1073/files. 
Enlever le only et corriger les tests de ce fichier.
Oups 😰
=> [TECH] Enlève only et corrige un fichier de test dans pix admin

mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/styles/globals/_buttons.scss, mon-pix/app/styles/pages/_fill-in-campaign-code.scss, mon-pix/app/styles/pages/_user-certifications-get.scss, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/app/templates/user-certifications/get.hbs, mon-pix/tests/acceptance/competences-details-test.js, mon-pix/tests/acceptance/competences-results-test.js
- Les liens "retour vers une page" ne sont pas uniformisé sur l'application mon-pix. Ca n'aide pas l'utilisateur à se repérer et comprendre la logique du site.
- Les erreurs qui s'affichent lorsqu'on rentre un code de parcours ne sont pas super lisible (car il y a peu de marge entre le champ d'entrée et le bouton pour passer à la suite).
- Uniformiser le bouton "Retour à la liste" (visible dans le détail d'une certification) avec le style du "Retour profil" (visible lorsqu'on clique sur un domaine).
**AVANT** 
**APRES** 
##
- Rajouter un espace lorsqu'un message d'erreur s'affiche lorsqu'on rentre un code de parcours.
**AVANT**
**APRES** 
Le bouton "Commencer mon parcours" descend légèrement quand une erreur apparaît. 
C'est déjà le cas sur d'autres pages de l'application et ce …
=> [FEATURE] Changer le design du bouton "Retour à la liste" sur la page certificat (PF-1051).

api/lib/application/organizations/organization-controller.js, api/lib/infrastructure/repositories/campaign-repository.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/unit/application/organizations/organization-controller_test.js, high-level-tests/e2e/cypress/support/step_definitions/login-logout.js, orga/app/controllers/authenticated/campaigns/list.js, orga/app/routes/authenticated/campaigns/list.js, orga/app/styles/pages/authenticated/campaigns/list.scss, orga/app/templates/authenticated/campaigns/list.hbs, orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs, orga/config/environment.js, orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Actuellement, les utilisateurs de pix orga ont la possibilité d'archiver leur campagnes, mais ce nouveau statut n'est pas présent dans l'affichage de la liste, ce qui encombre l'interface.
Rajout d'un filtre permettant de choisir les campagnes qui sont archivées de celles qui sont en cours de façon mutuellement exclusive.
=> [FEATURE] Ajout d'un filtre sur le status lors de l'affichage de la liste des campagnes (PO-314).

api/lib/application/campaigns/campaign-controller.js, api/lib/domain/usecases/update-campaign.js, api/lib/infrastructure/repositories/campaign-repository.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/unit/application/campaign/campaign-controller_test.js, api/tests/unit/domain/usecases/update-campaign_test.js, orga/app/routes/authenticated/campaigns/update.js, orga/app/templates/authenticated/campaigns/update.hbs, orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs
On ne peut pas changer le nom du campagne
Ajouter le champ nom dans le formulaire d'édition des campagnes
=> [FEATURE] Pouvoir modifier le nom de la campagne dans PIX Orga (PO-350). 

api/db/migrations/20200303153018_add-credit-column-to-organization.js
Le pôle partenariat surveille régulièrement metabase pour voir si les orgas ne dépassent pas le nombre de crédits qu’elles ont acheté. Et avec le nombre d’orgas qui augmente, ça devient fastidieux.
Ajout d'une colonne credit dans la table organizations
=> [FEATURE] Ajouter une colonne credit à la table organizations (PO-300).

api/db/migrations/20200303140224_add_columns_createdAt_and_updatedAt_to_user_orga_settings.js, api/lib/application/user-orga-settings/index.js, api/lib/application/user-orga-settings/user-orga-settings-controller.js, api/lib/application/users/index.js, api/lib/domain/errors.js, api/lib/domain/usecases/index.js, api/lib/domain/usecases/update-user-orga-settings.js, api/lib/infrastructure/data/user-orga-settings.js, api/lib/infrastructure/repositories/user-orga-settings-repository.js, api/lib/infrastructure/utils/error-manager.js, api/tests/acceptance/application/user-orga-settings-controller_test.js, api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js, api/tests/unit/application/user-orga-settings/index_test.js, api/tests/unit/application/user-orga-settings/user-orga-settings-controller_test.js, api/tests/unit/domain/usecases/update-user-orga-settings_test.js, orga/app/components/user-logged-menu.js, orga/app/controllers/authenticated/campaigns/list.js, orga/app/services/current-user.js, orga/app/styles/components/user-logged-menu.scss, orga/app/templates/components/user-logged-menu.hbs, orga/mirage/config.js, orga/tests/acceptance/switch-organization-test.js, orga/tests/helpers/test-init.js, orga/tests/integration/components/user-logged-menu-test.js, orga/tests/unit/components/user-logged-menu-test.js, orga/tests/unit/services/current-user-test.js
Actuellement dans Pix Orga, un utilisateur appartenant à plusieurs organisations n'a pas les moyens de se connecter à une organisation différente de son organisation courante. 
Ajout de la liste des organisations dans le menu utilisateur et de la possibilité de sélectionner une nouvelle organisation courante. 
La dernière organisation sélectionnée devient la nouvelle organisation courante.
=> [FEATURE] Pouvoir changer d'organisation courante dans Pix Orga (PO-237). 

orga/app/components/user-logged-menu.js, orga/tests/acceptance/switch-organization-test.js
Dans la liste des campagnes de Pix Orga, lorsque je filtre/change le nombre de campagnes affichées ou de page, des queryParams sont ajoutés à l'URL. Lorsque l'on change d'organisation principale, nous redirigeons l'utilisateur vers cette liste des campagnes mais les queryParams sont conservés.  
Supprimer les queryParams au moment de la redirection.
=> [BUGFIX] Réinitialiser l'URL des campagnes quand je change d'organisation (PO-361).

api/lib/domain/models/Course.js, api/lib/domain/services/smart-random/cat-algorithm.js, api/lib/domain/services/smart-random/skills-filter.js, api/lib/domain/services/smart-random/smart-random.js, api/lib/domain/services/tube-service.js, api/lib/infrastructure/serializers/jsonapi/course-serializer.js, api/tests/integration/domain/services/tube-service_test.js, api/tests/unit/domain/models/Course_test.js, api/tests/unit/domain/services/smart-random/skills-filter_test.js, api/tests/unit/infrastructure/serializers/jsonapi/course-serializer_test.js, mon-pix/app/models/course.js, mon-pix/app/routes/courses/create-assessment.js, mon-pix/mirage/data/demo.js, mon-pix/mirage/routes/get-assessment.js, mon-pix/mirage/routes/get-next-challenge.js, mon-pix/mirage/routes/post-assessments.js, mon-pix/mirage/scenarios/default.js, mon-pix/tests/acceptance/starting-a-course-test.js, mon-pix/tests/unit/routes/courses/create-assessment-test.js
Il fut un temps où le Course était utilisé un peu partout. Au fil des années et des évolutions de la base de code, le concept modèle de Course n'est plus utilisé que pour les démo. Ce legacy peut rendre difficile la lecture de code sur les démo. De plus, certaines parties du code sont restées inchangées au fil des évolutions. On a donc toujours un code qui permet de répondre à plusieurs types de "Courses", ce qui n'a plus de sens désormais puisqu'il ne s'agit que de démo à chaque fois !
- Simplification du chemin côté front pour créer un assessment de Demo. En effet, avant on demandait au serveur si il existait un assessment pour cette démo et cet utilisateur (ce qui n'a pas de sens vu qu'on est pas authentifié pour une démo !)
- Le modèle portait historiquement des méthodes pour extraire …
=> [TECH] Nettoyage du modèle Course (PF-1137)

api/lib/domain/usecases/find-organization-students.js, api/lib/infrastructure/serializers/jsonapi/student-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/application/organizations/index_test.js, api/tests/unit/domain/usecases/find-organization-students_test.js, orga/app/models/student.js, orga/app/styles/pages/authenticated/students/list.scss, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/tests/acceptance/student-list-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js, orga/tests/unit/models/student-test.js
Les enseignants ne savent pas si les élèves se sont réconciliés avec leur compte GAR, leur adresse email ou leur identifiant. Ils sont donc très limités pour les aider à se connecter une fois la première connexion est faite. On veut donc leur donner davantage d'infos pour les aider.
Afficher la méthode de connexion pour chaque élève. Pour préparer l'arrivée de la réinitialisation, l'email complet sera exposé par l'API : GET /organizations/{id}/students.
Cette feature inclus un enrichissement de cas de test sur le use-case utilisé par la route.
=> [FEATURE] Afficher les méthodes de connexion des élèves (PO-320)

orga/app/styles/globals/buttons.scss, orga/app/styles/pages/authenticated/students/list.scss, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/tests/acceptance/student-list-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js
Actuellement dans la liste des élèves de Pix Orga, il existe une colonne "Mot de passe" qui contient des boutons "Réinitialiser" permettant d'ouvrir une modal de changement de mot de passe pour les élèves ayant créé un compte avec identifiant. Dans le futur, cette modal ne permettra pas uniquement de réinitialiser un mot de passe mais proposera plusieurs actions s'inscrivant dans une gestion plus globale du compte d'un élève. Il apparaît alors que le titre de la colonne, ainsi que le libellé du bouton ne sont plus en accord avec les futurs objectifs de cette modal.    
Il a été choisi de supprimer le nom de la colonne et de remplacer le texte du bouton "Réinitialiser" par une icone représentant un engrenage. De plus, le survol de ce bouton, le libellé "Gérer" doit apparaître.
=> [FEATURE] Modifier l'entrée de menu de réinitialisation de mot de passe (PO-338).

api/lib/domain/models/CampaignParticipationResult.js, api/lib/domain/services/badge-criteria-service.js, api/lib/domain/usecases/get-campaign-participation-result.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js, api/tests/acceptance/application/campaign-participation-result-controller_test.js, api/tests/tooling/domain-builder/factory/build-campaign-participation-result.js, api/tests/unit/domain/models/CampaignParticipationResult_test.js, api/tests/unit/domain/services/badge-criteria-service_test.js, api/tests/unit/domain/usecases/get-campaign-participation-result_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js, mon-pix/app/controllers/campaigns/skill-review.js, mon-pix/app/models/campaign-participation-result.js, mon-pix/mirage/routes/get-campaign-participation-result.js, mon-pix/mirage/serializers/campaign-participation-result.js, mon-pix/tests/unit/controllers/campaigns/skill-review-test.js, mon-pix/tests/unit/models/campaign-participation-result-test.js
Actuellement, les badges sont générés "en dur" dans le front.
Historiquement, nous avions créé cette dette technique pour évaluer l'intérêt de la solution dans les délais accordés.
Pour vérifier si les critères de badges sont validés, nous procédons à : 
- un refactoring qui déplace le seul critère que nous avons pour le moment au niveau de l'API. 
- un refactoring côté front qui se base sur l'état `areBadgeCriteriaValidated` de la revue des critères d'obtention de badge faite côté back
La gamification peut s'exprimer sous l'équation suivante :
```
Gamification = Rules + Goals + Volontary Participation + Feedback
```
Concrètement, dans le code, cela va se modéliser selon les termes métier par :
```
Gamification = BadgeCriteria + Badge + BadgeAcquisition
```
avec : 
- `BadgeCriteria = …
=> [TECH] Déplacer les critères de badge vers l'API (PF-1149).

high-level-tests/e2e/cypress.json, high-level-tests/e2e/cypress/fixtures/organization-invitations.json, high-level-tests/e2e/cypress/fixtures/organizations.json, high-level-tests/e2e/cypress/integration/organization-management.feature, high-level-tests/e2e/cypress/support/commands.js, high-level-tests/e2e/cypress/support/step_definitions/assessment.js, high-level-tests/e2e/cypress/support/step_definitions/index.js, high-level-tests/e2e/cypress/support/step_definitions/organization.js, orga/app/router.js, orga/app/routes/application.js, orga/app/routes/join-when-authenticated.js, orga/app/routes/join.js, orga/tests/acceptance/join-test.js, orga/tests/unit/routes/join-when-authenticated-test.js, scalingo.json
Lorsqu'on est déjà authentifié sur Pix Orga, il n'est pas possible de répondre à une invitation.
Si l'utilisateur est déjà authentifié, le déconnecter, et le rediriger vers la page Rejoindre une organisation.
Un test Cypress a été créé à l'occasion.
=> [BUGFIX] Pouvoir accepter une invitation à rejoindre Pix Orga lorsqu'on est déjà authentifié (PO-240).

api/db/migrations/20200306143100_delete-snapshots-table.js
Tout le code lié à Pix Board a déjà été supprimé. La table Snapshots en est la dernière trace, et n'est donc plus utilisée.
Supprimer cette table, qui est désormais inutile ! 🎉 
end of pix board 🎉 🎉
=> [TECH] Suppression de la table Snapshots (PF-1126).

api/lib/application/answers/answer-controller.js, api/lib/domain/usecases/find-answer-by-challenge-and-assessment.js, api/lib/domain/usecases/get-answer.js, api/lib/domain/usecases/get-correction-for-answer.js, api/tests/acceptance/application/answers/answer-controller-find_test.js, api/tests/acceptance/application/answers/answer-controller-get-correction_test.js, api/tests/acceptance/application/answers/answer-controller-get_test.js, api/tests/acceptance/application/answers/answer-controller-update_test.js, api/tests/integration/infrastructure/repositories/answer-repository_test.js, api/tests/unit/domain/usecases/find-answer-by-challenge-and-assessment_test.js, api/tests/unit/domain/usecases/get-answer_test.js, api/tests/unit/domain/usecases/get-correction-for-answer_test.js
Là où tout a commencé.... https://github.com/1024pix/pix/pull/1062
Suite aux discussions amenées par ce ticket, il semblerait qu'une convention puisse s'en dégager.
Dans la base de code côté API, jusqu'à présent, nous jetions un code statut HTTP en accord avec l'erreur rencontrée pendant le traitement de la requête. Par exemple, si un utilisateur demande une ressource pour laquelle il n'est pas le propriétaire, on jette habituellement 403. Si une erreur se produit pendant la validation des paramètres d'entrée c'est 401, si la ressource n'est pas trouvée c'est 404, etc...
Or, on s'aperçoit que cette stratégie permet à un utilisateur mal-intentionné de crawler des informations utiles sur les ressources. Exemple :  en tant qu'utilisateur cherchant à obtenir des informations sur les données, …
=> [TECH] Démocratisation du code HTTP 404 quand il est impossible de récupérer une ressource : routes answers (PF-1131)

admin/app/templates/components/routes/authenticated/organizations/list-items.hbs, admin/tests/integration/components/routes/authenticated/organizations/list-items-test.js
L'information Identifiant externe est utile dans la gestion des organisations.
Mais cette information n'est pas visible dans le liste des organisations.
Ajouter la colonne Identifiant externe dans la page listant les organisations.
La fonction de recherche sera traitée dans un autre ticket.
=> [FEATURE] Ajouter l'identifiant externe dans la liste des organisations (PA-113).

api/lib/application/organizations/index.js, api/lib/application/usecases/checkUserBelongsToOrganization.js, api/lib/interfaces/controllers/security-controller.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/application/security-controller_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/unit/application/usecases/checkUserBelongsToOrganization_test.js, api/tests/unit/interfaces/controllers/security-controller_test.js
Actuellement si un user est membre, il ne peut pas filtrer (autre que sur lui) dans le filtre créé par. La route actuellement appelée retourne les membres de l'équipe d'une orga que pour les users admin.
Ouvrir l'accès à la requête même aux membres d'une équipe.
Ceci est un bugfix, ce n'est pas très grave d'ouvrir la liste des membres aux membres, puisque c'est même ce qui veut être fait pour l'onglet "Equipe".
=> [BUGFIX] Autoriser l'affichage des autres membres d'une organisation pour un simple membre (PO-374).

admin/app/models/organization.js, admin/app/models/target-profile.js, admin/app/templates/authenticated/organizations/get.hbs, admin/app/templates/components/organization-target-profiles-section.hbs, admin/tests/integration/components/organization-target-profiles-section-test.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Actuellement, la gestion des profils cibles ne se faisait pas dans Pix Admin, donnant lieu à beaucoup de support.
Ajouter cette gestion dans Pix Admin, en commençant par l'affichage de la liste des profils cible actifs rattachés à une organisation.
Ensuite viendra la possibilité de rattacher directement dans Pix Admin. :)
=> [FEATURE] Affichage de la liste des profils cibles d'une organisation (PA-162).

admin/app/services/session-info-service.js, admin/tests/unit/services/session-info-service-test.js, api/db/seeds/data/certification/certification-candidates-builder.js, api/db/seeds/data/certification/certification-courses-builder.js, api/db/seeds/data/certification/certification-scores-builder.js
**Après avoir publié les résultats** d’une session de certification, le pôle certif **exporte le fichier des résultats** de toutes les certif de la session afin de le transmettre au prescripteur de la certification. 
Or parfois, le pôle certif doit ‘invalider” une certification, et donc passer une certif à l’origine ‘started’ ou ‘validated’ au statut ‘rejected’ manuellement dans Pix Admin.
Dans le fichier des résultats, ces certif passées manuellement de ‘started’ ou ‘validated’ à ‘rejected’ gardent les infos d’origine. Mais on ne veut pas que le prescripteur ait des valeurs > 0 (pour les compétences évaluées) pour les certif ‘rejected’.
Dans le fichier des résultats, mettre des 0 pour les certif ‘rejected’ pour les compétences évaluées (les compétences non évaluées restent avec des …
=> [FEATURE] Lors de l'export des résultats, forcer les compétences à 0 pour les certifs rejected (PA-174)

admin/app/components/routes/authenticated/organizations/list-items.js, admin/app/controllers/authenticated/organizations/list.js, admin/app/routes/authenticated/organizations/list.js, admin/app/templates/authenticated/organizations/list.hbs, admin/app/templates/components/routes/authenticated/organizations/list-items.hbs, admin/tests/acceptance/organization-list-test.js, admin/tests/integration/components/routes/authenticated/organizations/list-items-test.js, api/lib/application/organizations/index.js, api/lib/infrastructure/repositories/organization-repository.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js
Si Pix Admin il n'est pas possible de filtrer la liste des organisations par l'identifiant externe.
Ajoutez un champs spécifique pour faire ce filtrage.
=> [FEATURE] Filtrer la liste des organisations par l'identifiant externe (PA-172).

api/lib/domain/services/solution-service-qrocm-dep.js, api/lib/domain/services/solution-service-qrocm-ind.js, api/tests/unit/domain/services/solution-service-qrocm-dep_test.js, api/tests/unit/domain/services/solution-service-qrocm-ind_test.js
Les nombres au format `1234.0`, `1234.00`, ... sont convertis comme suit `1234` et ne sont plus au format String.
Ajouter le [schéma de validation](https://github.com/nodeca/js-yaml#safeload-string---options-) `jsYaml.FAILSAFE_SCHEMA` lors de la conversion des réponses.
On en a profité pour supprimer une dépendance à la surcharge de lodash (lodashUtils) et pour remplacer `_.ensureString(foo)` par `foo || ''` directement à la conversion du scoring des answers.
https://app-pr1175.review.pix.fr/challenges/recSP9tZ5WUjjYMgN/preview
Solution 1 : `b2:m4`
Solution 2 : `7045,0` ou `7045.0`
=> [BUGFIX] Corriger la gestion des nombres décimaux en answer (PF-1155).

admin/app/models/organization.js, admin/app/templates/components/organization-information-section.hbs, admin/tests/integration/components/organization-information-section-test.js, api/lib/domain/models/Organization.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/tooling/database-builder/factory/build-organization.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Actuellement, les utilisateurs de Pix Admin ne voient pas combien de crédits ont été octroyés à une organisation donnée.
Afficher ce champ dans le détail d'une organisation.
La possibilité de modifier cette valeur arrive après ;)
=> [FEATURE] Affichage du nombre de crédits octroyés à une organisation dans Pix Admin (PA-173).

admin/config/environment.js, certif/config/environment.js, mon-pix/app/routes/index.js, mon-pix/config/environment.js, mon-pix/tests/unit/routes/index-test.js, orga/config/environment.js
2 problèmes : 
- Pix Orga est branché sur le container Matomo de Pix App ce qui fausse les données remontées
- par ailleurs, le fait de rediriger la route `index` vers la route `profile` en utilisant `transitionTo` ajoute une entrée dans l'historique de navigation et compte une PageView `/index` dans Matomo non pertinente
Cette PR fixe ces 2 problèmes.
Au passage, cette PR permet de tenir compte de l'environnement `development` pour le dev localhost.
=> [BUGFIX] Intégration de Matomo avec les apps front.

admin/app/models/session.js, admin/app/templates/components/routes/authenticated/sessions/list-items.hbs, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js
L’heure de début de session affichée dans la liste des session dans Pix Admin est erronée.
Heure de début dans Pix certif : 
Heure de début dans la liste des sessions dans Pix Admin :
Une session est en fait composée d'une date et d'une heure : 
On affichait uniquement la date qui était formattée avec toLocalString (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date/toLocaleString), ce qui part défaut est formatté avec une heure. 
Il faut donc formatter la date dans le format souhaité, par exemple JJ/MM/AAAA et après afficher l'heure.
J'aime les mangues 🥭
=> [EXPEDIT] Mauvais affichage des heures sur la liste des sessions (PA-183)

.circleci/config.yml
On n'a pas besoin de faire tourner les tests sur **dev** et **master** dans le cadre des MEP et cela réduit le temps d'exécution des tests.
=> [TECH] Exclure la branche master des tests sur la CI.

mon-pix/app/templates/error.hbs
Sur la page erreur, on proposait à l'utilisateur d'envoyer un mail, alors qu'un formulaire de contact a été créé à cet effet.
Changer le lien de contact.
=> [FEATURE] Changer la façon de contacter le support de la page d'erreur (PF-1166).

api/lib/domain/models/Assessment.js, api/lib/domain/models/CertificationChallenge.js, api/lib/domain/models/Challenge.js, api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js, api/tests/integration/domain/services/user-service_test.js, api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js, api/tests/unit/application/assessments/assessment-controller-save_test.js, api/tests/unit/application/challenges/challenge-controller_test.js, api/tests/unit/domain/models/Answer_test.js, api/tests/unit/domain/models/Assessment_test.js, api/tests/unit/domain/models/Challenge_test.js, api/tests/unit/domain/usecases/get-correction-for-answer_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-course-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/challenge-serializer_test.js
On supprime ces méthodes taggées dépréciées depuis déjà trop de temps.
Dans 99% des cas, ces méthodes dépréciées étaient utilisées dans les tests. On remplace le constructeur. Pareil pour le seul cas encore utilisé dans le code de production, à savoir dans le déserialiseur d'_Assessment_.
Le seul controller dans lequel on déserialise un assessment c'est dans le cas d'une Démo, c'est donc le test fonctionnel de non-régression à réaliser ici.
=> [CLEANUP] Supprimer les méthodes dépréciées fromAttributes (PF-1174)

api/db/seeds/data/po376-builder.js, api/db/seeds/seed.js, orga/app/controllers/terms-of-service.js, orga/app/services/current-user.js, orga/tests/acceptance/terms-of-service-test.js, orga/tests/unit/services/current-user-test.js
Il arrive parfois que nos utilisateurs de Pix Orga souhaitent supprimer l'accès à l'organisation à certaines personnes. N'ayant pas de moyen de le faire depuis nos applications pour le moment, la solution consiste à supprimer le membership de l'utilisateur (lien entre un user et une orga) en base de données. Cependant, il arrive parfois que l'organisation courante (stockée dans la table user-orga-settings) corresponde à l'organisation du membership qui vient d'être supprimé ce qui cause l'impossibilité pour l'utilisateur d'accéder à Pix Orga. 
- Créer le userOrgaSettings d'un utilisateur si celui-ci n'existe pas au moment où l'on souhaite y accéder.
- Mettre à jour l'organisation du userOrgaSettings avec l'organisation du premier membership si l'organisation n'existe plus dans les …
=> [BUGFIX] Permettre la connexion aux utilisateurs dont un des memberships a été supprimé (PO-376).

api/db/migrations/20200317112058_add_unique_constraint_on_userid_certificationcourseid_table_assessments.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/integration/infrastructure/repositories/certification-repository_test.js
Il existe encore un certain nombre de données inconsistantes dans la base dues à des bugs résolus depuis. Notamment, nous comptons actuellement dans la base 65 certification-courses pour lesquels il existe plus d'un assessment :
```sql
WITH ASSESSMENTS_BY_CERTIFICATION_COURSES AS (
SELECT distinct "as"."certificationCourseId" as id,
COUNT("as"."id") OVER (PARTITION BY "as"."certificationCourseId") AS CNT_ASSESSMENTS_PER_CERTIFICATION_COURSE
FROM "assessments" as "as"
WHERE "as"."certificationCourseId" IS NOT NULL
)
SELECT COUNT(id)
FROM ASSESSMENTS_BY_CERTIFICATION_COURSES
WHERE CNT_ASSESSMENTS_PER_CERTIFICATION_COURSE > 1;
```
Par effet boule de neige, une telle inconsistance rend inutilement complexe des opérations simples, je pense notamment à récupérer l'`assessment-result` _valide_ …
=> [TECH] Renforcer la contrainte d'unicité entre un assessment et un certification-course dans la table Assessments (PF-1161)

api/lib/application/assessments/assessment-controller.js, api/lib/domain/constants.js, api/lib/domain/models/Challenge.js, api/lib/domain/services/pick-challenge-service.js, api/lib/domain/usecases/get-next-challenge-for-competence-evaluation.js, api/lib/domain/usecases/get-next-challenge-for-smart-placement.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/caches/RedisCache.js, api/lib/infrastructure/datasources/airtable/challenge-datasource.js, api/lib/infrastructure/repositories/challenge-repository.js, api/lib/infrastructure/utils/request-response-utils.js, api/package-lock.json, api/package.json, api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-locale-management.js, api/tests/tooling/airtable-builder/factory/build-challenge.js, api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js, api/tests/tooling/domain-builder/factory/build-challenge.js, api/tests/tooling/fixtures/infrastructure/challengeAirtableDataObjectFixture.js, api/tests/tooling/fixtures/infrastructure/challengeRawAirTableFixture.js, api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js, api/tests/unit/domain/models/Challenge_test.js, api/tests/unit/domain/services/pick-challenge-service_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-smart-placement_test.js, api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js, api/tests/unit/infrastructure/utils/request-response-utils_test.js, mon-pix/app/adapters/application.js, mon-pix/app/services/current-domain.js, mon-pix/tests/unit/adapters/application-test.js
Dans l'objectif d'internationaliser l'accès à pix, il est nécessaire de proposer un référentiel unique et cohérent de manière mondiale.
Les acquis sont validés à travers des épreuves qui elles sont localisées.
Pour le moment, 2 localisations sont proposées.
Francophone : accessible via le site app.pix.digital (et à terme pix.org)
Franco-français : accessible via le site app.pix.fr.
Les acquis spécifiques France sont sortis du référentiel Pix et seront intégrés dans un référentiel Pix+ dédié.
Une colonne langue est ajoutée dans la table Epreuves. Cette colonne peut prendre la valeur `Francophone` ou `Franco Français`.
L'application front, en fonction de l'extension du domaine, valorise le header `Accept-Language` afin que l'API fournisse une épreuve correctement localisée.
Pour tester …
=> [FEATURE] Gérer la localisation des acquis francophone ou franco-français (PF-1035).

certif/app/styles/app.scss, certif/app/styles/components/ember-cli-notifications-ie-fallback.scss, certif/app/styles/components/finalize.scss, certif/app/styles/components/login-form.scss, certif/app/styles/components/session-finalization-examiner-global-comment-step.scss, certif/app/styles/components/session-finalization-formbuilder-link-step.scss, certif/app/styles/components/session-finalization-reports-informations-step.scss, certif/app/styles/components/session-finalization-step-container.scss, certif/app/styles/globals/app-modal.scss, certif/app/styles/globals/colors.scss, certif/app/styles/globals/forms.scss, certif/app/styles/globals/panels.scss, certif/app/styles/globals/tables.scss, certif/app/styles/globals/texts.scss, certif/app/styles/globals/titles.scss, certif/app/styles/pages/authenticated.scss, certif/app/styles/pages/authenticated/sessions/details.scss, certif/app/styles/pages/authenticated/sessions/details/certification-candidates.scss, certif/app/styles/pages/authenticated/terms-of-service.scss, certif/app/styles/pages/login.scss
Dans le cadre du design system qui se met en place afin de faciliter les échanges entre designers et developpeurs, une uniformisation des couleurs entre toutes les app est souhaitable.
Côté développeur, on recopie systématiquement certains éléments qui sont pourtant communs entre toutes les app, c'est le cas des couleurs. Cette ré-implémentation cause une perte de temps et même parfois des erreurs inattendues. 
Changer / adapter toutes les couleurs de pix certif à celles définitives et présentes sur ZeroHeight : https://zeroheight.com/8dd127da7/p/839645-couleurs/b/21317a . 
Ce travail sera fait prochainement sur pix orga ainsi que sur mon-pix. 
L'étape suivante serait de regrouper la palette de couleurs dans le dossier de design system "pix-ui" qui devrait arriver très prochainement.
=> [DESIGN-SYSTEM] Uniformisation des couleurs (CERTIF) (PF-1163)

api/lib/domain/usecases/create-user.js, api/lib/domain/validators/user-validator.js, api/lib/interfaces/jsonapi/unprocessable-entity-error.js, api/tests/unit/domain/usecases/create-user_test.js, api/tests/unit/domain/validations/user-validator_test.js, api/tests/unit/interfaces/jsonapi/unprocessable-entity-error-test.js, orga/app/components/routes/register-form.js, orga/app/templates/components/routes/register-form.hbs, orga/tests/integration/components/routes/register-form-test.js
Lors de l'inscription, si la saisie de l'utilisateur est invalide (ex: email non renseigné), la soumission est possible. De plus, l'API renvoit une erreur 500.
Ne pas faire appel à l'API si la saisie est invalide. 
Si les données reçues côté API sont invalides, renvoyer une erreur 422.
Mise à jour de la validation JOI pour rejeter le cas où ni l'email, ni le username ne sont fournis.
=> [BUGFIX] Bloquer l'inscription si le formulaire n'est pas valide (PO-381).

admin/app/components/certification-list-checkbox.js, admin/app/components/certification-list.js, admin/app/controllers/authenticated/certifications/sessions/info/list.js, admin/app/controllers/authenticated/certifications/single/info.js, admin/app/models/session.js, admin/app/templates/authenticated/certifications/sessions/info/list.hbs, admin/app/templates/authenticated/certifications/single/info.hbs, admin/app/templates/components/certification-list-checkbox.hbs, admin/app/templates/components/certification-list-select-all.hbs, admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
🦄 Problème
La migration de PIX admin sous Octane a écrasé quelques fonctionalités de la [PR](https://github.com/1024pix/pix/pull/1141/). La colonne permettant de sélectionner une ou plusieurs certifs d’une session est apparue à nouveau, et le bouton “Publier” ne fonctionne plus
🤖 Solution
Réparer la publication des certif par session en verifiant l'historique des fichiers
🌈 Remarques
La pagination n'est pas alignée. Ca peut-être fait en BSR si besoin
=> [BUGFIX]  Publication des certif par session KO dans Pix Admin (pa-184)

admin/tests/unit/controllers/authenticated/certifications/sessions/info/list-test.js
module.only() dans les test auto.
Le retirer.
=> [CLEANUP] Retrait d'un .only oublié dans les tests PixAdmin (PA-185)

api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
Les succès montraient aux utilisateurs des niveaux gagnés qu'ils n'avaient pas encore.
Exemple : un niveau gagné 3 sur une épreuve alors qu'il n'était que niveau 2.
Cause du problème : 
- Sauvegarde des KE sur les acquis déjà validé précédemment
- Au moment de calculer le nombre de Pix gagnés pour une épreuve, on regardait les KE créé, et donc on comptait les pix des acquis déjà validés précédemment
- Le total de Pix pour la compétence restait le même, car il on ignore les doublons
LA cause du problème : 
- Lors d'un précédent refacto, modification d'un `.map`par un `.filter`, qu'aucun test ne regardait. Au lieu de renvoyer l'acquis en entier, on renvoyait un tableau avec les ID d'acquis. Au moment de comparer deux acquis (celui déjà validé et celui en cours de validation), la méthode qui …
=> [BUGFIX] Des utilisateurs avaient un succès pour un niveau pas encore atteint (PF-1171).

api/package.json
Dans l'api, il existe un script npm pour lancer uniquement les tests unitaires, mais pas de script npm pour lancer uniquement les tests d'intégration ou les tests d'acceptance.
Comme c'est quelque-chose que je fais souvent pendant le développement, je propose d'ajouter ces scripts npm.
=> [TECH] Ajoute des scripts npm pour lancer les tests d'intégration ou d'acceptance

api/lib/domain/models/CampaignParticipationResult.js, api/lib/domain/services/campaign-participation-service.js, api/lib/domain/usecases/start-writing-campaign-results-to-stream.js, api/lib/infrastructure/repositories/campaign-participation-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js, api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/acceptance/application/campaign-participation-controller_test.js, api/tests/acceptance/application/campaign-participation-result-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-participation-repository_test.js, api/tests/unit/domain/models/CampaignParticipationResult_test.js, api/tests/unit/domain/services/campaign-participation-service_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-result-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js, orga/app/helpers/percentage.js, orga/app/models/campaign-participation-result.js, orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs, orga/tests/integration/components/routes/authenticated/campaigns/details/participants/results-item-test.js, orga/tests/unit/helpers/percentage-test.js, orga/tests/unit/models/campaign-participation-result-test.js
Le pourcentage de progression dans le CSV téléchargeable n'est pas le même que le pourcentage affiché dans la vue des résultats d'un candidat.
Pour reproduire :
Quand un candidat a terminé le parcours en répondant faux à certaines questions mais qu'il ne partage pas ses résultats.
Dans le CSV la progression du candidat n'est pas 1 comme dans la vue des résultats.
Passer le % à 100 si l'assessment est terminé.
Avoir ce calcul à un seul endroit dans l'application
=> [BUGFIX] Harmoniser le calcul de pourcentage de progression d'un candidat sur une campagne (PO-325)

mon-pix/app/styles/components/_challenge-actions.scss, mon-pix/app/templates/components/challenge-actions.hbs
Pour reproduire le bug.
1. Aller sur une question de type QROCM, choix multiples avec plusieurs champs de saisie.
2. Remplir les champs.
3. Appuyer sur la touche "Entrée".
Résultat attendu
Les réponses à la questions sont validées.
On passe à la question suivante.
Résultat observé
Rien ne se passe : ni la validation des réponses, ni la transition vers la prochaine question.
Les boutons des challenges ne sont pas des `buttons` sémantiquement parlant, mais des balises `a`.
Remplacer le `a` par `button` corrige le problème.
On a du également corriger le style pour conserver la même apparence que l'application actuelle.
Test à ajouter pour se prémunir d'une éventuelle régression.
Prévoir une passe sur toute l'application pour éviter ce genre de désagrément.
Cela permettra également …
=> [BUGFIX] La touche "Entrée" n'est pas prise en compte dans les questions à réponses multiples (PF-1176).

api/db/seeds/data/certification/certification-center-memberships-builder.js, api/db/seeds/data/certification/certification-centers-builder.js, api/db/seeds/data/certification/certification-sessions-builder.js, api/db/seeds/data/certification/users.js, api/lib/domain/usecases/create-certification-center-membership.js, api/lib/infrastructure/repositories/certification-center-membership-repository.js, api/lib/infrastructure/serializers/jsonapi/certification-center-membership-serializer.js, api/tests/acceptance/application/users/users-controller-get-certification-center-memberships_test.js, api/tests/integration/infrastructure/repositories/certification-center-membership-repository_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-center-membership-serializer_test.js, certif/app/authenticators/oauth2.js, certif/app/controllers/authenticated.js, certif/app/models/certification-center.js, certif/app/services/current-user.js, certif/app/styles/pages/authenticated.scss, certif/app/templates/authenticated.hbs, certif/tests/acceptance/authentication-test.js, certif/tests/unit/controllers/authenticated-test.js
Le pôle Certif souhaite mettre à disposition aux utilisateurs de PixCertif la documentation liée à leur exercice. La documentation est différente selon le type du centre de certification :
- 1 Doc spécifique pour les SCO
- 1 Doc pour les autres
On ajoute le bouton dans la bande latérale à la manière de PixOrga avec un lien conditionnel en fonction du type du centre de certification.
=> [FEATURE] Ajouter un bouton de documentation qui pointe vers un lien différent en fonction du type de centre de certification (PC-136)

api/db/migrations/20200320170707_add-type-to-campaign.js, api/db/seeds/data/campaigns-builder.js, api/lib/domain/models/Campaign.js, api/lib/domain/usecases/create-campaign.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/tests/tooling/database-builder/factory/build-campaign.js, api/tests/tooling/domain-builder/factory/build-campaign.js, api/tests/unit/domain/models/CampaignParticipation_test.js, api/tests/unit/domain/services/scorecard-service_test.js, api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js, api/tests/unit/domain/usecases/find-smart-placement-assessments_test.js, api/tests/unit/domain/usecases/get-assessment_test.js, api/tests/unit/domain/usecases/share-campaign-result_test.js, api/tests/unit/domain/usecases/start-writing-campaign-results-to-stream_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, high-level-tests/e2e/cypress/fixtures/campaigns.json, orga/app/models/campaign.js, orga/app/styles/pages/authenticated/campaigns/details.scss, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/tests/acceptance/campaign-details-test.js, orga/tests/unit/models/campaign-test.js
La fonctionnalité permettant de partager son profil au prescripteur arrive. Pour arriver à cela, il nous faut définir un type de campagne.
Afin que les US suivantes ne soient pas dépendantes, on a décidé de faire une US purement TECH, introduisant cette notion de type.
Les campagne seront soit de type TEST soit de type COLLECT_PROFILES. Il nous faut également ajouter ce champ en base, et migrer toutes les campagnes déjà présentes en base.
- S'assurer qu'il y a bien type dans la table `campaign` en base ;
- S'assurer que les anciennes campagnes ont bien été migrées (on ne peut vérifier qu'en local et en intégration, en RA la base se re-créée de zéro).
=> [TECH] Ajouter la possibilité d'avoir un type de campagne (PO-389).

admin/app/components/organization-information-section.hbs, admin/app/components/organization-information-section.js, admin/app/models/organization.js, admin/tests/integration/components/organization-information-section-test.js, api/db/migrations/20200324101353_add-can-collect-profiles-to-organization.js, api/db/seeds/data/dragon-and-co-builder.js, api/db/seeds/data/organizations-builder.js, api/lib/domain/models/Organization.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/tooling/database-builder/factory/build-organization.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js, orga/app/models/organization.js
La fonctionnalité de créer une Campagne de récupération de profils n'est pas souhaitée pour toutes les organisations, notamment côté PRO, où le pricing n'est pas défini. Mais, une partie des PRO va en avoir besoin, leur permettant de voir où on sont les utilisateurs au niveau des compétences numériques lorsqu'ils débutent au sein de l'organisation.
D'autre part, on ne peut pas se permettre d'afficher des choses et leur permettre la création de campagne de récupération profils pour ces mêmes utilisateurs PRO, même pour un court instant.
C'est pourquoi cet aspect a été développé entièrement techniquement, cela nous permet d'avancer sur les sujets que l'on ne doit pas afficher pour les prescripteurs non autorisés.
On a ajouté le champ `canCollectProfiles` en base, et on l'a remonté jusqu'au …
=> [TECH] Ajout d'une gestion de droits à la fonctionnalité de campagne de récupération profils (PO-390).

mon-pix/app/styles/components/_learning-more-tutorial-panel.scss, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/styles/globals/_colors.scss, mon-pix/app/styles/globals/_titles.scss, mon-pix/app/styles/pages/_user-tutorials.scss, mon-pix/app/templates/components/learning-more-panel.hbs, mon-pix/app/templates/components/scorecard-details.hbs
Nos différentes applications n'ont pas des éléments visuels unifiés. C'est notamment le cas des couleurs et des styles de titres.
Ajouter à Pix App les couleurs et les styles de titres qui sont mises en place par notre nouveau design system.
=> [CLEANUP] Ajouter les couleurs et les styles de titres du design system à PixApp (PF-1181).

api/.eslintrc.yaml, api/db/knex-database-connection.js, api/db/migrations/.eslintrc.yaml, api/db/seeds/.eslintrc.yaml
L'utilisation de `knex.raw` pour effectuer des opérations SQL **sans** utiliser les bindings crée une faille de sécurité de type `SQL injection` [https://fr.wikipedia.org/wiki/Injection_SQL]().
Pour imposer le bon usage de la fonction `knex.raw`, une règle de linter est ajoutée.
C'est la règle `no-restricted-syntax` qui permet d'interdire le code spécifier par le sélecteur AST.
Tout appel à `knew.raw` avec un premier argument qui est une `template string` est interdit.
`knex.raw` est parfois utilisé avec une template string pour formatter sur plusieurs lignes une longue instruction SQL.
C'est uniquement le cas dans les `seeds` et les `migrations`.
La règle `no-restricted-syntax` est donc spécifiquement ignorée pour ces deux répertoires.
Un appel comme le suivant doit lever une erreur du …
=> [TECH] Ajout d'une règle de linter pour éviter les injections SQL

api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/unit/domain/usecases/correct-answer-then-update-assessment_test.js
L'utilisateur : 
- Il répond à l'épreuve. L’answer est enregistré mais aucun Knowledge-Element pour cette réponse.
- L’algorithme cherche sa prochaine épreuve :
-Les KE n’ayant pas été enregistré, les skills associés ne sont pas considérés comme vus
-L’algorithme propose à nouveau de testé le skill précédemment vu, et repropose donc la même épreuve
- L’utilisateur revoie la même épreuve
- Mais vu qu’il y a déjà répondu (on le sait via l’answer), l'épreuve est noté comme “Déjà Répondu”
- L’utilisateur voit qu’il a déjà répondu à cette épreuve, et on lui demande de Poursuivre
- Au moment de Poursuivre, l’algorithme repropose encore la même épreuve, et l’utilisateur est bloqué
- Pour savoir quels KE créés, ne prendre que ceux de l'assessment en cours et ignorer ceux des autres assessments. …
=> [BUGFIX] Des utilisateurs sont bloqués sur une épreuve. (PF-1187).

certif/app/controllers/authenticated/sessions/details/certification-candidates.js, certif/tests/acceptance/session-candidates-test.js, certif/tests/acceptance/session-finalization-test.js, certif/tests/test-helper.js
La notification d'erreur qui s'affiche lors de l'échec de l'ajout d'un candidat contient une phrase incorrecte. La phrase parle d'une opération de suppression, alors qu'il s'agit d'une opération d'ajout.
Correction du mot + renforcement des tests sur la vérification du contenu de la notification.
Le bonus : réduction du temps d'exécution des tests grâce à du bidouillage dans le service de notifications.
En effet, certains d'entre vous ont certainement constaté un rallongement pénible des tests d'acceptance provoquant l'affichage de la notification _**ember-cli-notification**_.
C'est dû à ce code-ci : ->
https://github.com/mansona/ember-cli-notifications/blob/master/addon/services/notifications.js#L73
On remarque l'ajout d'un délai dans la runLoop() de 500ms fixes.
En m'inspirant des …
=> [BUGFIX] Mauvaise notification d'erreur lors de l'échec de l'ajout unitaire de candidat sur PixCertif (PC-139)

certif/app/adapters/application.js, certif/app/adapters/certification-candidate.js, certif/app/adapters/certification-report.js, certif/app/adapters/session.js, certif/app/app.js, certif/app/components/login-form.js, certif/app/components/session-finalization-formbuilder-link-step.js, certif/app/components/session-finalization-reports-informations-step.js, certif/app/controllers/authenticated/sessions/details.js, certif/app/controllers/authenticated/sessions/details/certification-candidates.js, certif/app/controllers/authenticated/sessions/details/parameters.js, certif/app/controllers/authenticated/sessions/finalize.js, certif/app/controllers/authenticated/sessions/list.js, certif/app/controllers/authenticated/sessions/new.js, certif/app/controllers/authenticated/sessions/update.js, certif/app/routes/application.js, certif/app/routes/authenticated.js, certif/app/routes/authenticated/index.js, certif/app/routes/authenticated/sessions/details.js, certif/app/routes/authenticated/sessions/details/certification-candidates.js, certif/app/routes/authenticated/sessions/finalize.js, certif/app/routes/authenticated/sessions/list.js, certif/app/routes/authenticated/sessions/new.js, certif/app/routes/authenticated/sessions/update.js, certif/app/routes/login.js, certif/app/templates/authenticated/sessions/details/parameters.hbs, certif/app/templates/authenticated/sessions/list.hbs, certif/config/environment.js, certif/tests/acceptance/session-details-test.js, certif/tests/acceptance/session-list-test.js
La feature de finalisation de session dans PixCertif était soumise à feature toggle.
La feature est maintenant considérée comme stable, on retire donc le toggle.
- Retrait du toggle (+ ne pas oublier de le retirer dans les autres environnements + dans le template des PR)
- Application de quelques bonnes pratiques octane :
- Privilégier `init()` à `constructor()`
- Inutile d'initialiser des propriétés dans `init()` si c'est pour y mettre une valeur simple
- Transformation des Mixin en native classe qui étend d'un Mixin (sauf pour AppModal, c'était difficile)
- Renommage des classes. Dans le doute, à l'époque, j'avais donné un nom à rallonge aux classes car j'avais peur d'avoir des collisions sur les noms. En fait c'est pas possible.
La réf que @jonathanperret m'a transmis pour appliquer …
=> [INFRA] Retrait du feature toggle FT_IS_SESSION_FINALIZATION_ACTIVE (PC-137)

orga/tests/test-helper.js
Les tests d'acceptance sont rallongés à cause du temps de disparition de la notification ember-cli-notification.
C'est dû à ce code-ci : ->
https://github.com/mansona/ember-cli-notifications/blob/master/addon/services/notifications.js#L73
On remarque l'ajout d'un délai dans la runLoop() de 500ms fixes.
En m'inspirant des propositions réalisées dans l'issue mansona/ember-cli-notifications#111, je propose la modif suivante :
Réouvrir le service et surcharger la méthode removeNotification() en virant le délai. Cette modification est réalisée dans le fichier tests/test-helper.js
Chronométrer le temps d'exécution des tests PixOrga avant et après ;) ~20% de temps en moins.
=> [INFRA] Réduit le temps de disparition de la notification pendant les tests d'acceptance (PO-396)

orga/app/styles/pages/login.scss, orga/app/templates/login.hbs
Le logo sous IE de Pix Orga est déformé. 
En prenant exemple sur Pix Certif, on a ajouté une div et un `text-align: center` sur celle-ci.
=> [BUGFIX] Faire en sorte que le logo de Pix Orga ne soit pas déformé sous IE (PO-289).

orga/app/styles/pages/authenticated/team/list.scss
Sur Pix Orga l'affichage d'une équipe ne se fait pas correctement quand elle contient beaucoup de membre, l'utilisateur peut ne pas comprendre qu'il s'agit de la fin du tableau.
Ajouter un margin-bottom afin de voir la fin du tableau et donc comprendre que c'est la fin de la page.
=> [BUFIX] Problème d'affichage d'une équipe avec beaucoup de membres. (PO-323).

certif/app/styles/app.scss, certif/app/styles/pages/authenticated.scss, certif/app/styles/pages/authenticated/terms-of-service.scss, certif/app/styles/pages/login.scss
Un bloc blanc s'affiche sur certaines dimension lors de l'acceptation des cgu.
Redimensionner les heights du body, html qui ne prennaient pas toute la hauteur disponible. 
Adapter leurs enfants directs.
Il semblerait que IE ne supporte pas l'unité `vh` (https://caniuse.com/#search=vh), d'où l'ajout de `min-height: 100%` (il ne prendra pas en compte le `min-height: 100vh`; mais les autres browsers si).
1- Se loger sur certif avec un compte : certifsup@example.net, certifsco@example.net, certifpro@example.net. Redimensionner la page. Constater qu'il n'y a plus de bloc blanc. 
2- Finir de se loger. Constater que l'application n'a pas changé. 
3- Faire la même chose en changeant de navigateur (Chrome, IE 11 ...)
=> [BUGFIX] Ne pas afficher une bande blanche en bas des CGUs de PixCertif (PC-80)

admin/app/controllers/authenticated/sessions/session.js, admin/app/routes/authenticated/sessions/session.js, admin/app/templates/authenticated/sessions/session.hbs, admin/tests/acceptance/session-test.js
L'input de recherche d'un id de session n'est pas toujours en accord avec la valeur de l'id de session de la page affichée (présent notamment dans l'url)
Initialiser l'input à l'id de la session sur laquelle on est lors d'une transition / chargement d'une session.
1- Aller sur une page de détail d'une session (par exemple la session 4) : http://localhost:4202/sessions/4
2- Taper dans l'input de recherche un nouvel id (par exemple 5, pas besoin de valider).
3- Aller sur une autre session via la liste des sessions http://localhost:4202/sessions/list. Par exemple la 6 : constater que le champ est resté à 5 au lieu d'être à 6.
=> [BUGFIX] Numéro de session dans la barre de recherche incohérent avec la page affichée (PA-191)

orga/app/models/campaign.js, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs
Parfois, il est impossible de modifier ou archiver une campagne d'évaluation.
Corriger la computed property pour la faire observer les bons trucs.
Le bouton d'export est lui aussi affiché conditionnellement.
- Aller le voir le détail d'une campagne d'évaluation.
=> [BUGFIX] [EXPEDITE] Correction de l'affichage des boutons sur la page de détails d'une campagne (PO-402).

certif/app/styles/pages/authenticated.scss
La barre de menu ne prend pas toute la hauteur de l'écran.
Il semblerait que `display: flex;` sous IE provoque des soucis avec la height de l'enfant. Il faut donc mettre : `min-heigth: 100vh;` ou `min-height: inherit` pour ce dernier. 
https://stackoverflow.com/questions/26596813/internet-explorer-doesnt-honor-my-min-height-100-with-flexbox
Se connecter à Pix certif sous IE et cliquer sur une session pour afficher sa page de détails
=> [BUGFIX] Affichage menu sous IE (PC-140)

admin/app/adapters/organization-invitation.js, admin/app/components/organization-members-section.hbs, admin/app/controllers/authenticated/organizations/get.js, admin/app/models/organization-invitation.js, admin/app/styles/authenticated/organizations/get.scss, admin/app/templates/authenticated/organizations/get.hbs, admin/app/utils/email-validator.js, admin/mirage/config.js, admin/tests/acceptance/organization-memberships-management-test.js, admin/tests/integration/components/organization-members-section-test.js, admin/tests/unit/controllers/authenticated/organizations/get-test.js, admin/tests/unit/utils/email-validator-test.js
Le processus actuel d'ajout du premier utilisateur à une organisation est long et nécessite de nombreuses étapes qui ne sont pas couvertes par l'application Pix Admin. 
Il existe cependant, un processus d'invitation par email (présent uniquement dans Pix Orga) qui permet de réaliser ces opérations plus simplement. Il a donc été décidé d'ajouter un formulaire dans Pix Admin permettant d'envoyer des invitations à rejoindre une organisation. 
Le premier utilisateur à rejoindre un organisation possède automatiquement le rôle ADMIN. Les utilisateur suivants auront par défaut le rôle MEMBER (le rôle est modifiable depuis Pix Orga). 
- Aller sur la page de détail d'une organisation dans Pix Admin.
- Renseigner une adresse email dans le formulaire "Inviter un membre" et cliquer sur "Inviter".
- …
=> [FEATURE] Invitation à Pix Orga depuis Pix Admin (PA-96).

docs/CONTRIBUTING.md
Dans le `CONTRIBUTING.md` les conventions de nommage des commits et des branches ne sont pas à jour.
Il y a une page qui est à jour dans le wiki, mais ce wiki est privé. Les contributeurs risquent de soumettre des contributions ne respectant pas ces conventions, ce qui obligera à les leur communiquer une fois que le code sera déjà écrit (rework).
Déplacer l'information à jour du wiki privé dans le `CONTRIBUTING.md` public, faire pointer la page du wiki vers le `CONTRIBUTING.md`.
La page en question :
- https://1024pix.atlassian.net/wiki/spaces/DEV/pages/5669184/Conventions+de+nommage
=> [DOC] Mise à jour des conventions de nommage des commits et des branches

api/lib/domain/services/mail-service.js, api/lib/domain/services/organization-invitation-service.js, api/lib/infrastructure/mailers/SendinblueProvider.js, api/scripts/send-invitations-to-sco-organizations.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/services/organization-invitation-service_test.js, api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Dans Sendinblue, après l'envoie d'e-mails (générés par un script ad hoc cf. `api/scripts/send-invitations-to-sco-organizations.js`), on veut faciliter le suivi de ces e-mails envoyés en masse.
Le dashbord Sendinblue propose une propriété "tags".
Actuellement les services e-mail de l'API ne l'utilisent pas.
On va exploiter cette propriété dans le mailService de l'API, et l'utiliser dans `api/scripts/send-invitations-to-sco-organizations.js`.
=> [TECH] Catégoriser les envois d'e-mail en alimentant la propriété TAGS (PF-1213).

docs/CONTRIBUTING.md
En fusionnant les conventions de nommage du wiki et de `docs/CONTRIBUTING.md`, j'ai laissé deux sections parlant des conventions de message de commits 😞
Fusionner ces deux sections 🙂
=> [DOC] Corriger la section sur le nommage des commits

mon-pix/app/templates/components/user-certifications-detail-result.hbs
La PR #1151 a introduit un logo de badge sur la page de résultat de certification.
Supprimer ce logo.
Comme quoi les branches qui durent longtemps c'est mal 🙈
- Aller sur Pix Admin, publier la session 4
- Se connecter en tant que Anne Success
- Afficher le résultat de certification publié
- Vérifier qu'il n'y a pas de logo de badge
=> [BUGFIX] Supprime un logo de badge sur la page de résultat de certification

api/lib/domain/services/mail-service.js, api/lib/domain/services/organization-invitation-service.js, api/lib/infrastructure/mailers/SendinblueProvider.js, api/scripts/send-invitations-to-sco-organizations.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/services/organization-invitation-service_test.js, api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Les mails d'invitation ne s'envoient plus sur notre environnement d'intégration et les RA à jour.
Les mails de création de compte et de réinitialisation de mot de passe ne sont pas impactés.
On pense que l'erreur vient d'une modification sur les tags des mails, liée à la PF-1213
L'erreur remontée est visible dans Jira
=> BUGFIX - Revert PF-1213 - Réparer l'envoi des mails d'invitation - (PF-1219)

api/lib/application/answers/answer-controller.js, api/lib/application/answers/index.js, api/lib/domain/usecases/find-answer-by-assessment.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js, api/tests/acceptance/application/answers/answer-controller-find_test.js, api/tests/acceptance/application/assessments/assessment-controller-get_test.js, api/tests/unit/application/answers/index_test.js, api/tests/unit/domain/usecases/find-answer-by-assessment_test.js, api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js, mon-pix/app/routes/assessments/challenge.js, mon-pix/mirage/routes/answers/get-answer-by-challenge-and-assessment.js, mon-pix/tests/unit/routes/assessments/challenge-test.js
- Lorsqu'on reprend un assessment, il y a X appels à `/api/answers/:id` pour les X answers déjà enregistrés pour l'assessment
- Ajout d'une route pour récupérer toutes les answers d'un assessment
- Cette route est précisé dans ce que renvoie le back pour l'assessment
- On a voulu éviter ces appels en front
- Supprimer la barre de progression qui semblait chercher les answers n'a pas modifié le comportement
- Actuellement, nous ne voyons pas où sont demandés ces answers
- Lorsqu'on ajoute `{ async: false}` dans le model Assessment pour les Answers coté front, on a un message d'erreur nous indiquant qu'il a besoin des answers (même quand la barre de progression n'est plus présente).
- Commencer une compétence
- Répondre à 2/3 questions
- Quitter pix/ vider le cache
- Revenir et reprendre la …
=> [TECH] Ajout et utilisation d'une route pour récupérer toutes les answers (PF-1195).

api/lib/domain/models/Challenge.js, api/lib/domain/services/pick-challenge-service.js, api/lib/infrastructure/datasources/airtable/challenge-datasource.js, api/lib/infrastructure/repositories/challenge-repository.js, api/tests/acceptance/application/assessments/assessment-controller-get-next-challenge-locale-management.js, api/tests/tooling/airtable-builder/factory/build-challenge.js, api/tests/tooling/domain-builder/factory/build-challenge-airtable-data-object.js, api/tests/tooling/domain-builder/factory/build-challenge.js, api/tests/tooling/fixtures/infrastructure/challengeAirtableDataObjectFixture.js, api/tests/tooling/fixtures/infrastructure/challengeRawAirTableFixture.js, api/tests/unit/domain/models/Challenge_test.js, api/tests/unit/domain/services/pick-challenge-service_test.js, api/tests/unit/infrastructure/datasources/airtable/challenge-datasource_test.js
Actuellement un épreuve ne peut avoir qu'une seule langue (représentée colonne "Langue" dans Airtable). Or, on voudrait qu'une épreuve puisse en avoir plusieurs.
Par exemple, si une épreuve est ['Franco Français', 'Francophone'], on voudrait pourvoir y accéder à la fois depuis app.pix.fr et app.pix.digital.
1. Dans un premier temps, renommer la colonne de Airtable 'Langue' => 'Langue**s**' et changer son type pour avoir une liste
2. Il faut aussi adapter le choix de la question pour choisir une épreuve par rapport à ses langues et son point d'entrée (.fr ou .digital)
Sur la review app:
* En passant par https://app-pr1252.review.pix.fr on ne doit voir que des épreuves Franco Françaises dont les id (visibles dans l'URL) sont :
```
recq9fXA6JylP1FaI
recRuRbNVtaFGJ5fn
rec27USdd7UOQ1CTL …
```
=> [FEATURE] Rendre une épreuve multilangue (PF-1196)

orga/app/styles/globals/pix-modal.scss
Suite au ticket https://1024pix.atlassian.net/browse/PO-382#icft=PO-382, le design des loader dans Pix Orga avaient été cassé.  
Réparer le design des loader.
Suite au merge de la PR de design system dans Pix Orga, le design final n'est pas identique à celui qui existait avant.
=> [BUGFIX] Correction du design du loader dans Pix Orga (PO-413).

admin/app/components/organization-target-profiles-section.hbs
Suite à la PR https://github.com/1024pix/pix/pull/1254, le design du formulaire de rattachement de profils cibles a été cassé. 
Correction de l'affichage du formulaire.
=> [BUGFIX] Correction du design du formulaire de rattachement de profils cibles (PA-200).

api/lib/domain/models/Campaign.js, api/lib/domain/usecases/create-campaign.js, api/lib/domain/validators/campaign-validator.js, api/lib/infrastructure/repositories/campaign-repository.js, api/lib/infrastructure/repositories/user-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-serializer.js, api/lib/infrastructure/serializers/jsonapi/membership-serializer.js, api/lib/infrastructure/serializers/jsonapi/user-orga-settings-serializer.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/acceptance/application/users/users-controller-get-memberships_test.js, api/tests/integration/domain/usecases/create-campaign_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/tooling/domain-builder/factory/build-campaign.js, api/tests/tooling/domain-builder/factory/build-membership.js, api/tests/tooling/domain-builder/factory/build-user-orga-settings.js, api/tests/unit/application/campaign/campaign-controller_test.js, api/tests/unit/domain/usecases/create-campaign_test.js, api/tests/unit/domain/validations/campaign-validator_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-orga-settings-serializer_test.js, high-level-tests/e2e/cypress/fixtures/organizations.json, high-level-tests/e2e/cypress/integration/campaign-management.feature, orga/app/components/routes/authenticated/campaigns/new-item.js, orga/app/models/campaign.js, orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs, orga/mirage/config.js, orga/tests/acceptance/campaign-creation-test.js, orga/tests/helpers/test-init.js, orga/tests/integration/components/routes/authenticated/campaigns/new-item-test.js
On a ajouté un nouveau type de campagnes pour collecter des profils mais on ne pouvait pas en créer dans l'application
Rajouter le champ type de campagne dans le formulaire de création de campagnes
Seules les organisations avec canCollectProfiles à true peuvent créer ces campagnes
Il faut essayer de créer une campagne de type collecte de profils avec le compte pro@example.net.
Il faut vérifier qu'avec le compte sup@example.net on ne peut pas créer de campagnes de type collecte de profils.
=> [FEATURE] Créer des campagnes de type collecte de profils (PO-392).

mon-pix/app/services/current-domain.js, mon-pix/app/services/current-user.js, mon-pix/app/services/google-recaptcha.js, mon-pix/app/services/mail-generator.js, mon-pix/app/services/peeker.js, mon-pix/app/services/splash.js
Le passage à Ember Octane implique d'utiliser une syntaxe JS Native.
Utilisation du codemod associé
=> [CLEANUP] Convertir les services PixApp en syntaxe native (PF-1193).

admin/package-lock.json, admin/package.json, mon-pix/package-lock.json, mon-pix/package.json, orga/package-lock.json, orga/package.json
Dans la mire de connexion/inscription de Pix Orga (accessible depuis un lien d'invitation), lorsque l'on tente de créer un compte avec une adresse email déjà existante, le message d'erreur "Cette adresse e-mail est déjà enregistrée, connectez-vous." est censé s'afficher en dessous du label "Adresse e-mail". Malheureusement, ce message d'erreur n'est plus affiché ce qui empêche l'utilisateur de comprendre ce qu'il se passe.    
Après analyse, il a été constaté que cette disparition est survenue suite au passage d'Ember en version 3.15 sur Pix Orga et plus spécifiquement à la montée de version d'ember-data (une explications plus complète du problème est disponible dans la section "Remarques"). Ce problème a été corrigé par l'équipe d'ember-data à partir de la version 3.16.2. Par ailleurs, …
=> [BUGFIX] Ré-afficher les messages d'erreurs renvoyés par l'API (PO-414).

api/lib/domain/models/KnowledgeElement.js, api/lib/domain/models/Skill.js, api/lib/domain/models/Tube.js, api/lib/domain/services/smart-random/cat-algorithm.js, api/lib/domain/services/tube-service.js, api/lib/domain/usecases/find-tutorials.js, api/tests/unit/domain/models/Skill_test.js
Dans Airtable, le nom du Skill est par exemple `@sourceImage2` et le nom du tube correspondant est `@sourceImage`.
Or, en examinant dans model/Skill.js, actuellement on a:
```
get tubeName() {
return this.name.slice(1, -1); //avec le skill @sourceImage2, cette fonction retourne sourceImage
}
get tubeNameWithAt() {
return this.name.slice(0, -1); //avec le skill @sourceImage2, cette fonction retourne @sourceImage
}
```
Ce que retourne `get tubeName()` n'est donc pas le nom du tube, car le nom du tube devrait avoir un '@'.
`get tubeName` deviendrait `get tubeNameWithoutPrefix `
et `get tubeNameWithAt` deviendrait `get tubeName`
```
get tubeName() {
return this.name.slice(0, -1);  //avec le skill ' @sourceImage2', cette fonction retourne '@sourceImage'
}
get tubeNameWithoutPrefix() {
return …
```
=> [TECH] Renommer tubeName de Skill dans api

.circleci/config.yml, high-level-tests/e2e/cypress.json, high-level-tests/e2e/cypress/fixtures/certification-candidates.json, high-level-tests/e2e/cypress/fixtures/certification-center-memberships.json, high-level-tests/e2e/cypress/fixtures/certification-centers.json, high-level-tests/e2e/cypress/fixtures/certification-courses.json, high-level-tests/e2e/cypress/fixtures/sessions.json, high-level-tests/e2e/cypress/fixtures/users.json, high-level-tests/e2e/cypress/integration/pix-certif/certification-candidates-management.feature, high-level-tests/e2e/cypress/integration/pix-certif/certification-session-creation.feature, high-level-tests/e2e/cypress/integration/pix-certif/certification-session-finalization.feature, high-level-tests/e2e/cypress/integration/pix-certif/certification-session-update.feature, high-level-tests/e2e/cypress/integration/pix-certif/login-logout-certif.feature, high-level-tests/e2e/cypress/support/commands.js, high-level-tests/e2e/cypress/support/step_definitions/index.js, high-level-tests/e2e/cypress/support/step_definitions/login-logout.js, high-level-tests/e2e/cypress/support/step_definitions/pix-certif/session.js, high-level-tests/e2e/package.json
L'application PixCertif n'était pas encore couverte par des tests E2E sur Cypress. Ce qui est bien dommage, étant donné la faible quantité de features que présente pour le moment l'application.
De plus, de tels tests nous permettent d'apporter de la sérénité quant à la non-régression de features classiques/autoroutes.
On ajoute des tests E2E dans les cas les plus classiques PixCertif :
- Connexion / Déconnexion PixCertif
- Création/Modification d'une session
- Gestion de candidats dans la liste des inscrits à la session
- Finalisation d'une session
Je veux bien des conseils pour ceux qui connaissent cypress, ce sont mes premiers tests ;)
Laissez la CI vous porter !!
=> [TECH] Ajout de tests E2E Cypress sur PixCertif (PC-142)

high-level-tests/e2e/cypress/integration/user-tutorials.feature, high-level-tests/e2e/cypress/support/step_definitions/user-tutorials.js
La fonctionnalité d'enregistrement et de retrait de tutoriels n'est pas couverte par des tests end-to-end.
Ajouter des tests end-to-end sur cette fonctionnalité.
RAS
Lancer les tests cypress contenus dans le fichier `user-tutorials.feature`.
=> [CLEANUP] Ajout de tests end-to-end pour la fonctionnalité de sauvegarde de tutoriels

api/lib/application/assessments/assessment-controller.js, api/lib/domain/events/AssessmentCompleted.js, api/lib/domain/events/handle-certification-scoring.js, api/lib/domain/events/index.js, api/lib/domain/services/certification-result-service.js, api/lib/domain/usecases/complete-assessment.js, api/tests/unit/application/assessments/assessment-controller_test.js, api/tests/unit/domain/events/handle-certification-scoring_test.js, api/tests/unit/domain/usecases/complete-assessment_test.js
La logique de scoring de la certification (contexte "Certification") transpire dans celle de la completion de l'assessment (contexte "Evaluation") : les fonctions contenant cette logique se trouvent dans le usecase `complete-assessment` qui est déclenché sur tous les assessments (évaluation de compétence, campagne et certification).
Déplacer la logique de scoring de certification dans un *Event handler* qui réagit à l'évènement `AssessmentCompleted`.
Voir le dernier commit seulement.
Non régression sur la fin d'un parcours de certification.
=> [CLEANUP] Extraire la logique de scoring de certification dans un Event Handler dédié (PF-1202)

api/lib/domain/models/Scorecard.js, api/lib/domain/services/certification-result-service.js, api/lib/domain/services/scorecard-service.js, api/lib/domain/services/scoring/scoring-certification-service.js, api/lib/domain/services/scoring/scoring-service.js, api/lib/domain/services/user-service.js, api/lib/domain/usecases/correct-answer-then-update-assessment.js, api/lib/domain/usecases/get-assessment.js, api/lib/domain/usecases/get-scorecard.js, api/lib/domain/usecases/get-user-scorecards.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/domain/services/scoring/scoring-certification_test.js, api/tests/unit/domain/models/Scorecard_test.js, api/tests/unit/domain/services/scorecard-service_test.js, api/tests/unit/domain/services/scoring/scoring-service_test.js, api/tests/unit/domain/usecases/get-user-scorecards_test.js
- La façon dont on faisait nos arrondis/somme/minimum pour calculer le score en pix et le niveau par compétence était fait à différents endroits, pouvant entraîner des différences.
- Création du `scoringService` utilisé dans les différents endroits qui calcules des pix.
- Dans le cas des certifications, on souhaite pouvoir dépasser le nombre de pix actuel.
- Modification de la manière dont on vérifie les succès. Avant, on calculait le level et le nombre de pix, et on vérifiait par rapport au nombre de Pix sur les KE gagnés. Suite à un bug, il y avait des KE qui n'auraient pas dû être dans la liste qui sont apparu, et qui ont donc fait buggué les succès. Pour éviter cela, on réutilise le scorecardService.
- Sur le profile, dans les scorecard : le nombre de Pix et le niveau sont plafonnés
- …
=> [CLEANUP] Faire les calculs de score et de niveau à un seul endroit.

admin/app/components/login-form.js, certif/app/components/login-form.js, certif/tests/integration/components/login-form-test.js, orga/app/components/routes/login-form.js, orga/tests/acceptance/join-test.js, orga/tests/integration/components/routes/login-form-test.js
Bug suite à la montée de la version de ember-simple-auth dans pix-certif et pix-admin. 
Il concerne les messages d'erreurs liées à l'authentification dans pix-certif.
Peu importe l’erreur lors la connexion dans Pix Certif, je vois toujours le même message d’erreur unique: 'Le service est momentanément indisponible. Veuillez réessayer ultérieurement'.
La strutcture de l'objet error response qui stocke la réponse d'api à change.
Pour accéder aux errors, il faut maintenant passer par la propriété response.responseJson.errors.
=> [BUGFIX] Messages d'erreurs d'authentifications erronés dans pix-certif (PC-143)

api/lib/domain/validators/campaign-validator.js, api/tests/unit/domain/validations/campaign-validator_test.js, orga/app/components/routes/authenticated/campaigns/new-item.js, orga/app/routes/authenticated/students.js, orga/app/services/current-user.js, orga/app/styles/globals/forms.scss, orga/app/templates/components/routes/authenticated/campaigns/new-item.hbs, orga/app/templates/components/sidebar-menu.hbs, orga/tests/integration/components/routes/authenticated/campaigns/new-item-test.js, orga/tests/unit/services/current-user-test.js
Il y a beaucoup de questions et de frustrations des professeurs concernant le contenu des profils cibles.
Une vingtaine de retours nous a été fait, et certains professeurs au vu du manque d’information sur les contenus des parcours ont décidé de ne pas utiliser Pix.
Ajout d'un commentaire en dessous du choix de la liste des profils cibles pour les organisations SCO gérant des étudiants (`isManagingStudents === true`) uniquement avec un lien vers https://cloud.pix.fr/s/Rxm5kLR2dmFW7qq?path=%2FLes%20parcours%20dans%20Pix%20Orga.
En passant sur l'écran, certains messages d'erreur étaient en anglais.
De plus certains messages n'étaient jamais affichées.
Cette PR inclue également ces correctifs (premiers commits) 
Se connecter à une organisation de type SCO gérant des étudiants.
Se rendre sur …
=> [FEATURE] Ajout d'un commentaire en dessous des profils cibles lors de la création d'une campagne (PO-415).

orga/app/components/recommendation-indicator.js, orga/app/helpers/multiply.js, orga/app/helpers/sum.js, orga/app/styles/app.scss, orga/app/styles/components/recommendation-indicator.scss, orga/app/templates/components/recommendation-indicator.hbs, orga/tests/integration/components/recommendation-indicator-test.js, orga/tests/unit/helpers/multiply-test.js, orga/tests/unit/helpers/sum-test.js
Pix ne souhaite pas afficher le score de recommandation exact pour les sujets.
Afficher la recommandation sous forme de niveaux de recommandation (1 - 2 - 3 - 4) sous forme de bulles bleues.
Ce composant n'est pas utilisé pour l'instant mais le sera quand la recommandation arrivera côté front (User Story en cours).
Tirer la branche en local et afficher le composant n'importe où.
Cela ressemblera à ça :
=> [FEATURE] Ajout d'un composant pour représenter les différents niveaux de recommandation des sujets (PO-403).

orga/README.md, orga/app/styles/pages/authenticated/campaigns/list.scss, orga/app/templates/authenticated/campaigns/list.hbs
Sur IE, les campagnes ne sont pas affichées (page blanche).
Après investigation, c'est l'ajout d'un `onclick` sur les items de liste (balise `li`) qui entraine une erreur sur IE, rendant l'affichage de la page impossible.
Ne pas utiliser de `li` mais des `buttons`.
D'autre part, cela permet de naviguer au clavier ce qui améliore l'accessibilité de la page.
RAS
Ouvrir pix-orga avec IE (utiliser lambdatest dans un environnement non Windows).
Se connecter (par exemple avec `sup@example.net`)
Vérifier que la liste des campagnes est affichées.
Cliquer sur l'onglet `Archivées`.
La liste affiche les campagnes archivées.
Cliquer sur l'onglet `Actives`.
La liste affiche les campagnes actives.
=> [BUGFIX] Campagnes non affichées sur IE (PO-398).

admin/app/controllers/authenticated/tools.js, api/lib/application/cache/cache-controller.js, api/tests/unit/application/cache/cache-controller_test.js
On a un endpoint PATCH /api/cache qui lance le rechargement du cache, puis retourne null à l'appelant lorsque le traitement est terminé.
La durée de ce traitement dépasse le timeout de Scalingo, et la requête est retournée en erreur (le traitement dans api continue de tourner mais on a pas attendu la fin).
Retourner un 204 sans attendre la fin du traitement.
EDIT: Finalement, c'est un 202 qui est retourné
Sur pix admin, reloader le cache.
Une notification apparaît immédiatement pour indiquer que la demande a été prise en compte.
=> [TECH] Retourner une réponse 204 lors de l'appel de rafraichissement du cache

orga/app/styles/app.scss, orga/app/styles/pages/authenticated/campaigns/details/analysis/analysis-tab.scss, orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs
L'utilisateur va voit un indicateur sans réelle explication de comment il a été calculé par pix.
Ajouter un titre et une phrase d’explication au dessus de la liste des recommendations.
RAS
Se connecter à Pix Orga.
Se rendre sur le détail d'une campagne.
Ajouter `/analyse` à l'url pour afficher l'analyse de la campagne.
Une phrase d'explication des recommendations doit s'afficher au dessus du tableau de recommendations.
=> [FEATURE] Ajout d'informations sur la méthode de calcul des recommandations (PO-405).

orga/app/services/current-user.js, orga/tests/acceptance/switch-organization-test.js, orga/tests/helpers/test-init.js, orga/tests/unit/models/campaign-test.js
Récemment une régression a été introduite n'affichant pas correctement le menu "Élèves" lorsque l'on change d'une organisation ne manageant pas d'élèves vers une organisation en manageant et inversement.
Corriger la régression, ajouter un test qui vérifie cette non-régression.
Un .only trainait également, c'est enlevé (problème de linter ? 🤔)
1 - Aller sur une organisation non SCO
2 - Voir qu'il n'y a pas le menu "élèves"
3 - Changer d'organisation (sans changer d'utilisateur) vers une organisation SCO `isManagingStudents`
4 - Voir qu'il y a bien le menu "élèves"
Et inversement :
1 - Aller sur une organisation SCO
2 - Voir qu'il y a bien le menu "élèves"
3 - Changer d'organisation (sans changer d'utilisateur) vers une organisation non SCO
4 - Voir qu'il n'y a pas le menu "élèves"
=> [BUGFIX] Le menu "Élèves" ne s'affiche pas correctement lorsque l'on change d'organisation (PO-426).

api/lib/infrastructure/repositories/session-repository.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js
Le filtre sur la colonne ID de la liste des sessions paginée est un filtre "lâche" de type `LIKE %<value>%`.
Cela ne s'avère pas très pratique, car en général quand on recherche par id, on a un id fixe ( :laughing: ) et on se retrouve avec une liste de sessions qui comprend des résultats non voulus. Typiquement, sur une liste de 5000 sessions, si on souhaite rechercher la session d'ID 22, on se retrouve avec toutes les sessions dont l'id contient 22....
Une recherche stricte sur le champ ID dans la méthode de repo !
Sans parler du petit gain en perf sur cette recherche.... Une recherche sur un LIKE '%..%' c'est forcément en Scan séquentiel, alors que la recherche direct par ID en revanche... :+1: 
Connectez-vous sur PixAdmin via le compte PixMaster, et testez la recherche sur le champ ID …
=> [FEATURE] Appliquer une recherche stricte sur le filtre de la colonne ID dans la liste des sessions sur PixAdmin (PA-202)

admin/app/components/sessions/list-items.hbs, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js
Le pôle certification souhaite pouvoir lire la date d'envoi des résultats au prescripteur par session depuis la liste des sessions paginées sur PixAdmin
Ajouter la colonne !
Rendez-vous sur PixAdmin ETQ pixmaster@example.net pix123, puis sur la liste des sessions et constater l'apparition de la date pour les sessions dont les résultats ont été marqués comme envoyés au prescripteur. Pour mettre une session dans cet état là, rendez-vous sur la page de détails d'une session finalisée mais qui n'a pas encore de date d'envoi des résultats au prescripteur, cliquer sur le bouton **Résultats transmis au prescripteur** et constater l'apparition de la valeur dans la colonne appropriée sur la liste paginée.
=> [FEATURE] Ajout de la date de diffusion au prescripteur dans la liste des sessions sur PixAdmin (PA-189)

api/tests/acceptance/application/tutorials/user-tutorials-controller_test.js
Le test ``should respond with a 201 and return user-tutorial created`` ne passe pas si on le lance plusieurs fois sans rafraîchir la base. 
Il teste la valeur d'un id généré par une séquence. 
Bien que la table soit vidée après chaque test, la séquence n'est pas réinitialisée.
On teste la présence d'un id mais pas sa valeur elle-même. 
On pourrait continuer à tester la valeur de l'identifiant mais il faudrait pour cela réinitialiser la séquence ce qui nécessite une requête native PostgreSQL :
``return knex.raw('TRUNCATE TABLE "user_tutorials" RESTART IDENTITY');``
Lancer plusieurs fois le test sans relancer de db:reset
=> [TECH] Tester la présence d'un ID et pas sa valeur dans le test auto sur les tutos (PF-1244)

admin/app/adapters/session.js, admin/app/controllers/authenticated/sessions/session/informations.js, admin/app/models/session.js, admin/app/templates/authenticated/sessions/session/informations.hbs, admin/tests/acceptance/flag-results-sent-to-prescriptor-test.js, admin/tests/acceptance/session-test.js, admin/tests/integration/components/routes/authenticated/sessions/session-id/informations-test.js, admin/tests/unit/adapters/session-test.js, admin/tests/unit/controllers/authenticated/sessions/session/informations-test.js, api/db/migrations/20200327225551_add-column-assignedCertificationOfficerId-column-table-sessions.js, api/lib/application/sessions/index.js, api/lib/application/sessions/session-controller.js, api/lib/domain/models/Session.js, api/lib/domain/usecases/assign-certification-officer-to-session.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/session-repository.js, api/lib/infrastructure/serializers/jsonapi/session-serializer.js, api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/tooling/database-builder/factory/build-session.js, api/tests/tooling/domain-builder/factory/build-session.js, api/tests/unit/application/session/index_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/models/Session_test.js, api/tests/unit/domain/usecases/assign-certification-officer-to-session_test.js, api/tests/unit/domain/usecases/flag-session-results-as-sent-to-prescriber_test.js, api/tests/unit/infrastructure/serializers/jsonapi/session-serializer_test.js, certif/app/models/session.js
Un statut “Finalisée” a été implémenté pour permettre au pôle certif de savoir quelles sessions doivent être traitées et dans quel ordre (selon la date de finalisation de session).
Le pôle certif est composé de plusieurs membres, il faut donc qu’un membre du pôle puisse savoir lorsqu’une session est en cours de traitement chez un autre membre afin d'éviter que plusieurs personnes traitent la même session au même moment.
La solution se fait en 2 parties. Cette PR est la première partie :
Un bouton a été rajouté sur PixAdmin dans les informations d'une session afin de pouvoir s'assigner la session. 
Cette dernière passe donc au status "En cours de traitement" (uniquement sur Pix Admin, elle reste "finalisée" sur Pix Certif).
La partie 2 implémentera la possibilité de voir qui est assigné à …
=> [FEATURE] Pouvoir s'assigner une session à traiter dans PixAdmin (PA-137)

mon-pix/app/components/challenge-embed-simulator.js, mon-pix/app/styles/components/_challenge-embed-simulator.scss, mon-pix/app/templates/components/challenge-embed-simulator.hbs, mon-pix/tests/integration/components/challenge-embed-simulator-test.js
Tout est parti d'une initiative d'ajout de la gestion des refresh_token, côté back/API. Pour ce faire, il "suffit" d'ajouter une propriété `expires_in` ou `expires_at` dans le retour de l'appel d'obtention d'un `access_token` (cf. `POST /api/token`).
Il s'avère qu'il existe [un bug](https://github.com/simplabs/ember-simple-auth/issues/2019) dans la version de l'addon Ember-Simple-Auth (ESA pour les intimes) actuellement utilisée dans mon-pix (v2.1.1). Ce bug est corrigé dans la version (mlajeure) suivante (3.0.0).
Pour rappel, avant les montées de version successives des apps Ember (pre-3.13), nous utilisions ESA v1.8.2. Lors de la montée de version de Pix App sous Ember 3.15, nous avons commencé par effectuer la montée de version des différentes dépendances. Nous avons rencontré un …
=> [CLEANUP] Glimmerisation du composant pour gérer les simulateurs embarqués dans les épreuves (PF-1241).

high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature, high-level-tests/e2e/cypress/support/step_definitions/campaign.js, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/tests/acceptance/campaign-details-test.js, orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
La page d'analyse d'une campagne n'est pas accessible depuis l'interface utilisateur.
On ajoute d'une entrée Analyse dans la sous navigation de la page de détails d'une campagne.
Aller sur la page de détails d'une campagne et constater la présence d'un nouvel onglet.
=> [FEATURE] Ajout d'une entrée Analyse dans la sous navigation du détails d'une campagne (PO-407).

admin/app/routes/authenticated/certifications/certification.js, admin/tests/unit/routes/authenticated/certifications/certification-test.js, admin/tests/unit/routes/authenticated/sessions/session-test.js
Le champs de recherche des certifs dans admin n'est pas reinitialisé quand on change de certification. 
On souhaite qu'il contienne toujours l'identifiant de la certification courante
Passer au controller l'identifiant de la route ne cours
Cela ne correspond pas aux attentes UX. Cette solution est temporaire en attendant de trouver un affichage plus approprié de cet identifiant
1) Aucun ID affiché
> - dans Pix Admin, aller sur la liste des session et ouvrir une page de détails de session
> - cliquer sur l’onglet “Certifications” pour afficher la liste des certif de cette session
> - ouvrir la page de détails d’une des certif
> 
> Résultat attendu : l’ID de certif en question devrait être affiché dans la barre de recherche
2) Mauvais ID affiché
> - dans Pix Admin, cliquer sur le menu …
=> [FEATURE] afficher l id de certif dans le champ de recherche admin (PA-201)

api/lib/application/assessments/assessment-controller.js, api/lib/application/certification-courses/certification-course-controller.js, api/lib/domain/services/certification-challenges-service.js, api/lib/domain/services/scorecard-service.js, api/lib/domain/services/user-service.js, api/lib/domain/usecases/begin-campaign-participation-improvement.js, api/lib/domain/usecases/create-assessment-for-campaign.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/domain/usecases/start-campaign-participation.js, api/lib/domain/usecases/start-or-resume-competence-evaluation.js, api/lib/infrastructure/data/certification-course.js, api/lib/infrastructure/repositories/assessment-repository.js, api/lib/infrastructure/repositories/certification-challenge-repository.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/tests/integration/domain/services/user-service_test.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js, api/tests/integration/infrastructure/repositories/certification-course-repository_test.js, api/tests/unit/application/assessments/assessment-controller-save_test.js, api/tests/unit/application/certification-courses/certification-course-controller_test.js, api/tests/unit/domain/services/certification-challenges-service_test.js, api/tests/unit/domain/services/scorecard-service_test.js, api/tests/unit/domain/usecases/begin-campaign-participation-improvement_test.js, api/tests/unit/domain/usecases/create-assessment-for-campaign_test.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js, api/tests/unit/domain/usecases/start-campaign-participation_test.js, api/tests/unit/domain/usecases/start-or-resume-competence-evaluation_test.js
On souhaite éviter d'ajouter davantage de données incohérentes à la base de données en cas de ralentissements serveurs ou BDD. En effet, nous avons actuellement en BDD des certificationCourse sans challenges ou sans assessment. Nous souhaitons éviter cela à l'avenir.
Mise en transaction de la création du certification-course, de son assessment et de ses challenges.
=> [TECH] Mise en transaction de la création des éléments nécessaires à un test de certification (CertifCourse, assessment et challenges) (PF-1179)

api/lib/application/campaigns/index.js, api/lib/application/usecases/checkUserCanAccessCampaign.js, api/lib/interfaces/controllers/security-controller.js, api/tests/acceptance/application/security-controller_test.js, api/tests/integration/application/campaigns/index_test.js, api/tests/unit/application/usecases/checkUserCanAccessCampaign_test.js, api/tests/unit/interfaces/controllers/security-controller_test.js
Depuis Pix Orga, il est possible d'accéder au détail de toutes les campagnes en modifiant l'id de la campagne dans l'url.
Autoriser l'accès au détail d'une campagne uniquement pour les utilisateurs appartenant à l'organisation pour laquelle la campagne a été créée.
=> [BUGFIX] Restreindre l'accès au détail d'une campagne dans Pix Orga (PO-357). 

orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
Le résumé des résultats collectifs s'affiche comme ceci :
Corriger cet affichage.
- Cliquer sur l'onglet "Résultats collectifs" d'une campagne d'évaluation et voir que le résumé s'affiche correctement.
=> [BUGFIX] Affichage non correct du résumé des résultats collectifs de campagne d'évaluation (PO-432).

api/lib/domain/services/mail-service.js, api/lib/domain/services/organization-invitation-service.js, api/lib/infrastructure/mailers/SendinblueProvider.js, api/scripts/send-invitations-to-sco-organizations.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/services/organization-invitation-service_test.js, api/tests/unit/infrastructure/mailers/SendinblueProvider_test.js
Dans Sendinblue, après l'envoie d'e-mails (générés par un script ad hoc cf. api/scripts/send-invitations-to-sco-organizations.js), on veut faciliter le suivi de ces e-mails envoyés en masse.
Le dashbord Sendinblue propose une propriété "tags".
Actuellement les services e-mail de l'API ne l'utilisent pas.
On va exploiter cette propriété dans le mailService de l'API, et l'utiliser dans api/scripts/send-invitations-to-sco-organizations.js.
Cette implémentation intègre le correctif de la PF-1213.
=> [TECH][FIX] Catégoriser les envois d'e-mail en alimentant la propriété TAGS (PF-1242).

admin/app/components/user-detail-personal-information.hbs, admin/tests/integration/components/user-detail-personal-information-test.js
Les valeurs cgus dans la vue : détail utilisateur dans Pix Admin sont erronés.
Les templates sont basé sur "computed property" qui ont été supprimés.
Les tests passaient car ces computed ont été stub dans les tests et aussi non supprimé du template.
Dans la vue 'utilisateurs dans Pix Admin' , clique sur la ligne du tableau des utilisateurs pour afficher le détail.
=> [BUG] Propriétés cgus incorrects lors de l'affichage de détail utilisateurs.(PA-208)

admin/config/environment.js, admin/package.json, certif/config/environment.js, certif/package.json, mon-pix/config/environment.js, mon-pix/package.json, orga/config/environment.js, orga/package.json
Nous utilisons mal l'option `--proxy` de la commande `ember serve`.
L'option `--proxy` nécessite un argument : l'URL à utiliser comme proxy, seulement nous ne lui en fournissons pas. 
La commande marche en partie car juste le fait d'avoir l'option `--proxy` [permet de désactiver mirage](https://github.com/miragejs/ember-cli-mirage/blob/e4b94da31b84eecb0ed0903291a1b2894b3ca40b/config/environment.js#L6), mais le proxy lui [n'est pas actif car l'URL est vide](https://github.com/ember-cli/ember-cli/blob/00a63f2daf5e560558ae2aa41a7a704b31441af5/lib/tasks/server/middleware/proxy-server/index.js#L17).
- Ajouter `http://localhost:3000` comme argument à l'option de la commande 
- Suppression de la surcharge de la variable d'environnement `ENV.APP.API_HOST` en environnement de développement qui …
=> [TECH] Problème de script npm start en développement. 

api/lib/domain/usecases/get-session-certifications.js
La Laura du passé pensait avoir l'idée du siècle en faisant un morceau de code qui calcule les résultats de certification par tranche de 10 certifs afin d'éviter de bombarder le serveur BDD. La Laura du présent a appris que des `Promise.all` en cascade n'y changent rien, cela provoque toujours N promesses lancées dans le vent.
On remplace l'usage de `Promise.all` par `bluebird.mapSeries`
De la non-régression sur l'affichage des certifications d'une session éventuellement sur PixAdmin
=> [BSR] Remplacer Promise.all par bluebird.mapSeries lors de la génération des résultats de certification d'une session entière (PA-209)

api/package.json
Quand on lance l'API en tapant :
```
$ nodemon bin/www
```
À chaque changement de code `nodemon` arrête le processus en lui envoyant le signal `SIGUSR2`. Malheureusement comme expliqué dans #514 ce signal est aussi utilisé par le module `heapdump` et par conséquent à chaque tentative de redémarrage de `nodemon` on a un _dump_ qui est créé.
Si on utilise `npm run start:watch` l'option `--signal SIGTERM` est bien passée à `nodemon` pour éviter le problème en utilisant un autre signal. Mais on a parfois envie d'utiliser `nodemon` directement, par exemple pour lui passer l'option `--inspect` afin de pouvoir utiliser un débogueur.
Au lieu d'ajouter l'option `--signal` sur la ligne de commande de `start:watch` on ajoute une section `nodemonConfig` dans `package.json` avec une entrée `"signal": …
=> [TECH] Éviter de générer des _heap dumps_ lors de l'utilisation de `nodemon`

api/lib/domain/usecases/compute-campaign-participation-analysis.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/domain/usecases/compute-campaign-participation-analysis_test.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/test-helper.js, orga/app/templates/authenticated/campaigns/details/analysis.hbs, orga/app/templates/authenticated/campaigns/details/participants/participant/analysis.hbs, orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs, orga/mirage/config.js, orga/mirage/serializers/campaign-participation.js, orga/tests/acceptance/campaign-participants-individual-results-test.js, orga/tests/acceptance/campaign-participants-indivual-analysis-test.js, orga/tests/integration/components/routes/authenticated/campaigns/details/analysis-tab-test.js
On ne voit le score de recommandation de sujet pour un participant dans l'analyse de la campagne de participation.
Ajouter la colonne recommandation et calculer le score pour un participant.
Réutilisation des composants fronts utilisés dans l'analyse de campagne
Ajout de la gestion des résultats de campagne non partagés par un participant (tableau d'analyse vide et message associé)
Test de l'affichage des scores:
1. Se connecter `PIX ORGA`
2. Aller sur une campagne d'évaluation avec des participants
3. Cliquer sur un participant avec des résultats partagés
4. Ajouter `/analyse` dans l'URL
5. Vérifier que les scores sont correctement affichés et triés
Test de l'affichage des résultats non partagés:
1. Se connecter `PIX ORGA`
2. Aller sur une campagne d'évaluation avec des participants
3. …
=> [FEATURE] Ajout de la recommandation pour un participant à une campagne (PO-422)

api/lib/domain/models/CampaignAnalysis.js, api/lib/domain/models/CampaignTubeRecommendation.js, api/lib/domain/usecases/compute-campaign-analysis.js, api/lib/domain/usecases/compute-campaign-participation-analysis.js, api/lib/infrastructure/repositories/tutorial-repository.js, api/lib/infrastructure/serializers/jsonapi/campaign-analysis-serializer.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/acceptance/application/campaign-participations/campaign-participations-controller-analyses_test.js, api/tests/integration/domain/usecases/compute-campaign-analysis_test.js, api/tests/integration/domain/usecases/compute-campaign-participation-analysis_test.js, api/tests/tooling/domain-builder/factory/build-campaign-tube-recommendation.js, api/tests/unit/infrastructure/repositories/tutorial-repository_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-analysis-serializer_test.js, high-level-tests/e2e/cypress/integration/pix-orga/campaign-management.feature, high-level-tests/e2e/cypress/support/step_definitions/campaign.js, orga/app/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row.js, orga/app/models/campaign-tube-recommendation.js, orga/app/models/tutorial.js, orga/app/styles/app.scss, orga/app/styles/components/recommendation-indicator.scss, orga/app/styles/globals/tables.scss, orga/app/styles/pages/authenticated/campaigns/details/analysis/tube-recommendation-row.scss, orga/app/templates/components/routes/authenticated/campaigns/details/analysis-tab.hbs, orga/app/templates/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row.hbs, orga/config/environment.js, orga/tests/integration/components/routes/authenticated/campaigns/details/analysis/tube-recommendation-row-test.js
Le prescripteur ne voit pas quel resource il peut fournir pour aider à améliorer les acquis des sujets les plus recommandés
Pour chaque sujet, proposer de voir les tutoriels le plus pertinents à travailler pour s'améliorer.
L'affichage des tutoriels par sujet fonctionne pour:
1. Les analyses collectives de campagne
2. Les analyses de campagne par participant
Cela a été résolu "automatiquement" grâce à l'utilisation de routes, modèles et de composants pour les 2 types d'analyse.
**Test d'une analyse collective de campagne :**
1. Se connecter sur pix-orga
2. Aller sur une campagne
3. Cliquer sur l'onglet "analyse"
4. Cliquer sur le chevron d'un sujet pour afficher les tutoriels recommandés
**Test d'une analyse de campagne par participant :**
1. Se connecter sur pix-orga
2. Aller sur une …
=> [FEATURE] Affichage des tutoriels par sujets dans l'analyse de campagne (PO-408).

api/lib/application/assessments/assessment-controller.js, api/lib/domain/events/CertificationScoringCompleted.js, api/lib/domain/events/handle-badge-acquisition.js, api/lib/domain/events/handle-certification-partner.js, api/lib/domain/events/handle-certification-scoring.js, api/lib/domain/events/index.js, api/lib/domain/models/CertificationPartnerAcquisition.js, api/lib/domain/usecases/complete-assessment.js, api/lib/infrastructure/DomainTransaction.js, api/lib/infrastructure/repositories/assessment-repository.js, api/lib/infrastructure/repositories/assessment-result-repository.js, api/lib/infrastructure/repositories/badge-acquisition-repository.js, api/lib/infrastructure/repositories/certification-challenge-repository.js, api/lib/infrastructure/repositories/certification-course-repository.js, api/lib/infrastructure/repositories/certification-partner-acquisition-repository.js, api/lib/infrastructure/repositories/competence-mark-repository.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/badge-acquisition-repository_test.js, api/tests/unit/application/assessments/assessment-controller_test.js, api/tests/unit/domain/events/handle-badge-acquisition_test.js, api/tests/unit/domain/events/handle-certification-partner_test.js, api/tests/unit/domain/events/handle-certification-scoring_test.js, api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js, api/tests/unit/domain/usecases/complete-assessment_test.js, docs/adr/0009-transaction-metier.md
La certification Clea doit pouvoir être obtenue en fonction de critères précis.
Implémentation de la “zone rouge” => un candidat ayant son badge Pix Emploi et ayant obtenu sa certif Pix avec un taux de repro <= 50% n'obtient pas sa certif Cléa.
Pas de changement visible (suite zone verte pas de certif pour repro < 80%).
Les changements métier sont très légers. On profite de ce ticket pour 
- ajouter les transactions métiers
- ajouter une `DomainTransaction` vide comme valeur par défaut pour les repos
- déplacer la logique depuis le handler vers l'objet métier `CertificationPartnerAcquisition`
ℹ️L'utilisateur no. 106 `certif1@example.net` généré par les seeds a obtenu le badge Pix Emploi.
=> [FEATURE] Certif clea zone rouge (PF-1147)

admin/app/components/sessions/list-items.hbs, admin/app/controllers/authenticated/sessions/list.js, admin/app/routes/authenticated/sessions/list.js, admin/app/templates/authenticated/sessions/list.hbs, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js, api/db/seeds/data/certification/certification-sessions-builder.js, api/lib/domain/usecases/find-paginated-filtered-sessions.js, api/lib/domain/validators/session-validator.js, api/lib/infrastructure/repositories/session-repository.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js, api/tests/unit/domain/validations/session-validator_test.js
Toujours dans l'objectif final de permettre au pôle certif de se passer de l'usage d'un google sheet afin de faire un suivi du traitement des sessions de certif, on cherche à rendre la liste des sessions paginées sur PixAdmin manipulable et exploitable selon l'usage du pôle certif.
Les membres du pôle certif ont besoin de pouvoir rapidement visualiser et filtrer les sessions selon :
1) Le statut
2) Selon si les résultats ont été envoyés au prescripteur ou pas
Ajouter deux menus déroulants sous chaque colonne correspondante
Se balader dans PixAdmin et jouer avec les filtres positionnés sur la liste des sessions paginées
=> [FEATURE] Ajouter des filtres concernant le statut et l'envoi des résultats au prescripteur sur la liste des sessions paginées (PA-205)

high-level-tests/e2e/cypress/integration/pix-app/campaign-assessment.feature, high-level-tests/e2e/cypress/integration/pix-app/campaign-collect-profiles.feature, mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs, mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Les codes campagnes correspondent à la fois à des campagnes d'évaluation et de collecte de profiles, mais le wording de la page de saisi n'a pas été changé et n'est donc plus cohérent.
Changer le wording de la page de saisi de code pour que le message puisse convenir autant pour une campagne de type parcours de test ou a des campagnes de collectes de profil.
RAS
Se connecter sur pix app.
Cliquer sur "Parcours"
Vérifier que le texte de la page a été changé et est valide pour les campagnes d'évaluation et de collecte de profiles.
=> [FEATURE] Changement du wording de la page de saisi de code (PF-1227).

admin/app/components/certification-centers/list-items.hbs, admin/app/components/organizations/list-items.hbs, admin/app/components/sessions/list-items.hbs, admin/app/components/users/list-items.hbs, admin/app/controllers/authenticated/certification-centers/list.js, admin/app/controllers/authenticated/organizations/list.js, admin/app/controllers/authenticated/sessions/list.js, admin/app/controllers/authenticated/users/list.js, admin/app/templates/authenticated/certification-centers/list.hbs, admin/app/templates/authenticated/organizations/list.hbs, admin/app/templates/authenticated/sessions/list.hbs, admin/app/templates/authenticated/users/list.hbs, admin/config/environment.js, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js, admin/tests/unit/controllers/authenticated/certification-centers/list-test.js, admin/tests/unit/controllers/authenticated/organizations/list-test.js, admin/tests/unit/controllers/authenticated/sessions/list-test.js, admin/tests/unit/controllers/authenticated/users/list-test.js, admin/tests/unit/routes/authenticated/certification-centers/list-test.js, admin/tests/unit/routes/authenticated/organizations/list-test.js, admin/tests/unit/routes/authenticated/sessions/list-test.js, admin/tests/unit/routes/authenticated/users/list-test.js
Lorsque, dans une liste avec filtres, on a des champs de recherche, il est commode d'attendre un peu de temps après saisie dans les champs de recherche afin de ne pas envoyer une requête par touche de clavier frappée.
La volonté de mettre un tel temps d'attente était bien présente dans les listes paginées sur PixAdmin, mais n'était malheureusement pas fonctionnel.
Le code en place pour debounce correctement marchait bien, jusqu'à la mise à jour vers _Ember Octane_ sur **PixAdmin**.
Mise en place :
Deux choses à savoir pour la suite. D'une part, c'est le controller qui porte les `queryParams`. De fait, dès lors qu'un attribut marqué comme étant `queryParam` est modifié, il déclenche le lancement de la requête XHR avec les filtres appropriés. D'autre part, les champs input permettant à …
=> [BUGFIX] Le temps d'attente (debounce) avant de lancer une requête de recherche ne marchait pas dans les listes paginées sur PixAdmin (PA-206)

api/lib/domain/services/campaign-csv-export-service.js, api/lib/domain/usecases/index.js, api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js, api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js, api/tests/integration/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js, api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
L'utilisation d'une collection contenant des objets `{ title: '', property: '' }` nous a semblé compliqué pour générer les csv. On pense qu'il est possible de simplifier ce code en utilisant des tableaux.
On a réussi à supprimer l'utilisation de ces collections pour des simples tableaux. De fil en aiguille nous avons migré le code vers un objet `CsvLine` pour la génération du contenu. On pourrait aller plus loin encore mais on pense que dans l'état le code est plus maintenable. Il faudrait faire la même évolution pour les campagnes de types collecte de profils.
=> [TECH] Simplification de la génération de CSV de campagne d'évaluation (PO-427).

mon-pix/app/styles/components/_navbar-burger-menu.scss, mon-pix/app/templates/components/navbar-burger-menu.hbs, mon-pix/app/templates/components/navbar-desktop-header.hbs, mon-pix/app/templates/components/navbar-mobile-header.hbs, mon-pix/tests/acceptance/navigation-test.js, mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js, mon-pix/tests/acceptance/start-campaigns-with-type-collect-profiles-test.js, mon-pix/tests/integration/components/navbar-burger-menu-test.js, mon-pix/tests/integration/components/navbar-desktop-header-test.js
Il y a des codes qui permettent de faire des collectes de profils mais le wording propose de participer à un parcours.
Changer le wording de l'item.
RAS
Se connecter à PIX app et voir que le menu à changé ( mobile et web).
=> [FEATURE] Renommer et déplacer l'entrée vers la page de saisie de code depuis le menu de PIX App (PF-1226).

mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
La formulation de la page d'identifiant externe n'est plus adaptée aux campagnes de collecte de profils.
Revoir la formulation.
NA
- Rejoindre une campagne à laquelle il est nécéssaire de remplir l'identifiant externe (AZERTY123) ;
- Passer la page de présentation ;
- Voir la page de d'identifiant externe.
=> [FEATURE] Ajuster la formulation de la page d'identifiant externe (PIX-564).

api/lib/application/user-orga-settings/index.js, api/lib/application/user-orga-settings/user-orga-settings-controller.js, api/lib/domain/usecases/create-or-update-user-orga-settings.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/user-orga-settings-repository.js, api/tests/acceptance/application/user-orga-settings-controller_test.js, api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js, api/tests/unit/application/user-orga-settings/index_test.js, api/tests/unit/application/user-orga-settings/user-orga-settings-controller_test.js, api/tests/unit/domain/usecases/create-or-update-user-orga-settings_test.js, orga/app/adapters/user-orga-setting.js, orga/app/components/user-logged-menu.js, orga/app/services/current-user.js, orga/mirage/config.js, orga/tests/unit/adapters/user-orga-setting-test.js
Lorsqu'un un utilisateur rejoint Pix Orga pour la première fois, on lui créé des paramètres utilisateurs : `user-orga-settings`, qu'on créé grâce à la route `POST /user-orga-settings`.
Un `user-orga-settings` est construit avec un `userId` et un `organisationId`. Il y a une contrainte d'unicité sur l'`userId`, car l'utilisateur n'a qu'un seul tuple de paramètre qu'on met à jour si besoin avec `PATCH /user-orga-settings`.
Seulement, on peut voir que presque tous les jours, nous avons des erreurs qui remontent de violation de contraintes d'unicité dont la plupart à cause de cette table `user-orga-settings`. 
Cette erreur est reproductible en ouvrant deux onglets de Pix Orga avec un nouveau compte, lorsqu'on arrive sur la page CGU, on voit dans le network de chaque onglet qu'une requête …
=> [TECH] Eviter les erreurs de contraintes d'unicité. 

orga/app/controllers/authenticated/campaigns/list.js, orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs, orga/app/templates/components/search-input.hbs, orga/config/environment.js, orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Il s'agit du même problème que sur PixAdmin, à savoir que depuis la montée de version vers EmberOctane, le debounce mis en place pour éviter le spam de requêtes ne marche plus.
L'explication + complète est ici : https://github.com/1024pix/pix/pull/1320 dans la description de la PR.
Mais grossièrement, deux facteurs :
1) Le `controller` lié à la page de liste des campagnes n'hérite plus d'EmberObject mais est une classe native JS. Du coup, plus besoin de passer par la méthode `set()` pour déclencher tous les `listeners` qui observent la variable mise à jour
2) L'input utilisé pour mettre en place le filtre sur le nom est un built-in component Ember <Input>, qui est two-way bindé. Ce qui veut dire que lorsque qu'on modifie la valeur du champ input ça modifie également la valeur bindée au …
=> [BUGFIX] Le temps d'attente d'envoi de requêtes mis en place lors de la recherche de campagnes par nom dans PixOrga ne marche plus (PO-440)

orga/app/controllers/authenticated/campaigns/list.js
Pour le reproduire :
- Aller sur la liste paginée des campagnes dans PixOrga (sur intégration ou une autre RA)
- Taper 'ezgjergbezfin' (_whatever_ en somme) dans la recherche par nom, pour n'obtenir aucun résultat lors de la recherche
- Effacer le contenu en appuyant en continu sur la touche **Backspace** sur clavier et être attentif à l'affichage
- On devrait constater l'apparition FURTIVE de la page qui s'affiche lorsqu'il n'existe aucune campagne et qu'on est invité à créer la toute première campagne de l'orga.
C'est dû au `computed` suivant dans le `controller` de la liste des campagnes :
```js
@computed('name', 'hasNoCampaign')
get displayNoCampaignPanel() {
return this.hasNoCampaign && isEmpty(this.name) && isEmpty(this.status) && isEmpty(this.creatorId);
}
```
La mise en place de …
=> [BUGFIX] Affichage défectueux lorsqu'on supprime rapidement un filtre sur nom dans la liste des campagnes (PIX-583)

admin/app/components/sessions/list-items.hbs, admin/app/models/session.js, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js, admin/tests/unit/models/session-test.js
A l'origine, la présence de cette colonne dans la googleSheet du pôle certification leur permettait de faire des stats (vu que googleSheet c'est un tableur, c'était facile).
Du coup, l'apparition de cette colonne dans PixAdmin n'a pas grand intérêt, d'autant que le besoin de réaliser cette statistique a été rempli via l'élaboration d'une requête sur Metabase.
On la supprime !
Constater la disparition de la colonne
=> [FEATURE] Retrait de la colonne "Nombre de certifications publiées" dans la liste des sessions de PixAdmin (PIX-566).

api/lib/infrastructure/utils/CampaignAssessmentCsvLine.js, api/tests/unit/domain/usecases/start-writing-campaign-assessment-results-to-stream_test.js
Certaines campagnes n'ont pas d'id externe.
L'export CSV de campagnes d'évaluation actuel ne met pas l'entête `id externe` mais exporte une donnée `NA`.
Cela entraîne un décalage entre les entêtes et les données.
Ne pas ajouter la donnée `NA` pour les campagnes d'évaluation sans id externe.
RAS
Exporter une campagne d'évaluation sans id externe.
Vérifier qu'il n'y a pas de décalage entre les entêtes et les données.
=> [BUGFIX] Export CSV d'une campagne, ne pas mettre l'id externe quand la campagne n'en a pas (PIX-592).

api/lib/application/sessions/index.js, api/lib/application/user-orga-settings/index.js, api/lib/application/users/index.js, api/lib/domain/models/CertificationCandidate.js, api/lib/domain/models/CompetenceMark.js, api/tests/acceptance/application/session/session-controller-create-certification-candidate-participation_test.js, api/tests/acceptance/application/session/session-controller-patch-user-assignment_test.js, api/tests/acceptance/application/session/session-controller-put-results-sent-to-prescriber_test.js, api/tests/unit/application/session/index_test.js
Sentry remontait régulièrement une erreur (https://sentry.io/organizations/pix/issues/1447539303/?project=1398749&query=is%3Aunresolved) indiquant : 
`select "certification-candidates".* from "certification-candidates" where "sessionId" = $1 and LOWER($2)=LOWER("firstName") and LOWER($3)=LOWER("lastName") and "birthdate" = $4 - invalid input syntax for integer: "2.1"`
Ce problème remonte car l'ID de session reçu par l'API peut être autre chose qu'un Integer
- Utiliser la validation Joi sur la route qui pose problème
- Vérifier que l'id est bien un nombre et un entier. 
- Les vérifications existantes utilisaient souvent `Joi.number()` seulement. Malheureusement, cela laisse passer les id comme "2.1". L'ajout de `.integer()` permet de préciser que l'on souhaite un entier
=> [TECH] Utiliser .integer() sur les validations d'ID (PIX-591).

docs/CONTRIBUTING.md
Le tag de PR `BUGFIX` comporte la restriction "hors itération", qui n'est pas utile à mon sens :
> PR relative à une correction d'un bug (hors itération)
Supprimer cette restriction pour ce tag :
> PR relative à une correction d'un bug
=> [DOC] Met à jour la description du tag de PR `BUGFIX`

mon-pix/app/router.js, mon-pix/app/routes/terms-of-service.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/pages/_terms-of-service.scss, mon-pix/app/templates/terms-of-service.hbs, mon-pix/tests/acceptance/terms-of-service-test.js
Les conditions d'utilisations de Pix App ont évolués. Il faut donc les faire accepter par les utilisateurs.
Une nouvelle page qui va informer l'utilisateur de valider les nouvelles conditions d'utilisations.
Les conditions sont affichées sous forme de redirection vers un lien vers Prismic.
Cette PR ne concerne que la partie graphique. Un autre PR va suivre pour enrichir la partie navigation.
Aller vers la nouvelle route {Pix App url}/cgu
=> [FEATURE] Création d'une page pour afficher la nouvelle version des cgus Pix. (PF-998)

mon-pix/app/components/routes/login-form.js, mon-pix/tests/integration/components/routes/login-form-test.js
La gestion du mot de passe à usage unique ne fonctionne sur la double mire de connexion.
Rajouter la gestion du mot de passe à usage unique sur la double mire de connexion.
=> [FEATURE] Ajout de la gestion du mot de passe à usage unique sur la double mire (PF-1216).

orga/app/templates/components/pagination-control.hbs
Actuellement, des appels trop long pour afficher la page de résultats des campagnes font planter des containers. Une solution est à l'étude pour éviter que ces appels soient trop long/trop lourd. 
En attendant la solution finale, je propose d'éviter la pagination à 100 utilisateurs, qui est souvent celle choisit sur les requêtes qui ne finissent pas coté API.
Ceci n'est pas une correction pour le moment, c'est juste pour éviter la casse.
=> [FEATURE] Retirer la pagination à 100 sur les participations aux campagnes (PIX-594).

high-level-tests/e2e/package.json
La PR #1326 a affiné notre utilisation de `npm start` en développement mais les commandes de lancement automatique de cypress sont devenues obsolètes. 
Ajouter le localhost aux composants des commandes de lancement automatique dans cypress.
Lancer les tests cypress en utilisant notamment la commande `npm run cy:test:open:local`
=> [INFRA] Corriger le démarrage des apps pour les tests Cypress en local (PIX-596).

mon-pix/app/templates/campaigns/loading.hbs
Quand on démarre une campagne de collecte de profil on a le texte suivant dans le loader:
"Test en cours de chargement..." ce qui n'est pas correct pour une campagne de collecte de profil.
Mettre le même texte pour les campagnes de collecte de profil et d'évaluation dans la loader:
"En cours de chargement..."
Dans Pix-app saisir le code de campagne d'évaluation AZERTY123
> Le loader apparaît avec le texte "En cours de chargement..."
Dans Pix-app saisir le code de campagne d'évaluation SNAP123
> Le loader apparaît avec le texte "En cours de chargement..."
=> [FEATURE] Changer le texte du loader de campagne dans pix-app  (PIX-572)

mon-pix/app/controllers/campaigns/fill-in-campaign-code.js, mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs, mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js, mon-pix/tests/unit/controllers/campaigns/fill-in-campaign-code-test.js
Les messages d'erreur à la saisie de code de campagne ne sont pas adaptés aux campagnes de collecte de profils
Modifier les messages d'erreur à la saisie de code pour qu'il soit valable pour les 2 types de campagnes.
Dans Pix-app 
1. Ne pas saisir de code
> Le message "Veuillez saisir un code." apparait
2. Saisir un mauvais code
> Le message "Votre code est erroné, veuillez vérifier ou contacter l'organisateur." apparait
3. Saisir le code de campagne d'évaluation AZERTY123
> La campagne se lance
4. Saisir le code de campagne de collecte de profils SNAP123
> La campagne se lance
=> [FEATURE] Changer les messages d'erreur à la saisie de code campagne (PIX-573).

orga/app/components/sidebar-menu.js, orga/app/models/organization.js, orga/app/templates/components/sidebar-menu.hbs, orga/tests/integration/components/sidebar-menu-test.js
Les utilisateurs d'organisations pro disposent d'une documentation cependant elle n'est pas accessible depuis PixOrga.
Ajout d'un lien vers la documentation dans la sidebar pour les utilisateurs d'organisations pro.
Se connecter avec l'utilisateur `pro@example.net` et constater la présence d'un lien vers la documentation en bas de la sidebar.
=> [FEATURE] Ajout d'un lien vers la documentation pour les utilisateurs d'organisations pro (PIX-565).

mon-pix/app/components/resume-campaign-banner.js, mon-pix/app/templates/components/resume-campaign-banner-assessment.hbs, mon-pix/app/templates/components/resume-campaign-banner-collect-profile.hbs, mon-pix/app/templates/components/resume-campaign-banner.hbs, mon-pix/tests/acceptance/profile-test.js, mon-pix/tests/integration/components/resume-campaign-banner-test.js, mon-pix/tests/unit/components/resume-campaign-banner-test.js
Quand un utilisateur n'a pas envoyé son profil pour une collecte de profil, il voit une bannière spécifique au campagne d'évaluation.
Faire un bannière dédié à la campagne de collecte de profil avec la phrase suivante:
> N'oubliez pas de finaliser votre envoi !
On en profite pour rendre les phrases des campagnes d'évaluation semblable à la phrase des collectes de profils: 
- Pour une campagne d'évaluation sans titre:
> N'oubliez pas de finaliser votre envoi !
- Pour une campagne d'évaluation avec titre:
> Parcours TITRE DU PARCOURS terminé. N'oubliez pas de finaliser votre envoi !
1. Se connecter sur mon pix
2. Démarrer une campagne de collecte (code: SNAP123)
3. Cliquer sur "c'est parti"
4. Revenir sur la page principal de mon pix
5. La bannière apparait avec "N'oubliez pas de finaliser …
=> [FEATURE] Ajout d'une bannière spécifique à l'envoi de profil (PIX-568).

mon-pix/app/styles/components/_navbar-desktop-header.scss, mon-pix/app/styles/components/_user-logged-menu.scss, mon-pix/app/styles/pages/_fill-in-campaign-code.scss
Suite au changement de la navigation de pix app (ajout du bouton `J'ai un code`), certaines marges ne respectent pas la maquette.
Modifier les marges comme demandé par @QuentinChapelain-ui .
Cette PR est le renommage avec le numéro JIRA de cette PR : https://github.com/1024pix/pix/pull/1352.
**Capture d'écran avant**
**Capture d'écran après**
Se rendre sur pix app et vérifier les margins, tels que mentionnées dans le ticket.
> margin entre logo Pix et marianne de 24px et non 16
> margin entre le logo Marianne et label “profil” 88 px
> margin entre les labels de la nav de 40 px margin de 40 px entre « Aide » et j’ai un code margin entre saisissez un code et sous-titre ” Ce code...” de 32 px
> margin entre le code de saisie et le bouton de 16px
=> [FEATURE] Mise à jour de l'apparence du bouton "J'ai un code" (PIX-595).

admin/app/components/sessions/list-items.hbs, admin/app/controllers/authenticated/sessions/list.js, admin/app/routes/authenticated/sessions/list.js, admin/app/templates/authenticated/sessions/list.hbs, admin/app/templates/components/pagination-control.hbs, admin/mirage/factories/session.js, admin/mirage/handlers/find-paginated-and-filtered-sessions.js, admin/tests/acceptance/sessions-list-test.js, admin/tests/integration/components/routes/authenticated/sessions/list-items-test.js, admin/tests/unit/controllers/authenticated/sessions/list-test.js, admin/tests/unit/routes/authenticated/sessions/list-test.js, api/lib/domain/usecases/find-paginated-filtered-sessions.js, api/lib/domain/validators/session-validator.js, api/lib/infrastructure/repositories/session-repository.js, api/tests/integration/infrastructure/repositories/session-repository_test.js, api/tests/unit/domain/usecases/find-paginated-filtered-sessions_test.js, api/tests/unit/domain/validations/session-validator_test.js
Toujours dans l'optique de faire de PixAdmin l'outil exclusif servant au traitement des sessions de certification pour le pôle certification.
Ils ont besoin de pouvoir filtrer par nom de centre de certification.
On ajoute un champ de saisie sur la colonne "Centre de certification". La recherche est insensible à la casse et est de type `LIKE %<value>%`
On en profite pour bien renforcer les tests d'acceptance sur la liste paginée des sessions.
Rendez-vous sur PixAdmin, dans la liste des sessions de certifs. Essayez des combinaisons de différentes casses sur la recherche par centre de certification
=> [FEATURE] Ajout d'un filtre sur la colonne "Centre de certification" dans la liste des sessions paginée sur PixAdmin (PA-210)

mon-pix/app/components/routes/register-form.js, mon-pix/app/controllers/campaigns/join-restricted-campaign.js, mon-pix/tests/integration/components/routes/register-form-test.js, mon-pix/tests/unit/controllers/campaigns/join-restricted-campaign-test.js
Au vu de l'arrivée des campagnes de collecte de profils, nous ne pouvons plus utiliser le terme parcours dans les pages de réconciliation.
Supprimer le terme parcours des messages d'erreurs présent sur les pages de réconciliation.
=> [FEATURE] Supprime le terme parcours des messages d'erreurs des pages de réconciliation (PIX-582).

mon-pix/app/routes/assessments/challenge.js
Depuis que le titre est dans l'objet Assessment, sur la page Challenge l'objet campaign n'est plus utilisé
Supprimer l'afterModel concerné.
Cela permet d'éliminer un appel qui était fait à chaque épreuve dans les campagnes.
=> [CLEANUP] Suppression d'un appel inutile dans la page challenge (PIX-609).

admin/app/controllers/authenticated/certification-centers/list.js, admin/app/controllers/authenticated/organizations/list.js, admin/app/controllers/authenticated/sessions/list.js, admin/app/controllers/authenticated/users/list.js, orga/app/controllers/authenticated/campaigns/list.js, orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Sur les listes paginées avec plusieurs filtres, le fait de modifier très rapidement plusieurs filtres est mal géré. En effet, il existe un temps d'attente entre le moment où on frappe sur le clavier et l'envoi de la requête de recherche. Durant ce temps d'attente, si on est très habiles, on peut modifier le contenu de plusieurs filtres. Malheureusement, dans le code, ce cas n'est pas bien géré.
Pour en avoir une illustration claire, rendez-vous sur PixAdmin en Intégration ou sur la RA de votre choix (mais pas celle-ci !) :
- Aller sur la liste des centres de certification
- Vous positionner sur le champ de recherche par ID
- Tapez rapidement du contenu, PUIS changer de champ (via la touche TAB par exemple) puis tapez encore du contenu une fois dans le champ de recherche par nom de centre. …
=> [BUGFIX] Le changement rapide du contenu de plusieurs filtres dans les listes paginées n'est pas bien géré (PIX-598)

docs/security/authenticate.puml, docs/security/reset_with_email.puml
Il y plusieurs ressources liées à l'authentification/autorisation, des scénarios métiers complexes (avec ou sans email, via le GAR), et il n'existe aucune vue d'ensemble.
Fournir des diagrammes de séquence avec les utilisateurs, le front et l'API.
Le format PlantUML est du markdown qui peut être rendu par les IDE (eg. Intellij) et les gestionnaires de sources (eg. GitHub).
=> [DOC] Ajouter des diagrammes de séquence sur la sécurité

admin/nginx.conf.erb, certif/nginx.conf.erb, mon-pix/nginx.conf.erb, nginx.conf.erb, orga/nginx.conf.erb
Sur nos différentes plateformes, nous utilisons pas les en-têtes HTTP de sécurité. Celles-ci sont donc produites par le serveur nginx  et les fournit au navigateur. Sans leurs utilisations, on permet certaines failles de sécurité côté client.  Voici [ici](https://infosec.mozilla.org/guidelines/web_security) une documentation plus détaillée. 
Ajouter aux différents fichiers `nginx.conf.erb` ces en-têtes de sécurité : 
- [X-Content-Type-Option](https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/X-Content-Type-Options) : bloque les attaques qui utilisent le "reniflement" (_sniffing_) pour modifier le type MIME d'une ressource (rendre exécutable un type MIME non exécutable). Ex : empêche la conversion d'un type MIME `text` en type MIME `application/javascript`.
- …
=> [INFRA] Ajout d'en-têtes HTTP pour la sécurité

mon-pix/app/components/user-certifications-detail-profile.js
Régression introduite par https://github.com/1024pix/pix/pull/1308/commits/3f4a85a93d173366a5026a0d3dae318fb1e7b8ed
Personnellement, ça reste encore un peu un mystère pour moi car :
Grâce à l'usage de classes natives JS en Octane, on n'est plus obligé de passer par la méthode `get()` pour lire des attributs en direct. Par contre, quand on cherche à lire le contenu d'une relation qui répond à un mécanisme de lazy-loading, il faut continuer à utiliser `.get()` car potentiellement la relation est toujours un _EmberProxy_, et donc pas encore chargée. 
Ce qui m'échappe, c'est que l'ensemble des relations, des grappes d'objets sérialisés retournés par l'appel `GET /api/certifications/:id` sont TOUTES incluses dans le résultat sérialisé (donc pas de lazy-loading à faire vu qu'on les a !)
Donc …
=> [BUGFIX] Le résultat de certificat de l'utilisateur ne s'affiche plus (PIX-631)

api/db/migrations/20200503193240_add_lastTermsOfServiceValidatedAt_to_user.js, api/db/seeds/data/users-builder.js, api/lib/application/users/index.js, api/lib/application/users/user-controller.js, api/lib/domain/models/User.js, api/lib/domain/usecases/accept-last-pix-terms-of-service.js, api/lib/domain/usecases/accept-pix-last-terms-of-service.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/user-repository.js, api/lib/infrastructure/serializers/jsonapi/user-serializer.js, api/tests/acceptance/application/users/accept-pix-terms-of-service_test.js, api/tests/acceptance/application/users/users-controller-get-current-user_test.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/tooling/database-builder/factory/build-user.js, api/tests/tooling/domain-builder/factory/build-user.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/models/User_test.js, api/tests/unit/domain/usecases/accept-pix-terms-of-service_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-serializer_test.js, mon-pix/app/adapters/user.js, mon-pix/app/controllers/terms-of-service.js, mon-pix/app/models/user.js, mon-pix/app/routes/terms-of-service.js, mon-pix/app/styles/pages/_terms-of-service.scss, mon-pix/app/templates/terms-of-service.hbs, mon-pix/mirage/config.js, mon-pix/tests/acceptance/terms-of-service-test.js, mon-pix/tests/unit/adapters/user-test.js, mon-pix/tests/unit/controllers/terms-of-service-test.js
Les conditions d'utilisation de Pix ont évoluées. Les utilisateurs ayant déjà validé l'ancienne version devront les approuver. Il faut garder une trace de la date d'approbation.
- Création de la colonne "users”.”LastTermsOfServiceValidatedAt"
- Création de la nouvelle page app.pix.fr/cgu qui affiche un lien vers les nouvelles conditions d'utilisation.
- Bouton "retour" qui redirige vers la page de connexion app.pix.fr/connexion 
- Bouton "je me connecte”
- La checkbox ‘je valide les cgu’ doit être coché sinon un message erreur apparait.
- Si la checkbox est cochée, et si succès alors:
- - Mettre à jour la colonne "mustValidateTermsOfService" à FALSE
- - Mettre à jour la colonne "LastTermsOfServiceValidatedAt" avec la date du jour 
- Connecter l’utilisateur
- Tester avec un utilisateur …
=> [FEATURE] Enregister l'acceptation des CGU par l'utilisateur (PF-1235)

api/lib/application/http-errors.js, api/tests/acceptance/application/campaign-participation-controller_test.js, api/tests/acceptance/application/organization-invitation-controller_test.js, api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js, api/tests/integration/application/error-manager_test.js, api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js, api/tests/integration/application/pre-response-utils_test.js, orga/app/components/routes/login-form.js, orga/app/controllers/authenticated/team/new.js, orga/app/routes/join.js, orga/mirage/config.js, orga/tests/acceptance/join-test.js, orga/tests/acceptance/team-creation-test.js
Dans le code pix, un status HTTP "Precondition Failed" renvoie le code `421`. Dans la spécification HTTP et dans le reste du monde, le code est en réalité `412`.
- https://tools.ietf.org/html/rfc7232#section-4.2
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412
Changer les occurrences de `421` correspondantes en `412`.
C'est compliqué, je tente une liste.
Vérifier qu'il y a bien une erreur et que c'est le bon message pour :
- POST /api/campaign-participations pour un utilisateur qui a déjà une participation pour cette campagne (est-ce possible en passant par le front ?)
- partager des résultats de campagne qui ont déjà été partagés
- accepter une invitation orga qui a déjà été acceptée (redirige vers terms of service)
- accepter une invitation orga alors qu'on est déjà membre …
=> [INFRA] Corrige le status code HTTP "precondition failed" (421 -> 412)

admin/nginx.conf.erb, certif/nginx.conf.erb, mon-pix/nginx.conf.erb, nginx.conf.erb, orga/nginx.conf.erb
On aimerait pouvoir rajouter à chaud des en-têtes HTTP aux réponses des applications, notamment pour pouvoir tester la mise en place d'une _Content Security Policy_.
Vérifier dans les fichiers nginx.conf.erb,  que des variables d'environnement commencent par `ADD_HTTP_HEADER` auquel cas on ajoute l'en-tête correspondant.
Par exemple, `ADD_HTTP_HEADER_X_EXAMPLE=test` ajoutera `X-Example: test` à toutes les réponses HTTP.
Ajouter une variable d'environnement qui commence par `ADD_HTTP_HEADER` sur le front de la review app et voir qu'après le restart celui-ci est ajouté.
=> [INFRA] Possibilité d'ajouter des en-têtes HTTP grâce à des variables d'environnement.

api/tests/integration/application/error-manager_test.js
La  gestions des ces cas d'erreurs sont testés dans plusieurs contrôleurs et dans le cas où l'on veut changer le traitement d'une erreur (Changer le code HTTP renvoyé par exemple) on doit changer les tests de plusieurs contrôleurs.
Regrouper les tests des cas d'erreurs ensemble et tester une erreur à un seul endroit en utilisant une route créée uniquement pour les tests.
Cette PR ne fait que regrouper les tests et ne supprime pas les tests dupliqués dans les contrôleurs
Lancer les tests
=> [TECH] Regrouper les tests des cas d'erreurs des contrôleurs (PIX-599).

api/lib/domain/usecases/update-campaign.js, api/lib/domain/validators/campaign-validator.js, api/tests/unit/domain/usecases/update-campaign_test.js, api/tests/unit/domain/validations/campaign-validator_test.js, orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs, orga/app/templates/components/routes/authenticated/campaigns/update-item.hbs, orga/tests/acceptance/campaign-update-test.js, orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js, orga/tests/integration/components/routes/authenticated/campaigns/update-item-test.js
On ne peut pas modifier un campagne de type collecte de profils.
Afficher le bouton modifier dans la page de détails d'une campagne. 
Cacher le champ titre du parcours dans le formulaire de mise à jour car les campagnes de collecte de profils n'ont pas de parcours.
RAS
Se connecter à PIX Orga et modifier une campagne.
Le champ titre du parcours ne doit pas être présent pour une campagne de type collection de profils, mais il est présent pour les campagnes de type évaluation
=> [FEATURE] Permettre la modification d'une campagne de type collecte de profils (PIX-579).

high-level-tests/e2e/cypress/fixtures/users.json, high-level-tests/e2e/cypress/integration/pix-app/terms-of-service.feature, mon-pix/app/mixins/secured-route-mixin.js, mon-pix/app/routes/campaigns/fill-in-id-pix.js, mon-pix/app/routes/campaigns/join-restricted-campaign.js, mon-pix/app/routes/campaigns/skill-review.js, mon-pix/app/routes/campaigns/start-or-resume.js, mon-pix/app/routes/campaigns/tutorial.js, mon-pix/app/routes/certifications/results.js, mon-pix/app/routes/certifications/start.js, mon-pix/app/routes/competences.js, mon-pix/app/routes/competences/details.js, mon-pix/app/routes/competences/results.js, mon-pix/app/routes/competences/resume.js, mon-pix/app/routes/index.js, mon-pix/app/routes/profile.js, mon-pix/app/routes/user-certifications/get.js, mon-pix/app/routes/user-certifications/index.js, mon-pix/app/styles/pages/_terms-of-service.scss, mon-pix/tests/acceptance/terms-of-service-test.js, mon-pix/tests/unit/mixins/secured-route-mixin-test.js
La page permettant d'accepter les nouvelles conditions d'utilisations dans Pix App a été créée (tickets https://1024pix.atlassian.net/browse/PF-998 et https://1024pix.atlassian.net/browse/PF-1235). Nous devons nous assurer qu'un utilisateur ne peut pas accéder au reste de l'application s'il n'a pas au préalable validé les nouvelles CGU (or routes accessibles sans être authentifié). Néanmoins, rien n'empêche aujourd'hui un utilisateur de modifier l'url d'accéder afin d'outrepasser la validation des CGU. 
Il a été décidé de créer un nouveau mixin en remplacement du mixin `AuthenticatedRouteMixin` d'ember-simple-auth. Celui-ci devra reprendre le fonctionnement du mixin d'ember-simple-auth à savoir empêcher l'utilisateur d'accéder à une route s'il n'est pas authentifié. De plus, il devra …
=> [FEATURE]  Ajout de la page /cgu au workflow de connexion (PF-1249). 

mon-pix/app/styles/components/_communication-banner.scss
Ce fichier est passé entre les mailles du filet et les rem dans `_communication-banner.scss` sont exprimés en `1 rem = 10 px`.
Convertir : new rem = old rem * 0.625.
Sur https://app.integration.pix.fr/ :
On veut :
=> [BUGFIX] Corriger les rem de la communication banner (PIX-646).

mon-pix/app/components/challenge-statement.js, mon-pix/app/templates/components/challenge-item-qcm.hbs, mon-pix/app/templates/components/challenge-item-qcu.hbs, mon-pix/app/templates/components/challenge-item-qroc.hbs, mon-pix/app/templates/components/challenge-item-qrocm.hbs, mon-pix/app/templates/components/challenge-statement.hbs, mon-pix/mirage/factories/challenge.js, mon-pix/tests/acceptance/challenge-qroc-test.js
Lorsqu'on a à la suite deux épreuves qui proposent de télécharger deux types de fichiers, la deuxieme épreuve propose encore le fichier de l'épreuve précédente (sauf si on change le type du fichier).
- Le selectedAttachmentsUrl, qui décrit l'URL du fichier à téléchargé, n'était pas mis à jour entre les deux épreuves. En repassant par une computed, elle l'est de nouveau.
- Ajout de test d'acceptance pour ce cas qui est une régression
- Passage des items des épreuves dans le même format octane (avec this. et @)
Création d'une démo avec deux épreuves :  https://app-pr1388.review.pix.fr/courses/recyLsVqy8Mm5rniR
=> [BUGFIX] Deux épreuves avec des fichiers à télécharger ont les mêmes fichiers (PIX-642).

mon-pix/app/controllers/terms-of-service.js, mon-pix/app/templates/terms-of-service.hbs, mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js
Lorsqu'un utilisateur essaye de rejoindre une campagne restreinte et qu'il valide les nouvelles CGU, celui-ci est redirigé vers son profil au lieu de la campagne.  
Vérifier s'il existe une transition qui a été annulée. Si oui, alors le rediriger vers sa transition initiale. 
En plus, le wording de la description a été modifié. 
- Taper un code parcours de campagnes restreinte. 
- Utiliser un utilisateur avec email devant valider les dernières CGU
- Valider les CGU.
- Et constater qu'on est bien redirigé vers la page de reconciliation de la campagne.
=> [BUGFIX] Rediriger vers la page de campagne après revalidation des CGU (PIX-644).

mon-pix/app/routes/assessments/resume.js, mon-pix/app/routes/campaigns/fill-in-id-pix.js, mon-pix/app/routes/campaigns/join-restricted-campaign.js, mon-pix/app/routes/campaigns/start-or-resume.js, mon-pix/tests/unit/routes/assessments/resume-test.js
On a des erreurs dans la console durant les évaluations, des `TransitionAborted`.
- Utiliser `redirect` à la place de `afterModel` dans les routes resume.js et start-or-resume.js.
En effet, ces pages ne servent qu'à faire des redirections. Si on utilise redirect à la place d'afterModel, la transition de start-or-resume ne pose plus problème.
- Attention avec les `return this.transitionTo` : il n'y a normalement pas de return devant les transitionTo. Ca lance bien la transition, mais la route dans laquelle on est attend le résultat pour le return et peut aussi provoquer les `transitionAborted`
- Modification sur : `this.set('givenParticipantExternalId', this.givenParticipantExternalId || transition.to.queryParams.participantExternalId);` qui posait problème car parfois on le récupère à la …
=> [BUGFIX] Ne plus avoir les erreurs de transition dans la console (PIX-632).

api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js, api/tests/acceptance/application/users/get-user-campaign-participation-to-campaign_test.js, api/tests/acceptance/application/users/users-get-campaign-participations_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-participation-serializer_test.js
> DEPRECATION: Encountered mismatched relationship: Ember Data expected data[0].relationships.user.data in the payload from user:10000000.hasMany("campaignParticipations") to include '{"id":"10000000","type":"user"}' but got 'null' instead.
> 
> The <campaign-participation:10000000> record loaded at data[0] in the payload specified null as its '"user"', but should have specified user:10000000 (the record the relationship is being loaded from) as its '"user"' instead.
> This could mean that the response for user:10000000.hasMany("campaignParticipations") may have accidentally returned '"campaign-participation"' records that aren't related to user:10000000 and could be related to a different user record instead.
> Ember Data has corrected the <campaign-participation:10000000> record's …
=> [BUGFIX] Suppression d'un warning ember-data sur les campaignParticipations.

orga/app/styles/components/login-form.scss, orga/app/styles/pages/login.scss, orga/app/templates/components/routes/login-form.hbs, orga/app/templates/login.hbs
Le message sur la page de connexion porte à confusion.
On a l’impression qu’on peut se connecter dès lors qu’on a un compte sur app.pix.fr, ce qui n’est pas vrai.
De plus le design de la page n'est pas à jour.
- Mettre à jour le texte en conséquence
- Mettre à jour le style css
- Aller sur la page de connexion
=> [FEATURE] Mettre à jour le texte de la page de login de PixOrga et son design (PIX-530).

mon-pix/app/templates/components/routes/login-form.hbs
Dans Mon Pix, sur la double mire de connexion SCO, un caractère unicode est utilisé dans la liste à puces.
Remplacer ce caractère par les éléments `<ul>` et `<li>`
* Aller sur la page /campagnes/RESTRICTD
* Cliquer sur Je me connecte
=> [FEATURE][FIX] Utiliser l'élément UL pour la liste à puces dans la double mire de connexion SCO (PIX-647).

api/lib/application/error-manager.js, mon-pix/app/controllers/campaigns/send-profile.js, mon-pix/app/templates/components/profile-sharing-form.hbs, orga/app/models/campaign.js, orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs, orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs, orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js, orga/tests/unit/models/campaign-test.js
On ne peut pas archiver une campagne de type collecte de profils.
Suppression du feature toggle spécifique au campaign de type évaluation.
Voici les impacts de l'archivage d'une campagne : 
- Affichage du bandeau archivage dans la campagne
- Ne plus pouvoir modifier une campagne (enlever le bouton)
- Ne plus pouvoir envoyer de profil pix dans Pix APP (lorsque le code de la campagne est saisie, reprendre le message d’erreur afficher dans le cas d’une campagne d’évaluation).
Rendez vous sur PixOrga et cliquer sur le bouton "Archiver" dans le détails d'une campagne de collecte de profils. Vous pouvez ensuite constater qu'elle apparaît dans la liste des campagne archivées et que vous ne pouvez plus la modifier. Si vous essayer d'utiliser son code dans PixApp vous aurez un message qui vous …
=> [FEATURE] Ajoute le système d'archivage sur les campagnes de type collecte de profils (PIX-584).

mon-pix/app/styles/components/_navbar-desktop-header.scss, mon-pix/app/templates/components/navbar-desktop-header.hbs, mon-pix/tests/integration/components/navbar-desktop-header-test.js
Le bouton "J'ai un code" apparaît sur la page `/campagnes` lorsque que l'utilisateur n'est pas connecté. 
Supprimer le bouton de l'entête de la page quand l'utilisateur n'est pas connecté.
Nous en avons profité pour aligner à droite les boutons connexion et s'inscrire. Cela a aussi corriger un petit problème graphique qui faisait que l'élément de profil du menu n'était pas parfaitement aligné à droite.
Se rendre sur la page `/campagnes` en étant non connecté et constater la disparition du bouton "J'ai un code".
=> [BUGFIX] Supprime le bouton "J'ai un code" pour les utilisateurs non connectés (PIX-601).

mon-pix/app/styles/components/_background-banner.scss
En rationalisant les couleurs utilisées dans l'application Pix App avec les couleurs du design system, une coquille s'est glissée dans le nom de la couleur utilisée pour le fond de la bannière de la page évaluation (`$pix-blue-gradient` au lieu de `$pix-gradient`).
Utiliser `$pix-gradient` comme couleur de fond de la bannière de la page évaluation.
RAS
Démarrer une évaluation en cliquant sur une compétence.
Vérifier que le rendu de la bannière correspond à la capture présente dans `Solution`.
=> [BUGFIX] Utiliser le bon dégradé de couleur pour le fond de la bannière de la page évaluation.

mon-pix/app/components/tutorial-item.js, mon-pix/app/templates/components/tutorial-item.hbs, mon-pix/tests/unit/components/tutorial-item-test.js
Depuis la mise en production de la fonctionnalité d'évaluation d'un tutoriel, sentry remonte plusieurs fois par jour l'erreur de violation de contrainte d'unicité.
```
duplicate key value violates unique constraint "tutorial_evaluations_userid_tutorialid_unique"
```
En analysant le code et les erreurs Sentry, ainsi que le contenu de la base de données, on se rend compte que l'erreur se produit quelques millisecondes après l'enregistrement en base de données.
En local, on arrive à déclencher 2 fois de suite le même appel réseau en faisant un double-clic sur le bouton, lorsque le réseau est lent (en le ralentissant avec les devtools).
La solution consiste alors, comme pour la sauvegarde d'un tutoriel, le bouton est désactivé durant l'appel API.
Cette PR est l'occasion de nettoyer le gommage …
=> [BUGFIX] Ne pas permettre d'évaluer un tutoriel 2 fois (PIX-648).

api/lib/infrastructure/repositories/knowledge-element-repository.js
Les méthodes du `knowledgeElementRepository` de type `findUniqByUserId*` n'étaient pas très efficaces d'un point de vue de l'usage de la mémoire et d'allocation d'objets.
En effet, la plupart de nos méthodes de répo se déroulent de la manière suivante :
-> Construction de la requête (via bookshelf)
-> Récupération des résultats via des objets Bookshelf
-> Transformation des objets Bookshelf en objets du domaine.
Ce qui signifie que les objets Bookshelf instanciés ont très peu (pas ?) d'utilité. De plus, des mesures nous ont montré que ces objets prenaient une place en mémoire non négligeable.
Nous proposons donc ici de remplacer l'usage de Bookshelf par celui du query-builder Knex, et d'instancier les résultats retournés directement en objets du domaine.
La requête de base est donc la …
=> [INFRA] Amélioration des performances mémoire (et donc vitesse) lors de l'utilisation du knowledge-element-repository (PIX-635).

mon-pix/app/styles/components/_navbar-desktop-menu.scss, mon-pix/app/styles/components/_navbar-header.scss, mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs, mon-pix/app/templates/certifications/start-loading.hbs, mon-pix/app/templates/certifications/start.hbs, mon-pix/app/templates/competences/details.hbs, mon-pix/app/templates/competences/results.hbs, mon-pix/app/templates/error.hbs, mon-pix/app/templates/profile.hbs, mon-pix/app/templates/user-certifications.hbs, mon-pix/app/templates/user-tutorials.hbs
Les boutons `Se connecter` et `S'inscrire` ne sont pas visibles (couleur trop claire).
Le fond de la barre de navigation est gris pâle au lieu d'être blanc.
Les deux problèmes ont des origines différentes.
Le problème des boutons est liés à l'uniformisation des couleurs du design system.
Il faut les remplacer par les couleurs correctes.
Le problème du fond de la barre de navigation est due à la glimmerisation du composant `NavbarHeader`. Chaque page affichant ce composant définit une classe pour ce composant comme suit.
```
<NavbarHeader @class="navbar-header--white">
```
Le composant en lui même override cette valeur en définissant la classe `navra-header`.
En regardant les usages, il apparaît que les 2 classes sont toujours utilisées ensemble. Aussi il est décidé de les fusionner dans …
=> [BUGFIX] Correction des couleurs de la navigation.

orga/app/styles/components/login-form.scss
Le design de la page de connexion de Pix Orga a changé.
Les textes sont dorénavant centrés.
Or les messages d'erreur ne le sont pas encore.
Modifier le css pour centrer ces messages.
* Se connecter en utilisant un password erroné
* Se connecter avec `userpix1@example.net`, qui n'est pas membre d'une organisation
=> [FEATURE] Centrer les messages d'erreur sur la page de connexion de Pix Orga (PIX-652).

api/lib/application/sessions/index.js, api/lib/config.js, api/tests/unit/application/session/index_test.js
Il est possible depuis Pix App de rejoindre une session de certification en spécifiant notamment un id de session. Néanmoins, il arrive parfois que des utilisateurs renseignent des id "fantaisistes"  tel que "99456787654321" ce qui cause l'erreur suivante en base: `value "99456787654321" is out of range for type integer`.
Ajouter dans la validation Joi un contrôle sur la longueur maximale d'un id de session en base, soit 2147483647 (2^31 - 1).  
L'erreur remontée ne concernait que la route `POST /api/sessions/{id}/candidate-participation` mais la validation a aussi été appliquée aux autres routes du session-controller.
- Se connecter à Pix App et cliquer sur l'onglet "Certifications".
- Remplir le champs "Numéro de session" avec la valeur "99456787654321".
- Remplir les autres champs.
- …
=> [BUGFIX] Validation de la longueur d'un id de session. 

api/lib/infrastructure/repositories/knowledge-element-repository.js
Un oubli (non impactant, mais oubli quand même) laissé par la PR https://github.com/1024pix/pix/pull/1382.
Vu que la charge de filtrer les KE (le + récent par acquis + exclusion des remises à zéro) a été remis au code JS (et pas à la BDD comme le suggérait la première proposition de la PR mentionnée ci-dessus), on n'a plus besoin de classer les KE par date.
Du coup j'ai oublié de retirer la fonction fenêtrée.
Retrait de la fonction fenêtrée. Aucun impact fonctionnel, car de toute façon le KE créé ne tenait pas compte du retour la fonction fenêtrée.
=> [CLEANUP] Retrait d'une clause SELECT inutile dans le KE repository

mon-pix/app/components/challenge-item-qrocm.js, mon-pix/app/styles/components/_challenge-actions.scss, mon-pix/tests/acceptance/challenge-qrocm-test.js
On laisse la possibilité à l'utilisateur de valider sa réponse même si tous les champs ne sont pas remplis. On peut également valider avec la touche `Entrée` ce qui amène parfois à valider avant d'avoir fini de répondre.
Modifier la vérification sur le formulaire au clic sur **Je valide**. 
Trouver un QROCM (par exemple : `recBzswglMDjdzrNp`) et valider sans répondre et en laissant un ou des champs vides. Un message d'erreur doit s'afficher.
=> [FEATURE] Valider les QROCM seulement si l'utilisateur a rempli tous les champs réponse (PIX-375).

api/lib/infrastructure/serializers/jsonapi/membership-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/application/users/users-controller-get-memberships_test.js, api/tests/unit/infrastructure/serializers/jsonapi/membership-serializer_test.js
> DEPRECATION: Encountered mismatched relationship: Ember Data expected data[0].relationships.user.data in the payload from user:4.hasMany("memberships") to include '{"id":"4","type":"user"}' but got 'null' instead.
> 
> The <membership:100048> record loaded at data[0] in the payload specified null as its '"user"', but should have specified user:4 (the record the relationship is being loaded from) as its '"user"' instead.
> This could mean that the response for user:4.hasMany("memberships") may have accidentally returned '"membership"' records that aren't related to user:4 and could be related to a different user record instead.
> Ember Data has corrected the <membership:100048> record's '"user"' relationship to user:4 so that user:4.hasMany("memberships") will include …
=> [BUGFIX] Suppression de warnings ember-data sur les memberships.

api/lib/infrastructure/serializers/jsonapi/user-orga-settings-serializer.js, api/tests/unit/infrastructure/serializers/jsonapi/user-orga-settings-serializer_test.js
> DEPRECATION: Encountered mismatched relationship: Ember Data expected data.relationships.user.data in the payload from user:4.belongsTo("userOrgaSettings") to include '{"id":"4","type":"user"}' but got 'null' instead.
> 
> The <user-orga-setting:10000000> record loaded at data in the payload specified null as its '"user"', but should have specified user:4 (the record the relationship is being loaded from) as its '"user"' instead.
> This could mean that the response for user:4.belongsTo("userOrgaSettings") may have accidentally returned '"user-orga-setting"' records that aren't related to user:4 and could be related to a different user record instead.
> Ember Data has corrected the <user-orga-setting:10000000> record's '"user"' relationship to user:4 so that …
=> [BUGFIX] Suppression d'un warning ember-data sur les user-orga-settings.

mon-pix/app/styles/components/_background-banner.scss, mon-pix/app/styles/components/_certification-banner.scss, mon-pix/app/styles/components/_congratulations-certification-banner.scss, mon-pix/app/styles/globals/_colors.scss, mon-pix/app/styles/pages/_campaign-tutorial.scss, mon-pix/app/styles/pages/_login-or-register-to-access-restricted-campaign.scss, mon-pix/app/styles/pages/_not-connected.scss, mon-pix/app/styles/pages/_sign-form.scss, mon-pix/app/styles/pages/_terms-of-service.scss, mon-pix/app/styles/pages/_update-expired-password-form.scss
Les deux bouttons de la page cgus s'affichent en superposé en version mobile
Restructurer le style pour gérer le responsive et avoir un affichage correct sous IE et Firefox.
Enlever le padding du boutton cancel qui déborde en responsive.
-Cette PR corrige une régression sur la couleur de Pix gradient utilisé. 
-En plus d'un refactoring des noms de couleurs pour être plus explicite.
-Se connecter avec un utilisateur qui doit valider les nouvelles cgus.
-Le champ mustValidateTermsOfService
Utilisateur: lasttermsofservice@notvalidated.net / Password123
-Pour vérifier la bonne couleur du gradient, il faut checker l'ensemble du site ( login form, reset mot de pass, page d'inscription ...)
=> [BUGFIX] Empêcher le chevauchement des boutons sur la page CGU en version mobile (PIX-662)

mon-pix/tests/helpers/contains.js, mon-pix/tests/integration/components/navbar-desktop-header-test.js, mon-pix/tests/unit/helpers/contains-test.js
Il est difficile de verifier la présence d'un élément textuel sans écrire un sélecteur lié à l'implémentation. Cela rend les tests moins robuste. Ils sont sensible aux changements de nom de classes ou au changement dans la structure du HTML.
Côté tests e2e avec Cypress on a l'habitude d'utiliser `contains` pour éviter ces problématiques. J'ai donc implémenté un helper du même nom qui vérifie sur le rendu du test courant contient un élément textuel. J'ai aussi réalisé le helper `containsAll` si on peut vérifier la présence de plusieurs éléments contenant le texte fourni en paramètre.
J'ai refactoré les tests de `navbar-desktop-header` qui donnent un exemple assez facile à réaliser.
=> [TECH] Ajout d'un helper de test contains pour vérifier qu'un texte est présent dans le rendu (PIX-675) .

api/lib/domain/models/CertificationProfile.js, api/lib/domain/services/certification-result-service.js, api/lib/domain/services/user-service.js, api/lib/domain/usecases/get-user-current-certification-profile.js, api/lib/domain/usecases/retrieve-last-or-create-certification-course.js, api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js, api/tests/integration/domain/services/user-service_test.js, api/tests/integration/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream_test.js, api/tests/unit/domain/models/CertificationProfile_test.js, api/tests/unit/domain/services/certification/certification-result-service_test.js, api/tests/unit/domain/services/certification/certification-service_test.js, api/tests/unit/domain/usecases/get-user-current-certification-profile_test.js, api/tests/unit/domain/usecases/retrieve-last-or-create-certification-course_test.js
Dans l'export de collecte de profil en CSV, on calcul le profil pix en prennant en compte les questions qui dépassent le niveau 5. On a alors un nombre de pix qui n’est pas le même entre le profil récupéré dans pix orga et le profil affiché au prescrit.
L'export de collecte de profil en CSV utilise le service `getCertificationProfile`. Il faut lui passer une option pour activer la limitation de pix et niveau sur la récupération des compétences de l'utilisateur.
1. Atteindre un niveau supérieur à 5 sur un compétence dans pix-app
2. Faire une campagne collecte de profil avec cet utilisateur
3. Extraire le CSV de la campagne de collecte
> Vérifier que la compétence est limitée au niveau 5 et avec un maximum de pix à 40
=> [BUGFIX] Limiter les Pix et Levels max sur l'export de collecte de profils (PIX-615).

mon-pix/app/templates/campaigns/tutorial.hbs
On n'a plus d'indication visuelle sur la progression du didacticiel.
Corriger la déclaration modifiée par erreur par le codemod.
Lancer une campagne et admirer les jolis ronds bleus :
=> [BUGFIX] Corriger l'affichage de la progression sur le didacticiel (PIX-560).

orga/app/styles/pages/login.scss
Le nouveau gradient n'a pas été validé pour toutes les pages. En attendant, nous remettons l'ancien. 
Remettre l'ancien gradient. `$pix-orga-gradient` 
Voir la page de connexion qui a l'ancien gradient.
=> [BUGFIX] Remettre l'ancien gradient sur la page de connexion sur Pix Orga (PIX-655).

certif/app/components/login-form.hbs, certif/app/styles/components/login-form.scss
La description du message de la page de login n'est pas bon.
Mettre la bonne description.
Un changement du font weight pour être iso Pix Orga.
Un changement du font family en robot.
Afficher la page de login de la page de certification
=> [BUGFIX] Changer la description de la page de connexion de Pix Certif (PIX-678)

api/lib/domain/services/scoring/scoring-service.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
Le nombre total de Pix est calculé de plusieurs façon en fonction:
- sur la page /profile mon-pix: on récupère le nombre pix de chaque compétence de l'utilisateur, puis on fait la somme et on affiche la valeur arrondi
- pour génération des résultats côté orga, les Pix de chaque compétence sont d'abord arrondi, puis on fait la somme
La valeur du nombre total de Pix peut alors différer.
Il a été opté de garder la méthode de calcul d'arrondir d'abord les pix de chaque compétence avant de faire la somme.
Normalement, le nombre total de Pix affiché sur la page `/profil` devrait correspondre au résultat de la requête:
```js
select SUM("pixEarnedByCompetence"."earnedPix")
FROM (
with earnedPixWithRankPerSkill as (
select "earnedPix",
"competenceId",
ROW_NUMBER() OVER (PARTITION BY "skillId" …
```
=> [FEATURE] Modification du calcul des Pix Globaux (PIX-649)

mon-pix/app/styles/pages/_update-expired-password-form.scss, mon-pix/app/templates/components/update-expired-password-form.hbs
La page de choix de nouveau mot de passe, suite à utilisation de mot de passe temporaire, utilise plusieurs termes: réinitialiser, nouveau, changer. Cela peut faire douter l'utilisateur
Garder le terme réinitialisation et supprimer les autres.
Se connecter sur [PixApp RA](https://app-pr1408.review.pix.fr/)
Utiliser le compte username123/Password123
=> [FEATURE] Clarifier la page de changement de mot de passe (PIX-554).

docs/test.md
Les standards de test, informels, ne sont pas connus de tout le monde, comme cet échange l'a montré #1321 
Suite à un atelier, les points en accord ont été dégagés, et cette PR les documente.
Les points en conflit sont en discussion sur des issues, par exemple #1365 
Ouvrir le fichier au format markdwon dans:
- GitHub, "Display Rich Diff" pour obtenir le formatage
- un IDE pour obtenir un somaire (ex IntelliJ: onglet structure)
=> [DOC] Ajouter un standard de test.

admin/ember-cli-build.js, certif/ember-cli-build.js, mon-pix/ember-cli-build.js, orga/ember-cli-build.js
Les sourcemaps ne sont jamais générés ce qui rend le debugging ember compliqué
Generer les sourcemaps en inline quand l'environnement est en mode "development"
- Les _sourcemaps_ sont en inline mais cela pourrait etre dans des fichiers séparés.
- La generation des _sourcemaps_ selon [la doc d'ember](https://cli.emberjs.com/release/advanced-use/asset-compilation/) ne fonctionne pas 
Lancer l'appli en dev, debugger/voir les sources depuis le browser
=> [TECH] Ajouter les sourcemaps en développement

admin/app/components/users/list-items.hbs, admin/app/controllers/authenticated/users/list.js, admin/tests/acceptance/authenticated/users/get-test.js
Aujourd'hui, l'accès à la page de détail d'un utilisateur dans Pix Admin se fait en cliquant sur une des lignes du tableau des utilisateurs. Ce fonctionnement, pose néanmoins problème lorsque l'on cherche à copier une des informations du tableau. En effet, tout clique puis relâchement du bouton de la souris entraîne l'ouverture de la page de détail.
Permettre l'accès à la page de détail d'un utilisateur en cliquant sur l'id de celui depuis le tableau.
=> [FEATURE] Changer la façon d'accéder à la page de détail d'un utilisateur dans Pix Admin (PIX-677). 

admin/app/services/session-info-service.js
Le nom du fichier avant jury dans Pix Admin n'est pas au format attendu (c'est à dire avec des "_" dans le nom du fichier).
Cela peut poser des problèmes de tris ou d'organisations pour la gestion de ce genre de fichier chez le pôle certif.
Uniformiser le nom du fichier avant jury et du fichier d'export des résultats au format `AAAAmmjj_hhmm_jury_session_IDsession` . 
Il a été vu avec le pôle certif que la date à afficher, pour le fichier avant jury, est bien la date de téléchargement du fichier (car elle correspond au jour où est fait le jury). Et non la date de la session comme pour le fichier de résultats. 
Je ne sais pas s'il est vraiment intéressant de chercher à tester le nom du fichier ? 
Ca semble assez difficile à réaliser... sauf si on teste juste la méthode …
=> [BUGFIX] Nom du fichier avant jury sans underscore (PIX-661)

api/lib/config.js, api/lib/domain/usecases/start-writing-campaign-assessment-results-to-stream.js, api/lib/domain/usecases/start-writing-campaign-profiles-collection-results-to-stream.js, api/lib/infrastructure/constants.js
L'export CSV pour les campagnes de type "collecte de profils" a été mis en production et exploitable, dans un premier temps,
par un groupe restreint d'organisations bêta testeuses. Malheureusement, les premiers retours indiquent un temps de téléchargement trop long. En effet, il semblerait qu'il faille plusieurs minutes pour télécharger un export csv de collecte de profils.
Ce n'est pas surprenant: les expérimentations passées nous ont apprises qu'à calculer le profil de plusieurs utilisateurs d'un coup, on risquait l'explosion mémoire. De fait, pour pallier à cela, divers travaux ont été effectués pour mettre en place, en dernière instance, un mécanisme de streaming pour la génération des CSV (export de résultats et de collecte de profils). Ce mécanisme de streaming s'associe à un calcul …
=> [BUGFIX] Stabilisation des perfs pour l'export CSV des campagnes de collecte de profils et d'évaluation (PIX-607).

mon-pix/app/templates/assessments/loading.hbs, mon-pix/app/templates/assessments/results-loading.hbs, mon-pix/app/templates/assessments/resume-loading.hbs, mon-pix/app/templates/campaigns/loading.hbs, mon-pix/app/templates/components/loader.hbs
Si ma connexion est lente et qu'on lance une évaluation par compétence, on a un écran blanc sans l'affichage du chargement.
Le souci est causé par l'utilisation des hooks `redirect` en lieu et place de `beforeModel`.
En ajoutant un fichier `loading.js` à la racine du répertoire `assessment`, le loader est affiché.
On profite de toucher au chargement pour créer un composant `Loader`.
Avec les devtools, limiter la vitesse de connexion.
Lancer une évaluation par compétence.
Vérifier que le loader est affiché.
=> [BUGFIX] Rétablissement du loader quand on lance une évaluation (PIX-653).

mon-pix/app/components/signup-form.js, mon-pix/app/services/url.js, mon-pix/app/templates/components/signup-form.hbs, mon-pix/tests/integration/components/signup-form-test.js, mon-pix/tests/unit/services/url-test.js, mon-pix/translations/en-us.json, mon-pix/translations/fr-fr.json
Le lien vers les CGU était en dur vers pix.fr
Utiliser le service url pour récupérer le bon host et injecter le bon lien dans le template.
On utilise le templating des traductions :
https://ember-intl.github.io/ember-intl/versions/master/docs/helpers/t
Sur .fr on veut un lien vers pix.fr/conditions-generales-d-utilisation, sur .org, pix.org/conditions-generales-d-utilisation
=> [FEATURE] Afficher le bon lien vers les CGU sur .org et .fr (PIX-683).

api/lib/infrastructure/repositories/jury-session-repository.js
La récupération paginée des sessions de certification dans un contexte de traitement des certifications présente un tri obligatoire (vu que le tri à la mano n'est pas disponible).
Le tri en vigueur actuellement est le suivant :
```
query.orderByRaw('?? ASC NULLS FIRST', 'publishedAt')
.orderByRaw('?? ASC', 'finalizedAt')
```
A savoir d'abord les sessions non publiées, puis de la plus anciennement publiée à la plus récemment publiée. Puis, en cas "d'égalité" au niveau de la publication (particulièrement dans le cas où `publishedAt` est NULL), on tri selon la date de finalisation, de la plus anciennement finalisée à la plus récemment finalisée. Ce stratagème permet de faire d'abord remonter les sessions finalisées mais non publiées. En effet, le statut d'une session se déduit à travers …
=> [BUGFIX] L'ordre de tri sur la liste paginée des sessions sur PixAdmin n'est pas déterministe (PIX-728)

api/lib/infrastructure/repositories/campaign-collective-result-repository.js, api/tests/acceptance/application/campaign-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-collective-result-repository_test.js
Des acquis vont changer de compétences et vont passer d'une compétence PIX à une compétence PIX + (international).
Ce qui va provoquer des erreurs côté calcul des résultats collectifs :
> Un prescrit envoi ses résultats avec l'acquis dans une compétence PIX.
> Un nouveau prescrit envoi ses résultats mais cette fois-ci l'acquis à changer de compétence pour être lié à une compétence Pix+. Même si il a eu 100% juste, le pourcentage de la nouvelle compétence ne sera pas 100% car elle n'aura pas été testée par les autres. 
Le problème vient du fait que les résultats collectifs sont calculés à partir du `competenceId` porté par les knowledge element. Ce compétence id peut ne plus correspondre à l'acqui associé avec les nouvelles compétences. 
Il faut utiliser la liste des compétences actuelle …
=> [FEATURE] Résultats collectifs prenant en compte les nouvelles compétences de Pix + (PIX-673)

admin/app/controllers/authenticated/sessions/list.js, admin/app/routes/authenticated/sessions/list.js, admin/app/styles/authenticated/sessions/list.scss, admin/app/templates/authenticated/sessions/list.hbs, admin/package-lock.json, admin/package.json, admin/tests/unit/routes/authenticated/sessions/list-test.js, api/lib/application/sessions/session-controller.js, api/lib/domain/validators/session-validator.js, api/lib/infrastructure/repositories/jury-session-repository.js, api/tests/integration/infrastructure/repositories/jury-session-repository_test.js, api/tests/unit/application/session/session-controller_test.js, api/tests/unit/domain/validations/session-validator_test.js
Le pôle certification a besoin de pouvoir connaître rapidement quelles sessions leurs sont assignées car cela correspond à leur travail à faire. 
_Exemple: si une (ou plusieurs) session est assignée à Mr.Dupont, ce dernier devrait pouvoir la voir rapidement afin de terminer son traitement. Or la liste des sessions actuelle ne permet pas cela, elle affiche la liste de toutes les sessions indépendamment de qui s'en occupe._
Ajouter un toogle / boutton interrupteur permettant de n'afficher que les sessions assignées à l'utilisateur courant. 
Nouvel addon ember installé pour les boutons toogle : https://github.com/knownasilya/ember-toggle
- Aller sur PixAdmin
- Liste des sessions
- S'assigner quelques sessions (cliquer sur l'id de la session puis le bouton "M'assigner la session")
- Liste des …
=> [FEATURE] Ajout du filtre sur la colonne "Qui ?" dans la liste des sessions dans Pix Admin (PA-211)

orga/app/adapters/campaign-profiles-collection-participation-summary.js, orga/app/routes/authenticated/campaigns/details/profiles.js
Lorsqu'on consulte l'onglet "participants" de 2 campagnes de collecte de profils à la suite, les participants se cumulent dans le tableau.
Utiliser `query` à la place de `findAll`.
- Afficher la liste des participants à une campagne A de type "collecte profils" ;
- Retourner sur la liste des campagnes ;
- Afficher la liste des participants à une campagne B de type "collecte profils" ;
- Vérifier que ce sont bien uniquement les participants de la campagne B qui sont affichés dans l'onglet "participants" de la campagne B.
=> [BUGFIX] Correction de la mise à jour de l'affichage de la liste des participants (PIX-747).

api/lib/application/organizations/organization-controller.js, api/lib/infrastructure/repositories/campaign-repository.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js, api/tests/unit/application/organizations/organization-controller_test.js, orga/app/controllers/authenticated/campaigns/list.js, orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs, orga/mirage/config.js, orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js, orga/tests/unit/controllers/authenticated/campaigns/list-test.js
Quand une organisation n'a que des campagnes archivées, la page de "Création de première campagne" s'affiche et il est possible de voir les campagnes archivées sans en créer de nouvelles.
Quand aucune campagne n'a été crée dans l'organisation, alors afficher la page "Création de première campagne". À partir du moment où au moins une campagne existe dans l'organisation (archivée ou non), il faut afficher la page de la liste des campagnes vide ou non (en fonction des campagnes actives et archivée)
Utilisation d'une meta JSON API `hasCampaigns` sur l'API `/api/organizations/{id}/campaigns` pour savoir si l'organisation possède déjà au moins une campagne (archivé ou non).
On affiche la page "Création de première campagne" uniquement si `hasCampaigns=false`
- Aller sur une organisation sans …
=> [FEATURE] Voir les campagnes archivées quand plus de campagnes actives (PIX-663)

admin/app/components/organization-members-section.hbs, admin/app/components/organization-members-section.js, admin/app/components/role-edit.hbs, admin/app/components/role-edit.js, admin/mirage/config.js, admin/tests/acceptance/organization-memberships-management-test.js, admin/tests/helpers/contains.js, admin/tests/helpers/test-init.js, admin/tests/integration/components/routes/role-edit-test.js, api/lib/application/memberships/index.js, api/lib/application/security-pre-handlers.js, api/tests/integration/application/memberships/membership-controller_test.js
Bien qu'il soit possible pour nos utilisateurs qui sont administrateur d'une organisation de modifier les rôles des membres de cette organisation dans Pix Orga, il arrive parfois que cet administrateur ne fasse plus partie de l'organisation. 
Permettre de modifier le rôle des membres d'une organisation dans PixAdmin.
Nous utilisons le composant ember-models-table pour afficher le tableau des memberships. Il a donc été nécessaire d'ajouter un composant afin de permettre d'afficher un select plutôt qu'un input dans la cellule du tableau.
=> [FEATURE] Permettre la modification du rôle d'un membership dans Pix Admin (PIX-455).

mon-pix/app/components/password-reset-demand-form.js, mon-pix/app/templates/components/password-reset-demand-form.hbs, mon-pix/tests/integration/components/password-reset-demand-form-test.js, mon-pix/tests/unit/components/password-reset-demand-form-test.js
Lorsque l'utilisateur est sur la page de réinitialisation de mot de passe par email, et lorsque la connection est lente, il peut cliquer plusieurs fois sur le bouton "Réinitialiser", avant que la page de confirmation ne soit affichée.  Cela envoie autant de demandes à l'API, qui ne sont pas utiles.
Désactiver le bouton "Réinitialiser" lorsqu'un appel a été effectué à l'API (afficher lo loader habituel avec des points). Si l'appel échoue, réactiver le bouton.
Attendre le merge de #1436
Lorsque l'utilisateur ne saisit pas de mot de passse, une vérification a été rajoutée, qui empêche l'appel à l'API. Elle n'affiche pas de mssage d'erreur, et ne désactive pas le bouton.
Se rendre sur la page [de réinitialisation](https://app-pr1428.review.pix.fr/mot-de-passe-oublie). Afficher les appels …
=> [BUGFIX] Empêcher l'utilisateur de demander plusieurs fois la réinitialisation de son mot de passe (PIX-489).

api/db/migrations/20200515163806_add-column-createdat-updatedat-to-memberships.js, api/lib/infrastructure/data/membership.js
Le support Pix souhaite savoir quand un utilisateur:
* a été rattaché à une organisation (création d'une appartenance)
* a vu son rôle sur l'organisation modifié (modification d'une appartenance)
Il doit pouvoir distinguer les cas où les données existaient avant la mise de cette fonctionnalité.
Le support modifie parfois ces données via une invite SQL.
Ajout de deux propriétés d'audit:
* createdAt: création
* upadtedAt: modification
Alimentation de ces champs:
* via l'application, par un modèle Bookshelf paramétré avec ces propriétés
* pour les données existantes, avec la date [Unix epoch (01/01/1970)](https://en.wikipedia.org/wiki/Unix_time)
* pour les données manipulées via une invite SQL, avec une valeur par défaut, l'horodatage du jour
En cas de mise à jour de données via une invite …
=> [FEATURE] Tracer les modifications des appartenances aux organisations (PF-494).

api/lib/domain/services/scoring/scoring-service.js, api/lib/domain/usecases/get-user-pix-score.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js, api/tests/unit/domain/usecases/get-user-pix-score_test.js
Le score (en pix) d'un utilisateur est parfois différent entre celui affiché sur son profil et celui dans la collecte de profil.
Le problème a été identifié sur la base de recette, sur l'utilisateur numéro `220970`.
Le score affiché est de 160 pix sur son profil.
Le score dans la collecte de profil est de 161.
Après investigation, il apparaît que la seule différence entre les deux calculs est que la somme des pix est faite en SQL pour le score affiché sur le profil et en JavaScript pour le score de la collecte de profil.
Le type en base de données de la colonne stockant les pix de chaque `knowledge-element` (`earnedPix`) est `real`.
En parcourant la [documentation de PostgreSQL](https://www.postgresql.org/docs/current/datatype-numeric.html), on voit que le type `real` est  un nombre à …
=> [BUGFIX] Correction du calcul du score en pix (différence entre export du profil et affichage sur le profil) (PIX-739).

admin/app/controllers/authenticated/certifications/certification/details.js, admin/app/controllers/authenticated/certifications/certification/informations.js, api/db/migrations/20200522090553_add-competenceId-column-competence-marks-table.js, api/db/seeds/data/certification/certification-data.js, api/lib/application/assessment-results/assessment-result-controller.js, api/lib/application/passwords/password-controller.js, api/lib/config.js, api/lib/domain/events/CertificationScoringCompleted.js, api/lib/domain/events/handle-certification-partner.js, api/lib/domain/events/handle-certification-scoring.js, api/lib/domain/events/index.js, api/lib/domain/models/CertificationPartnerAcquisition.js, api/lib/domain/models/CompetenceMark.js, api/lib/domain/services/mail-service.js, api/lib/domain/services/scoring/scoring-certification-service.js, api/lib/infrastructure/repositories/competence-mark-repository.js, api/tests/integration/domain/services/scoring/scoring-certification_test.js, api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js, api/tests/tooling/database-builder/factory/build-competence-mark.js, api/tests/tooling/domain-builder/factory/build-competence-mark.js, api/tests/unit/application/passwords/password-controller_test.js, api/tests/unit/domain/events/handle-certification-partner_test.js, api/tests/unit/domain/events/handle-certification-scoring_test.js, api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js, api/tests/unit/domain/services/certification/certification-service_test.js, api/tests/unit/domain/services/mail-service_test.js
La vérification du seuil des 75% CléA a été mis en place sur le score positionné par compétence. Ce n'est pas correct, ce devrait être sur le score certifié (sinon ça sert à quoi de passer une certif...)
On récupère le score certifié par compétence à l'aide des `CompetenceMarks`.
On en profite aussi pour ajouter la colonne `competenceId` dans la table `competence-marks`, plus utile qu'un `competence_code` sujet à moult transformations pour en tirer quelque chose...
A l'aide Anne-So pour tester cette CHOSE
=> [BUGFIX] Vérifier le seuil des 75% CléA sur le score certifié par compétence (et non positionné) (PIX-680)

mon-pix/app/routes/campaigns/fill-in-id-pix.js, mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js, mon-pix/tests/acceptance/navigation-test.js, mon-pix/tests/acceptance/resume-campaigns-with-type-assessment-test.js, mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js, mon-pix/tests/acceptance/start-campaigns-with-type-profiles-collection-test.js, mon-pix/tests/helpers/campaign.js, mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Si un utilisateur qui a déjà envoyé son profil Pix à son prescripteur ressaisi le code campagne, il revoit la page de présentation. De ce fait il a l'impression qu'il peut ré-envoyer ses résultats. Ce n'est pas le cas.
De même si l'utilisateur a déjà vu la page d'envoi profil, qu'il décide de l'améliorer puis ressaisi le code plus tard, il revoit la page de présentation.
Lorsque la participation à la campagne existe déjà, ne pas passer par cette page de présentation.
Une nouvelle page va également être réalisée pour spécifier de manière plus claire lorsque le profil a déjà été envoyé.
- Saisir le code SNAP123, et arriver jusqu'à la page d'envoi profil
- Sortir
- Cliquer sur le bandeau de reprise
- Vérifier qu'on arrive bien directement sur la page d'envoi profil
- Sortir
- Ressaisir le …
=> [FEATURE] Ne pas montrer la page de présentation si l'utilisateur a déjà commencé sa participation (PIX-616).

mon-pix/app/controllers/profiles-collection-campaigns/profile-already-shared.js, mon-pix/app/models/campaign-participation.js, mon-pix/app/router.js, mon-pix/app/routes/profiles-collection-campaigns/profile-already-shared.js, mon-pix/app/routes/profiles-collection-campaigns/start-or-resume.js, mon-pix/app/styles/pages/_send-profile.scss, mon-pix/app/templates/components/profile-sharing-form.hbs, mon-pix/app/templates/profiles-collection-campaigns/profile-already-shared.hbs, mon-pix/tests/acceptance/resume-campaigns-with-type-profiles-collection-test.js
Lorsque les utilisateurs qui ont envoyé leur profil Pix au prescripteur ressaisissent le code campagne, ils voient la page d'envoi profil avec comme titre "ENVOI DE VOTRE PROFIL PIX" et en petit "votre profil a déjà été envoyé". Cette page n'est pas suffisamment claire pour comprendre qu'on ne peut pas ré-envoyer son profil.
Faire un affichage dédié.
On va afficher par la suite le profil qui a été envoyé en dessous, sinon on n'a aucun moyen de le revoir.
- Saisir le code SNAP123
- Passer la page de présentation
- Envoyer son profil
- Sortir
- Ressaisir le code SNAP123
- Vérifier qu'on arrive bien sur la page dédiée
=> [FEATURE] Montrer de manière claire que l'utilisateur a déjà envoyé son profil Pix (PIX-610).

api/lib/application/passwords/password-controller.js, api/lib/config.js, api/lib/domain/services/mail-service.js, api/tests/unit/application/passwords/password-controller_test.js, api/tests/unit/domain/services/mail-service_test.js
Pix utilise différent nom de domaine : pix.fr, pix.org. 
Nous souhaitons que lorsqu’un utilisateur fait une demande de réinitialisation de mot de passe depuis un domaine, que les liens dans le mail envoyer redirige vers ce même domaine. Et nous voulons que pour les autres domaines que pix.fr, il n'y ai pas la Marianne dans le footer.
Ces deux domaines sont associés à des locales différentes
- Nous récupérons la locale de l'utilisateur dans le `password-controller` pour la fournir au `mail-service`.
https://github.com/1024pix/pix/blob/89574bf44e30301994e89a23d6e3713eac4393f2/api/lib/application/passwords/password-controller.js#L20-L21
- Nous avons ajouté des variables construites à partir de la locale, qui seront envoyés à notre mailer (SendInBlue). …
=> [FEATURE] Permettre à l'utilisateur d'obtenir un e-mail de réinitialisation de mot de passe en fonction de sa région (PIX-746).

api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/integration/infrastructure/repositories/knowledge-element-repository_test.js
Lors de l'analyse (individuelle et collective), les scores se trouvent supérieurs à 100, alors que normalement compris entre 0 et 100.
On doit filtrer les knowledge-elements ayant une date de création inférieure à la date de partage des résultats.
On doit également filtrer les knowledge-elements en ne gardant que les derniers
- répondre tout bon à la campagne QWERTY789 en étant userpix1 (je l'ai fait)
- aller sur pix orga dans l'onglet analyse et vérifier que dans "network" on a aucun `averageScore` dépassant 100
- idem dans l'onglet analyse individuelle
=> [BUGFIX] Récupérer les derniers knowledge-elements pour un skill avant la date de partage des résultats (PIX-767).

admin/nginx.conf.erb, api/server.js, certif/nginx.conf.erb, mon-pix/nginx.conf.erb, nginx.conf.erb, orga/nginx.conf.erb
La compression `gzip` des requêtes HTTP est faite au niveau applicatif alors que [le routeur Scalingo est capable de l'effectuer automatiquement](https://doc.scalingo.com/platform/internals/routing). Ceci consomme du CPU et de la mémoire inutilement sur les conteneurs applicatifs.
On désactive la compression :
* au niveau de HapiJS pour l'API ;
* au niveau `nginx` pour les applications _front_.
Sur une application Scalingo : vérifier que les réponses qui ont lieu de l'être (d'une taille supérieure à 1 kilo-octet environ) sont toujours compressées.
En local pour l'API : constater que les réponses API même conséquentes (ex. `/api/users/{id}/scorecards`) ne sont plus compressées.
=> [INFRA] Désactivation de la compression des réponses HTTP

mon-pix/app/components/challenge-item-qcm.js, mon-pix/app/components/qcm-proposals.js, mon-pix/app/templates/components/qcm-proposals.hbs
La façon dont on récupérait les réponses aux QCM utilisait le jQuery d'Ember, et était noté depuis longtemps en "FIX ME"
- Utiliser l'action answerChanged appelé à chaque modification pour récupérer la valeur et la mettre dans un tableau. Il faut aussi gérer le décochage.
- Ceci n'est qu'une proposition d'amélioration, la méthode actuelle ayant fait ses preuves au fil des années.
- Si cette façon convient, elle pourra être utilisé pour les QCU et d'autres types d'épreuves.
https://app-pr1457.review.pix.fr/courses/recvS3WQht3DV2nYM
=> [CLEANUP] Change la manière de récupérer les réponses d'un QCM (PIX-768).

mon-pix/app/templates/components/feedback-certification-section.hbs, mon-pix/app/templates/components/feedback-panel.hbs, mon-pix/tests/integration/components/feedback-certification-section-test.js, mon-pix/tests/integration/components/feedback-panel-test.js
Aujourd'hui, il y a 2 sources possibles de signalements dans le cadre d'une session de certification :
- la page de finalisation de session : le surveillant peut pendant la session noter tout incident concernant un candidat en particulier sur son PV de session, puis le reporter (lui ou toute personne en charge de l'espace Pix certif) sur la page de finalisation de session dans Pix certif
- le bouton "Signaler un problème" accessible depuis toutes les épreuves du test de certification
Seuls les signalements des surveillants sont pris en compte par le pôle certification qui pourra en fonction déclencher un jury si besoin. Il a donc été indiqué dans la dernière version du cahier des charges des centres de certification de ne plus demander aux candidats de "signaler un problème" via leur …
=> [FEATURE] Empêcher le candidat de faire un signalement pendant le test de certification (PIX-578)

api/lib/domain/models/CertificationPartnerAcquisition.js, api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
Le critère des 75% réussi par compétence a été mis en place sur les compétences Pix et non les compétences CléA (qui elles couvrent plusieurs compétences Pix). Ce qui signifie par exemple qu’un candidat n'étant pas certifiable sur une compétence Pix couverte par le CléA, ne pourra jamais avoir sa certif CléA alors qu’il aurait pu éventuellement se rattraper avec d’autres compétences Pix couvertes par la même compétence CléA
Il faut procéder au calcul d'évaluation de la certification CléA en se basant sur les compétences effectivement évaluées en certification (donc représentée dans les `competence-marks`). Plus précisément, il va s'agit d'une intersection entre les compétences certifiables (`competence-marks`) et les compétences PIX couvertes par CléA
=> [BUGFIX] Ne prendre en compte que les compétences évaluées en certification lors du scoring de certification CléA (PIX-679)

api/lib/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller.js, api/lib/application/users/user-controller.js, api/lib/config.js, api/lib/domain/services/mail-service.js, api/lib/domain/usecases/create-and-associate-user-to-schooling-registration.js, api/lib/domain/usecases/create-user.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/usecases/create-user_test.js
Pix utilise différent nom de domaine : pix.fr, pix.org. 
Nous souhaitons que lorsqu’un utilisateur se crée un compte depuis un domaine, que les liens dans le mail envoyer redirige vers ce même domaine. Et nous voulons que pour les autres domaines que pix.fr, il n'y ai pas la Marianne dans le footer.
Ces deux domaines sont associés à des locales différentes
- Nous récupérons la locale de l'utilisateur dans le `user-controller` pour la fournir à l'usecase qui la fournira au `mail-service`.
https://github.com/1024pix/pix/blob/b59a8421385fe5712fe196609b681573f207fe8a/api/lib/application/users/user-controller.js#L21-L29
- Nous faisons le même principe pour la création et reconciliation dans `schooling-registration-dependant-users` :
https://github.com/1024pix/pix/blob/f87e2953f665906c0959538bc5 …
=> [FEATURE] Permettre à l'utilisateur d'obtenir un e-mail de création de compte en fonction de sa région (PIX-745).

orga/app/components/user-logged-menu.js, orga/tests/acceptance/switch-organization-test.js
Une régression a été introduite récemment relative au changement de l'organisation courante dans Pix Orga. En effet, il arrive parfois que lors du clique sur une organisation afin de changer l'organisation courante, le rechargement du current-user (GET) soit effectué avant la requête de modification de l'organisation courante (PUT). Cette "inversion" de l'ordre des appels provoque un nom changement de l'affichage de l'organisation courante côté front bien que ce changement ait été pris en compte par l'API. Nous avons donc une désynchronisation entre la valeur de l'organisation courante côté back et côté front.
De plus, le menu ne se ferme pas suite au changement de l'organisation courante.
- Réparer le changement d'organisation.
- Fermer le menu suite au changement d'organisation.
Se …
=> [BUGFIX] Corrections relatives au changement d'organisation dans Pix Orga (PIX-538).

api/lib/domain/services/organization-invitation-service.js, api/lib/infrastructure/repositories/organization-invitation-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-invitation-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-invitation-repository_test.js, api/tests/unit/domain/services/organization-invitation-service_test.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-invitation-serializer_test.js, orga/app/models/organization-invitation.js, orga/app/templates/components/routes/authenticated/team/list-items.hbs, orga/tests/integration/components/routes/authenticated/team/list-items-test.js
Il est possible d'inviter plusieurs fois le même utilisateur à rejoindre une organisation dans Pix Orga. Cette ré-invitation ne recrée pas une entrée dans la table `organization-invitations` mais renvoie un email à l'utilisateur. Cependant, dans l'écran listant les invitations envoyées ne figure que la date de création de l'invitation ce qui ne permet pas à l'administrateur de l'organisation de s'assurer qu'un email a bien été envoyé.     
- Mettre à jour la date de modification d'une invitation à chaque ré-envoi d'un email.
- Afficher la dernière date de modification de l'invitation plutôt que sa date de création.  
Etant donné qu'il est possible de renvoyer plusieurs fois une invitation dans la même journée, on affiche dorénavant en plus de la date, l'heure à laquelle l'invitation à été …
=> [FEATURE] Afficher la dernière date d'envoi d'une invitation dans Pix Orga (PIX-730).

api/lib/infrastructure/serializers/jsonapi/campaign-participation-serializer.js, api/tests/acceptance/application/users/users-get-campaign-participations_test.js
Dans le bandeau "N'oubliez pas de finaliser votre envoi" nous devons voir le titre du parcours si le prescripteur en a renseigné un dans pix orga.
De plus, le message du bandeau affiché ne correspond pas à l'état actuel du parcous. Par exemple : Le bandeau d’envoi de résultat s’affiche alors que le parcours n’est pas terminé.
Les 2 problèmes observés sont liés au fait que la réponse de l'api `/users/{id}/campaign-participations` ne contient pas le type des campagnes liées aux participations. Par conséquent, le bandeau n'affichait que le texte par défaut qui était "N'oubliez pas de finaliser votre envoi".
Ajouter le type de la campagne dans la réponse de l'api `/users/{id}/campaign-participations`
1. Commencer une campagne d'évaluation: AZERTY123
2. Quitter le parcours
3. Faire un refresh …
=> [BUGFIX] Problème d'affichage de la bannière de reprise de parcours (PIX-770)

CHANGELOG.md
Le merge de la PR https://github.com/1024pix/pix/pull/1446 n'a pas été sans quelques problèmes. En effet, cette PR a embarqué par erreur des commits qui ne lui appartenait pas. Suite à diverses manips de drop, ré-ouverture de PR et re-merge, on s'est retrouvé avec un changelog qui présente deux fois la même entrée (une par PR ouverte).
On nettoie le changelog en conservant l'entrée pour la PR "corrective" (qui contient de toute façon un lien vers la PR d'origine)
Aucune régression attendue, c'est juste un diff de changelog
=> [CLEANUP] Correction du changelog après une mauvaise manip qui a provoqué la duplication d'une entrée (PIX-774)

api/sample.env
Lors de la PR #1471, 2 variables d'environnement ont été ajouté. 
```
DOMAIN_NAME_FR
DOMAIN_NAME_ORG 
```
Seulement, celles-ci n'ont pas été ajouté au fichier sample.env.
Ajouter ces variables dans le fichier sample.env et expliquer à quoi elles servent.
=> [INFRA] Ajouter les dernières variables d'environnement dans le fichier sample.env

high-level-tests/e2e/cypress/integration/pix-orga/student-management.feature, high-level-tests/e2e/cypress/support/step_definitions/student.js, orga/app/components/dropdown/content.hbs, orga/app/components/dropdown/icon-trigger.hbs, orga/app/components/dropdown/icon-trigger.js, orga/app/components/dropdown/item-link.hbs, orga/app/components/dropdown/item.hbs, orga/app/styles/app.scss, orga/app/styles/components/dropdown.scss, orga/app/styles/components/user-logged-menu.scss, orga/app/styles/pages/authenticated/students/list.scss, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/app/templates/components/user-logged-menu.hbs, orga/tests/acceptance/student-list-test.js, orga/tests/integration/components/dropdown/icon-trigger-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js, orga/tests/integration/components/user-logged-menu-test.js
Les utilisateurs de Pix Orga ne peuvent réaliser qu'une seule action ("gérer") sur un élève. Nous allons rajouter une action "dissocier" afin de dissocier un élève à son compte Pix si l'élève a fait une erreur.
Remplacer la roue crantée par un menu dropdown, afin de rajoutée une entrée à ce menu.
Création d'un composant et réutilisation de celui-ci au sein du composant `user-logged-menu`
- Se connecter en tant que sco@example.net
- Aller dans l'onglet élève
- Vérifier le bon fonctionnement du dropdown pour les élèves réconciliés
- Vérifier le bon fonctionnement de la pop-up au click sur "Gérer le compte"
- Vérifier le bon fonctionnement du menu pour changer de compte Orga
=> [FEATURE] Ajout d'un composant dropdown dans Pix Orga (PIX-716).

admin/app/components/organization-members-section.js, admin/app/styles/misc/tables.scss, admin/tests/acceptance/organization-memberships-management-test.js
Dans Pix Admin, toutes les colonnes du tableau listant les membres d'une organisation ont la même taille et il arrive parfois que l'adresse email ne soit pas entièrement visible car sa colonne est trop petite.  
Réduire la taille des colonnes `Numéro du membre`, `Rôle` et `Action`
La colonne `Numéro du membre` a été renommée en `ID Membre`
=> [BUGFIX] Réduction de la largeur de certaines colonnes dans le tableau des membres (PIX-459).

api/lib/application/assessments/assessment-controller.js, api/lib/domain/events/check-event-type.js, api/lib/domain/events/handle-badge-acquisition.js, api/lib/domain/events/handle-certification-partner.js, api/lib/domain/events/handle-certification-scoring.js, api/lib/domain/events/index.js, api/lib/infrastructure/events/EventDispatcher.js, api/lib/infrastructure/utils/dependency-injection.js, api/tests/integration/infrastructure/event-dispatcher_test.js, api/tests/tooling/events/event-dispatcher-builder.js, api/tests/unit/application/assessments/assessment-controller_test.js, api/tests/unit/domain/events/check-event-type_test.js, api/tests/unit/domain/events/event-choregraphy-badge-acquisition_test.js, api/tests/unit/domain/events/event-choregraphy-score-certification_test.js, api/tests/unit/domain/events/event-choregraphy-score-partner-certification_test.js, api/tests/unit/domain/events/handle-badge-acquisition_test.js, api/tests/unit/domain/events/handle-certification-partner_test.js, api/tests/unit/domain/events/handle-certification-scoring_test.js, docs/adr/0008-découplage-fonctionnel-via-evenements.md, docs/adr/0010-propager-domain-events-via-event-dispatcher.md
Les Domain Events sont passés à la mano entre les émetteurs et les handlers dans le controller.
Passer par un EventDispatcher (pub/sub) pour faire ça automatiquement.
Il reste à déplacer l'instanciation de l'EventDispatcher et les subscriptions hors du controller.
Valider une certification donnant lieu à un badge pix et cléa.
=> [TECH] Utiliser un EventDispatcher pour passer les Domain Events aux Event Handlers

api/tests/integration/infrastructure/utils/knex_utils_test.js
Un test unitaire de `knex-utils` échoue de façon aléatoire. Car dans le test, l'ordre des données insérées pendant l'initialisation du test n'est pas garantie et la requête testée ne contient pas d'`order by` dessus.
Ajout d'un `order by` dans la requête pour garantir toujours le même ordre dans le résultat de la requête.
=> [BUGFIX] Correction d'un test knex-utils aléatoire

mon-pix/app/styles/components/_checkpoint.scss
La flèche de checkpoint doit s'afficher en plus grand
Restaurer l'ancienne valeur
Aller jusqu'à un checkpoint
=> [BUGFIX] La flèche de checkpoint doit s'afficher en plus grand (PIX-811).

api/lib/domain/services/course-service.js, api/lib/infrastructure/repositories/course-repository.js, api/tests/acceptance/application/course-controller_test.js, api/tests/unit/domain/services/course-service_test.js, api/tests/unit/infrastructure/repositories/course-repository_test.js
Si on démarre un test de démo avec un courseId qui n'existe pas, l'API renvoie une erreur 500
Renvoyer un code 404 à la place.
Le CourseService ne sert plus à grand chose, la prochaine étape serait de le supprimer maintenant qu'il est en bonne santé.
Il y a aussi quelques appels explicites pour logger les erreurs, ce serait un job à faire en middleware.
=> [BUGFIX] Corrige une erreur 500 en 404 quand un test de démo n'est pas trouvé

api/db/migrations/20200608170256_alter_table_badgePartnerCompetences_column_color_from_notNullable_to_nullable.js, api/db/seeds/data/badge-target-profile-builder.js, api/lib/domain/models/CampaignParticipationResult.js, api/tests/integration/infrastructure/repositories/badge-repository_test.js, api/tests/tooling/database-builder/factory/build-badge-partner-competence.js, api/tests/tooling/domain-builder/factory/build-badge-partner-competence.js
L'implémentation impose de créer des `BadgePartnerCompetence` avec une couleur. C'était valable pour Pix Emploi. Avec l'introduction des nouveaux badges, c'est une règle qui n'est plus valable et contraignante.
Appliquer la modification en base de données 
Quelques questions en suspens : 
- est-ce qu'on doit tester davantage le cas null ?
- est-ce qu'on doit lui attribuer une couleur par défaut sachant qu'on ne l'exploitera jamais ?
C'est purement technique donc transparent. 
Éventuellement ajouter une nouvelle partner compétence sans couleur à un badge qui n'est pas celui de PixEmploi pour être sûr qu'il n'y a pas de bugs
=> [TECH] Simplification de la création de badge en BDD (PIX-736).

.circleci/config.yml, high-level-tests/e2e/cypress.json, high-level-tests/e2e/package.json
Le temps de build sur la CI dépasse largement les 10 minutes.
Cela ralentit la boucle de feedbacks.
Utiliser la fonctionnalité de parallélisation de cypress.
Cela permet de diviser par deux la durée des tests end-to-end (qui est le job le plus long dans notre pipeline).
Pour pouvoir utiliser cette fonctionnalité, il est nécessaire de créer un compte sur [cypress.io](dashboard.cypress.io).
Le compte est créé avec le login github (service+github@pix.fr).
Il est ensuite nécessaire de configurer circleCI pour fournir la `record key` comme variable d'environnement.
Cela se fait dans les `Organization settings`, en créant un `Context`.
Les informations de configuration sont dans le dashboard de cypress.io dans l'onglet `Organization settings`.
**Une demande de plan Open Source (qui nous …
=> [TECH] Paralléliser les tests end-to-end sur la CI.

api/scripts/create-sco-certification-centers.js
Le script de création des centres de certification écrit dans la log
`Starting creating or updating SCO organizations.`
Or, ce qui sera créé est un centre de certification (certification-center) , pas une organisation (organization). Cela peut causer de la confusion, ce dont on n'a pas besoin quand on insère en masse des données dans une table en production.
Remplacer la mention de l'organisation par celle du centre de certification (certification-center)
=> [CLEANUP] Clarifier la log du script de création des centres de certification.

admin/app/components/organization-members-section.hbs, admin/app/controllers/authenticated/organizations/get.js, admin/app/controllers/authenticated/organizations/get/members.js, admin/app/controllers/authenticated/organizations/get/target-profiles.js, admin/app/router.js, admin/app/routes/authenticated/organizations/get/index.js, admin/app/routes/authenticated/organizations/get/members.js, admin/app/routes/authenticated/organizations/get/target-profiles.js, admin/app/templates/authenticated/organizations/get.hbs, admin/app/templates/authenticated/organizations/get/members.hbs, admin/app/templates/authenticated/organizations/get/target-profiles.hbs, admin/tests/acceptance/organization-information-management-test.js, admin/tests/acceptance/organization-list-test.js, admin/tests/acceptance/organization-memberships-management-test.js, admin/tests/acceptance/organization-target-profiles-management-test.js, admin/tests/unit/controllers/authenticated/organizations/get/members-test.js
Trop d'informations sont contenues dans une seule et même page. Il existe plusieurs tableaux sur cette page, on si l'on veut faire une pagination pour chacun des tableaux, cela pose problème, car c'est la même url.
Ajouter un menu dans Pix Admin pour séparer les usages actuels de cette page :
- Les membres
- Les profils cibles
- Aller sur Pix Admin
- Aller dans l'onglet "organisations"
- Choisir une organisation et cliquer dessus
- Voir apparaître par défaut la page de membres
- Cliquer sur l'onglet "profils cibles" et vérifier le bon affichage
- Re-cliquer sur l'onglet "membres" et vérifier le bon affichage
=> [FEATURE] Ajouter un système d'onglets dans le détail d'une organisation dans Pix Admin (PIX-827).

api/lib/application/campaigns/index.js, api/tests/integration/application/campaigns/index_test.js
La route /campaigns/id/csvResults est une route dépréciée, plus utilisée. J'ai vérifié sur datadog, plus aucune utilisation de cette route depuis le début des logs.
Supprimer cette route.
=> [TECH] Suppression de la route dépréciée `/campaigns/id/csvResults` (PIX-832).

api/db/migrations/20200612093847_add-column-disabledAt-to-memberships.js, api/lib/infrastructure/repositories/prescriber-repository.js, api/lib/infrastructure/repositories/user-repository.js, api/tests/integration/infrastructure/repositories/prescriber-repository_test.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/tooling/database-builder/factory/build-membership.js
Lorsqu'un utilisateur ne fait plus partie d'une organisation, la solution utilisée consistait à supprimer le membership directement en base de donnée. Cette suppression de donnée n'est pas satisfaisante car on perd l'historique des appartenances à une organisation. 
Ajouter une date de désactivation dans la table `memberships` et alimenter cette date lorsque l'on souhaite désactiver l'appartenance d'un utilisateur à une organisation. Cette nouvelle façon de procéder implique que la présence d'un membership pour un utilisateur n'est plus suffisant pour valider l'appartenance à une organisation. Cette PR concerne :   
- L'ajout de la colonne en base
- La prise en compte de la date de désactivation lors de la connexion d'un utlisateur à Pix Orga
- La prise en compte de la date de …
=> [FEATURE] Empêcher la connexion à Pix Orga d'un utilisateur dont le membership a été désactivé (PIX-766).

admin/app/adapters/user.js, admin/app/components/user-detail-personal-information.hbs, admin/app/components/user-detail-personal-information.js, admin/app/templates/authenticated/users/get.hbs, admin/mirage/config.js, admin/tests/acceptance/user-details-personal-information-test.js, admin/tests/integration/components/user-detail-personal-information-test.js, api/lib/application/users/index.js, api/tests/acceptance/application/users/update-user-details-for-administration_test.js, api/tests/integration/application/users/index_test.js
L'aministrateur ne peut pas modifier les informations personnelles d'un utilisateur dans Pix Admin.
Proposer une page d'édition pour modifier le nom, prénom et l'email par un administrateur.
La modification n'est permise que pour les utilisateurs utilisant _exclusivement_ la méthode de connexion email.
Les autres informations personnelles ne sont pas ouvertes à la modification. 
Elles ne sont pas affichées dans la page d'édition.
Utilisation de ember-cp-validation pour gérer la validation.
Aller dans vue utilisateurs, cliquer sur une ligne.
Cliquer sur le bouton modifier pour voir le formulaire d'édition, modifier le contenu des champs, puis cliquer sur Editer.
=> [FEATURE] Permettre la mise à jour du prénom, nom et l'email d'un utilisateur connecté par email dans Pix Admin (PIX-458).

api/db/seeds/data/organizations-builder.js, api/lib/infrastructure/repositories/membership-repository.js, api/lib/infrastructure/repositories/organization-repository.js, api/tests/acceptance/application/security-pre-handlers_test.js, api/tests/acceptance/application/user-orga-settings-controller_test.js, api/tests/integration/infrastructure/repositories/membership-repository_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js
Lorsqu'un utilisateur ne fait plus partie d'une organisation, il apparait néanmoins
- dans Pix Admin (liste des membres d'une organisation),
- dans Pix Orga (Equipe)
Il ne devra plus apparaitre dans ces listes.
- Lorsque la liste des membres d'une organisation doit être récupérée, 
côté API, remonter uniquement les memberships dont le champ removedAt est vide.
- Dans l'API, les fonctions du `securityPreHandlers`, qui vérifient qu'un utilisateur est bien membre d'une organisation, tiendront compte de ce paramètre.
Cette branche est issue de la branche `pix-766-add-removedAt-to-memberships`.
L'utilisateur **mance.rayder@example.net** qui était membre de l'organisation **The Night Watch**, a été désactivé.
Vérifier qu'il n'apparait pas dans les listes citées plus haut.
=> [FEATURE] Ne plus afficher les membres désactivés dans PixOrga et PixAdmin (PIX-409).

api/lib/application/schooling-registration-dependent-users/index.js, api/lib/application/student-dependent-users/index.js, api/tests/integration/application/schooling-registration-dependent-users/index_test.js, api/tests/integration/application/schooling-registration-dependent-users/schooling-registration-dependent-user-controller_test.js, api/tests/integration/application/student-dependent-users/index_test.js
Une erreur 500 a été remontée suite à l'envoi d'une date invalide à l'API ("2005*-06-14") :
https://sentry.io/organizations/pix/issues/1704634340/events/454a8ab48deb407a9eefede275bea8dc/?project=1398749
Je n'ai malheureusement pas été en mesure de reproduire "normalement" cette erreur. Le processus d'inscription d'un élève s'effectue en deux étapes:
- Vérification de la possibilité d'associer un utilisateur à une `schooling-registration` via son nom, prénom et date de naissance (`PUT /api/student-user-associations/possibilities`). Cette route possède une validation front et back vérifiant le format de la date.
- Création de l'utilisateur et association de celui-ci à sa `schooling-registration` (`POST /api/student-dependent-users`). Cette route ne possède pas de validation et cette …
=> [BUGFIX] Format de date invalide lors de la création d'un utilisateur SCO (PIX-834).

admin/app/components/organization-information-section.hbs, admin/app/components/organization-information-section.js, admin/app/styles/app.scss, admin/app/styles/components/organization-information-section.scss, admin/config/environment.js, admin/tests/helpers/create-glimmer-component.js, admin/tests/unit/components/organization-information-section-test.js
La page de détail d'un organisation dans Pix admin manque d'informations.
Ces information sont disponibles dans Metabase, dans l'URL https://metabase.pix.fr/dashboard/137/?id={orga_id}
Ajouter un lien de la page PixAdmin vers Metabase
Il n'existe pas d'environnement de test Metabase, le lien redirigera toujours vers la base de production. L'authentification Metabase est à charge de l'utilisateur.
Local:
* démarrer l'application avec la variable  `ORGANIZATION_DASHBOARD_URL=https://metabase.pix.fr/dashboard/137/?id= npm start `
* aller sur le membre 4 dans [PixAdmin](http://localhost:4202/organizations/4/members)
RA:
* application Scalingo pix-**front**-review-pr1496 / Section "Environnement": ajouter une ligne `ORGANIZATION_DASHBOARD_URL=https://metabase.pix.fr/dashboard/137/?id=`   puis …
=> [FEATURE] Ajouter lien vers BI sur le détail d'une organisation (PIX-605).

.circleci/config.yml, INSTALLATION.md, admin/package.json, api/package.json, certif/package.json, high-level-tests/e2e/package.json, high-level-tests/load-testing/package.json, mon-pix/package.json, orga/package.json, package.json, scripts/configure.sh
Les versions LTS de node et npm ont été mises à jour mais nous n'avons pas effectué ces montées de versions.
Mettre à jour node vers la version 10.18.0.
Mettre à jour npm vers la version 6.14.4.
RAS
Les tests automatiques passent ➡️  🆗
=> [TECH] Montée de version de Node (12.18.0) et NPM (6.14.4).

high-level-tests/e2e/cypress.json, high-level-tests/e2e/package-lock.json, high-level-tests/e2e/package.json
Les jobs `e2e` CircleCI échouent de manière aléatoire.
Il est nécessaire de les relancer manuellement, parfois plusieurs fois de suite.
Exemples :
- https://app.circleci.com/pipelines/github/1024pix/pix/11492/workflows/0606b104-3bc2-4b29-a278-bfd684acb24e/jobs/115379
- https://app.circleci.com/pipelines/github/1024pix/pix/11492/workflows/98637618-a471-4c8e-8e95-c953bbdd4215/jobs/115374
Le message d'erreur est à chaque fois le suivant.
```
CypressError: `cy.screenshot()` timed out waiting `30000ms` to complete.
```
En cherchant dans le repo de cypress, la discussion suivante indique 2 possibles actions pour corriger la survenue de ce problème.
https://github.com/cypress-io/cypress/issues/5016
Les 2 actions sont :
- Utiliser une version supérieure à 79 de Chrome (en l'occurence on prend la …
=> [TECH] Correction des tests e2e qui échouent aléatoirement sur la CI.

certif/package-lock.json, certif/package.json
L'affichage des notifications est cassé : les icônes sont affichées très grandes et le texte au centre de la page au lieu d'en bas à droite.
Mettre à jour ember-cli-notification.
Cette dépendance était déjà à jour dans orga et admin.
- npm install
- ouvrir une session non finalisée
- la finaliser, et observer une notification en bas à droite, verte ou rouge.
=> [BUGFIX] Mauvais affichage des notifications après la finalisation (PIX-848)

api/lib/domain/read-models/CampaignProfile.js, api/lib/domain/read-models/CampaignProfileCompetence.js, api/lib/infrastructure/serializers/jsonapi/campaign-profile-serializer.js, api/tests/unit/domain/read-models/CampaignProfile_test.js, api/tests/unit/infrastructure/serializers/jsonapi/campaign-profile-serializer_test.js, orga/app/models/campaign-profile-competence.js, orga/app/models/campaign-profile.js, orga/app/styles/app.scss, orga/app/styles/globals/tables.scss, orga/app/styles/pages/authenticated/campaigns/profile.scss, orga/app/templates/components/routes/authenticated/campaigns/profile/profile.hbs, orga/app/templates/components/routes/authenticated/campaigns/profile/table.hbs, orga/tests/integration/components/routes/authenticated/campaigns/profile/table-test.js, orga/tests/unit/models/campaign-profile-test.js
Sur un profil d'une collecte de profil, on ne voit pas le détail du score et des niveaux par compétences.
Ajouter le tableau de compétence pour le profile de l'utilisateur avec le score et niveau par compétence.
(Uniquement s'il a partagé son profil, sinon indiqué qu'il n'est pas partagé).
1. Se connecter sur pix-orga avec le compte pro@example.net
2. Se rendre sur le campagne "Campagne Collecte Profils"
3. Cliquer sur l'onglet Participants
4. Cliquer sur un participant qui n'a pas partagé ses résultats
> Observer le message en "Attente de résultats"
5. Revenir en arrière et cliquer sur un participant qui a partagé ses résultats
> Observer la liste des compétences triée par index de compétence
> Avec un bordure de couleur pour chaque domaine
> Avec le nom de la compétence, le niveau …
=> [FEATURE] Afficher les competences avec score et niveau pour un participant (PIX-622)

.circleci/config.yml, admin/package.json, api/package.json, certif/package.json, high-level-tests/e2e/cypress.json, high-level-tests/e2e/package.json, high-level-tests/load-testing/package.json, mon-pix/package.json, orga/package.json, package.json
Dans la PR de montée de version de node vers 12.18.0, la version de node vérifiée (via la clé `engines` du `package.json`) était 12.x.x.
Spécifier la version `12.18.x` et utiliser la bonne image docker cypress pour le job de la CI.
On en profite pour ajouter la vérification dans les applications `high-level-tests`.
La CI passe, c'est tout ✅
=> [TECH] Assurer que la version de node installée est 12.18.x.

api/lib/application/organizations/organization-controller.js, api/lib/domain/usecases/find-user-with-schooling-registrations.js, api/lib/infrastructure/repositories/schooling-registration-repository.js, api/lib/infrastructure/utils/query-params-utils.js, api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/domain/usecases/find-organization-students_with-users-infos-test.js, orga/app/adapters/student.js, orga/app/components/password-reset-modal.js, orga/app/controllers/authenticated/students/list.js, orga/app/routes/authenticated/students/list.js, orga/app/templates/authenticated/students/list.hbs, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/mirage/config.js, orga/tests/acceptance/student-list-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js, orga/tests/unit/adapters/student-test.js
On ne peut pas filtrer la liste des élèves par nom dans pix-orga.
Ajout d'un filtre sur la colonne nom dans la liste des élèves.
N/A
1. Se connecter sur pix-orga avec sco@example.net
2. Cliquer sur "Elèves" dans le menu de gauche
3. Saisir un nom dans le champ de filtre des élèves dans la colonne nom
> Observer que la liste est filtré en rapport avec le filtre saisi
=> [FEATURE] Filtrer les élèves par nom dans pix-orga (PIX-719).

api/lib/application/sessions/index.js, api/lib/config.js, api/lib/domain/validators/id-specification.js, api/lib/domain/validators/session-validator.js, api/tests/acceptance/application/session/session-controller-get_test.js, api/tests/unit/application/session/index_test.js
Lorsqu'on cherche une session avec un identifiant trop grand (> 2147483647), l'api lève une erreur 500.
Valider que l'identifiant est inférieur à la valeur max acceptée par PostgreSQL en amont de l'appel à PostgreSQL et retourner une erreur 422.
Il y avait aussi un `idValidator` dans `lib/config.js`, on l'a déplacé dans `lib/domain/validators`.
Pour aller plus loin, l'erreur 422 n'est pas la plus appropriée mais l'erreur 400 (mauvaise requête) semble meilleure.
De plus la recherche filtrant sur différents paramètres + l'identifiant semble inutile : on peut utiliser la route qui retrouve une session avec l'identifiant. (GET /jury/sessions/{id}).
Sur pix admin, faire une recherche de sessions avec l'identifiant 5656355634.
=> [BUGFIX] Ne pas lever une erreur 500 lors de la recherche d'une session avec un identifiant trop grand.

admin/tests/unit/components/certification-details-competence-test.js, admin/tests/unit/components/certification-info-competences-test.js, admin/tests/unit/components/certification-info-field-test.js, admin/tests/unit/components/organization-information-section-test.js, admin/tests/unit/serializers/certification-details-test.js, admin/tests/unit/serializers/certification-test.js, admin/tests/unit/serializers/organization-test.js, admin/tests/unit/services/csv-service-test.js, certif/tests/unit/routes/application-test.js, orga/tests/unit/models/campaign-test.js, orga/tests/unit/models/competence-result-test.js, orga/tests/unit/models/student-test.js, orga/tests/unit/routes/application-test.js, orga/tests/unit/routes/not-found-test.js
Lors de la création d'un composant, Ember génère un test modèle qui vérifie uniquement l'existence du composant.
>   test('it exists', function(assert) {
>     const route = this.owner.lookup('route:not-found');
>     assert.ok(route);
>   });
Dès l'écriture d'un autre test, l'existence du composant est implicitement couverte, et ce test modèle génère du bruit.
Supprimer ce test dans les fichiers où au moins un autre test existe
Couvert par la CI
=> [TECH] Supprimer les tests unitaires Ember redondants

admin/app/adapters/user.js, admin/app/components/user-detail-personal-information.hbs, admin/app/components/user-detail-personal-information.js, admin/app/styles/misc/button.scss, admin/app/styles/misc/palette.scss, admin/mirage/config.js, admin/tests/acceptance/user-details-personal-information-test.js, admin/tests/integration/components/user-detail-personal-information-test.js, admin/tests/unit/adapters/user-test.js, api/lib/application/users/index.js, api/lib/application/users/user-controller.js, api/lib/domain/usecases/anonymize-user.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/user-repository.js, api/tests/acceptance/application/users/users-controller-anonymize-user_test.js, api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js, api/tests/tooling/database-builder/factory/build-user.js, api/tests/unit/application/users/index_test.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/usecases/anonymize-user_test.js
Aujourd'hui, le processus d'anonymisation d'un utilisateur consiste à modifier ses attributs nom, prénom et email sous la forme:
- Prénom: `prenom_{userId}`
- Nom: `nom_{userId}` 
- Email: `email_{userId}@example.net`
Cette modification est faite directement en base de donnée ce qui peut générer des erreurs.  
Ajouter un bouton `Anonymiser cet utilisateur` depuis la page de détail d'un utilisateur dans Pix Admin afin d'effectuer ce processus d'anonymisation.
=> [FEATURE] Permettre l'anonymisation d'un utilisateur depuis Pix Admin (PIX-729)

orga/app/components/routes/authenticated/campaigns/details/parameters-tab.js, orga/app/models/campaign.js, orga/app/services/current-domain.js, orga/app/services/url.js, orga/app/templates/components/routes/authenticated/campaigns/details/parameters-tab.hbs, orga/config/environment.js, orga/tests/integration/components/routes/authenticated/campaigns/details/parameters-tab-test.js, orga/tests/unit/services/url-test.js
app.pix est maintenant disponible en .org. Or, l'url de campagnes que l'on fourni sur Pix Orga est toujours en .fr !
- Faire un alias de orga.pix.fr en orga.pix.org ✔️ 
- Conditionner l'url sur l'extension du site sur lequel on est (cette PR)
La logique a été inspirée de ce qui a été fait sur app.pix par la team Expérience d'évaluation
Sur https://orga-pr1534.review.pix.fr et sur https://orga-pr1534.review.pix.org :
- Aller voir le détail d'une campagne
- Vérifier que l'affichage du lien est correct
- Vérifier que lors de la copie (petit bouton copier) la copie est correcte
=> [FEATURE] Afficher l'url d'une campagne dans Pix Orga suivant l'extension sur laquelle on est (fr ou org) (PIX-826).

admin/app/components/user-detail-personal-information.hbs, admin/app/components/user-detail-personal-information.js, admin/app/styles/app.scss, admin/app/styles/components/user-detail-personal-information-section.scss, admin/config/environment.js, admin/tests/unit/components/user-detail-personal-information-test.js
La page de détail d'un utilisateur dans Pix admin manque d'informations.
Ces information sont disponibles dans Metabase, dans l'URL `https://metabase.pix.fr/dashboard/132?id={user_id}`
Ajouter un lien de la page PixAdmin vers Metabase
Il n'existe pas d'environnement de test Metabase, le lien redirigera toujours vers l'environnement Metaase de production, qui utilise des données répliquées de la production. L'authentification Metabase est à charge de l'utilisateur.
Local:
* démarraer l'application avec la variable => `USER_DASHBOARD_URL=https://metabase.pix.fr/dashboard/132/?id= npm start `
* aller sur le membre 4 dans [PixAdmin](http://localhost:4202/users/3)
RA:
* application Scalingo pix-**front**-review-pr1496 / Section "Environnement": ajouter une ligne …
=> [FEATURE] Ajouter lien sur le tableau de bord d'un utilisateur (PIX-606).

api/lib/application/schooling-registration-user-associations/index.js, api/lib/application/schooling-registration-user-associations/schooling-registration-user-association-controller.js, api/lib/domain/usecases/dissociate-user-from-schooling-registration.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/schooling-registration-repository.js, api/lib/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/application/schooling-registration-user-association-controller_test.js, api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js, api/tests/tooling/domain-builder/factory/build-schooling-registration.js, api/tests/unit/domain/usecases/dissociate-user-from-schooling-registration_test.js, api/tests/unit/infrastructure/serializers/jsonapi/user-with-schooling-registration-serializer_test.js, orga/app/adapters/student.js, orga/app/components/dissociate-user-modal.js, orga/app/components/routes/authenticated/students/list-items.js, orga/app/controllers/authenticated/students/list.js, orga/app/models/student.js, orga/app/styles/app.scss, orga/app/styles/components/dissociate-user-modal.scss, orga/app/styles/components/modal.scss, orga/app/templates/authenticated/students/list.hbs, orga/app/templates/components/dissociate-user-modal.hbs, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/mirage/config.js, orga/tests/acceptance/dissociate-student-test.js, orga/tests/integration/components/dissociate-user-modal-test.js, orga/tests/unit/adapters/student-test.js, orga/tests/unit/models/student-test.js
Si un élève ou un professeur s’associe avec un compte au lieu d’une autre personne, il n’y a aucun moyen de défaire cette association. Des demandes à la hotline sont crées pour réaliser la dissociation. C’est pourquoi dans cette US, les administrateurs  de chaque organisation “sco, ismanagingstudent” pourront réaliser eux même la dissociation d'élève.
Ajouter une modal pour dissocier un compte sur Pix ORGA  
RAS
Se connecter à Pix ORGA avec un compte ADMIN sur une orga qui gère des étudiants et essayer de dissocier le compte d'un étudiant.
=> [FEATURE] Dissocier les comptes utilisateurs des élèves depuis Pix ORGA (Pix-718).

.circleci/config.yml, api/tests/integration/infrastructure/repositories/badge-repository_test.js, docker-compose.yml
La BDD est un service fourni par Scalingo, qui met à disposition un service de mise à jour de version. En local, les développeurs utilisent une BDD dans un conteneur, configurée via le fichier `docker-compose.yml.` Dans l'intégration continue, la version de BDD est également conditionnée par une configuration Docker `.circleci/config.yml`
Il est donc possible d'effectuer une montée de version dans Scalingo sans tester que cette montée de version n'introduire de régression.
Scalingo propose actuellement une montée de 11.7.0 vers 12.2.0-6 ([CHANGELOG](https://www.postgresql.org/docs/release/12.2/))
Suite à [discussion](https://1024pix.slack.com/archives/CVAMDQYHY/p1590415078003200) avec @jbuget et @jonathanperret, il est souhaitable d'effectuer cette montée de version. 
Description …
=> [TECH] Montée de la BDD en version 12

admin/app/components/user-detail-personal-information.hbs, admin/app/models/user.js, admin/tests/integration/components/user-detail-personal-information-test.js
Empêcher l'édition du nom, prénom, email d'un utilisateur connecté via le GAR dans Pix Admin.
Uniformiser l'écriture de la variable  isAuthenticatedFromGAR entre l'API et l'IHM.
Dans la vue utiliisateur dans Pix Admin, afficher le détail d'un utilisateur connecté via le GAR. 
Vérifier que le bouton Modifier n'est pas affiché dans la page de détail des utilisateurs.
=> [BUGFIX] Empêcher l'édition des informations d'un utilisateur connecté via le GAR depuis Pix Admin(PIX-861)

orga/app/services/current-user.js, orga/mirage/config.js, orga/tests/unit/services/current-user-test.js
Il arrive parfois que l'on ait besoin de désactiver un `membership` afin de couper l'accès à Pix Orga. Cependant, si l'utilisateur est toujours connecté quand cette désactivation arrive et qu'il rafraîchit la page, alors une page blanche apparaît (avec une erreur dans la console). 
Déconnecter l'utilisateur qui n'a plus de `membership`.
- Se connecter à Pix Orga
- Supprimer en base son `membership`
`select id from users where email = 'sco@example.net';  ` => 4
`delete from memberships where "userId" = 4;`
- Rafraîchir la page (F5) et vérifier que l'on est bien déconnecté
=> [BUGFIX] Déconnecter un utilisateur qui n'a plus de membership dans Pix Orga (PIX-837).

mon-pix/app/components/routes/register-form.js, mon-pix/app/controllers/campaigns/restricted/join.js, mon-pix/app/routes/campaigns/restricted/join.js, mon-pix/app/templates/campaigns/restricted/join.hbs, mon-pix/tests/integration/components/routes/register-form-test.js, mon-pix/tests/unit/controllers/campaigns/restricted/join.js
Les formulations d'erreurs et de titre ne sont pas très explicite lors de la réconciliation entre un compte Pix et une inscription d'élève.
Améliorer ces wordings : 
- Les informations saisies ont déjà été utilisées. Prévenez l’organisateur. > **Vous avez déjà rejoint votre établissement avec un autre compte. Retrouvez-le. En cas d’oubli, contactez votre enseignant.** (1)
- Vérifiez vos informations afin de continuer ou prévenez l’organisateur de votre parcours. > **Vous êtes enseignant ? L’accès à un parcours n’est pas disponible pour le moment. Vous êtes un élève ? Vérifiez vos informations afin de continuer ou prévenez l’organisateur de votre parcours.** (2)
- Un tout petit détail > **Rejoignez l’organisation NOM_DE_LORGANISATION** (3)
1 : Se connecter à Pix avec un premier compte, …
=> [FEATURE] Amélioration des formulations lors de la réconciliation (PIX-816).

api/lib/application/users/user-controller.js, api/lib/domain/services/mail-service.js, api/lib/domain/usecases/create-and-associate-user-to-schooling-registration.js, api/lib/domain/usecases/create-user.js, api/lib/infrastructure/utils/url-builder.js, api/tests/acceptance/application/users/users-controller-save_test.js, api/tests/unit/application/users/user-controller_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/usecases/create-and-associate-user-to-schooling-registration_test.js, api/tests/unit/domain/usecases/create-user_test.js, api/tests/unit/infrastructure/utils/url-builder_test.js, mon-pix/app/adapters/user.js, mon-pix/app/components/signup-form.js, mon-pix/tests/unit/adapters/user-test.js, mon-pix/tests/unit/components/signup-form-test.js
Certains utilisateurs créent leur compte en voulant rejoindre un parcours. 
Lorsqu'ils reçoivent l'e-mail, le lien dans celui-ci les redirige vers la page de profil. Ils commencent alors un positionnement et non leur parcours. 
Modifier le lien présent dans l'e-mail pour ces utilisateurs par celui de leur parcours. 
Pour cela : 
- Passer dans le payload en meta le code de la campagne 
- Créer un url-builder qui nous permet d'obtenir l'url de la campagne grâce au code campagne
- Remplacer le lien par défaut dans le service d'envoie d'e-mail par celui de la campagne.
- Créer un compte depuis la page d'inscription.
- Créer un compte en voulant rejoindre un parcours aussi bien en tant qu'utilisateur lambda ou comme étudiant.
=> [FEATURE] Permettre à l'utilisateur de rejoindre son parcours grâce à l'e-mail de création de compte (PIX-429).

orga/app/components/dissociate-user-modal.js, orga/tests/integration/components/dissociate-user-modal-test.js
Suite à la dissociation d'un élève, l'utilisateur n'a pas de retour clair sur la réussite ou l'échec de l'opération.
Ajout d'un notification qui informe l'utilisateur de si la dissociation a bien réussie ou échoué.
Se connecter avec le compte sco@example.net
Allez sur la page "Eleves"
Dissocier un élève et constater la présence d'une notification de succès
Pour l'erreur il faut se mettre en local : 
Throw une erreur dans le usecase de la dissociation
Se connecter avec le compte sco@example.net
Allez sur la page "Eleves"
Dissocier un élève et constater la présence d'une notification d'erreur
=> [FEATURE] Ajout d'un retour utilisateur lors de la dissociation d'un élève (PIX-865)

api/lib/application/assessment-results/assessment-result-controller.js, api/lib/application/certification-courses/certification-course-controller.js, api/lib/domain/models/CertificationResult.js, api/lib/domain/models/CompetenceMark.js, api/lib/domain/models/ResultCompetenceTree.js, api/lib/domain/services/assessment-result-service.js, api/lib/domain/services/certification-service.js, api/lib/infrastructure/repositories/assessment-repository.js, api/lib/infrastructure/repositories/competence-mark-repository.js, api/lib/infrastructure/serializers/jsonapi/certification-result-serializer.js, api/scripts/get-results-certifications.js, api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js, api/tests/integration/infrastructure/repositories/assessment-repository_test.js, api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js, api/tests/tooling/database-builder/factory/build-competence-mark.js, api/tests/unit/application/assessment-results/assessment-result-controller_test.js, api/tests/unit/domain/events/handle-certification-scoring_test.js, api/tests/unit/domain/models/CleaCertification_test.js, api/tests/unit/domain/models/CompetenceMark_test.js, api/tests/unit/domain/services/assessment-result-service_test.js, api/tests/unit/domain/services/certification/certification-service_test.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-result-serializer_test.js, api/tests/unit/scripts/get-results-certifications_test.js
Bug introduit par la PR https://github.com/1024pix/pix/pull/1468
Petit oubli de renommage. Un des commits provoque le renommage de `area-code` et `competence-code` (attributs de CompetenceMark) en respectivement `area_code` et `competence_code`
Corriger la coquille.
Aucun test auto n'a détecté ce problème, donc il faudrait peut-être trouvé où est-ce qu'on peut l'introduire.
Après, je sais que la tâche n'est pas aisée (la modification de résultats de certif dans PA n'est pas le code le plus carré de la base de code...)
Si on change le statut d'une certif en _started_, on a un crash 500. C'est dû à la spécification Bookshelf qu'on a donné d'un `AssessmentResult`. Dans le fichier `lib/infrastructure/data/assessment-result.js` on définit une liste finie de valeurs possibles pour le statut. …
=> [BUGFIX] Erreur lorsqu'on tente de modifier une certification sur PixAdmin (PIX-866)

mon-pix/app/routes/reset-password.js, mon-pix/tests/acceptance/reset-password-test.js
Lorsqu'un utilisateur fait une demande de réinitialisation de mot passe. Si celui-ci clique dans le lien dans l'email en étant connecté alors il est redirigé dans vers son profil. 
Enlever l`UnauthenticadtedRouteMixin` de la route de changement de mot de passe. 
- Faire une demande de changement de mot de passe 
- Etre connecté et cliquer dans le lien dans l'email
- Vérifier que l'on peut bien accéder à la page et changer son mot de passe.
=> [BUGFIX] Permettre à un utilisateur connecté d'aller sur la page de changement de mot de passe (PIX-516).

api/lib/infrastructure/repositories/schooling-registration-repository.js, api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js, api/tests/tooling/database-builder/factory/build-schooling-registration-with-user.js, api/tests/tooling/database-builder/factory/index.js, api/tests/unit/application/organizations/organization-controller_test.js, orga/app/components/search-input.hbs, orga/app/components/search-input.js, orga/app/components/select-input.hbs, orga/app/controllers/authenticated/campaigns/list.js, orga/app/controllers/authenticated/students/list.js, orga/app/models/student.js, orga/app/routes/authenticated/students/list.js, orga/app/styles/app.scss, orga/app/styles/components/select-input.scss, orga/app/styles/globals/forms.scss, orga/app/templates/authenticated/campaigns/list.hbs, orga/app/templates/authenticated/students/list.hbs, orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs, orga/app/templates/components/routes/authenticated/campaigns/select-creator.hbs, orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/app/templates/components/search-input.hbs, orga/mirage/config.js, orga/tests/acceptance/student-list-test.js, orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js, orga/tests/unit/controllers/authenticated/campaigns/list-test.js
On ne peut pas filtrer la liste des élèves par type de connexion dans pix-orga.
Ajout d'un filtre sur la colonne type de connexion dans la liste des élèves.
N/A
1. Se connecter sur pix-orga avec sco@example.net
2. Cliquer sur "Elèves" dans le menu de gauche
3. Sélectionner un type de connexion dans le champ de filtre des élèves dans la colonne "connecté avec"
> Observer que la liste est filtré en rapport avec le filtre saisi
=> [FEATURE] Filtrer les élèves par type de connexion dans pix-orga (PIX-722)

api/lib/domain/services/smart-random/data-fetcher.js, api/lib/domain/services/smart-random/skills-filter.js, api/lib/domain/services/smart-random/smart-random.js, api/tests/integration/domain/services/smart-random/smart-random_test.js, api/tests/unit/domain/services/smart-random/data-fetcher_test.js, api/tests/unit/domain/services/smart-random/skills-filter_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-campaign-assessment_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-competence-evaluation_test.js
Suite au bug remonté mi-février, durant lequel des utilisateurs avaient des réponses (answers) enregistrées mais pas les éléments de connaissances (KE) associés, il a été remarqué que l'algorithme de choix de question posait problème lorsque la base de données n'était pas cohérente. Une première correction a été apportée en ajoutant une transaction pour s'assurer du bon enregistrement entre les deux. Malgré cela, la problématique de l'algorithme qui ne fonctionne pas quand la base n'est pas saine doit être réglée.
On filtre les challenges sur la présence ou non d'answers.
=> [BUGFIX] Éviter de reposer un challenge auquel on a déjà répondu (PIX-210).

mon-pix/app/components/user-certifications-detail-header.js, mon-pix/app/models/certification.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_user-certification-hexagon-score.scss, mon-pix/app/styles/components/_user-certifications-detail-banner.scss, mon-pix/app/styles/components/_user-certifications-detail-header.scss, mon-pix/app/styles/components/_user-certifications-detail-result.scss, mon-pix/app/styles/pages/_user-certifications-get.scss, mon-pix/app/templates/components/user-certifications-detail-header.hbs, mon-pix/app/templates/components/user-certifications-detail-result.hbs, mon-pix/app/templates/components/user-certifications-hexagon-score.hbs, mon-pix/app/templates/user-certifications.hbs, mon-pix/app/templates/user-certifications/get.hbs, mon-pix/app/templates/user-certifications/index.hbs, mon-pix/public/images/macaron-certif.svg, mon-pix/tests/integration/components/user-certifications-detail-header-test.js, mon-pix/tests/integration/components/user-certifications-detail-result-test.js
Lors de l'epix "Partage et contrôle du certificat" un nouveau design de certificat a été créé.
Ce nouveau design permettra d'aider au partage du certificat (notamment avec une vérification par code).
Cette première partie permet de changer le "header"/haut du certificat : 
- ajout de la bannière bleu de fond
- modification du contenu du premier bloc blanc (ajout d'un nouveau hexagone de certif + formatage du texte)
- suppression de l'ancien macaron et inversement des deux panels du bas
Résultat attendu pour cette PR : 
Modèles responsives ici : https://app.abstract.com/projects/3e4937ef-48a8-408b-9edd-1f69dab81b39/branches/288b95d2-6697-44a9-a4ba-2339a4480aad/collections/4ea4253d-5685-4ffc-afaa-632e144ec8f4
- lancer l'app mon-pix
- se connecter avec un compte ayant passé une certif et …
=> [FEATURE] PART-1 : Nouveau visuel certificat (PIX-597)

api/tests/integration/infrastructure/repositories/schooling-registration-repository_test.js
Le test suivant plante aléatoirement dans la CI
Suite à un merge malencontreux, le firstName d'un jeu de donnée a été effacé
Avant le merge:
Après le merge:
Le firstName est alors généré par faker ce qui peut parfois faire planter le test.
Remettre le firstName en dur dans le jeu de donnée.
N/A
=> [BUGFIX] Correction d'un test aléatoire sur les filtres des élèves

mon-pix/app/components/password-reset-demand-form.js, mon-pix/app/routes/reset-password.js, mon-pix/app/services/errors.js, mon-pix/app/styles/components/_password-reset-demand-form.scss, mon-pix/app/styles/pages/_sign-form.scss, mon-pix/app/templates/components/password-reset-demand-form.hbs, mon-pix/tests/acceptance/reset-password-test.js, mon-pix/tests/integration/components/password-reset-demand-form-test.js, mon-pix/tests/unit/services/errors-test.js
Lorsqu'un utilisateur clique de nouveau dans le lien de l'email de réinitialisation de mot de passe après avoir déjà changé celui-ci. Ou lorsqu'il tape un mauvais token après `/changer-mot-de-passe`. Il se retrouve sur une page d'erreur peu explicite.  
Rediriger l'utilisateur sur la page de demande de réinitialisation de mot de passe et lui fournir un message d'erreur plus explicite. 
Un nouveau service `errors` a été ajouté. Il permet de pusher une erreur depuis un endroit et de la récupérer à un autre. 
Dans le component cela donne : 
- dans le fichier js : 
- l'import du service : 
https://github.com/1024pix/pix/blob/4b8d3e09fba3d000f66961579db86b19c3afc41f/mon-pix/app/components/password-reset-demand-form.js#L7
- l'ajout de deux méthodes : …
=> [BUGFIX] Gérer les erreurs sur la page de changement de mot de passe (PIX-434).

mon-pix/app/components/feedback-panel.js, mon-pix/app/components/tutorial-item.js, mon-pix/app/templates/components/feedback-panel.hbs, mon-pix/app/utils/button-status-types.js, mon-pix/config/environment.js, mon-pix/tests/unit/components/feedback-panel-test.js
Lorsqu'un utilisateur double-clique sur l'envoi de signalement, nous enregistrons deux entrées en base de données.
Ajouter un statut au bouton d'envoi de signalement
- Nous en avons profité pour enlever jQuery du fichier.
Pour cela, nous utilisons https://developer.mozilla.org/fr/docs/Web/API/Element/scrollIntoView.
Ce nettoyage se fait au prix de l'animation douce lors de l'ouverture du formulaire de signalement.
Les options d'animation proposées par la méthode `scrollIntoView` ne nous ont pas permis d'obtenir un résultat similaire. 
La variable d'environnement `SCROLL_DURATION` est alors supprimée.
À voir si on conserve comme cela. 
1 - Se rendre sur une épreuve
2 - Ouvrir le feedback + le panel de network du browser
3 - Double-cliquer sur le bouton d'envoi et constater qu'il n'y a …
=> [BUGFIX] Bloquer les double-clics sur l'envoi de signalements (PIX-704).

api/lib/application/organizations/organization-controller.js, api/lib/config.js, api/lib/domain/services/mail-service.js, api/lib/domain/services/organization-invitation-service.js, api/lib/domain/usecases/create-organization-invitations.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/domain/services/mail-service_test.js, api/tests/unit/domain/services/organization-invitation-service_test.js, api/tests/unit/domain/usecases/create-organization-invitations_test.js, orga/app/adapters/application.js, orga/tests/unit/adapters/application-test.js, scalingo.json
Nous avons récemment mis en place orga.pix.org. Nous souhaitons que lorsqu'un administrateur est sur ce nouveau domaine, que les mails d'invitations redirigent vers ce même domaine. 
- Envoyer le header Accept-language pour tous les requêtes de Pix Orga.
- Récupérer la locale grâce à la méthode `extractLocaleFromRequest` et la passer au mail service pour qu'il construise la bonne url de redirection.
S'inviter dans une organisation depuis les différents domaines et voir que les liens sont différents en fonction de ce dernier.
=> [FEATURE] Permettre à un prescripteur d'obtenir un e-mail d'invitation en fonction de sa région (PIX-810).

mon-pix/app/components/signup-form.js, mon-pix/tests/acceptance/start-campaigns-with-type-assessment-test.js, mon-pix/tests/unit/components/signup-form-test.js
La PR #1516 ne se comporte pas comme attendu suite à un changement concommitant : le fragment d'URL campaign_code a été remplacé par code dans `http://<HOST>/campagnes/<CAMPAIGN_CODE>`.
Mettre à jour le fragment de route lu dans le code.
Rajouter un test pour prendre en charge ce cas.
Etapes:
* activer le mailing: ajouter la variable d'environnement `MAILING_ENABLED=true`
* aller sur la [campagne AZERTY123](https://app-pr1558.review.pix.fr/campagnes/AZERTY123/presentation)
* créer un compte
* démarrer le parcours
* ouvrir l'email d'inscription et cliquer sur le lien
* vérifier l'on est redirirgé sur le parcours
=> [BUGFIX] Rediriger le prescrit vers son parcours après inscription (PIX-886).

mon-pix/app/components/competence-card-default.js, mon-pix/app/styles/components/_competence-card-desktop.scss, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/templates/components/competence-card-default.hbs, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/tests/integration/components/competence-card-default-test.js, mon-pix/tests/unit/components/competence-card-default-test.js
- Le bouton Retenter n'est actuellement présent que sur la page de la compétence
- Ajouter le bouton retenter, dans le même style que Commencer, sur la carte de la compétence
- Changement de style de la même manière sur la page de détail de la compétence
- Glimmerisation de CompetenceCardDefault
- Finir une compétence pour avoir le bouton Retenter
=> [FEATURE] Afficher le bouton retenter sur la carte de la competence (PIX-757).

api/lib/application/authentication/index.js, mon-pix/app/components/signin-form.js, mon-pix/app/styles/pages/_sign-form.scss, mon-pix/app/templates/components/signin-form.hbs, mon-pix/config/ember-intl.js, mon-pix/config/environment.js, mon-pix/tests/integration/components/signin-form-test.js, mon-pix/translations/en-us.json, mon-pix/translations/fr-fr.json
A date d'aujourd'hui, il existe un seul message affiché pour l'ensemble des erreurs générées lors de la connexion et de la demande de réinitilisation de mot de passe  dans Pix App `L'adresse e-mail et/ou le mot de passe saisis sont incorrects.`
Ce fonctionnement induit l'utilisateur final en erreur , ce qui pourrait le pousser à mener des actions en vain telle que la modification de son MDP même si ses  identifiants sont corrects.
En outre, les champs du formulaire n'étaient pas obligatoires, ce qui engendrait un appel inutile ( générer le token avec des identifiants vides).
Catcher coté IHM les messages d'erreurs d'api et afficher un message d'erreur adapté par rapport à chaque famille d'erreur.
```javascript
"api-error-messages": {
"unauthorized-error": "L'adresse e-mail et/ou le mot de …
```
=>  [FEATURE] Afficher un message d'erreur approprié lors de la connexion à Pix App (PIX-367).

api/lib/infrastructure/repositories/campaign-repository.js, api/tests/integration/infrastructure/repositories/campaign-repository_test.js
Quand un membre d'une organisation est désactivé, il peut toujours accéder à certaines routes de campagnes (archivage...)
Ajouter une condition dans la méthode `checkIfUserOrganizationHasAccessToCampaign` en prenant en compte que le membre est désactivé.
N/A
1. Se connecter à PIX-ORGA et désactiver un membre sur l'organisation
3. Essayer d'archiver une campagne avec ce membre en exécutant directement une requête API d'archivage sur une campagne de la l'organisation.
=> [BUGFIX] Vérifier qu'un membre désactivé n'accede pas aux routes de campagnes (PIX-857).

admin/app/components/certification-details-competence.js, admin/app/components/certification-info-competences.js, admin/app/components/confirm-popup.js, admin/app/templates/authenticated/certifications/certification/informations.hbs, admin/app/templates/authenticated/sessions/session/certifications.hbs
Certains fichiers modifiés dans la PR #1552 (fix lint), ne fonctionnent pas avec la notation Octane.
Revenir en arrière et désactiver le linter pour ces fichiers.
Potentiel problèmes sur des montées de version d'Ember
Mettre à jour une certification dans admin
=> [BUGFIX] Rollback Ember lint compatibilité (PIX-890)

api/lib/domain/usecases/get-progression.js, api/tests/unit/domain/usecases/get-progression_test.js
Lorsque l'on retente une compétence, la barre de progression au checkpoint est toujours à 100%.
Filtrer les KE des challenges déjà passés pour n'avoir que les KE à retenter.
- Retenter une compétence
- Arrivé au checkpoint: la barre de progression n'est plus à 100% si on est pas au bout du challenge
=> [BUGFIX] Corriger le pourcentage de la barre de progression lorsque la compétence est retentée (PIX-841).

mon-pix/app/controllers/campaigns/assessment/skill-review.js, mon-pix/app/styles/app.scss, mon-pix/app/styles/components/_badge-acquired-card.scss, mon-pix/app/styles/pages/_skill-review.scss, mon-pix/app/templates/campaigns/assessment/skill-review.hbs, mon-pix/app/templates/components/badge-acquired-card.hbs, mon-pix/app/templates/components/profile-content.hbs, mon-pix/tests/acceptance/skill-review-page-test.js, mon-pix/tests/integration/components/badge-acquired-card-test.js, mon-pix/tests/unit/controllers/campaigns/assessment/skill-review-test.js
- Le design des badges sur la page de résultat n'était pas pensé pour plusieurs badges.
- Ajout d'un composant `badge-acquired-card` et utilisation de ce dernier.
- Questionnement sur le titre du badge : est-ce que ça devrait être un titre ? Ou plutôt mettre tous les badges au sein d'une liste ? 
- Terminer la campagne `BADGES789` pour voir un badge.
=> [FEATURE] Modification dans le design des badges sur la page de résultat (PIX-778).

api/db/migrations/20200625113402_add-column-email-to-organizations.js
Dans le cadre de la mise en place d'un accès simplifié à Pix Orga, nous avons besoin de stocker pour chaque organisation SCO un email de récupération.
Ajout d'une colonne `email` dans la table `organizatons`.
Vérifier la présence de la colonne en base de données.
=> [FEATURE] Ajout d'un email de récupération pour les organisations (PIX-843).

mon-pix/app/components/scorecard-details.js, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/tests/integration/components/scorecard-details-test.js, mon-pix/tests/unit/components/scorecard-details-test.js
On ne veut pas afficher le bouton Retenter quand la compétence est terminée avec le niveau max.
Cacher le bouton si le niveau max est atteint.
🐬 On a nettoyé le hbs en remplaçant `this.args` par `@` dans le .hbs
🐬 On a crée une nouvelle classe CSS pour tester vs. utiliser le helper `.contains` : 
- faciliter plus tard la traduction 
- faciliter le tracking sur Matomo
Terminer une compétence avec le niveau 5 et constater que le bouton n'est pas affiché sur la carte et la page de détails.
Terminer une compétence avec un niveau inférieur et constater que le bouton est affiché sur la carte et la page de détails.
=> [FEATURE] Cacher le bouton Retenter quand l'utilisateur a terminé une compétence avec le niveau max (PIX-759).

api/scripts/populate-organizations-email.js, api/tests/integration/infrastructure/repositories/user-orga-settings-repository_test.js, api/tests/integration/scripts/populate-organizations-email_test.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/tooling/database-builder/factory/build-organization.js
Afin de permettre la continuité pédagogique, le professeur qui remplaçe celui qui tenait le rôle d'administrateur de PixOrga doit pouvoir obtenir un rôle administrateur. Cela doit pouvoir se faire sans intervention du professeur précédent. 
Envoyer une demande de rattachement, via PixOrga, à une adresse email générique, accessible à l'organisation.
La liste des adresses génériques est fournie pour initialisation, elle sera chargée par un script qui est l'objet de cette PR.
Le fichier de données doit contenir l'UAI de l'organisation et l'adresse e-mail.
Le script sera lancé en ligne de commande en production.
Une vérification des en-têtes est effectuée.
L'adresse e-mail, si elle existe, sera remplacée.
Créer un fichier nommé organization-email.csv
>uai;email
>AUT;uai1@example.net …
=> [FEATURE] Alimenter les adresses e-mail des organisations (PIX-874).

orga/app/templates/components/routes/login-form.hbs, orga/tests/integration/components/routes/login-form-test.js
On ne souhaite pas avoir le message de contexte de Pix Orga sur la double mire.  
Retirer le message
Aller sur la page : https://orga-pr1574.review.pix.fr/rejoindre?code=DZWMP7L5UM&invitationId=100047
=> [BUGFIX] Retirer le message de contexte sur la double mire de Pix Orga (PIX-912).

api/lib/config.js, api/lib/domain/services/mail-service.js, api/lib/infrastructure/utils/url-builder.js, api/sample.env, scalingo.json
Lorsqu'on teste l'envoie des e-mails, ceux-ci ne redirigent pas vers les review apps. 
Ajouter une variable d'environnement générée dynamiquement grâce au fichier `scalingo.json` : 
https://github.com/1024pix/pix/blob/49b2c6d45dad29df49ffbf02e09e20dfeba3b9d4/scalingo.json#L8-L11
Et utiliser cette variable d'environnement pour la construction des url envoyées dans les e-mails.
Vérifier que les e-mails redirigent vers la RA : 
- Création de compte
- Changement de mot de passe
=> [INFRA] Permettre que les e-mails renvoient vers le bon environnement (PIX-888).

api/lib/domain/validators/user-validator.js, api/tests/unit/domain/validators/user-validator_test.js, orga/app/controllers/authenticated/team/new.js, orga/tests/acceptance/team-creation-test.js
Il est possible, dans Pix Orga, d'inviter des membres à rejoindre une organisation. Néanmoins, lorsque l'adresse email est invalide, aucune invitation n'est envoyée mais aucun message d'erreur n'est affiché afin d'informer l'utilisateur.
Rajouter une notification "Le format de l'adresse e-mail est incorrect."
Le message renvoyé lorsqu'un utilisateur tente de se créer un compte avec une adresse e-mail incorrecte à été modifié en conséquence.
Dans le validateur Joi, un e-mail est invalide (entre autres) lorsque: 
- Il ne possède pas d'@ (ou plus d'un @)
- Il possède des caractères non ASCII
- Il ne possède rien avant et/ou après l'@
- Il fait plus de 254 caractères ou la partie avant l'@ fait plus de 64 caractères
- La dernière partie du domaine ne fait pas partie de la liste: …
=> [BUGFIX] Afficher un message d'erreur dans Pix Orga lorsque l'e-mail d'invitation est incorrect (PIX-471).

mon-pix/app/templates/components/challenge-statement.hbs
L'attribut `target="_blank"` sur le bouton de téléchargement de fichier d'une épreuve ouvre un nouvel onglet lors du téléchargement, ce qui change complètement le focus de l'utilisateur en situation de handicap.
Supprimer l'attribut `target = "blank"`
Tester le téléchargement sur différents navigateurs.
Exemple d'épreuves avec téléchargement: rec00qXohUCqeIhmA, rec5B4raGf9qZmd40
=> [A11Y] Supprimer target='blank" des fichiers téléchargeables depuis les épreuves (PIX-835).

admin/.template-lintrc.js, admin/app/components/certification-details-competence.js, admin/app/components/certification-info-competences.js, admin/app/components/certification-info-field.js, admin/app/components/pagination-control.js, admin/app/templates/components/certification-details-answer.hbs, admin/app/templates/components/certification-details-competence.hbs, admin/app/templates/components/certification-info-competences.hbs, admin/app/templates/components/certification-info-field.hbs, admin/app/templates/components/certification-info-published.hbs, admin/app/templates/components/certification-status-select.hbs, admin/app/templates/components/confirm-popup.hbs, admin/app/templates/components/pagination-control.hbs, admin/package.json, admin/tests/integration/components/certification-info-competences-test.js, admin/tests/integration/components/certification-status-select-test.js
Dans Pix Admin, de nombreuses erreurs existent dans les templates (linter hbs).
Effectuer la correction de ces erreurs.
* Trois templates contiennent un marqueur pour désactiver la `no-action rule`.
* Le composant [emberx-select](https://www.npmjs.com/package/emberx-select) est utilisé dans Pix Admin. Il n'est pas Octane compatible, et n'est pas maintenu depuis 2 ans.
Exécuter le linter `npm run lint`.
: warning: Il est nécessaire d'effectuer une recette fonctionnelle générale de Pix Admin.
=> [CLEANUP] Corriger les erreurs signalées dans Pix Admin par le linter (PIX-889).

admin/app/components/organization-information-section.hbs, admin/app/models/organization.js, api/db/seeds/data/organizations-builder.js, api/lib/domain/models/Organization.js, api/lib/infrastructure/repositories/organization-repository.js, api/lib/infrastructure/serializers/jsonapi/organization-serializer.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/infrastructure/repositories/organization-repository_test.js, api/tests/integration/scripts/send-invitations-to-sco-organizations_test.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/domain/usecases/get-organization-details_test.js, api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
Afin de permettre la continuité pédagogique, le professeur qui remplaçe celui qui tenait le rôle d'administrateur de PixOrga doit pouvoir obtenir un rôle administrateur. Cela doit pouvoir se faire sans intervention du professeur précédent. 
Le but est d'envoyer une demande de rattachement, via PixOrga, à une adresse email générique, accessible à l'organisation.
Cette adresse email générique a été initilisée dans la PR #1567 
Si cette adresse email est incorrecte, le support sera contacté, et il doit pouvoir vérifier si c'est le cas.
Afficher l'adresse mail de l'organization dans PixAdmin
Etapes:
* localiser une organisation possédant une adresse, par exemple The Night Watch 
`SELECT  id, name, email FROM organizations WHERE email IS NOT NULL; `
* se rendre sur [la page de …
=> [FEATURE] Afficher l'email de l'organisation dans Pix Admin (PIX-844).

api/lib/infrastructure/serializers/jsonapi/certification-serializer.js, api/tests/unit/infrastructure/serializers/jsonapi/certification-serializer_test.js
Lorsqu'une certification était modifiée depuis sa page de détail dans Pix Admin cela supprimait son signalement de surveillant (examinerComment)
Lors de la deserialisation de la certif le champs "examinerComment" était mis à `null` lorsque ce dernier était : null / undefined / string vide ou string contenant des espaces. 
Le champ n'est plus mis à `null` maintenant s'il était `undefined`.
Ce bug est présent depuis 4mois en prod.
Il a été découvert par Anne-C qui a constaté des différences dans le fichier avant jury avant et après avoir modifié des certifications.
- aller sur Pix admin et trouver une session avec des certif qui ont des examinerComment (ex: session 6)
- télécharger le fichier avant jury
- aller sur la page de détail d'une des certifs de la session
- enregistrer (en bas) + …
=> [BUGFIX] Le signalement surveillant était supprimé en enregistrant une certif (PIX-916)

mon-pix/app/styles/components/_certification-joiner.scss, mon-pix/app/styles/components/_congratulations-certification-banner.scss, mon-pix/app/styles/components/_user-certifications-detail-result.scss, mon-pix/app/styles/pages/_certification-start.scss, mon-pix/app/templates/components/certification-joiner.hbs, mon-pix/app/templates/components/congratulations-certification-banner.hbs, mon-pix/app/templates/components/navbar-header.hbs, mon-pix/app/templates/components/user-certifications-detail-result.hbs
Le macaron cléa ne s'affiche pas comme prévu sous IE (trop large) et Edge (trop grand).
Nettoyer les styles obsolètes et corriger le nom de la classe appelée pour l'image.
J'en ai profité pour fixer 2/3 ptits trucs vus avec @QuentinChapelain-ui  : 
- Le line-height & font-size du bandeau vert (sur la page pour rejoindre une session de certif)
- La taille du boutton "X" du bandeau vert
- Les marges entre les inputs
- La sémantique des balises de la même page (pour rejoindre une session de certif) = améliore l'accessibilité de la page
> _Les instructions pour reproduire le problème, les profils de test, le parcours spécifique à utiliser, etc._
=> [BUGFIX] Correction de l'affichage du macaron Cléa sur la certif (PIX-879)

api/lib/domain/models/CertificationAssessment.js, api/lib/domain/services/certification-result-service.js, api/lib/domain/usecases/get-next-challenge-for-certification.js, api/lib/infrastructure/repositories/certification-assessment-repository.js, api/lib/infrastructure/repositories/certification-challenge-repository.js, api/tests/integration/infrastructure/repositories/certification-assessment-repository_test.js, api/tests/integration/infrastructure/repositories/certification-challenge-repository_test.js, api/tests/unit/application/assessments/assessment-controller-get-next-challenge_test.js, api/tests/unit/domain/models/CertificationAssessment_test.js, api/tests/unit/domain/services/certification/certification-result-service_test.js, api/tests/unit/domain/usecases/get-next-challenge-for-certification_test.js
Dans Pix Admin, sur la page de détail d'une certification, les épreuves posées aux candidat sont numérotées dans l'ordre inverse de ses réponse (l'épreuve numérotée 1 est la dernière épreuve à laquelle le candidat a répondu, et ainsi de suite).
Trier les réponses par ordre croissant de création lors de leur récupération.
- Passer une certification, par exemple avec certif5@example.net (AnneNormal5)
- En notant les épreuves et leur ordre, en sautant les 15 questions
- Afficher les détails de cette certification dans Pix Admin
- Vérifier que la numérotation des épreuves correspond à l'ordre dans lequel le candidat les a vues
=> [BUGFIX] Corrige la numérotation des épreuves de certif dans Pix Admin (PIX-869)

mon-pix/app/styles/components/_user-certifications-detail-competence.scss, mon-pix/app/styles/components/_user-certifications-detail-result.scss, mon-pix/app/styles/pages/_user-certifications-get.scss, mon-pix/app/templates/components/user-certifications-detail-competence.hbs, mon-pix/app/templates/components/user-certifications-detail-competences-list.hbs, mon-pix/app/templates/components/user-certifications-detail-result.hbs, mon-pix/app/templates/user-certifications/get.hbs, mon-pix/tests/integration/components/user-certifications-detail-competence-test.js
PART 1 : #1509
PART 2 : #1561
On implémente le nouveau design du certificat Pix au fur et à mesure.
https://1024pix.atlassian.net/browse/PIX-838
Cette pr change l'affichage des commentaires jury et le badge CléA
-Si l'utilisateur n'as pas de badge cléa, le bloc "Certifié CléA" n'est pas affiché
-Si l'utilisateur n'as pas de commentaire jury pour son certificat, le bloc "Observation jury" n'est pas affiché
-Si il n'y a ni badge, ni commentaire, le bloc des compétences occupe 100% des 980px de large du certificat
- lancer l'app mon-pix
- se connecter avec un compte ayant passé une certif et l'ayant obtenue (ex: certif-success@example.net)
- A l'aide de l'extension Ember, dans "Data" -> "certification", passer hasCleaCertif à true et remplir commentForCandidate
- aller sur la page de détail …
=> [FEATURE] PART 3 - Nouveau design certificat (PIX-839)

api/lib/domain/models/Scorecard.js, api/lib/infrastructure/serializers/jsonapi/scorecard-serializer.js, api/tests/acceptance/application/scorecard-controller_test.js, api/tests/acceptance/application/users/users-controller-get-user-scorecard_test.js, api/tests/acceptance/application/users/users-controller-reset-scorecard_test.js, api/tests/unit/domain/models/Scorecard_test.js, mon-pix/app/components/competence-card-default.js, mon-pix/app/components/scorecard-details.js, mon-pix/app/models/scorecard.js, mon-pix/app/styles/components/_competence-card-desktop.scss, mon-pix/app/styles/components/_competence-card.scss, mon-pix/app/styles/components/_scorecard-details.scss, mon-pix/app/templates/components/competence-card-default.hbs, mon-pix/app/templates/components/competence-card-mobile.hbs, mon-pix/app/templates/components/scorecard-details.hbs, mon-pix/mirage/factories/user.js, mon-pix/mirage/routes/users/reset-scorecard.js, mon-pix/mirage/serializers/scorecard.js, mon-pix/tests/acceptance/competences-details-test.js, mon-pix/tests/acceptance/tutorial-actions-test.js, mon-pix/tests/integration/components/competence-card-default-test.js, mon-pix/tests/integration/components/profile-content-test.js, mon-pix/tests/integration/components/scorecard-details-test.js, mon-pix/tests/unit/components/competence-card-default-test.js, mon-pix/tests/unit/components/scorecard-details-test.js
Actuellement, l'utilisateur n'est pas en mesure de re-valoriser ses apprentissages sur une compétence de l'univers Pix.
Sur chaque compétence, permettre à l'utilisateur de retenter des acquis de compétence échoués au bout de 4 jours. 
Dans le cadre de cette PR, nous mettons en place un décompte de 4 jours au bout duquel l'utilisateur sera en capacité présenter le fruit de sa progression et ainsi améliorer son score de Pix.
Quelques commits de BSR ont été exécutés au passage : 
- utiliser `<FaIcon>` au lieu de `{{fa-icon}}`;
- délier nos tests automatisés pour le décompte de jours des variables d'environnement locales ; 
- remplacer par des `<div>` les `<header>` et `<footer>` utilisés à mauvais escient et de surcroît néfastes aux travaux engagés pour améliorer l'accessibilité de l'univers …
=> [FEATURE] Retenter des acquis de compétence échoués au bout de 4 jours (PIX-758).

orga/app/components/routes/join-request-form.js, orga/app/router.js, orga/app/routes/join-request.js, orga/app/styles/app.scss, orga/app/styles/components/join-request-form.scss, orga/app/styles/pages/join-request.scss, orga/app/templates/components/routes/join-request-form.hbs, orga/app/templates/join-request.hbs, orga/app/utils/uai-validator.js, orga/tests/integration/components/routes/join-request-form-test.js, orga/tests/unit/routes/join-request-test.js, orga/tests/unit/utils/uai-validator-test.js
Nous souhaitons faciliter l'accès à Pix Orga. 
Nous voulons qu'un nouveau directeur d'établissement n'ait pas à contacter l'ancien directeur pour l'inviter à rejoindre l'organisation puis changer son rôle en admin. 
Nous voulons mettre en place un nouveau formulaire qui enverra un e-mail d'invitation à l'adresse e-mail de récupération de l'organisation dont aura l'accès le nouveau directeur. Cette invitation lui donnera le rôle d'administrateur de l'organisation. 
Dans cette PR, seulement la nouvelle page avec le formulaire a été fait. 
Un nouveau validateur d'input a été ajouté : `uai-validator`. 
Un UAI (Unité Administrative Immatriculée), et un code unique donnée à chaque établissement. Il se compose de 7 chiffres et d'une lettre comprise entre la position 0 et 22. Elle correspond au …
=> [FEATURE] Permettre l'envoi d'une invitation par une nouvelle page (1ère partie)(PIX-881).

admin/app/adapters/membership.js, admin/app/components/confirm-popup.js, admin/app/components/member-item.hbs, admin/app/components/member-item.js, admin/app/components/organization-members-section.hbs, admin/app/controllers/authenticated/organizations/get/members.js, admin/app/models/membership.js, admin/app/styles/app.scss, admin/app/styles/components/member-item.scss, admin/app/styles/misc/tables.scss, admin/app/templates/authenticated/organizations/get/members.hbs, admin/app/templates/components/confirm-popup.hbs, admin/mirage/config.js, admin/mirage/handlers/organizations.js, admin/tests/acceptance/organization-information-management-test.js, admin/tests/acceptance/organization-memberships-management-test.js, admin/tests/integration/components/confirm-popup-test.js, admin/tests/integration/components/member-item-test.js, admin/tests/unit/adapters/membership-test.js, api/lib/application/memberships/index.js, api/lib/application/memberships/membership-controller.js, api/lib/domain/usecases/disable-membership.js, api/lib/domain/usecases/index.js, api/tests/acceptance/application/membership-controller_test.js, api/tests/integration/application/memberships/membership-controller_test.js, api/tests/unit/domain/usecases/disable-membership_test.js
Depuis peu, la suppression d'un membre n'est plus effectuée par une suppression dans la base mais par l'ajout d'une date de désactivation. Néanmoins, cette opération devait jusque ici être effectuée directement en base de données.
Ajout d'un bouton dans le tableau des membres de Pix Admin afin de permettre cette désactivation.
- Un refacto de la mise à jour du rôle d'un membre a été effectué afin de faire l'appel à l'API depuis le controller et non plus directement dans le composant. Cette PR s'appuie sur ce refacto afin d'effectuer la désactivation d'un membre.
- Le composant `confirm-popup` a évolué afin de permettre la surcharge du titre, du libellé du bouton de confirmation ainsi que celui d'annulation.
- Le CSS du tableau a évolué afin de faire apparaître des points de suspension …
=> [FEATURE] Permettre la désactivation d'un membre depuis Pix Admin (PIX-394).

api/lib/domain/models/Challenge.js, api/lib/infrastructure/datasources/airtable/challenge-datasource.js, api/lib/infrastructure/repositories/challenge-repository.js, api/lib/infrastructure/serializers/jsonapi/challenge-serializer.js, api/tests/tooling/airtable-builder/factory/build-challenge.js, api/tests/tooling/domain-builder/factory/build-challenge.js, api/tests/tooling/fixtures/infrastructure/challengeAirtableDataObjectFixture.js, api/tests/tooling/fixtures/infrastructure/challengeRawAirTableFixture.js, api/tests/unit/domain/models/Challenge_test.js, mon-pix/app/models/challenge.js
Certaines épreuves avec des Embed vont avoir une "Réponse automatique", qui fera que l'utilisateur n'aura pas à remplir de champ réponse
- Ajout d'une colonne "Réponse automatique" dans Airtable, avec une case à cocher
- Ajout de l'attribut `autoReply` dans le model Challenge en back et en front
- Aller sur l'épreuve recab7EiQWXfuVKqI et voir qu'elle a l'attribut `autoReply` à true en front
- Aller sur une autre épreuve et voir que l'attribut `autoReply` est à false
=> [FEATURE] Ajout de la colonne Réponse Automatique (PIX-899).

admin/app/components/organization-information-section.hbs, admin/app/components/organization-information-section.js, admin/tests/acceptance/organization-information-management-test.js, admin/tests/integration/components/organization-information-section-test.js, api/lib/application/organizations/organization-controller.js, api/lib/domain/usecases/update-organization-information.js, api/lib/infrastructure/repositories/organization-repository.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/integration/domain/usecases/update-organization-information-test.js, api/tests/tooling/domain-builder/factory/build-organization.js, api/tests/unit/application/organizations/organization-controller_test.js, api/tests/unit/domain/usecases/update-organization-information_test.js
On ne peut pas éditer le champ e-mail d'une organisation SCO dans Pix Admin.
Rajouter le champ e-mail dans l'édition des informations d'une organisation SCO.
Le champ est optionnel et peut être vidé lors de la mise à jour.
Pas de règle de gestion au niveau de l'affichage de l'e-mail pour l'instant, on l'édite pour toutes les organisations.
Aller dans Pix Admin, dans la vue détail d'une organisation, puis cliquer sur Editer.
Vérifier que le champ e-mail est présent et le modifier.
Vérifier que la mise à jour s'est bien effectuée.
=> [FEATURE] Permettre l'édition de l'e-mail d'une organisation dans Pix Admin (PIX-880).

api/db/migrations/20200702114943_add_check_on_memberships_role.js
La table memberships contient des rôles, mais ceux-ci ne sont référencés que dans le code [API](https://github.com/1024pix/pix/blob/prod/api/lib/domain/models/Membership.js)
`const roles = {
ADMIN: 'ADMIN',
MEMBER: 'MEMBER',
};`
Des scripts SQL étant exécutés en dehors de l'API, il est possible que, par erreur, un rôle incohérent (ex: `ADMI`) soit attribué.
Implémenter cette vérification côté BDD avec une contrainte CHECK.
Lors de la création de la contrainte, une vérification des données existantes est effectuée, qui peut prendre du temps sur une table volumineuse (FULL TABLE SCAN en l'absence d'index). Cette étape peut être annulée avec l'option NO VALID. 
Comme la table memberships est peu volumineuse (20 000 enregistrements), et que l'exécution de cette étape sur la réplication de la …
=> [TECH] Empêcher la création d'appartenance à une organisation si le rôle n'est pas connu.

.gitignore, .run/debug_admin.run.xml, .run/debug_certif.run.xml, .run/debug_mon-pix.run.xml, .run/debug_orga.run.xml, .run/start_api.run.xml, .vscode/sample.launch.json, .vscode/sample.settings.json
Un commit a ete supprimé sur les configs d'IDE (vscode/intellij)
Les debug ember ne fonctionne pas en l'etat
Les confs vs code n'existe pas
- intellij:  supprimer le start ember qui entrait en conflit avec le debug
- vscode: ajout des fichiers de config "sample"
Les debug ember (vscode ou intellij), nécessite d'avoir lancé au préalable un ember start (`cd mon-pix && npm start`)
`cp .vscode/sample.launch.json .vscode/launch.json`
`cp .vscode/sample.settings.json .vscode/settings.json`
Depuis la vue "debug", on voit apparaitre différent run
- **api watch**: lance l'api en watch (nodemon)
- **api mocha current file api**: lance les tests du fichier courant
- **api mocha all tests**: lance tout les tests api
- **mon-pix chrome**: lance une fenêtre chrome sur mon-pix (+debug dans l'IDE)
- …
=> [TECH] Mettre à disposition des configurations d'IDE

admin/app/controllers/authenticated/certifications.js, admin/app/controllers/authenticated/sessions/session.js, admin/tests/unit/controllers/authenticated/certifications-test.js, admin/tests/unit/controllers/authenticated/sessions/session-test.js
Le champ de recherche par certification id ne fonctionnait plus (reload rapide de la même page avec une notification d'erreur très rapide). 
Le problème a été introduit il y a 10 jours lors d'un [refacto pour le linter](https://github.com/1024pix/pix/pull/1552/commits/85684d9881f059ca53303f27d096e1d73eda4408).
Ce qui a fait planter le champ de recherche est la modification de cette ligne :
```
<form class='form-inline' {{action "loadCertification" on='submit'}}>
```
en 
```
<form class="form-inline" {{on 'submit' this.loadCertification}}>
```
Du coup si j'ai bien compris, par défaut le `on 'submit'` de ember va chercher à changer de page. Pour ne pas avoir ce comportement là (car on redirige nous même vers la page souhaitée) on rajoute `event.preventDefault()` à l'action appelée. …
=> [BUGFIX] Recherche par certification id mort (PIX-922)

admin/app/templates/components/certification-details-competence.hbs, admin/tests/integration/components/certification-details-competence-test.js
Le niveau certifié n'est plus affiché. Cela rends la lecture plus compliquée.
Le bug a été introduit il y a 3 jours dans [cette PR](https://github.com/1024pix/pix/pull/1562/commits/bd7eabea1dd359c88bffd460c23a3e11dbeabf5c).
C'était un simple bug dût à une lettre retirée.
- aller sur la page de détail d'une certification et constater que le niveau certifié est bien affiché dans la barre orange.
=> [BUGFIX] Niveau certifié non affiché dans le détail d'une certification (PIX-930)

api/lib/domain/errors.js, api/lib/domain/models/CleaCertification.js, api/lib/domain/models/PartnerCertification.js, api/lib/infrastructure/repositories/partner-certification-repository.js, api/tests/integration/infrastructure/models/assessment_result_test.js, api/tests/integration/infrastructure/repositories/partner-certification-repository_test.js, api/tests/tooling/domain-builder/factory/build-clea-certification.js, api/tests/unit/domain/models/CleaCertification_test.js
Lorsqu'un candidat passe une certification et qu'aucune question ne porte sur un tube lié au Clea, une erreur (422) survient 
Permettre de créer CleaCertification avec cleaCompetenceMarks vide via la validation JOI
Passer une certif avec un profil certifiable avec 0 tubes lié au Cléa
=> [BUGFIX] Les certification sans cleaCompetenceMarks ne passent pas en completed (PIX-915)

orga/app/templates/components/routes/authenticated/students/list-items.hbs, orga/tests/acceptance/dissociate-student-test.js, orga/tests/integration/components/routes/authenticated/students/list-items-test.js
Lorsqu'un membre d'une organisation veut dissocier un élève, une erreur se produit. Seuls les administrateurs d'une organisation ont les droits de dissocier un compte. Cependant les membres voit le bouton "Dissocier le compte" malgré tout.
Cacher le bouton "Dissocier le compte" pour les membres d'une organisation.
Aller sur Pix Orga et se connecter avec le compte mance.rayder@example.net (Pix123). Se rendre dans l'onglet élève. Lorsqu'on clique sur le trois petits points en bout de ligne vous ne devriez pas voir l'action "Dissocier le compte".
=> [BUGFIX] Cache l'action dissocier le compte pour les membres d'une organisation (PIX-941).

orga/app/templates/terms-of-service.hbs
Les conditions d'utilisations ne correspondent pas au pix.org.
Mettre à jour les conditions d'utilisations avec la mention vers pix.orga
Se connecter à [Pix orga](https://orga-pr1596.review.pix.fr) avec l'utilisateur testcgu@example.net Password123
Vérifier que les commentaires sont bien appliquées dans les conditions d'utilisations de Pix Orga.
https://docs.google.com/document/d/1EDxhHB5P3ZIrveD2poNh3PM_uS2UN519AY5fQjh1kZ0/edit#
=> [FEATURE] Mettre à jour les conditions d'utilisation de Pix Orga en incluant le pix.org ( PIX-871 )

api/lib/infrastructure/repositories/jury-certification-summary-repository.js, api/tests/integration/infrastructure/repositories/jury-certification-summary-repository_test.js
La liste des certifications dans Pix Admin ne se met pas à jour quand on a plusieurs certif en "started"
Le problème venait de la requête qu'on faisait pour récupérer les certifs.
AVANT, avec un ROW_NUMBER() : 
APRES, avec un RANK() : 
- rejoindre une session de certification avec un candidat 
- entrer le code d’accès a la session : un nouveau certif-course est créé
- ne PAS finir la certif de façon à ce qu’elle reste au statut “started”
- aller dans Pix Admin sur la page de détails de la session puis cliquer sur l’onglet “Certifications” : la certif “started” est affichée
- rejoindre la même session avec un autre candidat
- ne PAS finir non plus cette certif de façon à ce qu’elle reste également au statut “started”
- aller dans Pix Admin …
=> [BUGFIX] Il manque des certifs dans le détails d'une session (PIX-877)

admin/app/components/user-detail-personal-information.hbs, admin/tests/integration/components/user-detail-personal-information-test.js
Dans le formulaire d'anonymisation de Pix Admin, il y a des typos.
Il y a aussi un petit bug visuel sur le bouton `Anonymiser cet utilisateur` : Au survol la couleur rouge est remplacée par du gris.
- Corriger le texte de la popup par : `Êtes-vous sûr de vouloir anonymiser cet utilisateur ? Ceci n’est pas réversible.`
- Corriger le css du bouton
Aller sur la page des utilisateurs.
Vérifier au survol du bouton la couleur rouge.
Vérifier dans la popup que le texte est correct.
=> [BUGFIX] Corriger le formulaire d'anonymisation d'utilisateur de Pix Admin (PIX-944).

api/lib/infrastructure/repositories/jury-certification-summary-repository.js
La requête pour récupérer le dernier assessmentResult d'une certification fonctionne par coïncidence (voir conversation liée dans les remarques).
Faire un ROW_NUMBER en regroupant par certificationCourseId
[Lien vers la conversation de @jonathanperret à propos du ticket pix-877](https://github.com/1024pix/pix/pull/1599#discussion_r450182948
)
Mêmes tests que pour #877 :
- rejoindre une session de certification avec un candidat 
- entrer le code d’accès a la session : un nouveau certif-course est créé
- ne PAS finir la certif de façon à ce qu’elle reste au statut “started”
- aller dans Pix Admin sur la page de détails de la session puis cliquer sur l’onglet “Certifications” : la certif “started” est affichée
- rejoindre la même session avec un autre candidat
- ne PAS finir non plus cette …
=> [CLEANUP] Requête SQL plus cohérente pour les détails d'une session (PIX-877)

mon-pix/app/templates/components/challenge-statement.hbs
Suite à la suppression du `target=_blank` pour des raisons d'accessibilité, lorsqu'on clique sur le bouton de téléchargement, on sort de l'assessment. (cf. #1575)
Une solution "quick & dirty" a été tentée (cf. #1605) mais celle-ci entraîne d'autres problèmes.
Dans un premier temps, on choisit de revenir en arrière sur cette correction.
Une solution pérenne sera ensuite implémentée, sur la base des suggestions de @jonathanperret (cf. https://github.com/1024pix/pix/pull/1605#issuecomment-654175891).
RAS
https://app-pr1612.review.pix.fr/challenges/recP1GPtuYjQE5mPM/preview
https://app-pr1612.review.pix.fr/challenges/rec65HeFvjaeC2QA2/preview
=> [BUGFIX] Retour en arrière sur le correctif des liens téléchargeables (`target=_blank`)(PIX-835).

api/lib/config.js, api/lib/plugins.js
Par défaut, le message d'erreur envoyé depuis l'api à Sentry est tronqué à 250 caractères.
[Depuis la version 5.0.0 il est possible de surcharger ce comportement grâce au paramètre `maxValueLength`.](https://docs.sentry.io/platforms/javascript/#truncating-strings-on-the-event)
J'ai arbitrairement mis une limite à 1000 caractères. Prix à débattre.
Me demander.
=> [TECH] Augmenter la taille des messages d'erreur dans Sentry

admin/app/controllers/authenticated/certifications/certification/informations.js, admin/app/services/mark-store.js, admin/tests/unit/controllers/authenticated/certifications/certification/informations-test.js
Pas de test sur certification information onSaveConfirm
Ajout de test + BSR
Verifier l'affichage de la popup lors du clic sur la sauvegarde d'une certification, et des messages d'erreur.
=> [CLEANUP] Refacto admin save certification (PIX-946)

api/db/knexfile.js
Quand une exception survient au niveau de knex, la stacktrace visible dans Sentry ne comprend que peu d'information:
En activant l'option asyncStackTraces: true il est possible d'y inclure toute la stacktrace :
L'option knex en question est décrite ici : http://knexjs.org/#Installation-asyncStackTraces
À noter :
> _This has small performance overhead, so it is advised to use only for development. Turned off by default._
Me demander.
=> [TECH] Inclure toute la stack trace asynchrone dans les erreurs Knex

mon-pix/app/components/challenge-item-qroc.js, mon-pix/app/styles/components/_challenge-item.scss, mon-pix/app/templates/components/challenge-item-qroc.hbs, mon-pix/mirage/factories/challenge.js, mon-pix/tests/acceptance/challenge-qroc-test.js, mon-pix/tests/integration/components/form-textfield-date-test.js
Lorsqu'une épreuve est un embed auto-validé nous ne voulons pas faire apparaître le champ de réponse.
Cacher le champ de réponse.
L'alerte prévenant qu'il faut que le champs réponse soit remplis si l'on veut valider l'épreuve a été modifiée pour toutes les épreuves de type QROC, par la phrase "'Jouer l'épreuve pour valider. Sinon, passer.'"  
Utiliser ces challenges : 
- [recWndEZbiReZ0zsz](https://app-pr1597.review.pix.fr/challenges/recWndEZbiReZ0zsz/preview)
- [recab7EiQWXfuVKqI](https://app-pr1597.review.pix.fr/challenges/recab7EiQWXfuVKqI/preview)
- [recy37FMPthJpfWmd](https://app-pr1597.review.pix.fr/challenges/recy37FMPthJpfWmd/preview)
- [rec0w9GHcxIPxDY5z](https://app-pr1597.review.pix.fr/challenges/rec0w9GHcxIPxDY5z/preview)
=> [FEATURE] Cacher le champ de réponse si l’épreuve est un embed auto-validé (PIX-900)

.github/workflows/auto-merge.yml
Le processus de merge des PRs est assez fastidieux actuellement.
Quand on souhaite merger une PR, on doit :
- Prévenir les autres dev que l'on souhaite merger une PR
- Rebase la PR avec la branche `dev`
- Attendre que le workflow de CI soit ok
- Prier pour que personne n'ai mergé entre temps
- Faire le merge de la PR et changer le titre de merge par défaut avec celui de la PR
Automatiser ce processus grâce aux Github Actions.
Nous utilisons un github action qui répond exactement à nos besoins : 
https://github.com/pascalgn/automerge-action
Elle permet de déclencher un processus de merge automatique sur le PR ayant été labellisées ":rocket: Ready to merge". Quand la PR a ce label, l'action va:
- Checkout la branche
- Vérifier que les checks **obligatoires** sont passés et ok
- Vérifier que …
=> [TECH] Merge automatique grâce aux Github Actions

api/db/migrations/20200702135519_add-sup-columns-to-schooling-registrations.js
Le SUP a besoin d'importer ses étudiants également, en plus du SCO.
Ajouter les colonnes pour le SUP dans la table schooling-registrations.
Pour le "régime" : contient la même chose que la colonne status (formation continue, apprenti, etc) mais sûrement pas sous la même forme (ST, AP, etc). On a choisit de garder une seule colonne.
=> [TECH] Ajouter les colonnes SUP à la table schooling-registrations (PIX-925).

.github/workflows/auto-merge.yml
L'action de vérification d'automerge se déclenche beaucoup trop souvent (à chaque changement de status d'un commit) quand passe d'un état (pending, progress et success)
Limiter le déclenchement juste au changement de la fin de la suite de test et pas à chaque changement de status de la PR.
=> [TECH] Suppression du déclencheur status pour le workflow automerge

.github/workflows/auto-merge.yml
La github action pour l'auto-merge n'a pas les autorisations de pusher sur la branche protégée `dev`.
La solution pour contourner ce problème est de créer un Personal Access Token ayant les droits de push sur le repo.
(voir https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/23)
Nous avons le compte de service `pix-service`. Nous pourrions utiliser son Personal Access Token avec les droits nécessaires et ensuite de l'ajouter en tant que secret dans les settings du repo pix. On peut alors utiliser ce token dans la Github Action.
J'ai également enlevé le trigger de l'action quand un utilisateur approuve une PR qui n'était pas forcément nécessaire.
=> [TECH] Utiliser un token pix-service dédié à la Github Action Auto-merge

orga/app/components/sidebar-menu.js, orga/tests/integration/components/sidebar-menu-test.js
Actuellement, le lien de la documentation pour les orga SCO is managing Student pointe vers un sous-dossier d’un espace partagé en public. Or, il doit contenir des docs qui ne doivent pas être partagés en mode public.
Changer le lien de la documentation.
RAS
Vérifier qu'on a le bon lien
=> [ORGA] Mettre à jour le lien de la documentation pour les organisation de type SCO. (Pix-817)

mon-pix/app/components/comparison-window.js, mon-pix/app/templates/components/comparison-window.hbs, mon-pix/tests/acceptance/challenge-qcm-test.js, mon-pix/tests/acceptance/challenge-qcu-test.js, mon-pix/tests/acceptance/challenge-qroc-test.js, mon-pix/tests/acceptance/challenge-qrocm-test.js, mon-pix/tests/integration/components/comparison-window-test.js, mon-pix/tests/unit/components/comparison-window-test.js
Les questions avec des embed validés automatiquement n'affichent pas de champs texte à l'utilisateur. 
Il n'y a donc pas de champ réponse dans la fenêtre "Réponses et tutos".
Dans le cas d'un challenge de type QROC dont `autoReply` vaut `true`.
Dans le composant `comparison-window` :
- Changer le titre par 
`Vous n’avez pas réussi l'épreuve` ou
`Vous avez réussi l'épreuve` ou
`Vous avez passé l’épreuve`
- Retirer `correction-qroc-box rounded-panel`
On en profite pour corriger les apostrophes de tous les messages présents dans `comparison-window`.
Utiliser ces challenges :
[recWndEZbiReZ0zsz](https://app-pr1621.review.pix.fr/challenges/recWndEZbiReZ0zsz/preview)
[recab7EiQWXfuVKqI](https://app-pr1621.review.pix.fr/challenges/recab7EiQWXfuVKqI/preview) …
=> [FEATURE] Ne pas afficher le champ "Réponse" sur la page de résultat pour les challenges QROC sans réponse(PIX-902).

api/lib/config.js, api/lib/domain/services/mail-service.js, api/lib/infrastructure/mailers/mailer.js, api/sample.env, api/tests/unit/domain/services/mail-service_test.js
Dans le cadre de l'Accès simplifié aux espaces Pix Orga SCO, on voudrait utiliser un template e-mail spécifique.
Entre autres, les prénom et nom du futur membre d'une organisation SCO devront apparaitre dans l'e-mail envoyé.
- Créer un nouveau template (qui sera une duplication du template Organisation-Invitation).
- Créer et utiliser la variable d'environnement  qui portera l'ID du template.
- Créer la fonction `mail-service.sendOrganizationInvitationScoEmail()`.
- Ce ticket est le complément d'un autre ticket front/API à venir.
- Les tests fonctionnels ne pourront être réalisés qu'à la livraison du ticket mentionné ci-dessus.
=> [FEATURE] Utilisation d'un nouveau template e-mail pour rejoindre une Organisation SCO (PIX-883).

api/lib/application/error-manager.js, api/lib/application/http-errors.js, api/lib/domain/errors.js, api/lib/domain/services/get-competence-level.js, api/lib/domain/usecases/improve-competence-evaluation.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/competence-evaluation-repository.js, api/lib/infrastructure/repositories/knowledge-element-repository.js, api/tests/acceptance/application/competence-evaluation-controller-improve_test.js, api/tests/integration/application/error-manager_test.js, api/tests/integration/domain/usecases/improve-competence-evaluation_test.js, api/tests/tooling/domain-builder/factory/build-competence-evaluation.js, api/tests/unit/domain/services/get-competence-level_test.js, api/tests/unit/domain/usecases/improve-competence-evaluation_test.js, mon-pix/app/components/competence-card-default.js, mon-pix/app/components/scorecard-details.js, mon-pix/app/services/competence-evaluation.js, mon-pix/tests/unit/components/competence-card-default-test.js, mon-pix/tests/unit/components/scorecard-details-test.js, mon-pix/tests/unit/services/competence-evaluation-test.js
Le bouton permettant de retenter une compétence n'est pas visible quand la personne a atteint le niveau maximum.
Pourtant, en gardant un onglet ouvert ou en passant par l'API, ça reste possible.
Création du service `getCompetenceLevel` qui calcule le niveau d'un utilisateur pour une compétence donnée.
Si le niveau maximum est atteint alors une erreur `403 - Forbidden` est renvoyée par l'API.
RAS
- Mettre 0 jour pour pouvoir retenter dans les variables d'env.
- Finir une compétence en étant niveau 3 ou 4.
- Voir que le bouton retenter est là.
- Garder l'onglet ouvert (onglet 1)
- Dans un autre onglet (onglet 2), remettre à zéro la même compétence et la repasser en ayant un niveau 5.
- Voir qu'à la fin, le bouton n'est pas là sur l'onglet 2.
- Revenir sur l'onglet 1, et cliquer sur Retenter …
=> [FEATURE] Ne pas autoriser un utilisateur à retenter une compétence quand le niveau maximum de la compétence est atteint (PIX-898).

api/db/seeds/data/organizations-builder.js, api/lib/application/organizations/index.js, api/lib/application/security-pre-handlers.js, api/lib/application/usecases/checkUserBelongsToOrganizationManagingStudents.js, api/lib/domain/usecases/retrieve-campaign-information.js, api/tests/acceptance/application/organization-controller_test.js, api/tests/acceptance/application/organizations/organization-controller-import-schooling-registrations_test.js, api/tests/integration/application/organizations/index_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/unit/application/security-pre-handlers_test.js, api/tests/unit/application/usecases/checkUserBelongsToOrganizationManagingStudents_test.js, api/tests/unit/domain/usecases/retrieve-campaign-information_test.js
Actuellement seules les organisations SCO peuvent gérer des élèves. Demain d'autres types d'orgas vont pouvoir le faire.
Décorréler cet usage là où c'est nécéssaire :
- lors de l'import ;
- lors de la récupération des élèves.
Cette corrélation a été laissée en place pour les cas suivants (valable uniquement pour le SCO qui gèrent des élèves - il y a des SCO qui ne gèrent pas encore d'élèves) :
- la mise à jour du mot de passe des élèves ;
- l'accès à la documentation pour gérer des élèves dans Pix Orga ;
- l'accès à la page /eleves (puisque pour les étudiants du SUP ce sera une autre page).
Non régression de :
- l'affichage des élèves ; 
- la modification des élèves (changement mot de passe) ;
- accès à la documentation (dans le panel à gauche et lors de la création d'une campagne) ;
- la …
=> [TECH] Décorréler l'utilisation de isManagingStudents du type d'organisation SCO (PIX-924).

api/lib/infrastructure/utils/query-params-utils.js, api/tests/acceptance/application/users/users-controller-find-users_test.js, api/tests/unit/domain/services/user-reconciliation-service_test.js
Les tests suivants sortent en erreur de manière non déterminisite sur la CI (pas en local).
```javascript
Unit | Service | user-reconciliation-service
#findMatchingCandidateIdForGivenUser
When schoolingRegistration list is not empty
When one schoolingRegistration matched on names
When schoolingRegistration found based on his...
...middleName:
AssertionError: expected null to equal 0
```
```javascript
Acceptance | users-controller-find-users 
GET /users 
Success case 
should return a 200 status code with paginated and filtered data:
AssertionError: expected { Object (page, pageSize, ...) } to deeply equal { Object (page, pageSize, ...) } 
+ expected - actual
{ 
"page": 2 
-  "pageCount": 3 
+  "pageCount": 2 
"pageSize": 1 
-  "rowCount": 3 
+  "rowCount": 2 
} 
```
Le faire exécuter par …
=> [BUGFIX] Rendre des tests plus déterministes dans l'API (PIX-959). 

docs/security/security.md, orga/app/routes/application.js, orga/app/services/url.js, orga/config/environment.js, orga/tests/acceptance/terms-of-service-test.js
La totalité des données données applicatives (venant de l'API, hors token) est stocké dans l'espace mémoire du navigateur, dont le store Ember.
Sur l'application MonPix, lorsque l'utilisateur se déconnecte du site, le store Ember est vidé.
Sur les applications Certif/Orga/Admin, ce n'est pas le cas.
Si l'utilisateur n'arrête pas le navigateur et ne verrouille pas sa session, un autre utilisateur a accès à l'ensemble des données qu'il a consultées avec:
* le plugin Ember Inspector
* la console.
Par exemple, sur PixOrga, s'il a visité la page Elèves, l'ensemble des emails des prescrit peut être obtenu dans la console avec: `Ember.Application.NAMESPACES_BY_ID['pix-orga'].__container__.lookup('service:currentUser').prescriber.fullName`
Cela est dû au fait que, suite à une montée de version …
=> [BUGFIX] Supprimer les données lors de la déconnexion (PIX-954).

admin/public/robots.txt, certif/public/robots.txt, mon-pix/public/robots.txt, orga/public/robots.txt
Les applications ember de Pix sont indexées par le moteur de recherche google.
On se retrouve donc avec des pages privées indexées. Par conséquent, des liens qui affichent du détail sur les questions par exemple.
En complément de la désactivation via la console google de l'indexation par @jbuget.
Et de la modification du header ADD_HTTP_HEADER_X_ROBOTS_TAG=noindex par @VincentHardouin.
On configure les fichiers robot.txt des applications ember qui sont générés à la création du projet par ember-cli, afin d'éviter l'indexation et le crawling des pages Pix apps.
https://support.google.com/webmasters/answer/93710?hl=fr#:~:text=d'aideCommunaut%C3%A9-,Bloquer%20l'indexation%20de%20la%20recherche%20avec%20l'instruction%20%22,noindex%22%20dans%20la%20requ%C3%AAte%20HTTP …
=> [TECH] Configurer les fichiers robots.txt des applications Ember pour éviter l'indexation et le crawling par les moteurs de recherches.

api/db/seeds/data/organizations-builder.js, api/lib/application/organization-invitations/index.js, api/lib/application/organization-invitations/organization-invitation-controller.js, api/lib/application/passwords/password-controller.js, api/lib/domain/models/OrganizationInvitation.js, api/lib/domain/usecases/accept-organization-invitation.js, api/lib/domain/usecases/answer-to-organization-invitation.js, api/lib/domain/usecases/index.js, api/lib/infrastructure/repositories/user-repository.js, api/tests/acceptance/application/organization-invitation-controller_test.js, api/tests/integration/application/organization-invitations/index_test.js, api/tests/integration/application/organization-invitations/organization-invitation-controller_test.js, api/tests/integration/application/organizations/organization-controller_test.js, api/tests/integration/domain/services/organization-invitation-service_test.js, api/tests/integration/infrastructure/repositories/user-repository_test.js, api/tests/tooling/domain-builder/factory/build-organization-invitation.js, api/tests/unit/application/organization-invitations/index_test.js, api/tests/unit/application/organization-invitations/organization-invitation-controller_test.js, api/tests/unit/application/passwords/password-controller_test.js, api/tests/unit/domain/usecases/accept-organization-invitation_test.js, api/tests/unit/domain/usecases/answer-to-organization-invitation_test.js, orga/app/components/routes/login-form.js, orga/app/components/routes/register-form.js, orga/app/models/organization-invitation-response.js, orga/mirage/config.js
Les professeurs voulant récupérer l'accès d'administration à Pix Orga suite au départ d'un collègue se voient attribuer le rôle de membre.
Leur attribuer le rôle d'administrateur, soit en créant ce rôle, soit en mettant à jour le rôle existant.
Attente du ticket pour PIX-882 pour rebase (colonne en BDD)
La prise en compte du statut envoyé par Pix Orga a été supprimée (code mort)
Etapes:
- créer une [demande d'invitation](https://orga-pr1609.review.pix.fr/demande-administration-sco), sur l'UAI `1234567A`
- récupérer le code et l'id associée `select email, id, code from "organization-invitations"`
- construire l'URL`https://orga-pr1609.review.pix.fr/rejoindre?invitationId=<ID>&code=<CODE>`
- se rendre sur l'URL, créer un compte pour accepter l'invitation
- se connecter sur ce compte et …
=> [FEATURE] Assurer à l'utilisateur auto-invité un rôle d'administrateur (PIX-845).

mon-pix/app/components/user-certifications-detail-header.js, mon-pix/app/controllers/user-certifications.js, mon-pix/app/formats.js, mon-pix/app/styles/components/_certifications-list-item.scss, mon-pix/app/styles/components/_certifications-list.scss, mon-pix/app/styles/components/_user-certification-hexagon-score.scss, mon-pix/app/templates/components/certifications-list-item.hbs, mon-pix/app/templates/components/certifications-list.hbs, mon-pix/app/templates/components/user-certifications-detail-competence.hbs, mon-pix/app/templates/components/user-certifications-detail-competences-list.hbs, mon-pix/app/templates/components/user-certifications-detail-header.hbs, mon-pix/app/templates/components/user-certifications-detail-result.hbs, mon-pix/app/templates/components/user-certifications-hexagon-score.hbs, mon-pix/app/templates/user-certifications/get.hbs, mon-pix/app/templates/user-certifications/index.hbs, mon-pix/tests/helpers/setup-intl.js, mon-pix/tests/integration/components/certifications-list-item-test.js, mon-pix/tests/integration/components/user-certifications-detail-competences-list-test.js, mon-pix/tests/integration/components/user-certifications-detail-header-test.js, mon-pix/translations/en.json, mon-pix/translations/fr.json
Dans le cadre de l'internationalisation de PIX, on souhaite pouvoir voir la page "mes certifications" en plusieurs langues
On deplace toutes les chaines de caractères des templates vers le fichiers de traduction d'_ember-intl_
Aller sur les certifications et voir que l'affichage se fait correctement. On peut modifier la variable d'environnement pour changer de langue mais le fichier en anglais sera fait par des professionnels
=> [FEATURE] Internationalisation de "mes certifications" (PIX-797)

admin/app/routes/authenticated/certifications/certification.js, admin/app/routes/authenticated/sessions/session.js, admin/app/services/error-notifier.js, admin/tests/unit/routes/authenticated/certifications/certification-test.js, admin/tests/unit/routes/authenticated/sessions/session-test.js, admin/tests/unit/services/error-notifier-test.js
Les erreurs JSONAPI ne sont pas remonté correctement par ember data.
Utiliser un service qui récupère le message de l'erreur/des erreurs renvoyé par JSONAPI (api) et les affiche via le service de notification
Les erreurs hors JSONAPI sont notifiés tel-quel (le comportement est inchangé)
Faire une erreur 422 sur la page des certifications. Verifier le message
=> [TECH] Manage errors from api (JSONAPI)
