1024pix/pix

- api/lib/application/assessments/assessment-controller.js
- api/lib/application/assessments/index.js
- api/lib/domain/services/assessment-service.js
- api/scripts/compute-missing-assessments-certification-marks.js
- api/tests/unit/application/assessments/assessment-controller_test.js
- api/tests/unit/application/assessments/index_test.js
- api/tests/unit/domain/services/assessment-service_test.js
WARNING : ce code sera supprimé une fois que la migration passée.
> [#21] [CLEANUP] Calcul des marks pour les anciennes certifications (US-1051)

- api/lib/cat/assessment.js
- api/tests/unit/cat/assessment_test.js
> [#47] L'algorithme ne pose pas de question de plus de deux niveaux au-dessus du niveau prédit (US-1114).

- api/lib/cat/assessment.js
- api/tests/unit/cat/assessment_test.js
https://1024pix.atlassian.net/browse/PF-149
> [#60] [FEATURE] L'algo doit parcourir les tubes "facile" en priorité (PF-149).

- api/lib/cat/challenge.js
- api/lib/cat/skill.js
- api/package.json
- api/tests/factory/build-answer.js
- api/tests/factory/build-assessment-result.js
- api/tests/factory/build-cat-challenge.js
- api/tests/factory/build-cat-tube.js
- api/tests/factory/build-certification.js
- api/tests/factory/build-challenge.js
- api/tests/factory/build-competence-mark.js
- api/tests/factory/build-skill-collection.js
- api/tests/factory/build-skill.js
- api/tests/factory/index.js
- api/tests/unit/cat/answer_test.js
- api/tests/unit/cat/assessment_test.js
- api/tests/unit/cat/challenge_test.js
- api/tests/unit/cat/skill_test.js
- api/tests/unit/domain/strategies/SmartRandom_test.js
Recommandation: lire le diff par commit.
Le premier commit est le fix avec ses tests. Le second est une BSR sur un fichier de test.
> [#82] [BUGFIX] Les skills doivent être comparés par noms (PF-103)

- live/app/components/certification-results-page.js
- live/app/styles/components/_certification-result.scss
- live/app/templates/components/certification-results-page.hbs
- live/tests/integration/components/certification-results-page-test.js
*US :* [Lien JIRA](https://1024pix.atlassian.net/secure/RapidBoard.jspa?rapidView=24&projectKey=PF&modal=detail&selectedIssue=PF-164)
*Besoin :*
- Ajout d'un message invitant l'utilisateur à appeler son surveillant avant de voir le message de fin
*Dev :*
- J'ai garder la route certification-result comme elle était. J'ai ajouter un message différent selon si la validation a été faite ou non. 
- Ajout de tests d'intégrations
> [#99] [FEATURE] Modification de l'écran de fin de certif (PF-164).

- api/package.json
- live/scripts/deploy.sh
* api: don't fail db:reset if db/dev.sqlite3 does not exist
* live: suppress terminal error messages on CircleCI
* live: report correct URL at the end of deployment
> [#100] Corrections mineures sur les scripts de déploiement (PF-256)

- api/scripts/reset_db.sh
- live/app/components/certification-code-validation.js
- live/app/styles/components/_certification-code-validation.scss
- live/app/styles/pages/_certification-start.scss
- live/app/templates/certifications/start.hbs
- live/app/templates/components/certification-code-validation.hbs
- live/package.json
- live/tests/integration/components/certification-code-validation-test.js
- live/tests/unit/components/certification-code-validation-test.js
- live/tests/unit/models/certification-test.js
- live/tests/unit/models/organization-test.js
- check if an access code has been entered; if not, display a new error
- refacto certification start page style
> [#106] [FEATURE] Ajout d'un message d'erreur dans la page de saisie du code accès d'une certification en cas de code vide (PF-19).

- live/app/components/competence-level-progress-bar.js
- live/app/components/pix-modale.js
- live/app/styles/components/_competence-level-progress-bar.scss
- live/app/styles/globals/_pix-modale.scss
- live/app/templates/components/competence-level-progress-bar.hbs
- live/tests/integration/components/competence-level-progress-bar-test.js
- live/tests/integration/components/share-profile-test.js
Afficher une fenêtre modale, lorsque l'utilisateur essay de faire une 'Second Chance'.
> [#109] Ajout d'une modale demandant confirmation avant de rejouer une épreuve (PF-40).

- api/lib/application/certificationCourses/certification-course-controller.js
- api/lib/application/certificationCourses/index.js
- api/lib/domain/models/CertificationContract.js
- api/lib/domain/services/certification-service.js
- api/lib/infrastructure/repositories/assessment-repository.js
- api/tests/integration/infrastructure/repositories/assessment-repository_test.js
- api/tests/unit/application/certificationCourses/certification-course-controller_test.js
- api/tests/unit/domain/services/certification-service_test.js
[PF-253] Add ignoreError in computeResult to ignore them when we compute (for details route)
> [#114] [TECH] Réparer la route /details des certifs (PF-253).

- live/app/router.js
- live/app/routes/assessments/resume.js
- live/app/routes/board.js
- live/app/routes/campaigns/skill-review.js
- live/app/routes/certifications/results.js
- live/app/routes/certifications/resume.js
- live/app/routes/compte.js
- live/app/routes/courses/create-assessment.js
- live/app/routes/index.js
- live/app/routes/reset-password.js
- live/app/routes/user-certifications/get.js
- live/app/routes/user-certifications/index.js
- live/app/styles/app.scss
- live/app/styles/globals/_pix-button.scss
- live/app/styles/globals/_pix-page.scss
- live/app/styles/pages/_error.scss
- live/app/templates/error.hbs
- live/tests/unit/routes/assessments/resume-test.js
- live/tests/unit/routes/board-test.js
- live/tests/unit/routes/certifications/results-test.js
- live/tests/unit/routes/certifications/resume-test.js
- live/tests/unit/routes/compte-test.js
- live/tests/unit/routes/index-test.js
- live/tests/unit/routes/reset-password-demand-test.js
> [#134] [CLEANUP] Amélioration de la gestion d'erreurs côté front (PF-292).

- mon-pix/app/components/signin-form.js
- mon-pix/app/components/signup-form.js
- mon-pix/app/routes/inscription.js
- mon-pix/app/styles/components/_competence-level-progress-bar.scss
- mon-pix/app/styles/components/_signin-form.scss
- mon-pix/app/styles/globals/_breakpoints.scss
- mon-pix/app/templates/components/signin-form.hbs
- mon-pix/app/templates/components/signup-form.hbs
- mon-pix/app/templates/inscription.hbs
- mon-pix/package-lock.json
- mon-pix/tests/integration/components/signup-form-test.js
- mon-pix/tests/unit/components/signin-form-test.js
- mon-pix/tests/unit/components/signup-form-test.js
- mon-pix/tests/unit/routes/inscription-test.js
Effectué : 
- Suppression de la redirection forcé vers /compte lors de l'inscription, pour utiliser la redirection vers intentUrl de la session
- Ajout d'un message lorsque l'on va commencer une campagne (code voué à être supprimé dès que la landing page sera faite)
- Nettoyage du bug de "Disponible prochainement" sur les niveau de la home, parce que ça me piquait trop les yeux
> [#155][FEATURE] Rediriger sur une campagne après inscription (PF-241).

- api/lib/domain/services/assessment-service.js
- api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
- api/tests/unit/application/assessments/assessment-controller-save_test.js
- api/tests/unit/domain/services/assessment-service_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
- mon-pix/app/routes/challenge-preview.js
TODO: utiliser un uuid lodash au lieu de `Math.random()` si possible
EDIT: plus besoin.
> [#209] Corrige les previews d'épreuves (PF-396)

- api/lib/infrastructure/datasources/airtable/skill-datasource.js
- api/lib/infrastructure/repositories/challenge-repository.js
- api/tests/acceptance/application/assessments/assessment-controller-get-adaptive-correct_test.js
- api/tests/acceptance/application/assessments/assessment-controller-get-adaptive_test.js
- api/tests/acceptance/application/assessments/assessment-controller-get_test.js
- api/tests/integration/infrastructure/repositories/smart-placement-assessment-repository_test.js
- api/tests/unit/infrastructure/datasources/airtable/skill-datasource_test.js
- api/tests/unit/infrastructure/repositories/challenge-repository_test.js
* Use one request to get all the skills from airtabe
* Load it in Redis to access it in cache
> [#223] [TECH] Modification de la requête des Skills à AirTable (PF-413)

- mon-pix/public/google4f0d4d3693bb73c2.html
Améliorer le référencement par Google Search.
Il suffit d'ajouter le fichier de validation d'indexation fourni par Google Search à la racine du domaine pour en attester la propriété.
⚠️ ⚠️ ⚠️ ATTENTION À NE JAMAIS EFFACER CE FICHIER !!! ⚠️ ⚠️ ⚠️
> [#232] [FEATURE] Ajout d'un fichier de validation pour l'indexation par Google Search Console (PF-412).

- mon-pix/app/routes/campaigns/tutorial.js
- mon-pix/app/styles/globals/_buttons.scss
- mon-pix/app/styles/pages/_campaign-tutorial.scss
- mon-pix/app/templates/campaigns/tutorial.hbs
- mon-pix/tests/acceptance/challenge-page-banner-test.js
- mon-pix/tests/acceptance/resume-campaigns-test.js
- mon-pix/tests/acceptance/start-campaigns-test.js
Ajout d'un bouton gris pour passer les tuto avant une campagne.
> [#261] [FEATURE] Modification du tutorial avec ajout du bouton Ignorer (PF-443).

- mon-pix/app/styles/pages/_campaign-landing-page.scss
Adding css property to horizontly aligns logo on landing page
> [BSR] Aligner horizontalement les logos sur la page de landing.

- api/lib/domain/usecases/create-assessment-result-for-completed-assessment.js
Bugfix d'un bug staging introduit par PF-143.
> [BUGFIX] Changement de l'état d'une évaluation avant la création des résultats (PF-143).

- docs/CONTRIBUTING.md
Ajout d'une partie de nos standards dans le fichier contributing.md
RAS
Les règles ajoutées viennent de feu notre Loi. Elles devraient déjà être respectées.
Si jamais vous souhaitez les changer, n'hésitez pas à faire une PR de changement de règle :)
> [TECH] Ajout de règles dans le fichier contributing.md

- api/lib/domain/validators/session-validator.js
- api/tests/unit/domain/validations/session-validator_test.js
- certif/app/components/routes/authenticated/sessions/new-item.js
- certif/app/styles/globals/forms.scss
- certif/app/styles/pages/authenticated/sessions/no-session-panel.scss
- certif/app/templates/components/routes/authenticated/sessions/new-item.hbs
- certif/app/templates/components/routes/authenticated/sessions/no-session-panel.hbs
- certif/ember-cli-build.js
- certif/package-lock.json
- certif/package.json
- certif/tests/acceptance/session-list-test.js
- certif/tests/acceptance/session-new-test.js
- certif/tests/integration/components/routes/authenticated/sessions/new-item-test.js
- certif/tests/unit/components/routes/authenticated/sessions/new-item-test.js
> Amélioration du style de la page de création de session (suite au merge un peu trop vite de la PC-6)
On a rajouté un datepicker pour la saisie de la date et de l'heure de session.
https://github.com/shipshapecode/ember-flatpickr
Après comparaisons, c'est le mieux qu'on ait trouvé (il permet notamment de saisir une heure !!).
Nada
> [FEATURE] Amélioration de la page de création de session (PC-32)

- .gitignore
- README.md
- api/package.json
- api/scripts/database/empty-database.js
- high-level-tests/e2e/.eslintrc.js
- high-level-tests/e2e/README.md
- high-level-tests/e2e/cypress.json
- high-level-tests/e2e/cypress/fixtures/campaigns.json
- high-level-tests/e2e/cypress/fixtures/organizations.json
- high-level-tests/e2e/cypress/fixtures/target-profiles.json
- high-level-tests/e2e/cypress/fixtures/users.json
- high-level-tests/e2e/cypress/integration/campaign.feature
- high-level-tests/e2e/cypress/integration/demo.feature
- high-level-tests/e2e/cypress/integration/login.feature
- high-level-tests/e2e/cypress/plugins/index.js
- high-level-tests/e2e/cypress/support/commands.js
- high-level-tests/e2e/cypress/support/index.js
- high-level-tests/e2e/cypress/support/step_definitions/assessment.js
- high-level-tests/e2e/cypress/support/step_definitions/campaign.js
- high-level-tests/e2e/cypress/support/step_definitions/index.js
- high-level-tests/e2e/cypress/support/step_definitions/login.js
- high-level-tests/e2e/package-lock.json
- high-level-tests/e2e/package.json
🚀 Contenu
-----------
L'objet de cette PR est d'ajouter Cypress à la base de test haut niveau de Pix.
Cette PR implémente des test **End to End** de Pix, et permet de les exécuter sur un poste de développeur.
Les tests fonctionnent sur SQLite et PostgreSQL.
Pour l'utiliser, lire le README.
🦄 Détails d'implémentation
----------------------------
Nous avons créé un fichier `high-level-tests\e2e` qui contient Cypress.
À terme le dossier `high-level-tests` contiendra aussi les tests de charge et de sécurité.
Les tests sont écrits en Gherkin, langage utilisé par Cucumber.
> [TECH] Ajouter des tests end-to-end en local avec Cypress (PF-500).

- high-level-tests/e2e/cypress/support/step_definitions/login.js
> Le test de bout en bout qui vérifie la connexion est cassé car il s'appuie sur un style css qui a changé.
> Ce changement supprime la dépendance au style css pour soumettre le formulaire.
> Moi ça va pas mal, et toi ?
> [TECH] Fix the login end to end test

- api/lib/application/snapshots/snapshot-controller.js
Le but de cette PR est essentiellement de remplacer une longue chaîne de promesses par du async/await, permettant de clarifier le code et d'extraire des méthodes privées
Dans cette PR, les tests unitaires n'ont pas été touché. Il serait intéressant de le faire, car leur structure est pour le moins incongrue.
> [TECH] Remplacement d'une longue chaîne de promesses par async/await

- admin/app/components/login-form.js
- admin/tests/integration/components/login-form-test.js
- api/lib/application/authentication/index.js
- api/lib/infrastructure/errors.js
- api/lib/infrastructure/serializers/jsonapi/error-serializer.js
- api/lib/infrastructure/utils/error-manager.js
- api/tests/acceptance/application/assessment-results/assessment-result-admin-controller_test.js
- api/tests/acceptance/application/organization-controller_test.js
- api/tests/integration/application/authentication/index_test.js
- api/tests/unit/infrastructure/errors_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/error-serializer_test.js
- mon-pix/app/routes/campaigns/fill-in-id-pix.js
- mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
> [BUGFIX] Corrige la serialization des erreurs.

- api/lib/domain/services/user-service.js
- api/tests/unit/domain/services/user-service_test.js
> Les sessions ne se lançaient plus
> Le repository Answers retourne maintenant un objet Answer et plus un objet Bookshelf.
> [BUGFIX] Problème lors des lancements de certifications

- mon-pix/app/styles/components/_password-reset-demand-form.scss
- mon-pix/app/styles/pages/_sign-form.scss
L'affichage sous IE des pages de login et de réinitialisation de mot de passe était un tout petit peu cassé suite au ticket PF-497 (sur staging).
> [BUGFIX] Fix bugs affichage réinitialisation mot de passe sous IE

- api/lib/domain/models/CompetenceResult.js
- api/lib/domain/usecases/get-campaign-participation-result.js
- api/lib/infrastructure/serializers/jsonapi/campaign-participation-result-serializer.js
- api/tests/acceptance/application/campaign-participation-result-controller_test.js
- api/tests/unit/domain/usecases/get-campaign-participation-result_test.js
> _Décrivez ici le besoin lié à la Pull Request._
> _Ajoutez à cet endroit, si nécessaire, des détails quant à la solution technique mise en place._
> [FEATURE] Ajout des résultats par compétences au résultat d'un participant. (PF-543)

- api/scripts/database/create-database.js
- api/scripts/database/drop-database.js
- api/scripts/database/empty-database.js
- docker-compose.yml
Tous les matins je lance ces deux lignes de commande issue du wiki pour lancer mes containers. Ceci facilitera la vie des nouveaux arrivants qui passeront par la dockerisation de la base PG et Redis comme indiqué dans le wiki.
Un docker-compose file qui documente et permet le démarrage des services.
> Add db:docker script

- api/lib/plugins.js
- api/package-lock.json
- api/package.json
Améliorer la remontée d'erreurs vers sentry.io
On remplace le module obsolète `hapi-raven` par `hapi-sentry`.
> [TECH] Mise à jour du client Sentry côté API.

- certif/app/templates/components/routes/authenticated/sessions/details-item.hbs
- certif/app/templates/components/routes/authenticated/sessions/list-items.hbs
- certif/app/templates/components/routes/authenticated/sessions/new-item.hbs
- certif/app/templates/components/routes/authenticated/sessions/update-item.hbs
Renommer surveillant en surveillants dans tout pix-certif
> [FEATURE] Renommage de surveillant en surveillant(s) (PC-44).

- .circleci/config.yml
- high-level-tests/e2e/cypress/integration/demo.feature
- high-level-tests/e2e/cypress/support/commands.js
- high-level-tests/e2e/cypress/support/step_definitions/assessment.js
- high-level-tests/e2e/package-lock.json
- high-level-tests/e2e/package.json
Vérifier que PIX fonctionne correctement de bout en bout à chaque incrément fonctionnel ou technique.
Faciliter la vie d'Emmy.
Cypress save the Queen.
- Ajout d'un job e2e en CI
- Update de Cypress en 3.2.0
- Ajout de jeux de tests pour les démos
Chose un peu curieuse : ne fonctionne pas actuellement (alors qu'avant si) avec sqLite...
> [TECH] Ajouter Cypress en CI.

- docs/CONTRIBUTING.md
Enrichir le `CONTRIBUTING.md` pour consolider nos aquix et réduire le temps passé en revue de code.
Utilisation d'un bloc-note et création d'un récapitulatif des remarques faites lors de la PR de la PF-371 > PF-536 dédiée à la création de la nouvelle page profil V2
La psilocybine, qui cause les hallucinations, est produite par les champignons pour éloigner les insectes qui pourraient les manger.
> [TECH] Enrichissement du CONTRIBUTING.md sur la base de PF-371 > PF-536

- certif/app/templates/components/routes/authenticated/sessions/details-item.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
- orga/tests/acceptance/campaign-details-test.js
`git rebase -i` et `git reflog` c'est la vie.
> [FEATURE] Renommer les onglets "Paramètres" en "Détails" dans Pix Orga et Pix Certif (PO-202).

- api/lib/application/assessments/assessment-controller.js
- api/lib/domain/models/Assessment.js
- api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
- api/tests/acceptance/application/assessments/assessment-controller-get_test.js
- api/tests/integration/application/assessments/assessment-controller_test.js
- api/tests/tooling/domain-builder/factory/build-assessment.js
- api/tests/unit/application/assessments/assessment-controller_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
Réécriture du serializer à la manière des autres seralizers (en utilisant 'jsonapi-serializer').
> [BSR] Réécriture du serializer d'assessment.

- high-level-tests/e2e/cypress/fixtures/target-profiles_skills.json
- high-level-tests/e2e/cypress/integration/demo.feature
- high-level-tests/e2e/cypress/support/step_definitions/assessment.js
- high-level-tests/e2e/cypress/support/step_definitions/campaign.js
- high-level-tests/e2e/cypress/support/step_definitions/index.js
- mon-pix/app/models/campaign-participation.js
- mon-pix/app/routes/profilv2.js
- mon-pix/app/templates/profilv2.hbs
- mon-pix/mirage/config.js
- mon-pix/mirage/routes/get-user-campaign-participations.js
- mon-pix/mirage/scenarios/default.js
- mon-pix/mirage/serializers/campaign-participation.js
- mon-pix/mirage/serializers/user.js
- mon-pix/tests/acceptance/profilv2-test.js
L'utilisateur doit pouvoir reprendre une campagne entamée depuis son profilv2.
Ajouter le composant déjà existant à profilv2.
> [FEATURE] Ajout de la bannière "Reprendre la campagne" sur profilv2 (PF-544)

- api/lib/application/assessments/assessment-controller.js
- api/lib/domain/models/Assessment.js
- api/lib/infrastructure/serializers/jsonapi/assessment-serializer.js
- api/tests/acceptance/application/assessments/assessment-controller-get_test.js
- api/tests/integration/application/assessments/assessment-controller_test.js
- api/tests/tooling/domain-builder/factory/build-assessment.js
- api/tests/unit/application/assessments/assessment-controller_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/assessment-serializer_test.js
This reverts commit 81c35b9c5e2da721085472d4b43ad8dea81bb3b1.
> _Décrivez ici le besoin ou l'intention couvert par cette Pull Request._
> _Ajoutez à cet endroit, si nécessaire, des détails concernant la solution technique retenue et mise en oeuvre, des difficultés ou problèmes rencontrés._
> [HOTFIX] Correction de la régression de la barre de progression introduite par la PR #438.

- api/lib/domain/models/Assessment.js
La présence dans le code de commentaires obsolète rend sa lecture déplaisante.
Les supprimer en s'assurant auprès des anciens membres de l'équipe qu'ils sont effectivement obsolètes.
> [TECH] Suppression d'anciens commentaires

- api/lib/domain/models/Scorecard.js
- mon-pix/tests/acceptance/competence-details-test.js
Dev n'est plus linté
Le linter
Lint lint lint!
> [TECH] Lint dev

- mon-pix/app/styles/pages/_competence-details.scss
- mon-pix/app/styles/pages/_profilv2.scss
- mon-pix/app/templates/profilv2.hbs
Certains liens couvrent 100% de l'espace disponible dans mon-pix.
Les wrapper ou modifier leur css.
> [BUGFIX] Corriger l'affichage de certains liens de mon-pix. (PF-590)

- mon-pix/app/controllers/assessments/checkpoint.js
- mon-pix/app/styles/components/_checkpoint.scss
- mon-pix/app/styles/globals/_buttons.scss
- mon-pix/app/templates/assessments/checkpoint.hbs
- mon-pix/mirage/data/assessments/ref-assessment-no-answer.js
- mon-pix/mirage/routes/get-assessment.js
- mon-pix/tests/acceptance/checkpoint-test.js
- mon-pix/tests/unit/controllers/assessments/checkpoint-test.js
Avant un utilisateur pouvait tomber sur cette page s'il commençait une campagne en ayant précédemment répondu à toutes les questions:
Ajouter un message quand ce cas surgit:
> [FEATURE] Afficher un message lors d'un checkpoint si aucune réponse n'est affichée. (PF-581)

- mon-pix/app/styles/components/_feedback-panel.scss
- mon-pix/app/templates/components/feedback-panel.hbs
Pour être meilleur en RGPD, nous avons besoin de changer le texte du formulaire de Feedbacks
Changer le texte :)
> [FEATURE] Changement du texte pour les signalements (PF-504).

- mon-pix/app/templates/components/feedback-panel.hbs
Sur les feedbacks, renommer PIX en Pix
> [FEATURE] Renommer PIX en Pix dans les signalements (PF-608).

- orga/app/templates/components/campaign-item.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
Changement de wordings sur les pages de résultats individuels de campagnes
> [FEATURE] Changement de wordings sur les pages de résultats de campagnes (PO-208).

- mon-pix/app/templates/components/certification-results-page.hbs
> On veut supprimer la phrase `Vous serez averti par e-mail.` sur la page de fin de certification.
> Supprimer une phrase sur la page de fin de certification (PF-611).

- mon-pix/app/styles/components/_competence-card.scss
- mon-pix/app/styles/globals/_palette.scss
- mon-pix/app/templates/components/competence-card.hbs
Competence-card n'est pas animée.
Rajouter des transitions CSS à foison.
> [FEATURE] Ajouter des animations CSS sur competence-card (PF-586).

- api/package.json
Le script pour créer une migration a été supprimé dans une PR précédente.
Remettre le script en question.
> [TECH] Ajout d'un script pour créer une nouvelle migration.

- orga/app/styles/pages/authenticated/campaigns/details.scss
- orga/app/templates/components/routes/authenticated/campaigns/details-item.hbs
- orga/tests/integration/components/routes/authenticated/campaigns/details-item-test.js
Le code d'une campagne n'est pas clairement affiché.
L'afficher :)
> [FEATURE] Afficher le code campagne dans Pix Orga (PO-213)

- mon-pix/app/components/signup-form.js
- mon-pix/app/styles/components/_rounded-panel.scss
- mon-pix/app/styles/globals/_palette.scss
- mon-pix/app/styles/pages/_profile.scss
- mon-pix/app/templates/profile.hbs
- mon-pix/tests/integration/components/signup-form-test.js
Le rendu visuel du bandeau de nouveau profil peut être améliorer ainsi que le responsive.
On affiche le lien sur l'évolution du nouveau profil pour tous les utilisateurs après qu'ils aient fermé le gros bandeau.
> [FEATURE] Optimisation graphique du bandeau de nouveau profil. (PF-772)

- mon-pix/app/styles/components/_scorecard-details.scss
Problème d'affichage des détails d'une compétence sous IE.
Prise en compte d'IE dans le css.
> [BUGFIX] Problème d'affichage des détails d'une compétence sous IE (PF-775).

- docs/Glossaire-Variables-Env.md
Les variables d'environnement sont associées à des fonctionnalités parfois fondamentales de nos applications et parfois même critiques. La connaissance de leur utilité et de leur nécessité dans un environnement E n'est pas forcément diffusée.
* Créer un glossaire des variables d'environnement sur Confluence
* Reporter ce glossaire dans la documentation du code pour faciliter les recherches
* Compléter ces documents des différents ajouts dans le code
> [TECH] Ajout d'un glossaire des variables d'environnement dans la documentation

- high-level-tests/e2e/package-lock.json
- high-level-tests/e2e/package.json
Afin de pas être dépassés dans les versions des différentes dépendances du projet, il est nécessaire de mettre à jour régulièrement ces dépendances.
Cette PR permet de maintenir à jour Cypress, qui est utilisé pour les tests de bout en bout.
> [TECH] Mise à jour de Cypress.

- mon-pix/app/templates/components/signup-form.hbs
Le texte des détails légaux n'est plus à jour.
Le mettre à jour avec le nouveau texte.
> [FEATURE] Mettre à jour le texte sur la page d'inscription (PF-797).

- mon-pix/app/controllers/campaigns/campaign-landing-page.js
- mon-pix/app/controllers/campaigns/fill-in-id-pix.js
- mon-pix/app/controllers/campaigns/skill-review.js
- mon-pix/app/routes/campaigns/campaign-landing-page.js
- mon-pix/app/routes/campaigns/fill-in-id-pix.js
- mon-pix/app/routes/campaigns/skill-review.js
- mon-pix/app/templates/campaigns/fill-in-id-pix.hbs
- mon-pix/app/templates/campaigns/skill-review.hbs
- mon-pix/tests/acceptance/skill-review-page-test.js
- mon-pix/tests/unit/controllers/campaigns/campaign-landing-page-test.js
- mon-pix/tests/unit/controllers/campaigns/fill-in-id-pix-test.js
- mon-pix/tests/unit/controllers/campaigns/skill-review-test.js
- mon-pix/tests/unit/routes/campaigns/campaign-landing-page-test.js
- mon-pix/tests/unit/routes/campaigns/fill-in-id-pix-test.js
Il peut être compliqué de se retrouver dans le code de certaines routes des campagnes.
Réécriture de certaines parties du code en suivant des standard plus clairs:
- async / await
- utilisation des computed de Ember
- redistribuer certaines responsabilités selon les conventions Ember
> [TECH] Réécriture de certaines routes des campagnes.

- mon-pix/app/styles/components/_form-textfield.scss
Sur Mon-Pix le contour des champs de formulaire sont peu visible sur certain écran du à leur faible résolution.
S'inspirer des formulaires de Pix orga et certif qui eux sont visibles.
> [FEATURE] Améliorer l'affichage des champs de formulaire (PF-114).

- docs/adr/0003-langages-frameworks-et-technologies.md
> [DOC] Ajout d'une ADR à propos du choix des langages, frameworks et technologies sur Pix.

- mon-pix/app/styles/components/_certification-starter.scss
- mon-pix/app/styles/pages/_certification-start.scss
- mon-pix/app/templates/components/certification-starter.hbs
- mon-pix/package-lock.json
- mon-pix/package.json
On souhaite homogénéiser le look de la page de lancement de test de certification et se rapprocher de celui de lancement d'un parcours.
- Modification de la police et de la taille du titre
- Inversement des positions du texte officiel et du bouton Lancer le test
- Ajout des indicateurs de nombre de caractères
- Appuyer sur la touche entrée pour lancer le test
> [FEATURE] Modification du design de la page de lancement de test de certification (PF-849)

- orga/app/styles/pages/authenticated/terms-of-service.scss
- orga/app/styles/pages/login.scss
Problème d'affichage de background sur page login et cgu, en fonction de la hauteur de la page.
Régler l'alignement en hauteur et ajouter une min-height.
> [BIUGFIX] Problème de background sur les pages de connexion et CGU (PO-206).

- api/lib/config.js
- api/lib/plugins.js
- package-lock.json
- package.json
- scripts/release/publish.sh
Quand un problème survient côté API et est remonté par Sentry, il est difficile de savoir s'il s'agit d'un nouveau bug, d'une régression ou d'une mauvaise correction.
Cette PR a pour objectif de mieux intégrer Sentry dans l'API.
**1/** La première amélioration consiste à prendre en compte de **nouveaux paramètres** tels que : 
- `client.release` : la version de l'application attaché à l'évènement
- `client.maxBreadcrumbs` : la taille du message remonté
> Objectif : pouvoir associer un problème à une release particulière et pouvoir récupérer plus d'information que les 100 lignes par defaut.
**2/** La seconde amélioration touche le script de mise en production et rajoute une étape de création et **publication d'une _release_ dans Sentry**, en associant les commits concernés.
> Objectif : …
> [TECH] Amélioration de l'intégration de Sentry dans l'API (PF-921)

- .circleci/config.yml
- high-level-tests/e2e/.eslintrc.js
- high-level-tests/e2e/cypress/fixtures/memberships.json
- high-level-tests/e2e/cypress/fixtures/users.json
- high-level-tests/e2e/cypress/integration/campaign-management.feature
- high-level-tests/e2e/cypress/support/commands.js
- high-level-tests/e2e/cypress/support/step_definitions/assessment.js
- high-level-tests/e2e/cypress/support/step_definitions/campaign.js
- high-level-tests/e2e/cypress/support/step_definitions/index.js
- high-level-tests/e2e/cypress/support/step_definitions/login.js
- high-level-tests/e2e/package.json
Il n'existait pas de tests end-to-end sur Pix Orga.
Ajouter des tests Cypress.
> [TECH] Ajout de tests e2e avec Cypress sur Pix Orga (PO-280)

- api/db/migrations/20191202164101_replace_unique_on_national_student_id_by_unique_on_national_student_id_and_organization_id.js
- api/lib/domain/usecases/import-students-from-siecle.js
- api/lib/infrastructure/repositories/student-repository.js
- api/tests/acceptance/application/organization-controller_test.js
- api/tests/integration/infrastructure/repositories/student-repository_test.js
- api/tests/unit/domain/usecases/import-students-from-siecle_test.js
Actuellement certains établissements ne peuvent pas importer leurs élèves, car ces derniers étaient déjà importés dans d'autres établissements.
Permettre qu'un élève puisse être importé dans plusieurs établissements.
> [FEATURE] Permettre à un élève d'être importé dans plusieurs établissements scolaires (PO-293).

- high-level-tests/e2e/cypress/integration/login.feature
- high-level-tests/e2e/cypress/integration/signup.feature
- high-level-tests/e2e/cypress/support/step_definitions/index.js
- high-level-tests/e2e/cypress/support/step_definitions/login.js
- mon-pix/app/styles/components/_navbar-desktop-header.scss
- mon-pix/app/styles/components/_navbar-mobile-header.scss
- mon-pix/app/styles/components/_user-logged-menu.scss
- mon-pix/app/templates/components/navbar-mobile-header.hbs
- mon-pix/app/templates/components/user-logged-menu.hbs
- mon-pix/public/images/burger.svg
- mon-pix/public/images/pix-logo.svg
- mon-pix/tests/integration/components/user-logged-menu-test.js
Le design du menu de mon-pix comportait des lacunes historiques
> [TECH] Ajuster le design du menu de mon-pix (PF-925)

- certif/app/components/login-form.js
- certif/tests/unit/components/login-form-test.js
- mon-pix/app/components/password-reset-demand-form.js
- mon-pix/app/components/signup-form.js
- mon-pix/app/routes/login.js
- mon-pix/tests/unit/components/password-reset-demand-form-test.js
- mon-pix/tests/unit/components/signup-form-test.js
- mon-pix/tests/unit/routes/login-test.js
- orga/app/components/routes/login-form.js
- orga/package-lock.json
- orga/package.json
- orga/tests/unit/components/routes/login-form-test.js
* Lors des process de connexion, inscription et changement de mot de passe, s'il y a un espace au début ou à la fin de l'e-mail, alors le user ne sera pas reconnu (même si son e-mail originel se trouve bien en base de données).
* Le prénom et le nom doivent être identiquement _nettoyés_ lors d'une inscription.
Dans Mon-Pix, Orga et Certif supprimer les espaces en trop au début et à la fin des champs email, firstName et lastName dans les routes ou components concernés, avant les appels à l'API.
> [FEATURE] Suppression des espaces inutiles (e-mail, prénom et nom) lors des connexion, inscription et changement de mdp (PF-847).

- orga/app/components/routes/authenticated/students/list-items.js
- orga/app/controllers/authenticated/campaigns/new.js
- orga/app/controllers/authenticated/students/list.js
- orga/app/controllers/authenticated/team/new.js
- orga/app/routes/authenticated/students/list.js
- orga/app/routes/authenticated/team/new.js
- orga/app/services/notifications.js
- orga/app/styles/globals/colors.scss
- orga/app/styles/globals/errors.scss
- orga/app/templates/application.hbs
- orga/app/templates/authenticated/campaigns/new.hbs
- orga/app/templates/authenticated/students/list.hbs
- orga/app/templates/authenticated/team/new.hbs
- orga/app/templates/components/routes/authenticated/students/list-items.hbs
- orga/config/environment.js
- orga/package-lock.json
- orga/package.json
- orga/tests/acceptance/campaign-creation-test.js
- orga/tests/acceptance/student-list-test.js
- orga/tests/acceptance/team-creation-test.js
Les notifications ne sont pas uniformisées sur toutes les applications Pix. De plus, celles actuelles ne nous permettent pas d'envoyer une notification alors que l'on est redirigé.
Ajout de la librairie `ember-cli-notifications` et remplacement de l'ancien système par le nouveau dans les pages suivantes :
- création de campagnes ;
- ajout de membre à l'organization ;
- import du fichier SIECLE.
> [FEATURE] Mettre en place un système de notifications sur Pix Orga (PO-236).

- api/db/migrations/20191217105506_add_username_to_users.js
- api/db/seeds/data/users-builder.js
- api/lib/application/authentication/authentication-controller.js
- api/lib/application/authentication/index.js
- api/lib/domain/models/User.js
- api/lib/domain/usecases/authenticate-user.js
- api/lib/infrastructure/data/certification-center-membership.js
- api/lib/infrastructure/repositories/user-repository.js
- api/tests/integration/application/authentication/index_test.js
- api/tests/integration/infrastructure/repositories/user-repository_test.js
- api/tests/tooling/database-builder/factory/build-user.js
- api/tests/tooling/domain-builder/factory/build-user.js
- api/tests/unit/application/authentication/authentication-controller_test.js
- api/tests/unit/domain/usecases/authenticate-user_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/validation-error-serializer_test.js
- certif/app/templates/components/login-form.hbs
- high-level-tests/e2e/cypress/support/step_definitions/login.js
- mon-pix/app/components/signin-form.js
- mon-pix/app/templates/components/signin-form.hbs
- mon-pix/mirage/routes/post-authentications.js
- mon-pix/tests/acceptance/authentication-test.js
- mon-pix/tests/acceptance/profile-test.js
- mon-pix/tests/acceptance/resume-competence-evaluations-test.js
- mon-pix/tests/helpers/testing.js
- mon-pix/tests/integration/components/signin-form-test.js
- orga/app/templates/components/routes/login-form.hbs
- orga/package-lock.json
Certains utilisateurs de Pix n'ont pas d'adresse e-mail, on souhaite alors leur proposer un autre moyen de connexion. 
Ajout de la possibilité de connexion avec un identifiant. 
La partie inscription avec un identifiant sera faite dans une prochaine PR.
> [FEATURE] Pouvoir se connecter avec un identifiant (PF-982).

- api/db/seeds/data/campaigns-builder.js
- api/db/seeds/data/organizations-builder.js
- mon-pix/app/components/routes/login-form.js
- mon-pix/app/components/routes/login-or-register.js
- mon-pix/app/components/routes/register-form.js
- mon-pix/app/router.js
- mon-pix/app/routes/campaigns/start-or-resume.js
- mon-pix/app/routes/login-or-register-to-access-restricted-campaign.js
- mon-pix/app/styles/app.scss
- mon-pix/app/styles/components/_login-form.scss
- mon-pix/app/styles/components/_login-or-register.scss
- mon-pix/app/styles/components/_register-form.scss
- mon-pix/app/styles/globals/_breakpoints.scss
- mon-pix/app/styles/globals/_buttons.scss
- mon-pix/app/styles/pages/_login-or-register-to-access-restricted-campaign.scss
- mon-pix/app/styles/pages/_sign-form.scss
- mon-pix/app/templates/components/password-reset-demand-form.hbs
- mon-pix/app/templates/components/routes/login-form.hbs
- mon-pix/app/templates/components/routes/login-or-register.hbs
- mon-pix/app/templates/components/routes/register-form.hbs
- mon-pix/app/templates/login-or-register-to-access-restricted-campaign.hbs
- mon-pix/package-lock.json
- mon-pix/tests/acceptance/login-or-register-to-access-restricted-campaign-test.js
- mon-pix/tests/acceptance/start-campaigns-test.js
- mon-pix/tests/integration/components/routes/login-form-test.js
- mon-pix/tests/integration/components/routes/register-form-test.js
Mise en place d'une double mire de connexion/inscription une fois que l'élève a saisi un code parcours.
L'élève étant mineur ici, il a fallu faire évoluer l'API de création d'utilisateur afin de permettre de créer un utilisateur sans validation de CGU au préalable.
> [FEATURE] Ajout d'une page de connexion/inscription après avoir renseigné un code parcours (PF-942).

- mon-pix/app/templates/error.hbs
Ajout d'une phrase d'information dans la page d'erreur afin d'informer l'utilisateur de l'importance pour nous du code d'erreur affiché en bas de page.
> [FEATURE] Amélioration du message de la page d'erreur (PF-1023)

- api/lib/application/student-user-associations/student-user-association-controller.js
- api/lib/domain/services/user-reconciliation-service.js
- api/lib/domain/usecases/create-and-associate-user-to-student.js
- api/lib/domain/usecases/generate-username.js
- api/lib/domain/usecases/link-user-to-organization-student-data.js
- api/tests/acceptance/application/student-user-association-controller_test.js
- api/tests/integration/application/student-dependent-users/index_test.js
- api/tests/integration/application/student-user-associations/index_test.js
- api/tests/integration/domain/usecases/create-and-associate-user-to-student_test.js
- api/tests/unit/domain/services/user-reconciliation-service_test.js
- api/tests/unit/domain/usecases/create-and-associate-user-to-student_test.js
- api/tests/unit/domain/usecases/generate-username-test.js
- api/tests/unit/domain/usecases/link-user-to-organization-student-data_test.js
Après les review du PF-966, quelques modifications techniques mineures demandées n’ont pas été  implémentées, avant la MEP.
Ce ticket va prendre en charge ces modifications.
> _Voir @jonathanperret pour : https://github.com/1024pix/pix/pull/973#discussion_r366985863_
> [TECH] Prise en compte des derniers retours de la PR #913 (prereconciliation) (PF-1038).

- docs/adr/0006-ajout-du-support-de-sendinblue-pour-le-mailing.md
On à oublier de modifier le statut de l'ADR concernant Sendinblue.
On passe le statut à "Accepter".
En pensant, j'en profite pour faire la 1000 ème sur Pix =P
> Changer le statut de l'ADR n°6 pour la 1000ème.

- api/lib/application/passwords/password-controller.js
- api/tests/unit/application/passwords/password-controller_test.js
Le code qui générait le mail de reset de mot de passe créait un lien en http
Créer un lien en https
> [TECH] Générer des liens de reset de mot de passe en https (PF-1065).

- api/lib/application/campaigns/campaign-controller.js
- api/tests/unit/application/campaign/campaign-controller_test.js
Le téléchargement des fichiers CSV (résultats de campagne) ne se fait plus 😢
Réparer le téléchargement ! 😀
C'est une régression (mais uniquement en intégration)
> [BUGFIX] Réparer le téléchargement des CSV sur Pix Orga (PO-333).

- api/lib/infrastructure/repositories/campaign-repository.js
- api/tests/integration/infrastructure/repositories/campaign-repository_test.js
- orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
- orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
Actuellement nous n'avons pas beaucoup d'informations sur la page des campagnes.
Nous avons rajouté la date de création de la campagne.
Vive le TDD :D !!!
Ne pas valider cette PR avant d'avoir validé la https://github.com/1024pix/pix/pull/992 \(^_^)/
> [FEATURE] Ajouter la colonne "Créé le" dans la liste des campagnes (PO-307).

- orga/app/controllers/authenticated/team/new.js
- orga/app/templates/authenticated/team/new.hbs
- orga/app/templates/components/routes/authenticated/team/new-item.hbs
- orga/tests/acceptance/team-creation-test.js
Il est possible de cliquer plusieurs fois sur le bouton 'inviter', et d'avoir ensuite des appels API surnuméraires.
Ajouter un système de désactivation du bouton, lors du premier clic.
> [BUGFIX] Correction dans Pix Orga du multi click sur le bouton d'invitation (PO-335).

- api/lib/domain/usecases/index.js
Le fichier get-user est vide depuis [ce commit](https://github.com/1024pix/pix/commit/6357b38f75830b96a6643965d425697aa9f7d276)
> [TECH] Suppression de get-user.

- mon-pix/app/styles/app.scss
- mon-pix/app/styles/components/_form-textfield.scss
- mon-pix/app/styles/components/_register-form.scss
- mon-pix/app/styles/pages/_join-restricted-campaign.scss
- mon-pix/app/templates/components/routes/register-form.hbs
- mon-pix/public/images/pix-logo.svg
Correction de petits bugs sur pix app
> [BUGFIX] Correction de régressions visuelles mineures sur Pix App.

- admin/app/services/csv-service.js
- admin/app/services/session-info-service.js
- admin/config/environment.js
- admin/tests/unit/services/csv-service-test.js
- admin/tests/unit/services/session-info-service-test.js
Une faille de sécurité (comma-separated-vulnerabilities) peut être exploitée lors de la génération et l'export des fichiers csv dans Pix Admin.
En effet, lorsque le fichier csv sera lu par un tableur, toutes les cellules commençant par le caractère «=» seront interprétées comme des formules.
cf. https://www.contextis.com/en/blog/comma-separated-vulnerabilities
Echapper les chaines de caractères commençant par les symboles =, -, +, ou @
avec le caractère " **'** "
> [FEATURE] Gestion des caractères à risque lors des exports CSV dans Pix Admin (PA-148).

- orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
Changer le terme *Parcours* par le terme métier *Campagne* dans Orga.
> [FEATURE] Remplacer le terme Parcours par Campagne. (PO-348)

- mon-pix/app/styles/components/_assessment-banner.scss
Le bouton quitter lors des évaluations n'étaient pas assez visible
Changer la police du texte et bien l'aligner
> [FEATURE] Améliorer la visibilité du bouton quitter (PF-1014).

- api/db/migrations/20200225130232_remove-user-id-in-organizations.js
- api/db/seeds/data/dragon-and-co-builder.js
- api/db/seeds/data/organizations-builder.js
- api/lib/domain/models/Organization.js
- api/lib/infrastructure/data/organization.js
- api/lib/infrastructure/data/user.js
- api/lib/infrastructure/repositories/organization-repository.js
- api/lib/infrastructure/serializers/jsonapi/organization-serializer.js
- api/tests/acceptance/application/organization-controller_test.js
- api/tests/integration/infrastructure/repositories/organization-repository_test.js
- api/tests/tooling/database-builder/factory/build-organization.js
- api/tests/tooling/domain-builder/factory/build-organization.js
- api/tests/unit/domain/models/organization_test.js
- api/tests/unit/infrastructure/serializers/jsonapi/organization-serializer_test.js
La relation User-Organization servait à définir qui avait le droit d'accéder à Pix Board. Cette relation est désormais obsolète.
Suppression du code relatif à cet usage.
Un backup de la base sera stocké quelque part pour l'archivage des données.
> [TECH] Pix Board - Suppression du code relatif au lien user-organization dans l'API (PF-876-5).

- api/lib/infrastructure/repositories/campaign-repository.js
- api/tests/integration/infrastructure/repositories/campaign-repository_test.js
- orga/app/components/routes/authenticated/campaigns/list-items.js
- orga/app/controllers/authenticated/campaigns/list.js
- orga/app/routes/authenticated/campaigns/list.js
- orga/app/styles/app.scss
- orga/app/styles/components/search-input.scss
- orga/app/styles/components/select-creator.scss
- orga/app/styles/globals/tables.scss
- orga/app/templates/authenticated/campaigns/list.hbs
- orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
- orga/app/templates/components/routes/authenticated/campaigns/select-creator.hbs
- orga/mirage/serializers/membership.js
- orga/tests/acceptance/campaign-list-test.js
- orga/tests/integration/components/routes/authenticated/campaigns/list-items-test.js
Actuellement, on voit l'ensemble de la liste des campagnes liés à une organisation. On voudrait pouvoir filtrer la liste par créateur de campagne.
Ajout d'un select afin de pouvoir afficher les campagnes créé par une personne de l'organisation.
> [FEATURE] Ajout d'un filtre sur la colonne "Créé par" dans la liste des campagnes (PO-330).

- high-level-tests/e2e/cypress/fixtures/answers.json
- high-level-tests/e2e/cypress/fixtures/assessments.json
- high-level-tests/e2e/cypress/fixtures/campaign-participations.json
- high-level-tests/e2e/cypress/fixtures/knowledge-elements.json
- high-level-tests/e2e/cypress/fixtures/target-profiles.json
- high-level-tests/e2e/cypress/fixtures/users.json
- high-level-tests/e2e/cypress/integration/campaign-management.feature
- high-level-tests/e2e/cypress/integration/campaign.feature
- high-level-tests/e2e/cypress/integration/demo.feature
- high-level-tests/e2e/cypress/integration/login-logout-app.feature
- high-level-tests/e2e/cypress/integration/login-logout-orga.feature
- high-level-tests/e2e/cypress/integration/organization-management.feature
- high-level-tests/e2e/cypress/plugins/index.js
- high-level-tests/e2e/cypress/support/step_definitions/campaign.js
- high-level-tests/e2e/cypress/support/step_definitions/index.js
- high-level-tests/e2e/cypress/support/step_definitions/login-logout.js
- mon-pix/app/templates/campaigns/fill-in-campaign-code.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details/collective-results-tab.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details/participants-tab.hbs
- orga/app/templates/components/routes/authenticated/campaigns/details/participants/results-item.hbs
- orga/app/templates/components/routes/authenticated/campaigns/list-items.hbs
Les POs passent une batterie de tests manuels à chaque mise en production. Ils sont listés dans un fichier de recette.
Automatiser une partie des tests présents dans le fichier de recette pour l'application Pix Orga.
On a commencé par les tests les plus critiques.
> [TECH] Ajout de tests E2E sur Pix Orga (PO-383).

- docs/pull_request_template.md
Il est récurrent de ne pas savoir quoi faire pour tester une PR.
Dédier une section à cet effet dans le template de la PR.
C'est une suggestion. Keep / Drop
> [DOC] Ajouter la section de test dans le template de PR.

- api/lib/application/error-manager.js
- api/lib/domain/errors.js
- api/tests/acceptance/application/organizations/organization-controller-import-students_test.js
- orga/app/controllers/authenticated/students/list.js
- orga/app/styles/globals/errors.scss
- orga/mirage/config.js
- orga/tests/acceptance/student-list-test.js
Actuellement le message d'erreur générique dit de contacter support@pix.fr.
Pour soulager le support, on remplace cette mention par un lien vers le formulaire présent dans le centre d'aide.
> [FEATURE] Modifier le message d'erreur générique lors d'un import SIECLE en ajoutant un lien vers le formulaire du centre d'aide (PO-388).

- mon-pix/app/components/learning-more-panel.js
- mon-pix/app/components/qrocm-dep-solution-panel.js
- mon-pix/app/components/qrocm-ind-solution-panel.js
- mon-pix/tests/unit/components/qrocm-dep-solution-panel-test.js
- mon-pix/tests/unit/components/qrocm-ind-solution-panel-test.js
- Les QROM s'affichent mal sur les résultats.
- Problème de .get lors du cleanup octane.
> [BUGFIX] Problème d'affichage des réponses des QROCM (PIX-636).

- api/db/seeds/data/organizations-builder.js
- orga/app/components/password-reset-window.js
- orga/app/styles/globals/pix-modal.scss
- orga/app/templates/components/password-reset-window.hbs
- orga/tests/acceptance/student-list-test.js
- orga/tests/integration/components/password-reset-window-test.js
Dans Pix Orga, un membre d'une organisation SCO (un professeur) peut générer un mot de passe unique pour un élève.
Le professeur ne se trouve pas dans la même salle que l'élève, ou souhaite éviter les erreurs de compréhension orale. Il veut pouvoir les transmettre par mail ou par chat. Dans ce cas, il doit écrire le mot de passe, ce qui peut engendrer des erreurs et est fastidieux.
Utilisation de la fonctionnalité apportée par ember-cli-clipboard pour copier du texte dans le presse-papier
- Se connecter en tant que membre d'une organisation de type SCO (sco@example.net)
- Aller sur la page listant les élèves
- Gérer un élève
- Dans la pop-up copier/coller les informations
> [FEATURE] Copier/Coller les informations contenues dans la pop-up Gestion du compte de l'élève de PixOrga (PIX-557).

- certif/app/components/login-form.hbs
- certif/app/styles/components/login-form.scss
- certif/app/styles/pages/login.scss
Le message sur la page de connexion porte à confusion. On a l’impression qu’on peut se connecter dès lors qu’on a un compte sur app.pix.fr, ce qui n’est pas vrai.
Supprimer la mention du compte Pix
Mise en cohérence du design avec la page de login Pix orga.
Rendre la page de login responsive.
Fixer proprement le centrage vertical du form sur IE qui ne fonctionnait pas correctement avec du Flex.
Enlever un padding-top.
Pas besoin de compte
> [FEATURE] Améliorer le design de la page de login (PIX-511).

- mon-pix/app/components/challenge-statement.js
- mon-pix/app/templates/components/challenge-item-qcm.hbs
- mon-pix/app/templates/components/challenge-item-qcu.hbs
- mon-pix/app/templates/components/challenge-item-qroc.hbs
- mon-pix/app/templates/components/challenge-item-qrocm.hbs
- mon-pix/app/templates/components/challenge-statement.hbs
- mon-pix/tests/integration/components/challenge-statement-test.js
- mon-pix/tests/unit/components/challenge-statement-test.js
Challenge statement est décoré en classic.
Le glimmerizer
- Tester plusieurs questions, de différents types 
- https://app-pr1393.review.pix.fr/courses/recyLsVqy8Mm5rniR
> [TECH] Glimmerize challenge-statement (PIX-676).

- admin/app/controllers/authenticated/certifications/certification/details.js
- admin/app/controllers/authenticated/certifications/certification/informations.js
- api/db/migrations/20200522090553_add-competenceId-column-competence-marks-table.js
- api/db/seeds/data/certification/certification-data.js
- api/lib/application/assessment-results/assessment-result-controller.js
- api/lib/domain/events/CertificationScoringCompleted.js
- api/lib/domain/events/handle-certification-partner.js
- api/lib/domain/events/handle-certification-scoring.js
- api/lib/domain/events/index.js
- api/lib/domain/models/CertificationPartnerAcquisition.js
- api/lib/domain/models/CompetenceMark.js
- api/lib/domain/services/scoring/scoring-certification-service.js
- api/lib/infrastructure/repositories/competence-mark-repository.js
- api/tests/integration/domain/services/scoring/scoring-certification_test.js
- api/tests/integration/infrastructure/repositories/competence-mark-repository_test.js
- api/tests/tooling/database-builder/factory/build-competence-mark.js
- api/tests/tooling/domain-builder/factory/build-competence-mark.js
- api/tests/unit/domain/events/handle-certification-partner_test.js
- api/tests/unit/domain/events/handle-certification-scoring_test.js
- api/tests/unit/domain/models/CertificationPartnerAcquisition_test.js
- api/tests/unit/domain/services/certification/certification-service_test.js
Voir la PR https://github.com/1024pix/pix/pull/1446. 
Suite à une mauvaise manip, la PR a du être refaite.
> [BUGFIX] Vérifier le seuil des 75% CléA sur le score certifié par compétence (et non positionné) (PIX-680).

- mon-pix/app/components/qroc-proposal.js
- mon-pix/app/templates/components/qroc-proposal.hbs
- mon-pix/mirage/factories/challenge.js
- mon-pix/mirage/factories/tutorial.js
- mon-pix/mirage/serializers/correction.js
- mon-pix/tests/acceptance/challenge-qcm-test.js
- mon-pix/tests/acceptance/challenge-qcu-test.js
- mon-pix/tests/acceptance/challenge-qroc-test.js
- mon-pix/tests/acceptance/challenge-qrocm-test.js
- mon-pix/tests/acceptance/challenge-timed-test.js
- Lors d'une précédente MEP, des erreurs étaient passés sur des types d'épreuves spécifiques, sur la page d'épreuve et sur la page de résultat.
- Compléter nos tests pour que ces regressions soient visibles durant le développement
- Rien pour l'instant
> [CLEANUP] Ajout de tests sur les challenges (PIX-638).

- api/scripts/generate-certification-test-statistics.js
> Quels sont les impacts sur les process de certification du déplacement des tubes.
Des statistiques ont été recueillies en générant massivement des tests de certification, un premier temps en se basant sur un référentiel avant les changements, puis après.
Il en retourne que les compétences sujettes au déplacement des tubes vont voir la proportion de tests de certif évaluant cette compétence avec moins de 3 questions s'agrandir, mais toujours sur une échelle négligeable.
Consultez l'équipe certif si vous souhaitez avoir le détail des résultats de l'étude.
Sinon, on merge quand même cette PR car le script écrit permet de générer massivement des tests de certifs et d'en recueillir des statistiques. #CaPeutServir
> [TECH] Ecriture d'un script pour élaborer des statistiques sur la qualité des tests de certification (PIX-738)

- orga/app/components/routes/register-form.js
- orga/app/styles/globals/errors.scss
- orga/app/templates/components/routes/register-form.hbs
- orga/app/utils/input-validator.js
- orga/tests/unit/utils/input-validator-test.js
Suite à l'empêchement d'envoyer le formulaire d'inscription à Pix Orga si celui-ci n'était pas valide, les messages d'erreurs avaient disparu.  
Modifier la gestion de la validation du formulaire d'inscription.
https://orga-pr1477.review.pix.fr/rejoindre?invitationId=100047&code=DZWMP7L5UM
> [BUGFIX]  Amélioration de la validation du formulaire d'inscription dans Pix Orga (PIX-468).

- admin/app/components/organization-information-section.hbs
- admin/app/components/organization-information-section.js
- admin/app/controllers/authenticated/organizations/get.js
- admin/app/styles/authenticated/organizations/get.scss
- admin/app/styles/misc/form.scss
- admin/app/styles/misc/global.scss
- admin/app/styles/misc/palette.scss
- admin/app/templates/authenticated/organizations/get.hbs
- admin/mirage/config.js
- admin/package-lock.json
- admin/package.json
- admin/tests/acceptance/organization-information-management-test.js
- admin/tests/integration/components/organization-information-section-test.js
- api/lib/domain/usecases/update-organization-information.js
- api/tests/unit/domain/usecases/update-organization-information_test.js
Il est aujourd'hui impossible (à part directement en base en base) de modifier le nom, identifiant externe et département d'une organisation.
Rajouter dans Pix Admin, un formulaire de mise à jour de ces informations.
- Afin de gérer la validation du formulaire, nous avons fait le choix d'ajouter la librairie `ember-cp-validations` dans Pix Admin.
- Ajout d'une validation du payload coté API sera effectuée dans un prochain ticket.
> [FEATURE] Mettre à jour le nom, identifiant externe et département d'une organisation dans Pix Admin (PIX-456).

- docs/Accessibilite.md
Suite au point sur l'accessibilité, petite proposition d'update de notre doc sur le sujet :)
> [DOC] Mise à jour des bonnes pratiques d'accessibilité

- mon-pix/app/static-data/feedback-panel-issue-labels.js
On souhaite permettre à l'utilisateur de notifier d'un problème d'accessibilité.
Ajouter un nouveau type de feedback dans la dropdown du bouton "signaler" d'une épreuve.
Sur une épreuve, créer un nouveau feedback sur l'accessibilité.
Après envoi, le feedback est bien présent en DB.
> [FEATURE] Ajouter un nouveau type de signalement (PIX-836).

- admin/.template-lintrc.js
- admin/app/styles/misc/page.scss
- admin/app/templates/authenticated/certifications.hbs
- admin/app/templates/authenticated/certifications/certification/details.hbs
- admin/app/templates/authenticated/certifications/certification/informations.hbs
- admin/app/templates/authenticated/organizations/get.hbs
- admin/app/templates/authenticated/sessions/session.hbs
- admin/app/templates/authenticated/sessions/session/certifications.hbs
- admin/app/templates/authenticated/sessions/session/informations.hbs
- admin/app/templates/authenticated/tools.hbs
- admin/app/templates/authenticated/users/get.hbs
Dans Pix Admin, de nombreuses erreurs existent dans les templates (linter hbs).
Effectuer la correction de ces erreurs dans `app/templates/authenticated/**.hbs`
Effectuer un test fonctionnel général de Pix Admin.
Exécuter le linter npm run lint
> [CLEANUP] Corriger les erreurs signalées dans Pix Admin, par le linter dans app/templates/authenticated (PIX-878).

- api/lib/domain/services/user-service.js
En menant l'enquête :detective:  sur les performances dégradées de l'export CSV sur les campagnes de collecte de profil,
nous nous sommes aperçus qu'une amélioration intéressante (et à petit prix !) pouvait être réalisée via un petit refacto.
En gros, pour créer l'objet CertificationProfile (qui permet de savoir si la personne est certifiable ou pas etc...), on passait par la construction d'une Scorecard (très coûteuse) dont la plupart des informations ne nous intéresse pas (on n'a besoin que du pixScore et level par compétence).
Cette PR propose d'interroger directement le scoring-service afin de calculer les pixScores et les niveaux par compétence.
Comparer deux exports CSV de collecte de profils entre cette PR et une autre : pro@example.net, campagne de nom : Campagne collecte de …
> [CLEANUP] Accélère la manière de construire un CertificationProfile (PIX-896)

- api/lib/domain/models/CertificationAssessment.js
- api/tests/unit/domain/models/CertificationAssessment_test.js
- api/tests/unit/domain/services/certification/certification-result-service_test.js
Impossible d'accéder a une certification STARTED  sur la page admin
Un assessment-result peut avoir 0 answer (s'il est STARTED)
- Commencer une certif et s’arrêter avant d'avoir répondu a une question
- Aller voir les infos de celle-ci sur sa page admin
> [BUGFIX] Fix admin certification detail page
